### ISSUE TITLE
It's not showing stats

### ISSUE THREAD

**Issue by ImHammer** [pterodactyl/panel#3974] opened 2022-02-18 18:59 UTC
### Current Behavior

The panel is not showing the usage information of the vps resources, I believe it's docker but I couldn't find any article that was useful for my case, so come here for help

Panel
![Captura de tela de 2022-02-18 15-46-46](https://user-images.githubusercontent.com/59282552/154745106-bd4e1476-2c0e-4852-925e-98ce1b359fe5.png)

Docker
![Captura de tela de 2022-02-18 15-55-50](https://user-images.githubusercontent.com/59282552/154745151-ded825e5-98c3-4cb8-8c3a-0947c1f6f152.png)

### Expected Behavior

I expected it to show all the information, at least the RAM usage and processing usage.

### Steps to Reproduce

I'm not sure how to reproduce it, it's just not working what it was supposed to.

### Panel Version

1.6.6

### Wings Version

1.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by yesBad** [comment] 2022-02-18 19:00
Update your wings. (and panel)

**Comment by QuintenQVD0** [comment] 2022-02-18 20:45
You have a old panel and old wings. This is a docker issue. Come to the discord and type :`docker stats` and the bot will respond.

**Comment by QuintenQVD0** [comment] 2022-02-18 20:47
![SmartSelect_20220218-214618_Discord-Beta](https://user-images.githubusercontent.com/67589015/154759038-37457bc4-eb1c-4679-9e9b-d8c3245e8c1a.jpg)

**Comment by trenutoo** [comment] 2022-02-18 23:30
Duplicate of #2756 #3835 #3969

**Closed as completed** 2022-02-18 23:31 UTC
