### ISSUE TITLE
Manual server order sorting

### ISSUE THREAD

**Issue by masmc05** [pterodactyl/panel#4843] opened 2023-08-17 14:53 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Allow users to sort the servers in an order that they like, not by creation order (in the admin panel they may remain in that order, only in the user's server view)

### Describe the solution you'd like.

Before the name of the server to add an interaction point that can be dragged and the server will be moved to where the cursor wants, the new order of the server should be saved in the database

### Additional context to this request.

If you use pterodactyl not as a hosting provider, but as a server owner of a big network, your list of servers will be big, and because it's chaos, it's very confusing and harder to use

**Comment by mason-rogers** [comment] 2023-08-17 14:57
duplicate of #498

**Closed as completed** 2023-08-17 14:58 UTC
