### ISSUE TITLE
Reorder Servers

### ISSUE THREAD

**Issue by expxx** [pterodactyl/panel#3120] opened 2021-02-23 19:54 UTC
**Is your feature request related to a problem? Please describe.**

Allow us to reorder our servers, currently they’re in the order they were created in, allow us to reorder them

**Describe the solution you'd like**

Make a drag and drop with servers thing, where you can select a server and reorder it with the others.

**Describe alternatives you've considered**

I suppose we could just live with what we have

**Additional context**

**Comment by FoksVHox** [comment] 2021-02-23 19:58
Duplicate of #1885 which is a duplicate of #1439

**Closed as completed** 2021-02-23 19:58 UTC
