### ISSUE TITLE
Backup function

### ISSUE THREAD

**Issue by outtimes** [pterodactyl/panel#1291] opened 2018-08-19 07:28 UTC
**Is your feature request related to a problem? Please describe.**
I want to get backup everyday in 3:00 AM.

**Describe the solution you'd like**
Add a choose in panel,and we can setting whether or not to backup in 3:00 AM.
And if they do,the daemon will backup the server files in 3:00 AM in to backup folder.
Users can go back to the backup.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by hariaakash** [comment] 2018-08-19 08:53
Duplicate of #114

**Closed** 2018-08-19 09:28 UTC
