### ISSUE TITLE
Server state handling and usage info not working

### ISSUE THREAD

**Issue by Trimilur** [pterodactyl/panel#2325] opened 2020-09-10 18:44 UTC
![Unbenannt](https://user-images.githubusercontent.com/22460686/92783956-82097500-f3a6-11ea-9c2d-61927eed802b.png)
**Background (please complete the following information):**
* Panel or Daemon: 1.0-rc3
* Version of Panel/Daemon:  Newest
* Server's OS: Ubuntu 20
* Your Computer's OS & Browser: Windows 10 Firefox

**Describe the bug**

PHP 7.4.10 (cli)
 5.4.0-47-generic #51-Ubuntu
 Kernel Version: 5.4.0-47-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
Server Version: 19.03.12

When you restart the whole root server without shutting down the teamspeak server the ts3 server does not normally start up with server state handling. first you have to manually start and kill it and even then it stays in the "starting" phase and does not show proper usage info although teh container itself runs properly.

**To Reproduce**
Create Teamspeak Server, Start it. let it run and hard reboot your system. After the system is rebooted panel and wings start normally but the server doesnt.  If you do nothing there will be an error code on the client side similar to "server not reachable".

 if you press on start after that the server might be not starting at all. If it soes start it doesnt show proper usage information.

If you then stop AND kill teh container and start it again the server pops up in docker ps but still no usage information although the container runs normally. The starting flag will stay yellow as well "Starting"

When you try to normally delete this server there might be  an error with the daemon prompted as well "I'm getting this error right now "There was an exception while attempting to communicate with the daemon resulting in a HTTP/E_CONN_REFUSED response code. This exception has been logged.".

**Comment by DaneEveritt** [comment] 2020-09-10 19:45
Seems like a duplicate of https://github.com/pterodactyl/panel/issues/2298

**Closed by DaneEveritt** 2020-09-10 19:45 UTC

**Comment by Trimilur** [comment] 2020-09-10 19:51
@DaneEveritt yes for the usage info part I agree that looks similar. what about the server state handling? The container didnt restart automatically this was not adressed in your mentioned report neither the problem that the server cannot be started manually at the first time and you have to first start and the kill the container to get it at somehow running at all

**Comment by DaneEveritt** [comment] 2020-09-11 01:41
It is likely all related. This issue is just far too broad to even begin to try and tackle. It is entirely possible everything is stemming from one bad part of the code. I'd much rather focus on fixing the issue that is plaguing many users than an issue that is all over the place and seems to only affect one user right now.

We can re-evaluate this down the road once we fix the more pressing and noticeable issues.
