### ISSUE TITLE
Re-Ordering Servers.

### ISSUE THREAD

**Issue by HorrifyingMonkey** [pterodactyl/panel#1885] opened 2020-04-02 18:27 UTC
**Is your feature request related to a problem? Please describe.**

Unable to 'reorder' servers in the server list without deleting/remaking them. Unable to look neat/sorted.

**Describe the solution you'd like**

The Ability to rearrange servers in the server list to make everything neater, similar to how you can re-arrange servers on discord. 

**Describe alternatives you've considered**

Sub-Folders, allowing servers of different categories to be put into different folders.

**Additional context**

**Comment by TrixterTheTux** [comment] 2020-04-02 18:29
Duplicate of https://github.com/pterodactyl/panel/issues/1439

**Closed by TrixterTheTux** 2020-04-02 18:29 UTC
