### ISSUE TITLE
Add searching user by nickname

### ISSUE THREAD

**Issue by ririko5834** [pterodactyl/panel#3166] opened 2021-03-09 14:33 UTC
Hello, can you please add also support for searching **users by their usernames** when creating server for user and when searching user in Users category?

It should be added here: 
![image](https://user-images.githubusercontent.com/64729293/110486208-ba3b0780-80ec-11eb-83a7-c0091d851f54.png)
and here:
![image](https://user-images.githubusercontent.com/64729293/110486249-c4f59c80-80ec-11eb-985b-bac5bd88e877.png)

**Comment by Boy132** [comment] 2021-03-09 14:34
I'm sure you can search by username, can't you?

**Comment by trenutoo** [comment] 2021-03-09 14:35
Duplicate of #2366 and is something that will be addressed in the new React admin area release

**Closed as completed** 2021-03-09 15:39 UTC
