### ISSUE TITLE
Create archive archives all files starting with selected file's name

### ISSUE THREAD

**Issue by dawon** [pterodactyl/panel#4078] opened 2022-05-16 08:56 UTC
### Current Behavior

When I try to archive single folder (e.g. Folder) in Ptero Panel, archive containing all files with names starting with 'folder' (case insensitive).

### Expected Behavior

Only the selected folder is archived

### Steps to Reproduce

1) Have files and folders with the same prefix in Ptero folder. (e.g. "folder")
2) Try to archive a folder that is named "Folder" (both three dots menu and archive selected produce this issue)

### Panel Version

1.7.0

### Wings Version

1.6.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment] 2022-05-16 09:23
I'm not able to reproduce this...

**Comment by trenutoo** [comment] 2022-05-16 10:00
This has been fixed on Wings develop branch and in the next release. Duplicate of #3946

**Closed as completed** 2022-05-16 10:00 UTC

**Comment by dawon** [comment] 2022-05-16 10:06
Ah, did not check Closed issues, thank you!
