### ISSUE TITLE
Server Folders

### ISSUE THREAD

**Issue by HeadMonitor** [pterodactyl/panel#3312] opened 2021-04-29 16:46 UTC
**Is your feature request related to a problem? Please describe.**
I am really frustrated with the amount of servers that my organization has.

**Describe the solution you'd like**
A really good solution would be to be able to group your servers into folders.

**Comment by trenutoo** [comment] 2021-04-29 16:46
Duplicate of #498

**Closed as completed** 2021-04-29 16:47 UTC
