### ISSUE TITLE
Startup changes are not getting applied

### ISSUE THREAD

**Issue by LucidAPs** [pterodactyl/panel#2276] opened 2020-08-27 15:17 UTC
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0.0-rc.2
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Win 10 / Brave

Startup changes are not getting applied.

![image](https://user-images.githubusercontent.com/42933023/91461230-6a53cc00-e891-11ea-9bdf-17ac091e6efc.png)

![image](https://user-images.githubusercontent.com/42933023/91461331-88b9c780-e891-11ea-862a-0578700ee1fe.png)

**Comment by fabm3n** [comment] 2020-08-27 15:22
Dupe of #2269 (and maybe #2255 ?)

**Closed** 2020-08-27 15:37 UTC
