### ISSUE TITLE
Add Servers autostart

### ISSUE THREAD

**Issue by xyronexus** [Pterodactyl/Panel#490] opened 2017-06-13 20:23 UTC
Could you please add options for servers to autostart on boot?
For TeamSpeak is a very good option.
Also it would be nice if user can batch delete ports from allocation in node, when i added 100 of them i got to remove them one by one.
Thx for your support.

**Comment by DaneEveritt** [comment] 2017-06-13 23:02
duplicate of #136

**Closed by DaneEveritt** 2017-06-13 23:02 UTC
