### ISSUE TITLE
Addons feature for gameservers

### ISSUE THREAD

**Issue by SanjaySRocks** [pterodactyl/panel#3283] opened 2021-04-21 06:01 UTC
**Is your feature request related to a problem? Please describe.**
No its not related to problem but it is to ease task to install stuff quickly

**Describe the solution you'd like**
Simply add the feature of addons tab in server section so we can set a link from where files get downloaded and install on gameserver .
example installing sourcemod on cs go server in 1 click.

**Describe alternatives you've considered**
Alternative we have to do that work using putty or sftp that create a mess and uploading file take time

**Additional context**
1. Create addons section just like startup section and add the text field there with text name "Sourcemod" and add button there to install it.
2. Inside admin panel we can define the link of file which is to be extracted on root of game folder
3. We can add as many addons to install it in server by providng a link to a file.
- sourcemod
- metamod
- server plugins
- maps etc.

**Comment by alexevladgabriel** [comment] 2021-04-21 06:46
@SanjaySRocks You can do already this thing with the add-on **Mod Manager**. I had used it for the same thing you want, to allow clients, to **1-click install/uninstall** (sourcemod/metamod & others).

**Comment by SanjaySRocks** [comment] 2021-04-21 07:04
Ok can I get a link of that mod manager ?

**Comment by alexevladgabriel** [comment] 2021-04-21 07:15
That's the link for the add-on: https://pterodactylmarket.com/resource/143

**Comment by FoksVHox** [comment] 2021-04-21 07:22
Duplicate of #1084

**Comment by SanjaySRocks** [comment] 2021-04-21 07:38
Its a paid feature but I am using panel for personal use is there any free version of it?

**Comment by FoksVHox** [comment] 2021-04-21 07:51
> Its a paid feature but I am using panel for personal use is there any free version of it?

@SanjaySRocks No, it's a third-party addon. But you should close this issue, as it's an duplicate of #1084.

**Comment by DaneEveritt** [comment] 2021-04-21 15:27
Won't implement.

**Closed as completed by DaneEveritt** 2021-04-21 15:27 UTC
