### ISSUE TITLE
Login flow interrupted by bugs with recaptcha causing blank page

### ISSUE THREAD

**Issue by vingaltwitch** [pterodactyl/panel#2011] opened 2020-05-09 16:00 UTC
* Panel or Daemon: Panel 
* Version of Panel/Daemon: 1.0 Beta
* Server's OS: Ubuntu 18.04 LTS
* Your Computer's OS & Browser: Windows 10 Home / Firefox

**Describe the bug**

When I log into the panel, It redirects me to 'auth/login/checkpoint' where nothing is displayed. Until I refresh the page then the checkpoint displays itself.

Panel: PHP 7.4.5 (cli)

**To Reproduce**
1. Go on to the panel login page.
2. Click on Login
3. (2FA must be enabled on the user) and then you should see nothing when logging but it says your on 'auth/login/checkpoint'.
4. Then press F5 and you will then see the checkpoint

[Video Vimeo](https://vimeo.com/416683582)

**Comment by Sir3lit** [comment] 2020-05-09 16:38
Are you on beta 3? As that was fixed in beta 3. #1962

**Comment by vingaltwitch** [comment] 2020-05-09 17:21
Yes. I'm on beta 3.

**Comment by Sir3lit** [comment] 2020-05-09 17:52
You right. 

The Browser Console log is as follows.

![image](https://user-images.githubusercontent.com/1757840/81481164-1d71ba00-91fc-11ea-97ff-56aeb9be69d0.png)

**Comment by DaneEveritt** [comment] 2020-05-10 02:47
I am not able to reproduce this against develop?

**Comment by Sir3lit** [comment] 2020-05-10 02:54
Hmm, I'm running beta 3. Maybe when we push we can check again. until then have this issue on the back burner?

**Comment by DaneEveritt** [comment] 2020-05-10 02:59
Did you make modifications to your Recaptcha settings? That stack doesn't indicate anything to do with the 2FA checkpoint, other than Recaptcha issues.

**Comment by Sir3lit** [comment] 2020-05-10 03:05
Nope? using whatever ReCaptcha ships with the panel, I just enabled 2fa on my account and logged in

**Comment by Sir3lit** [comment] 2020-05-21 08:42
@DaneEveritt Still not working on the latest beta.

**Comment by Sir3lit** [comment] 2020-05-25 23:24
Should be noted when I disabled reCaptcha for #2064 the box appeared right away. and didn't have to refresh to see it.

**Comment by fabm3n** [comment] 2020-07-14 14:09
Can't reproduce it in latest develop. Should it be closed?

**Comment by DaneEveritt** [comment] 2020-07-14 15:22
Its difficult to reproduce, seems to be specific machines and users running into the issue.

**Comment by Sir3lit** [comment] 2020-07-22 05:52
Should be noted that this is still an issue in Beta 6. 

![image](https://user-images.githubusercontent.com/1757840/88139496-cf930e00-cbbd-11ea-9505-ab9a4406638f.png)

**Comment by DaneEveritt** [comment] 2020-07-30 03:35
Closing in favor of #2064

**Closed by DaneEveritt** 2020-07-30 03:35 UTC
Labels: beta 🦈, bug 🐛
