### ISSUE TITLE
IPv6 only on the deamon

### ISSUE THREAD

**Issue by PaulaBras** [pterodactyl/panel#2243] opened 2020-08-16 11:03 UTC
**Is your feature request related to a problem? Please describe.**
I have a network where I can only access IPv6. The panel and the deamon (wings and beta panel) can apparently not communicate with each other. So it would be nice if the panel could also talk to the Deamon about IPv6 only.

**Describe the solution you'd like**
The simple solution is not only to be able to use an A record, but also an AAAA record.

**Additional context**
Provided Error:
```
There was an error validating the data provided.
The FQDN or IP address provided does not resolve to a valid IP address.
```
![Capture](https://user-images.githubusercontent.com/68814660/90332877-e52f0400-dfc0-11ea-8bdb-c2896351647d.JPG)

**Comment by DaneEveritt** [comment] 2020-08-18 02:37
Duplicate of https://github.com/pterodactyl/panel/issues/1778

**Closed by DaneEveritt** 2020-08-18 02:37 UTC
