### ISSUE TITLE
No Server Owner Option Available When Creating Server

### ISSUE THREAD

**Issue by AtomynosAtom** [pterodactyl/panel#1936] opened 2020-04-17 15:04 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-beta.1
* Server's OS: Ubuntu LTS 18.04.4 Server 64-bit
* Your Computer's OS & Browser: Arch Linux & Opera

**Describe the bug**
When creating a new server no options are available for the Server Owner Setting.

Please provide additional information too, depending on what you have issues with:
Panel: `PHP 7.2.24-0ubuntu0.18.04.4`  (the php version in use).
Daemon: -
`Linux ubonic 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

`Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-96-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.852GiB
 Name: ubonic
 ID: COEC:6ETK:3PZ6:3GNX:6XMK:AMMO:FR4P:MTIH:5TUB:C24W:EQDW:EZVW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

` (your kernel version and information regarding docker)

**To Reproduce**
1. Go to 'admin/servers/new'.
2. Click on 'Server Owner Selector'.
3. No options given.

**Expected behavior**
Show user list to select as server owner.
![Screenshot_20200417_203539](https://user-images.githubusercontent.com/33798072/79583714-0bb06180-80eb-11ea-87c1-d70e2f3b951f.png)

**Comment by parkervcp** [comment] 2020-04-17 15:08
This is the same in 0.7. You just start typing in a name.

**Comment by AtomynosAtom** [comment] 2020-04-17 15:09
That option isn't there for some reason.

**Comment by parkervcp** [comment] 2020-04-17 15:10
You should start typing and it search for a name.

**Comment by synocx** [comment] 2020-04-17 15:13
Why are you using PHP7.2?

**Comment by AtomynosAtom** [comment] 2020-04-17 15:14
I tried typing....It just shows a slim blue line along the bottom of the box...Nothing else

**Comment by AtomynosAtom** [comment] 2020-04-17 15:16
![Screenshot_20200417_204554](https://user-images.githubusercontent.com/33798072/79584762-76ae6800-80ec-11ea-82dc-1079c5dd9413.png)
Also Some errors.

**Comment by synocx** [comment] 2020-04-17 15:23
![20200417_232248](https://user-images.githubusercontent.com/62736272/79585447-643f2900-8102-11ea-909d-a6bb7f15ab07.jpg)
?

**Comment by AtomynosAtom** [comment] 2020-04-17 16:47
Ummm... I have installed php 7.4
PHP 7.4.4 (cli) (built: Mar 20 2020 13:47:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies

The issue still persists.... Should I just reinstall everything?

**Comment by DaneEveritt** [comment] 2020-04-17 16:57
No, this has nothing to do with your PHP version. You've installed beta software and at the moment this bug is not a current priority for me to look into. It will be fixed as soon as time permits.

**Comment by AtomynosAtom** [comment] 2020-04-17 18:12
Sure take your time... And please do inform me when this bug is fixed so I can use this amazing program and help y'all by reporting bugs to smash and make the beta version more stable than before.

Btw the new UI is amazing. **Keep Up The Good Work!**

**Comment by DarthShmev** [comment] 2020-04-17 22:16
This issue looks to have been resolved or is an issue on your installation. I can confirm the server owner option is shown when creating a new server.

![image](https://user-images.githubusercontent.com/34663790/79618225-75267500-80d7-11ea-80ba-3956703f2584.png)

**Comment by matthewpi** [comment] 2020-04-17 22:22
From the error in the browser console that looks like an issue with the way I handled persisting the `Server Owner` when an error occurs, I'll take a look into it when I get a chance.

**Comment by Sir3lit** [comment] 2020-04-17 23:32
I'm not able to reproduce this.

**Comment by parkervcp** [comment] 2020-04-18 14:10
![image](https://user-images.githubusercontent.com/1207679/79639926-a1d0a000-815c-11ea-8262-6b23adb5055e.png)

Also working for me.

PHP 7.4.4 (cli) (built: Mar 24 2020 01:34:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by DaneEveritt** [comment] 2020-04-18 17:42
I am also not able to reproduce this, closing the issue for now until someone is able to definitively show reproduction steps.

**Closed by DaneEveritt** 2020-04-18 17:42 UTC
Labels: 1.0.0-beta, Type: Bug

**Comment by serpahot** [comment] 2021-03-16 15:39
Enter 2 inicial characters of the name of the user.

**Comment by JacobHolman** [comment] 2022-02-21 19:00
It could do with the theme...
