### ISSUE TITLE
Mobile responsiveness is broken between lg and md sized screen sizes.

### ISSUE THREAD

**Issue by gabefraser** [pterodactyl/panel#2365] opened 2020-09-18 10:24 UTC
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon:  1.0.0-rc6
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chrome 85.0.4183.102

**Describe the bug**
- Text isn't being shrunk to the proper screen size / it's causing an overflow with large titles.
- Text is overflowing on the console.
- Breakpoints aren't wrapping correctly.

![image](https://user-images.githubusercontent.com/10922294/93587186-d76c0480-f9ec-11ea-84fa-c5638cf71d53.png)
![image](https://user-images.githubusercontent.com/10922294/93587199-ddfa7c00-f9ec-11ea-88fd-d52043c856f4.png)
![image](https://user-images.githubusercontent.com/10922294/93587209-e357c680-f9ec-11ea-962b-8b278fe31516.png)

**To Reproduce**
Shrink the panel to the certain sizes.

**Expected behavior**
Proper flow of mobile responsiveness.

**Comment by zKoz210** [comment] 2020-09-20 09:45
![image](https://user-images.githubusercontent.com/28255085/93708375-50c73c80-fb3e-11ea-81e1-d1e77c81e6ed.png)
![image](https://user-images.githubusercontent.com/28255085/93708379-5755b400-fb3e-11ea-8e70-62d085b5444a.png)
![image](https://user-images.githubusercontent.com/28255085/93708410-810edb00-fb3e-11ea-8996-1e90775f89d6.png)

**Comment by LeCodeCo** [comment] 2020-09-20 20:51
So me and @AreYouRlyScared were testing it out and we located the issue. It seems to only exist on Chrome and it's caused by the graphs when the server is running. The moment the server stops and the graphs disappear, everything works again.

We need to identify why the graphs stay really big.

**Comment by AreYouRlyScared** [comment] 2020-09-21 02:04
@zKoz210 The payload text was fixed to display as.
![image](https://user-images.githubusercontent.com/1757840/93727800-db358d80-fb8a-11ea-90d0-2dce40e47dd9.png)

As for the title, nobody should really have a title that's that long.... But ill work on fixing it.

The others will be fixed in a pr in the coming hour.

As for the API Keys one... it works properly for me?
![image](https://user-images.githubusercontent.com/1757840/93728283-408a7e00-fb8d-11ea-8740-d6e55f9ba124.png)

**Comment by zKoz210** [comment] 2020-09-21 09:45
![image](https://user-images.githubusercontent.com/28255085/93749983-7d915780-fc03-11ea-844a-db10e0da3108.png)
![image](https://user-images.githubusercontent.com/28255085/93749699-078cf080-fc03-11ea-9e5d-14a358045790.png)

Modal window in the database view is not the same as everywhere else (background)

It would be cool if it was in the middle, instead of going to the bottom

**Comment by AreYouRlyScared** [comment] 2020-09-25 06:47
I mean it does go to the "middle" just the screen is too small to display all the information.

**Closed** 2020-10-04 02:21 UTC
Labels: 1.0 🦈, ui/ux
