### ISSUE TITLE
Folder uploads are not supported at this time with .db files

### ISSUE THREAD

**Issue by AlexTheGoat69** [pterodactyl/panel#4326] opened 2022-08-18 00:03 UTC
### Current Behavior

Have a .db file. Try to upload it on panel, it won't allow you and this appears.

ERROR
Folder uploads are not supported at this time.

only started happening when I updated the panel

### Expected Behavior

It to upload because it's not a folder.

### Steps to Reproduce

1) have .db file
2) try to upload it on panel
3) get error

### Panel Version

1.10.1

### Wings Version

1.7.0

### Games and/or Eggs Affected

discord.py / using pycord on this

### Docker Image

https://github.com/parkervcp/eggs/tree/master/bots/discord/discord.py

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment] 2022-08-18 00:29
Duplicate of https://github.com/pterodactyl/panel/issues/4280

**Comment by parkervcp** [comment] 2022-08-18 00:31
closing as a duplicate.

**Closed as completed by parkervcp** 2022-08-18 00:31 UTC
