### ISSUE TITLE
Storage Not Showing

### ISSUE THREAD

**Issue by DomiiBunn** [pterodactyl/panel#1671] opened 2019-08-06 23:15 UTC
Issue With: Panel
Panel Version: 0.7.15
Server Os: Ubuntu 18.04
Web Server: Nginx
Browser: Chrome, FireFox, Edge
Client Os: Linux, Windows

Panel Not showing disk usage on the main servers page, Whoever it does appear in the node info.

**To Reproduce**
1. Create a server
2. Wait for the install
3. Go to the main servers page
4. No disk info will be displayed

**Expected behavior**
Panel shows how much drive space is used.

**Php Info**
php-common/bionic,now 2:69+ubuntu18.04.1+deb.sury.org+2+php7.3 all [installed,automatic]
php7.2/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 all [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-bcmath/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-cli/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-common/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-curl/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-fpm/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-gd/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-json/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-mbstring/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-mysql/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-opcache/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-readline/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-xml/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]
php7.2-zip/now 7.2.20-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1]

**Comment by DrumSlayers** [comment] 2019-08-06 23:25
Same issue here on 0.7.15
The current doesn't show on home page, but does show in node's server information

**Home page:**
![image](https://user-images.githubusercontent.com/4050278/62583789-fcb5b600-b8b1-11e9-8bd4-28fdbeef1fc4.png)

**Node's Server Page**
![image](https://user-images.githubusercontent.com/4050278/62583816-148d3a00-b8b2-11e9-9814-c9898094585c.png)

Running on same browser, web server and php version as @DomiiBunn .

**Comment by Sir3lit** [comment] 2019-09-17 22:14
I'm not able to reproduce this, As im the one that put it in, im not seeing any way it could fail. When viewing the Your Servers page could you see if any errors are in the console log of the browser? As memory/CPU is all from the same call to the daemon as the disk usage...

I can be reached on discord @ AreYouScared#4689

**Comment by arcdigital** [comment] 2020-04-09 04:48
Closing, as there hasn't been a response. Feel free to reopen if this is still happening.

**Closed by arcdigital** 2020-04-09 04:48 UTC
Labels: Type: Bug

**Comment by NotYusta** [comment] 2020-12-23 12:25
it's still not showing in December 2020

**Comment by DomiiBunn** [comment] 2020-12-23 12:38
Does not happen in 1.0

**Comment by matthewpi** [comment] 2020-12-23 21:52
There were a bunch of changes to fix race conditions relating to disk space and resources, I doubt this is still a problem and if it is, it has most likely been fixed on `develop`.
