### ISSUE TITLE
Backup sucess notification fail to reach panel

### ISSUE THREAD

**Issue by Malachiel87** [pterodactyl/panel#3516] opened 2021-08-03 13:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Creating a backup with sucess from panel, the backup status will stay in looping phase and this error popup:

### Expected Behavior

It should notify correct the panel  for completed backup

### Steps to Reproduce

1.Create a backup
2. The backup for the panel will never completed and keep to be in waiting status while it is compeleted in real

### Panel Version

1.5.0

### Wings Version

1.4.6

### Error Logs

```bash
https://bin.byreqz.de/?a09ca6040c2da35e#E9x5UnHMQ6keYT4HdxR8u8oHij7vmxKkd1iVfvDuV9Sv
```

**Comment by nikrozman21** [comment] 2021-08-03 14:24
Would be nice if you could provide the password to that paste

**Comment by nikrozman21** [comment] 2021-08-03 14:26
Same issue here. Out of curiosity, what S3 provider are you using?

**Comment by notAreYouScared** [comment] 2021-08-03 14:35
This is a validation error the panel throws when the required fields are not in the request. Has nothing to do with the S3 provider.

**Comment by matthewpi** [comment] 2021-08-03 15:16
This is not a 1.5.0 issue, this exact error has occurred in previous releases.

**Comment by matthewpi** [comment] 2021-08-03 16:53
Duplicate of https://github.com/pterodactyl/panel/issues/3334

**Closed as completed by matthewpi** 2021-08-03 16:53 UTC
