### ISSUE TITLE
Wings are online but shows offline on web panel

### ISSUE THREAD

**Issue by AtomynosAtom** [pterodactyl/panel#1933] opened 2020-04-16 18:39 UTC
**Background:**
* Panel or Daemon: 
* Version of Panel/Daemon: 1.0.0-beta.1
* Server's OS: Ubuntu LTS 18.04.4 Server
* Your Computer's OS & Browser: Arch Linux & Opera

**Describe the bug**
Panel: Creates Config file without uuid and does not detect node.
Daemon: Accepts Config file and runs without errors.

**To Reproduce**
1. Create node
2. Copy and run config token command on server.
3. Run wings.
4. Does not show on panel.

**Expected behavior**
Show node online on panel and also generate a uuid for config file.

**Comment by parkervcp** [comment] 2020-04-16 18:54
Please take this to our discord server.

**Comment by parkervcp** [comment] 2020-04-16 18:55
Seeing this is a 1.0 beta bug will leave it closed as a duplicate of #1930

**Closed by parkervcp** 2020-04-16 18:54 UTC
