### ISSUE TITLE
Using docker to run, no matter which option is set in the node settings and clicked to save, a 500 error will appear.

### ISSUE THREAD

**Issue by aopkcn** [pterodactyl/panel#4920] opened 2023-11-11 13:53 UTC
### Current Behavior

Using docker to run, no matter which option is set in the node setting and click save, a 500 error will appear. My environment is Docker installed in Debian12. After initialization, log in to create a node, modify the node and save, and a 500 error will appear.

### Expected Behavior

-

### Steps to Reproduce

-

### Panel Version

v1.11.5

### Wings Version

v1.11.8

### Error Logs

```bash
[2023-11-10 17:58:01] production.NOTICE: 尝试从数据库加载设置时遇到查询异常: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.settings' doesn't exist (Connection: mysql, SQL: select * from `settings`)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jcodeerd** [comment] 2023-11-11 14:35
> Your database migration was skipped or failed. You may attempt to complete it by running `php artisan migrate --seed --force`  in the Pterodactyl install directory. If you encounter errors, please do not ignore them and instead post them here.
According to the discord this can be your issue, not a bug.

**Comment by aopkcn** [comment] 2023-11-11 16:39
php artisan migrate --seed --force
I have tried all these commands and still cannot modify the node.

**Comment by Roncarlos** [comment] 2023-11-26 17:51
Same here
![image](https://github.com/pterodactyl/panel/assets/9269672/9590ede5-e56d-4dd1-bae0-1f4ba048cde6)

I already did "php artisan migrate --seed --force" nothing changed.
I deleted everything and start over, and still have the error.

**Comment by Boy132** [comment] 2023-11-27 07:44
Make sure you are using the official docker images (and compose files):
[ghcr.io/pterodactyl/panel](https://github.com/pterodactyl/panel/blob/1.0-develop/docker-compose.example.yml)
[ghcr.io/pterodactyl/wings](https://github.com/pterodactyl/wings/blob/develop/docker-compose.example.yml)

If you are using the official images and the issue persists join the [Discord](https://discord.gg/pterodactyl) and post in **#panel-in-docker**. _(the channel is at the very bottom and may be hidden by default)_

**Comment by danny6167** [comment] 2024-08-07 02:49
Duplicate of https://github.com/pterodactyl/panel/issues/5051

**Closed as completed by danny6167** 2024-08-07 02:49 UTC
