### ISSUE TITLE
Suspend message in console while server is suspended

### ISSUE THREAD

**Issue by LevM-A** [pterodactyl/panel#4235] opened 2022-07-06 02:48 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A message, when we are trying to get suspended server's console. In this message it just explain that server suspended.

### Describe the solution you'd like.

A message, when we are trying to get suspended server's console. In this message it just explain that server suspended.
Before 1.9 it had this feature but it seems that it was removed, right now it just keep loading forever 
![image](https://user-images.githubusercontent.com/59459622/177457266-d494d48b-e091-4e70-b5d8-767b4c1fbedf.png)
![image](https://user-images.githubusercontent.com/59459622/177466499-1cd26a46-6b30-4d93-bb44-c7a71ed54b48.png)

**Comment by DaneEveritt** [comment] 2022-07-06 12:51
Duplicate of #4230

**Closed as not planned by DaneEveritt** 2022-07-06 12:51 UTC
