### ISSUE TITLE
External Connections

### ISSUE THREAD

**Issue by dabou0** [pterodactyl/panel#1983] opened 2020-04-28 14:09 UTC
**Is your feature request related to a problem? Please describe.**
Not being able to use external folders to acess a server folder, even if its in the same dedicated machine

**Describe the solution you'd like**
A way if the user wants to allow files to be acessed by the machine, or even external, for example for a minecraft server, so i will put a plugin in a folder and this folder will update it to all servers,.

**Describe alternatives you've considered**
Not using the panel, cause this is very useful if you will find many bugs on a minigames network for example, on the core, or the game plugin, that you will need everytime you fix something to update on all servers

**Additional context**
folder where the plugin would be put
https://cdn.discordapp.com/attachments/467450978090876929/701968199197130872/unknown.png
inside srv/daemon-data/core or for example srv/daemon-data/skywars

**Comment by parkervcp** [comment] 2020-04-28 14:14
#1915 would resolve this.

I would also say this is a duplicate of may of the older issues like #714

**Closed by parkervcp** 2020-04-28 14:14 UTC
