### ISSUE TITLE
Add option to allow users to receive notifications for specific functions

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#776] opened 2017-11-22 16:27 UTC
Just a minor feature request.

Was thinking it would be cool (and I assume not overly difficult) to add an email notification for users, customizable of course for their needs, where they can select what options to be notified for.

For example: if they want to be notified if their server is restarted, stopped, etc.

**Comment by schrej** [comment] 2017-11-27 09:25
actually a duplicate of #89, maybe add your ideas there

**Closed by schrej** 2017-11-27 09:25 UTC
Labels: Feature Request, P: Low
