### ISSUE TITLE
Unexpected EOF, Breaks console/WS

### ISSUE THREAD

**Issue by AreYouRlyScared** [pterodactyl/panel#1950] opened 2020-04-19 18:57 UTC
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: Beta 1.0
* Server's OS: Ubuntu 1804
* Your Computer's OS & Browser: Android 10, Chrome

**Describe the bug**
Server console will randomly brick itself and only refresh on page refresh. Console states unexpected End Of File then stops. 
![Screenshot_20200419-143859_Chrome](https://user-images.githubusercontent.com/1757840/79696925-9a3cf400-824d-11ea-8529-a5247e03a7ca.jpg)

Should be noted thus server is a modded minecraft server using the mod pack ATM3. Issue doesn't appear every time server starts but has happened twice over the span from using alpha 1 to beta 1

**To Reproduce**
Not sure how to exactly reproduce this issues, @TrixterTheTux mentioned that alot of lines at once might cause this issue. 

**Expected behavior**
If the issue is due to the mass of lines at once, then it to self throttle or suck it up and display them all as they appear.

**Comment by DaneEveritt** [comment] 2020-04-26 01:25
This is coming from docker itself, and isn't an error I can catch. Not entirely sure how best to handle this honestly.

https://github.com/docker/engine/blob/4839b27a1fb9abcfb2142d46a6afe40bdf9f150b/api/server/httputils/write_log_stream.go#L41-L44

**Comment by Sir3lit** [comment] 2020-09-06 19:24
I haven't ran into this issue since I reported it, and neither has other users using anything more recent builds.... Going to close.

**Comment by popcorn9499** [comment] 2020-12-09 03:12
I could send the docker logs I have seen but it says a similar thing to what you have already discussed earlier.

I had some sort of way to potentially solve this in the panel however I will have to take a look at it once I get a chance. The idea is basically whenever it encounters a bad line it tries to reload the output which we are reading. However I have to look at how many things I will have to change in wings to make that work as expected resetting correctly. If I come up with anything that works well I will be sure to post it here if you don't mind. 

Another potential solution as in my experience this has only happened with certain modded servers however up until this point I had any modded servers in a wrapper to manage backups for me. So that wrapper may of been stripping any eof issues that were occurring so that may be another solution even if its abit of a hacky work around. 

Its more problematic for me because this seems to happen frequently during some of the long 250 line strings of exceptions minecraft forge 1.12.2 loves to throw. In fact I get the unexpected EOF bug happening multiple times a night. 

Hopefully we can come up with a solution.

**Comment by DaneEveritt** [comment] 2020-12-09 03:20
This error is currently "uncatchable" via any normal manner as it isn't actually an error response from the command we're executing, its just an error dumped straight into stdout and therefore it never triggers any flows internally. Wings thinks it is still connected just fine.

**Comment by popcorn9499** [comment] 2020-12-09 03:23
ye so we can read the line that printed that output and we could create our own exception based on that. could we not? Then from that we could have wings reset reading from the container could we not?

**Comment by AoElite** [comment] 2020-12-23 13:52
I've been having the same issue for months. It'd be great if this was resolved. Also, I'm using the latest version of everything (panel, wings & daemon) with Ubuntu 20.04.

**Comment by popcorn9499** [comment] 2020-12-24 00:21
> I've been having the same issue for months. It'd be great if this was resolved. Also, I'm using the latest version of everything (panel, wings & daemon) with Ubuntu 20.04.

I might have at least a workaround. I had prior to backups being added to this panel written my own wrapper that started the server and printed the output. I had no issues with this bug prior to that running any modded servers. however I haven't tested enough since I haven't found a way in the game to reliably replicate it. if I had that I may actually have found a way to make the panel work correctly with it.

not promising anything since I need to sit down and mess around with the panel. if I find a work around I will try to submit a pull request

**Comment by DaneEveritt** [comment] 2020-12-24 17:06
This has nothing to do with wrappers, its entirely the fault of Docker not throwing that error in a manner that can be caught using idiomatic Go error handling, therefore causing Wings to think everything is running smoothly. Actual reproduction is difficult, but it is consistent so I'm not super worried about that.

**Comment by popcorn9499** [comment] 2020-12-24 17:20
I understand that. However the wrapper I was using was stripping most of the line endings and creating its own more or less. So java wasn't making docker think it hit a end of file like docker was thinking. That is I think? why it worked "correctly" before hand. 

However I agree it should throw an exception so that wings can realize it isn't working correctly.

**Comment by Irgendwer01** [comment] 2020-12-29 23:14
The issue is an other, i have exactly the same issue after adding Sponge the Panel sends after a specific line stop signal for some reason, i haven't figured out yet why it does that but it could be because in the console are many errors that are thrown at once.

**Comment by matthewpi** [comment] 2021-01-09 16:09
Should be resolved by https://github.com/pterodactyl/wings/commit/0aab4b1ac2ba9c08b351aa0c0340b887eee7f060

**Closed by matthewpi** 2021-01-09 16:09 UTC
Labels: bug, help wanted :wave:, high priority
