### ISSUE TITLE
Panel File manager recursively search 

### ISSUE THREAD

**Issue by draand28** [pterodactyl/panel#4004] opened 2022-03-15 14:01 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add an option to the panel, in the File Manager section of a particular server to search recursively.

### Describe the solution you'd like.

A search button next to the create directory button.

**Comment by Jelcoo** [comment] 2022-03-15 14:04
Duplicate of https://github.com/pterodactyl/panel/issues/3503

**Comment by YomoSK** [comment] 2022-03-15 14:10
Duplicate of #3926

**Closed as completed** 2022-03-15 14:47 UTC
