### ISSUE TITLE
Email notification that the server has been suspended

### ISSUE THREAD

**Issue by pavl21** [pterodactyl/panel#4794] opened 2023-05-30 15:03 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Once an owner's server is suspended, an email should be sent informing them that the server has been shut down and disabled.

### Describe the solution you'd like.

Same

**Comment by devnote-dev** [comment] 2023-05-30 15:05
Duplicate of #3411.

**Closed as not planned** 2023-05-30 15:52 UTC
