### ISSUE TITLE
Sync eggs/nests with a repo(s) on github

### ISSUE THREAD

**Issue by diedyesterdaywashere** [pterodactyl/panel#4828] opened 2023-07-22 19:26 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

This feature would allow user to set a link to a github repo, and panel would sync the nests/eggs with the repo, so every time it updates it would download new eggs (and preferably notify users if any eggs were changed). Of course ability to add own eggs should still remain... Maybe also have an option to add multiple repositories?

### Describe the solution you'd like.

Just have a setting dedicated for a github repository link, and then it would check for new commits every once in a while, and reimport eggs if any of them were updated... If you will be able to add multiple repositories, maybe nests should be named as repository - nest name (parkervcp/eggs - SteamCMD Servers), or have a column with the repository owner, and repository name, if nest is synced

**Comment by Software-Noob** [comment] 2023-07-22 19:35
This would essentially DDOS Github

**Comment by diedyesterdaywashere** [comment] 2023-07-22 19:48
> This would essentially DDOS Github

Meh, I don't mean to run the checks every second, maybe every day, or a random amount of time

**Comment by Boy132** [comment] 2023-07-22 19:57
Duplicate of #3479

**Closed** 2023-07-23 13:29 UTC
Labels: feature request
