### ISSUE TITLE
Transfer backups with server

### ISSUE THREAD

**Issue by OpenSource03** [pterodactyl/panel#3682] opened 2021-10-12 13:01 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Please make sure backups are transferred as well on server transfer or link backups to the node the server was initially on.

### Describe the solution you'd like.

I don't really see much point in this field 😋

**Comment by Jelcoo** [comment] 2021-10-12 13:02
Also add the databases to this

**Comment by matthewpi** [comment] 2021-10-13 00:49
> Also add the databases to this

Databases are a completely separate thing to transfer.  https://github.com/pterodactyl/panel/issues/2786

---

Duplicate of https://github.com/pterodactyl/panel/issues/2623

**Closed as completed by matthewpi** 2021-10-13 00:49 UTC
