### ISSUE TITLE
New users unable to set password

### ISSUE THREAD

**Issue by kruthers** [pterodactyl/panel#2186] opened 2020-07-22 22:44 UTC
**Background):**
* Panel
* Version of Panel: 1.0 - beta 6 `php-7.4`
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 Chrome

**Describe the bug**
When creating a new user via the users tab in the administrator section or via adding a new sub users. The person is unable to set a password and get: "ERROR An error was encountered while processing this request." 

The console output is as follows:
```
locales/en/translation.json:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
/auth/password/reset:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
bundle.20022364.js:1 Error: Request failed with status code 400
    at e.exports (bundle.20022364.js:1)
    at e.exports (bundle.20022364.js:1)
    at XMLHttpRequest.p.onreadystatechange (bundle.20022364.js:1)
```

**To Reproduce**
1. Go into the admin section
2. Click on users
3. Create a new user without a password
4. Go into the email and click "setup your account"
5. Enter a password

You get the same bug from adding sub users

**Expected behaviour**
The persons password gets set but it does not

**Comment by DaneEveritt** [comment] 2020-07-26 17:50
Duplicate of #2011

**Closed by DaneEveritt** 2020-07-26 17:50 UTC
Labels: beta 🦈, bug 🐛
