### ISSUE TITLE
Timeout when try to decompress a tar.xz file

### ISSUE THREAD

**Issue by VibeGAMESNL** [pterodactyl/panel#4415] opened 2022-10-08 11:30 UTC
### Current Behavior

.tar.xz decompress via the file manager results in a timeout.
.tar.gz works fine.

### Expected Behavior

.tar.xz files should not timeout when you try to decompress it.

### Steps to Reproduce

1. upload a .tar.xz file to the server
2. Try decompress it via the file manager

### Panel Version

1.10.1

### Wings Version

1.7.0

### Error Logs

```bash
Panel:
[2022-10-08 13:18:40] production.WARNING: GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://xxxxxx:8080/api/servers/2011f34f-2609-4169-b724-89ba03c993f1/files/decompress in /var/www/pterodactyl/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210

wings:
INFO: [Oct  8 11:30:25.879] starting file decompression file=1.19.2.tar.xz request_id=936bc0d0-46aa-44c6-a258-9ccec8ace6af root_path=/ server_id=2011f34f-2609-4169-b724-89ba03c993f1
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment] 2022-10-08 11:34
what is the size of the compresed file?

**Comment by VibeGAMESNL** [comment] 2022-10-08 11:53
> what is the size of the compresed file?

129.99 MB

**Comment by parkervcp** [comment] 2022-10-08 12:55
the gzip and xz are different formats. Just because one type unpacks fine doesn't mean the other will. We aren't using tar to unpack the files but a golang based archival solution.

**Comment by Boy132** [comment] 2022-10-08 13:43
Looks like duplicate of #2878 ?

**Comment by VibeGAMESNL** [comment] 2022-10-09 01:08
> Looks like duplicate of #2878 ?

That's not the same issue

**Comment by matthewpi** [comment] 2022-10-09 03:38
I have a pending PR that overhauls the existing unarchive logic and updates a lot of the dependencies related to it.  Might be useful to test that and see if the problem persists.  The general timeout when decompressing still exists though.

**Comment by VibeGAMESNL** [comment] 2022-11-22 18:07
It seems that the files are decompressed correctly but for some reason it will timeout if it takes more then 5 seconds.

**Comment by matthewpi** [comment] 2022-11-22 18:37
> It seems that the files are decompressed correctly but for some reason it will timeout if it takes more then 5 seconds.

If the files are decompressed but it seems to timeout and break then it seems that it's facing the same problem as described in https://github.com/pterodactyl/panel/issues/2878

**Comment by BenasPaulikas** [comment] 2024-03-28 18:38
I have 360MB File (.tar.gz) which takes 14+minutes to unarchive.
I'm more than happy to share it for testing purposes.
This is first time me seeing this...
Unarchiving on local takes few seconds
Final output 9.6k files and ~650MB
Wings is using one CPU core/thread for this

@matthewpi how could I test your pending PR ?

P.S. I'm using latest version 1.11.11 (Latest: 1.11.11)

**Comment by BenasPaulikas** [comment] 2024-03-28 18:41
![image](https://github.com/pterodactyl/panel/assets/6473565/56b657cd-206c-4975-9651-89b953e3e8b0)
Proof of someone attempting to unarchive it 5 times :moon_cake:

**Closed as not planned** 2024-05-04 22:39 UTC

**Comment by beckylemesmash** [comment] 2024-06-25 16:10
> I have a pending PR that overhauls the existing unarchive logic and updates a lot of the dependencies related to it. Might be useful to test that and see if the problem persists. The general timeout when decompressing still exists though.

@matthewpi I would love to test that PR 

I currently have 162MB .tar.gz file that fails to unarchive in 8 minutes :warning:  (1 core 100% cpu)
It unarchives to ~800MB and 3781 files
While locally it's 5seconds with way less cpu.

Thank you.

**Comment by beckylemesmash** [comment] 2024-12-07 01:14
moved to https://github.com/pterodactyl/panel/issues/5253
