### ISSUE TITLE
Language changes do not apply.

### ISSUE THREAD

**Issue by GeistFighter** [pterodactyl/panel#2341] opened 2020-09-14 16:19 UTC
How come my site stays in English when it is configured in French?
He seems to understand that it is in French in the global configuration and in the configuration of each user, but everything is still written in English.
(And when I try to put it in another language in the global configuration, it always brings back French (while remaining written in English).
But in the user configuration I can change the language, but as for the global one, it will always stay in English).

**Comment by fabm3n** [comment] 2020-09-14 16:32
Please use the Template and provide more Informations like your used version.

**Comment by GeistFighter** [comment] 2020-09-14 17:00
* Panel or Daemon: Panel 
* Version of Panel/Daemon: 1.0.0-rc.5
* Server's OS: DEBIAN 9
* Your Computer's OS & Browser: Windows 10 & FireFox

**Describe the bug**
How come my site stays in English when it is configured in French?
He seems to understand that it is in French in the global configuration and in the configuration of each user, but everything is still written in English.
(And when I try to put it in another language in the global configuration, it always brings back French (while remaining written in English).
But in the user configuration I can change the language, but as for the global one, it will always stay in English).

**To Reproduce**
1. Go to 'Setting'  https://exemple.com/admin/settings
2. Click on 'Language' and change it
3. The language stay in english !


I hope this will suit you

**Comment by LeCodeCo** [comment] 2020-09-14 17:16
I don't believe translations have been implemented yet.

**Comment by fabm3n** [comment] 2020-09-14 17:35
Yes language support is not implemented in 1.0 yet. so this is a dupe of #1106

**Comment by schrej** [comment] 2020-09-14 19:14
Well, not really a duplicate tbf., but we're aware that there is no language support in the new panel (yet).

**Closed** 2020-09-14 19:13 UTC

**Comment by mrgame-memo** [comment] 2020-10-13 09:26
> Well, not really a duplicate tbf., but we're aware that there is no language support in the new frontend (yet).

Oh, this is quite annoying, I hope it'll be added soon, will I be noticed of this by commenting here :o ?

**Comment by neophitt** [comment] 2025-02-06 12:48
And where can we find some languages ? I need french translation :/
