### ISSUE TITLE
Unexpected Error on full storage

### ISSUE THREAD

**Issue by edbrk** [pterodactyl/panel#2689] opened 2020-11-09 16:50 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: V1.1.1/1.1.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10, Brave Browser. 

**Describe the bug**

When the file storage amount is over the allocated amount (EG 1.2GB/1.0 GB) when the server is offline A error is displayed "There was a Error Validating the credentials Provided for the websocket, Please refresh the page." The console also buffers. 

Please provide additional information too, depending on what you have issues with:
Panel:  PHP 7.4.7

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a server with a realitlvey low storage amount. 
2. Go to file manager for the server created and upload a file that is going to exceed the total storage amount.
3. Go to the console page for that server. 
4. Stop the Server.
5. Refresh the page.
6. Attempt to start the server. 
4. See error. 

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

The expected behaviour is the server should start and no error should be displayed, or a error that its out of storage should be displayed, i don't believe there is a error for this case yet.

**Comment by DaneEveritt** [comment] 2020-11-10 18:47
Are you sure that error is a result of the disk space and not just funky timing?

**Comment by edbrk** [comment] 2020-11-10 18:49
> Are you sure that error is a result of the disk space and not just funky timing?

I am almost certain its to do with disk space, as the error only appears when i change the disk space below the current capacity of what it is. I can do further testing however.

**Comment by DaneEveritt** [comment] 2020-11-10 18:51
Ah, its likely I'm just aborting the validation if there isn't disk space available (which is probably bugged) but I'll dig in more later.

**Comment by Takabrycheri** [comment] 2020-12-01 07:24
There seems to be the same problem with RAM too

**Comment by DaneEveritt** [comment] 2020-12-06 22:19
Duplicate of https://github.com/pterodactyl/panel/issues/2709

**Closed as completed by DaneEveritt** 2020-12-06 22:19 UTC
