### ISSUE TITLE
Ability to transfer servers between nodes

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#280] opened 2017-01-31 23:05 UTC
It should be possible to transfer servers between nodes easially from the panel.

A first idea was to select the new node, ip and port, zip up the server, transfer it to the new node, unzip it and set it up. Also keep the old server backed up or validate everything with some checksum.

**Comment by DaneEveritt** [comment] 2017-02-01 00:00
Duplicate of #18

**Closed by DaneEveritt** 2017-02-01 00:00 UTC
Labels: feature

**Comment by schrej** [comment] 2017-02-01 00:22
Oops, didn't see that one, sorry.
