### ISSUE TITLE
Reinstall button on fail install

### ISSUE THREAD

**Issue by IceCupe123** [pterodactyl/panel#1748] opened 2019-11-17 17:13 UTC
I would suggest to add a reinstall button if a server fail its installation so u dont need to recreate the server every time it fails

**Comment by TrixterTheTux** [comment] 2019-11-17 17:16
Duplicate of #1590

**Closed by TrixterTheTux** 2019-11-17 17:16 UTC

**Comment by JanDevDE** [comment] 2019-11-17 18:12
@IceCupe123 TL;DR Once you are on the Install Failed admin page, add /manage in the end and you'll be able to toggle the status just fine ;)
