### ISSUE TITLE
Console still not updating occasionally 1.0 RC.5

### ISSUE THREAD

**Issue by ablac** [pterodactyl/panel#2342] opened 2020-09-14 16:38 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0 RC 5/Wings RC 5
* Server's OS: CentOS 8.2
* Your Computer's OS & Browser: Google Chrome

**Describe the bug**
After a full server restart, and making sure wings is running, as well as docker, I started the server, and the console failed to update. Though this was remedied by a Restart of wings. Refreshing the panel does update the console, but it will not update live till doing "systemctl restart wings"

**To Reproduce**
Do a full server Reboot "sudo reboot"
Login to the panel
Click start on a Minecraft server.

**Expected behavior**
When the server boots, and accessing the panel, the Consoles should work as expected, and not get froze, until you reload the panel or restart wings.

**Comment by MrSheen123** [comment] 2020-09-14 19:31
This bug occurs when the containers have not been shut down before a reboot. Once you log into the panel you have to restart Wings while on every server console that is affected before the console, RAM and CPU usage resume working properly.

**Comment by DaneEveritt** [comment] 2020-09-14 21:53
Can you try downloading and running this build on your machine to see if the issue is solved. I ended up rewriting a ton of the logic that was super fragile, should work a lot better.

https://github.com/pterodactyl/wings/actions/runs/252795306

You have to download this on your computer and manually upload, GitHub doesn't support unauthenticated downloads for some stupid reason.

**Comment by ablac** [comment] 2020-09-14 21:54
I will do that tonight, and let you know!

**Comment by sachk** [comment] 2020-09-15 07:42
@DaneEveritt's build appears to have entirely fixed the issue for me

**Comment by DaneEveritt** [comment] 2020-09-17 03:21
Closing as we seem to have resolved it.

**Closed by DaneEveritt** 2020-09-17 03:21 UTC
