### ISSUE TITLE
Mod/Plugin selector

### ISSUE THREAD

**Issue by RedstoneWizard08** [pterodactyl/panel#4029] opened 2022-03-29 15:14 UTC
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to see a panel inside each server's control panel that allows you to choose mods or plugins to install on the server. This could use the CurseForge API for CurseForge mods and the SpiGet API for SpigotMC/Paper/Bukkit plugins.

### Describe the solution you'd like.

This panel would automatically only show you the plugins or mods that are compatible with the server's game version. This would also only show up if you are running a compatible server. Ex: If you are running a vanilla server this panel will not show up. However, if you are running a Fabric/Forge/Bukkit server, it will show up.

### Additional context to this request.

This could also be implemented for games other than Minecraft, but I don't know the modding systems for that.

**Comment by trenutoo** [comment] 2022-03-29 15:27
Duplicate of #3283 and #1084

**Comment by matthewpi** [comment] 2022-03-29 15:28
Game specific features like this most likely not be implemented, not to mention the limited development time available.

**Closed as completed by matthewpi** 2022-03-29 15:28 UTC
