### ISSUE TITLE
Server creation using API

### ISSUE THREAD

**Issue by BeastGamer81** [pterodactyl/panel#4096] opened 2022-05-30 13:39 UTC
### Current Behavior

When i tried to create a server using API it reported an error version 1.8.0 broke the api

### Expected Behavior

Server should have been created

### Steps to Reproduce

Make api as 1.7 

### Panel Version

1.8.0

### Wings Version

1.6.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by BeastGamer81** [comment] 2022-05-30 13:39
Iam not a coder so i don't really know what to do

**Comment by parkervcp** [comment] 2022-05-30 13:39
You have given no logs or errors for us to look at here.

**Comment by Boy132** [comment] 2022-05-30 13:40
Duplicate of #4092 (probably)

**Closed as completed** 2022-05-30 14:00 UTC
