### ISSUE TITLE
Daemon 0.5.4 fails to start after upgrade from 0.4.x due to not finding containers

### ISSUE THREAD

**Issue by schrej** [pterodactyl/panel#1023] opened 2018-03-05 16:44 UTC
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.4.x -> 0.5.4

----

Following the daemon upgrade guide when upgrading from 0.4.x to 0.5.4 results in errors that prohibit the daemon from starting.
https://hastebin.com/ebegixucuw

Probably related to the new way of finding containers using the uuid. We should actually never fail to start when not finding containers as they can always be recreated.

**Comment by DaneEveritt** [comment] 2018-03-06 04:41
I am unable to replicate this on my dev environment, even after downgrading to `docker-ce=17.05.0-ce`. I tried normal daemon operations, editing each `server.json` file to point to a non-existent container, and also pruning existing containers after they were created. Nothing has triggered that error and unfortunately the stack trace provided doesn't really point towards anything specific.

**Comment by vipesz** [comment] 2018-03-06 05:06
I might know a few **possible** solutions.

Are you running a CentOS machine?

**Comment by DaneEveritt** [comment] 2018-03-06 05:06
```
Kernel Version: 4.9.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
```

**Comment by vipesz** [comment] 2018-03-06 05:13
interesting, what's the output of `docker ps -a`

**Comment by DaneEveritt** [comment] 2018-03-06 06:32
Can you please check and see if the latest changes to the development branch fix this problem?

**Comment by Bl4ckSpr4y** [comment] 2018-03-08 16:59
Daemon version: 0.5.4
I tested this a little bit, it turns out I get that error after the upgrade from 0.4.x with servers STILL RUNNING during the upgrade. Restarting Docker (stops all containers), running ```docker system prune``` , and running the panel rebuild command seems to fix it.

**Comment by Bl4ckSpr4y** [comment] 2018-03-08 20:35
https://asciinema.org/a/oUbJvUng3wExPdqbgt6zBEduQ
That's what happens when you try to upgrade the daemon when servers are still running.
Easy fix: ```systemctl restart docker``` so all containers get stopped and ```docker system prune``` to remove them.

**Comment by DaneEveritt** [comment] 2018-03-09 02:06
Closing this as the errors are addressed in the development branch, and the actual issue is caused by something that is covered as a step in the documentation. 👍

**Closed by DaneEveritt** 2018-03-09 02:06 UTC
Labels: Bug, P: High
