### ISSUE TITLE
"Build Configuration" is not updated

### ISSUE THREAD

**Issue by lMozGl** [pterodactyl/panel#3622] opened 2021-09-14 14:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

For the created server, when trying to update the "Build Configuration" data, all the settings that were changed after the creation are not saved, but return to the old values.

### Expected Behavior

"Build Configuration" settings will be saved and used after server restart

### Steps to Reproduce

I looked for an error on my server and in the logs but found nothing.
Then I found the script "/var/www/pterodactyl/app/Services/Servers/BuildModificationService.php" and copied the method "handle(Server $server, array $data)" from the previous version of the panel (1.4.2) and everything worked.
An example of what happened to me: https://pastebin.com/fwzHN0tb

### Panel Version

1.6.0

### Wings Version

1.5.0

### Error Logs

```bash
There were no error logs
```

**Comment by trenutoo** [comment] 2021-09-14 14:28
Update your panel. It was fixed in 1.6.1

Duplicate of #3613

**Closed as completed by trenutoo** 2021-09-14 14:28 UTC
