### ISSUE TITLE
Backup Failed

### ISSUE THREAD

**Issue by RealH0peLess** [pterodactyl/panel#3691] opened 2021-10-18 21:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

i have a critical bug: the panel can't backup big servers, my server has about 100GB of data and the backup fails every time
all other servers with around 20GB have no problems

### Expected Behavior

The panel should backup the server on my wasabi cloud storage via S3.

### Steps to Reproduce

Try to backup a very big minecraft server with over 120GB of data via S3.

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

```bash
https://ptero.co/ivokugofoj.makefile
https://bin.ptdl.co/in6jw/
```

**Comment by PadowYT2** [comment] 2021-10-19 00:35
duplicate of #3334

**Comment by matthewpi** [comment] 2021-10-19 00:57
> duplicate of #3334

No, it is not a duplicate.

---

`write tcp XXXXX:53172->38.91.42.22:443: write: connection reset by peer`

This is a problem with your server's connection to Wasabi, which is causing it to fail while uploading a part.

**Closed as completed by matthewpi** 2021-10-19 00:57 UTC

**Comment by RealH0peLess** [comment] 2021-10-19 09:23
And why does the other backups work? Its only when I want to backup big files. Wasabi is a S3 Storage, for files over 1000 TB of data. it must be the panel
