### ISSUE TITLE
Wings Error 

### ISSUE THREAD

**Issue by Pidihajzlikhra** [pterodactyl/panel#2371] opened 2020-09-18 23:32 UTC
I followed the instructions until I got to the  wings --debug and then it wrote this

panic: yaml: unmarshal errors:
  line 17: cannot unmarshal !!map into []string

goroutine 1 [running]:
github.com/pterodactyl/wings/cmd.rootCmdRun(0x17ded20, 0xc0001eb700, 0x0, 0x1)
        /home/runner/work/wings/wings/cmd/root.go:110 +0x21a8
github.com/spf13/cobra.(Command).execute(0x17ded20, 0xc00000e090, 0x1, 0x1, 0x17ded20, 0xc00000e090)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(Command).ExecuteC(0x17ded20, 0x0, 0xffffffff, 0xc000096058)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/pterodactyl/wings/cmd.Execute(...)
        /home/runner/work/wings/wings/cmd/root.go:355
main.main()
        /home/runner/work/wings/wings/wings.go:8 +0x2e

**Comment by matthewpi** [comment] 2020-09-18 23:37
Duplicate of #2631

**Closed** 2020-09-18 23:38 UTC
