### ISSUE TITLE
FR: Option to restore backup without downloading to local machine

### ISSUE THREAD

**Issue by zefir-git** [pterodactyl/panel#2924] opened 2020-12-28 10:42 UTC
**Is your feature request related to a problem? Please describe.**
With Minecraft's poor optimisation, backups can super easily get to 40GB and above for a very inactive and small vanilla server (especially preloaded worlds). To restore a backup, you need to download the file and then upload it, which is x2 transfer data than the size the file.

**Describe the solution you'd like**
The transfer data could be minimised to the size of the file (and to 0 for the client). Add an option to `Run` or `Restore` a backup, which downloads it directly to the target container (e.g. with get or curl), server-side. Furthermore, it is more likely that a server will have better connectivity than a residential computer. The server should be shut down and all other files deleted before the backup is extracted.

**Comment by fabm3n** [comment] 2020-12-28 12:05
Dupe of #2016 which is a restore function

**Comment by zefir-git** [comment] 2020-12-28 13:38
> Dupe of #2016 which is a restore function

That seems to be about reinstalling the server and with that restoring a backup, which I find to be a bad idea. Restoring a backup should not require a full reinstall, a reboot of the container ought to be more that sufficient to flush data in memory.

**Comment by matthewpi** [comment] 2020-12-28 16:41
> > Dupe of #2016 which is a restore function
> 
> That seems to be about reinstalling the server and with that restoring a backup, which I find to be a bad idea. Restoring a backup should not require a full reinstall, a reboot of the container ought to be more that sufficient to flush data in memory.

Restoring a backup would not trigger a reinstall of a server, regardless of what that issue is requesting.

**Closed as completed by matthewpi** 2020-12-28 16:41 UTC
