### ISSUE TITLE
"xhr poll error" on "Nodes / <Node> / Servers" page

### ISSUE THREAD

**Issue by BrainStone** [pterodactyl/panel#2284] opened 2020-08-28 23:46 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-rc.2
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 + Firefox 80.0 (64-bit)

**Describe the bug**
When opening the URL `<panel_URL>/admin/nodes/view/<node>/servers` the server stats don't show and I get a red error popup that has the error message "xhr poll error". Screenshot:  
![grafik](https://user-images.githubusercontent.com/4106544/91622659-855d3380-e998-11ea-82d7-eb9a7ac834a5.png)

In the Browser console it shows that it tries to reach the URL ``https://undefined/socket.io?...``  
![grafik](https://user-images.githubusercontent.com/4106544/91622842-58f5e700-e999-11ea-979a-caafd6c00348.png)

`php -v`:  
```
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
```

**To Reproduce**
1. Go to the admin area
2. Go to Nodes, select a node, then Servers
3. Error pops up.
4. Open server console to see it trying to reach the URL mentioned above

**Expected behavior**
The panel being able to properly pull the server data.

**Comment by Sir3lit** [comment] 2020-08-29 00:58
Duplicate of #1942

**Closed** 2020-08-29 01:42 UTC
