### ISSUE TITLE
Suspend Server console loading state

### ISSUE THREAD

**Issue by windlessme** [pterodactyl/panel#4248] opened 2022-07-09 16:13 UTC
### Current Behavior

when the server is Suspend, 
The server console is always loading
![image](https://user-images.githubusercontent.com/83590234/178113769-9169cabd-0704-4c2a-945e-517daa9c3f07.png)

### Expected Behavior

The console renders the loading state

### Steps to Reproduce

suspend the server, enter the server console.

### Panel Version

1.9.2

### Wings Version

1.6.4

### Games and/or Eggs Affected

all

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment] 2022-07-09 16:15
Duplicate of #4235

**Closed as completed** 2022-07-09 16:17 UTC
