### ISSUE TITLE
Panel server status problem 0.8-alpha

### ISSUE THREAD

**Issue by DarKiiii** [pterodactyl/panel#1805] opened 2020-01-03 09:03 UTC
**Background (please complete the following information):**
* Panel or Daemon: Both
* Version of Panel/Daemon: 0.8-alpha / 1.0-alpha
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 / Chrome

**Describe the bug**
So, I installed a gmod server, but when I start it, the resources graphs does not change and when I leave the panel and re-open it, the server is marked as offline and the resources graphs are saying "server offline" but the server continue to run and when I press start the graphs appears and the server is marked as online.

*My server was actually starting*
![Capture3](https://user-images.githubusercontent.com/52256277/71714855-aec8be00-2e0f-11ea-960d-de41b118da54.PNG)

*Just pressed start*
![Capture4](https://user-images.githubusercontent.com/52256277/71714923-e9325b00-2e0f-11ea-866c-e0a97f479912.PNG)

**To Reproduce**
1. Start a server
2. Close the panel
3. Open the panel
4. Go on your server page

**Expected behavior**
I expected that the server would be marked as online when online and offline when offline and that the resources graphs will work

**Comment by DarKiiii** [comment] 2020-01-03 11:57
Hum, idk why but I restarted my daemon and now it works

**Comment by DarKiiii** [comment] 2020-01-03 12:44
Hum, sometimes it works, sometimes not so ...

**Comment by DaneEveritt** [comment] 2020-01-03 15:08
Duplicate of #1802 see https://github.com/pterodactyl/panel/issues/1802#issuecomment-570335564

**Closed by DaneEveritt** 2020-01-03 15:08 UTC
Labels: 0.8.0-alpha, Go Daemon
