### ISSUE TITLE
[Wings] Invalid memory address or nil pointer dereference error on ARM build

### ISSUE THREAD

**Issue by wardpieters** [pterodactyl/panel#2698] opened 2020-11-10 19:11 UTC
* Panel or Daemon: Daemon / Wings
* Version of Panel/Daemon: Panel 1.1.1 / Wings 1.1.1
* Server's OS: Raspbian GNU/Linux 10 (buster) (armv7l) (ARM)
* Your Computer's OS & Browser: N/A

**Describe the bug**
Tried to upgrade Wings to version 1.1.1. Encountered the following error after starting it (using `wings --debug`):
```
DEBUG: [Nov 10 19:57:02.004] syncing stop configuration with configured docker environment server=7bf7dd5d-99e9-42fc-a6af-e0ca69721b52
 INFO: [Nov 10 19:57:02.008] finished processing server configurations duration=17.150758ms
 INFO: [Nov 10 19:57:02.018] loaded configuration for server server=f308d45f-3ffc-40ba-b759-59931c7af826
 INFO: [Nov 10 19:57:02.020] loaded configuration for server server=7bf7dd5d-99e9-42fc-a6af-e0ca69721b52
 INFO: [Nov 10 19:57:02.021] configuring server environment and restoring to previous state server=7bf7dd5d-99e9-42fc-a6af-e0ca69721b52
 INFO: [Nov 10 19:57:02.022] configuring server environment and restoring to previous state server=f308d45f-3ffc-40ba-b759-59931c7af826
 INFO: [Nov 10 19:57:02.031] detected server is running, re-attaching to process... server=7bf7dd5d-99e9-42fc-a6af-e0ca69721b52
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11db8]

goroutine 21 [running]:
runtime/internal/atomic.goStore64(0x2d34564, 0xa6f0aa, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/runtime/internal/atomic/atomic_arm.go:144 +0x1c
github.com/pterodactyl/wings/server.(*Server).Proc(0x2d343c0, 0x0)
        /home/runner/work/wings/wings/server/resources.go:48 +0x4c
github.com/pterodactyl/wings/server.(*Server).OnStateChange(0x2d343c0)
        /home/runner/work/wings/wings/server/state.go:66 +0x1c
github.com/pterodactyl/wings/server.(*Server).StartEventListeners.func2(0xa2d5ce, 0x7, 0xa32952, 0xc)
        /home/runner/work/wings/wings/server/listeners.go:103 +0x2c
github.com/pterodactyl/wings/events.(*EventBus).Publish.func1()
        /home/runner/work/wings/wings/events/events.go:62 +0x40
github.com/gammazero/workerpool.startWorker(0x2e5eba0, 0x2c5bfc0)
        /home/runner/go/pkg/mod/github.com/gammazero/workerpool@v1.0.0/workerpool.go:194 +0x1c
created by github.com/gammazero/workerpool.(*WorkerPool).dispatch
        /home/runner/go/pkg/mod/github.com/gammazero/workerpool@v1.0.0/workerpool.go:156 +0x238
```
This has probably something to do with https://github.com/pterodactyl/wings/commit/944d3817787ba44f361c8a228ea622d1e21d152c or https://github.com/pterodactyl/wings/commit/e29789114cfd79a741a7117da170018ce1a3f113.

**To Reproduce**
Execute the following commands on a ARM based device (e.g. a Raspberry Pi 4):
1. `curl -L -o /usr/local/bin/wings https://github.com/pterodactyl/wings/releases/download/v1.1.1/wings_linux_arm`
2. `chmod u+x /usr/local/bin/wings`
3. `wings --debug`

**Expected behavior**
A working daemon.

**Additional information**
If you need more information or want to test somehting, just let me know. You can also contact me on Discord.

**Comment by matthewpi** [comment] 2020-11-29 00:03
Please try https://github.com/pterodactyl/wings/suites/1576577848/artifacts/28483400 and see if the problem is resolved, this may be a problem with go itself.

**Comment by wardpieters** [comment] 2020-11-29 00:50
Hi @matthewpi, I am using ARM, not ARM64. I've downloaded artifact 28483399, which is build for ARM. Unfortunately it resulted in the same error.

```
DEBUG: [Nov 29 01:46:08.652] syncing stop configuration with configured docker environment server=7bf7dd5d-99e9-42fc-a6af-e0ca69721b52
DEBUG: [Nov 29 01:46:08.654] syncing server settings with environment server=7bf7dd5d-99e9-42fc-a6af-e0ca69721b52
 INFO: [Nov 29 01:46:08.656] performing server limit modification on-the-fly server=7bf7dd5d-99e9-42fc-a6af-e0ca69721b52
DEBUG: [Nov 29 01:46:08.659] parsing server configuration file parser=yaml path=/var/lib/pterodactyl/volumes/7bf7dd5d-99e9-42fc-a6af-e0ca69721b52/config.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11db8]

goroutine 97 [running]:
runtime/internal/atomic.goStore64(0x24b4384, 0xa6f178, 0x0)
	/opt/hostedtoolcache/go/1.15.5/x64/src/runtime/internal/atomic/atomic_arm.go:144 +0x1c
github.com/pterodactyl/wings/server.(*Server).Proc(0x24b41e0, 0x0)
	/home/runner/work/wings/wings/server/resources.go:48 +0x4c
github.com/pterodactyl/wings/server.(*Server).OnStateChange(0x24b41e0)
	/home/runner/work/wings/wings/server/state.go:65 +0x1c
github.com/pterodactyl/wings/server.(*Server).StartEventListeners.func2(0xa2e69e, 0x8, 0xa32605, 0xc)
	/home/runner/work/wings/wings/server/listeners.go:102 +0x2c
github.com/pterodactyl/wings/events.(*EventBus).Publish.func1()
	/home/runner/work/wings/wings/events/events.go:61 +0x40
github.com/gammazero/workerpool.startWorker(0x22ccd60, 0x2059b40)
	/home/runner/go/pkg/mod/github.com/gammazero/workerpool@v1.0.0/workerpool.go:194 +0x1c
created by github.com/gammazero/workerpool.(*WorkerPool).dispatch
	/home/runner/go/pkg/mod/github.com/gammazero/workerpool@v1.0.0/workerpool.go:156 +0x238
```

**Comment by DaneEveritt** [comment] 2020-12-06 23:19
Yes, this won't work because we're trying to store a 64 bit value.

**Comment by DaneEveritt** [comment] 2020-12-06 23:20
Closing this as 32-bit systems are not supported by Wings and I have no desire to deal with trying to support them.

**Closed as completed by DaneEveritt** 2020-12-06 23:20 UTC
