### ISSUE TITLE
Change theme colors & other customizations

### ISSUE THREAD

**Issue by calebgruber** [pterodactyl/panel#4292] opened 2022-07-31 17:57 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to see a bunch more options under settings to input your color or image to be displayed on the background of the panel instead of the default colors.  

This could also give the ability to also change the icons.  Logo is already implemented. 

### Describe the solution you'd like.

Under admin settings a new tab would allow for color and theme settings.

**Comment by trenutoo** [comment] 2022-07-31 18:27
Duplicate of #3252 #3013

**Closed as completed** 2022-09-23 01:16 UTC
