### ISSUE TITLE
Own Simple Server Templates or Server Dupliation/Cloning

### ISSUE THREAD

**Issue by ozanaaslan** [pterodactyl/panel#3543] opened 2021-08-14 11:35 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The ability to either clone/duplicate an already existing server and run them simultaneously.
The use case here would be f.e. Round based games like Bedwars or Skywars.
So there is one server, of which the already set up data is being cloned to another instance .

It would be too complicated to create another server manually and reconfigure this server manually even though you already have one completely finished.

OR you can select an already existing server as template on server creation. 
So all plugins and worlds are being copied..

I know that you could create an egg, but it would be too complicated..
 

### Describe the solution you'd like.

Templates:
Click on "Create New" in "Servers".
With a dropdown in "core details". "SelectServer Template" (Not required)-

Clone/Duplicating:
The "Servers" tab.
Each entry has an icon for cloning on the left next to "Active".
If clicked, another entry is being added below with all the exact same files and configurations of the server.

### Additional context to this request.

As already mentioned, it would be very useful for round-based games or Networks that need multiple similar servers in general.

I'd donate for it :D

**Comment by FoksVHox** [comment] 2021-08-14 11:51
Duplicate of #2059 & #2148

**Comment by notAreYouScared** [comment] 2021-08-14 12:49
You could also do this with the install script. Have it download a package of files you've created, extract them and then it would be set.... IF the world, configs, plug-ins etc. Don't need to be changed.

**Closed as completed** 2021-08-14 14:00 UTC
