### ISSUE TITLE
Docker - Restore Last Power State of Containers

### ISSUE THREAD

**Issue by BLEEPBLOOPforLife** [pterodactyl/panel#1383] opened 2018-11-13 22:00 UTC
**Is your feature request related to a problem? Please describe.**

Yes. When Docker updates through apt-get, all docker containers shut down including the game server docker containers.

**Describe the solution you'd like**

I would like all Docker containers created by Pterodactyl to restore the last power state whenever Docker starts/restarts.

**Describe alternatives you've considered**

None.

**Additional context**

Nothing else. The solution is just to have the daemon add to the Docker container configuration file to restore the last power state.

**Comment by parkervcp** [comment] 2018-11-13 22:04
Duplicate of #136 Please check before opening issues.

**Closed by parkervcp** 2018-11-13 22:04 UTC
