### ISSUE TITLE
Feature request: Add hcaptcha option

### ISSUE THREAD

**Issue by ririko5834** [pterodactyl/panel#3107] opened 2021-02-21 09:20 UTC
Hello, can you add also hcaptcha option for securing panel?

**Comment by FoksVHox** [comment] 2021-02-22 11:04
Use the templates that have been provided... They're there for a reason. This issue will be closed if you don't update it to use the provided templates for requesting features.

**Comment by RihanArfan** [comment] 2021-02-22 13:58
Duplicate of #1895 and #1958.

**Closed as completed** 2021-02-22 16:23 UTC
