### ISSUE TITLE
server over ~20-30gb marks backup as failed

### ISSUE THREAD

**Issue by JakeySuccessor** [pterodactyl/panel#2751] opened 2020-11-26 20:32 UTC
**Background (please complete the following information):**
* Panel or Daemon: V1.1.1
* Version of Panel/Daemon: V1.1.1 
* Server's OS:  Ubuntu 18.04
* Your Computer's OS & Browser:  Chrome & Windows 10

**Describe the bug**

ERROR: [Nov 26 20:16:31.836] failed to generate backup for server error=backup: error while generating server backup: archive/tar: write too long server=3dbdbdcf-744e-4680-b070-b313c3f09c3c
panic: interface conversion: errors.withMessage is not cli.tracer: missing method StackTrace

goroutine 319 [running]:
github.com/pterodactyl/wings/loggers/cli.getErrorStack(0x1181f40, 0xc0016700c0, 0xc006d6b401, 0x49, 0x1181f40, 0xc0016700c0)
        /home/runner/work/wings/wings/loggers/cli/cli.go:91 +0xb9
github.com/pterodactyl/wings/loggers/cli.getErrorStack(0x1181f40, 0xc001670040, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/wings/wings/loggers/cli/cli.go:94 +0x152
github.com/pterodactyl/wings/loggers/cli.(Handler).HandleLog(0xc00028f780, 0xc00021aa10, 0x0, 0x0)
        /home/runner/work/wings/wings/loggers/cli/cli.go:76 +0x61a
github.com/apex/log/handlers/multi.(Handler).HandleLog(0xc000637f20, 0xc00021aa10, 0x10512ad, 0x24)
        /home/runner/go/pkg/mod/github.com/apex/log@v1.8.0/handlers/multi/multi.go:26 +0x6f
github.com/apex/log.(Logger).log(0x17d97d0, 0x3, 0xc00021a9a0, 0x10512ad, 0x24)
        /home/runner/go/pkg/mod/github.com/apex/log@v1.8.0/logger.go:146 +0x7c
github.com/apex/log.(*Entry).Error(...)
        /home/runner/go/pkg/mod/github.com/apex/log@v1.8.0/entry.go:96
github.com/pterodactyl/wings/router.postServerBackup.func1(0x11a30e0, 0xc000842cf0, 0xc00054a780)
        /home/runner/work/wings/wings/router/router_server_backup.go:43 +0x145
created by github.com/pterodactyl/wings/router.postServerBackup
        /home/runner/work/wings/wings/router/router_server_backup.go:41 +0x29b

**To Reproduce**
1. Any server around ~20-30gb+
2. Backup
3. wait around 10min it should fail for "archive/tar: write too long server"

**Expected behavior**
Should still make the backup and not stop the backup if it is larger than ~20-30gb

**Comment by matthewpi** [comment] 2020-11-26 23:12
This happens when a file was edited while it was being read from, this is a duplicate of https://github.com/pterodactyl/panel/issues/2068

**Closed as completed by matthewpi** 2020-11-26 23:12 UTC
