### ISSUE TITLE
Bundle.js Error Cannot view server console when I build the project after doing changes

### ISSUE THREAD

**Issue by ShootDot** [pterodactyl/panel#2507] opened 2020-10-13 12:48 UTC
Hey there, 
I am using Panel 1.0.1
Ubuntu 20.04
Brave Browser Windows 10 Pro 
I have changed some of the files in the panel then when I built using the command `yarn build:production` it builds successfully. But then when I navigate to server console I see a blank screen with bunch of errors in browser console. I have noted all errors below.
`bundle.c5edd476.js:1 TypeError: (intermediate value)(intermediate value) is not a function
    at Lc (bundle.c5edd476.js:1)
    at vs (bundle.c5edd476.js:1)
    at hs (bundle.c5edd476.js:1)
    at ms (bundle.c5edd476.js:1)
    at is (bundle.c5edd476.js:1)
    at bundle.c5edd476.js:1
    at t.unstable_runWithPriority (bundle.c5edd476.js:1)
    at La (bundle.c5edd476.js:1)
    at Ua (bundle.c5edd476.js:1)
    at Ba (bundle.c5edd476.js:1)
nc @ bundle.c5edd476.js:1
n.callback @ bundle.c5edd476.js:1
io @ bundle.c5edd476.js:1
lc @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
ws @ bundle.c5edd476.js:1
t.unstable_runWithPriority @ bundle.c5edd476.js:1
La @ bundle.c5edd476.js:1
bs @ bundle.c5edd476.js:1
is @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
t.unstable_runWithPriority @ bundle.c5edd476.js:1
La @ bundle.c5edd476.js:1
Ua @ bundle.c5edd476.js:1
Ba @ bundle.c5edd476.js:1
ts @ bundle.c5edd476.js:1
_i @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
g @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
o @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
u @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
n @ bundle.c5edd476.js:1
c @ bundle.c5edd476.js:1
Promise.then (async)
n @ bundle.c5edd476.js:1
c @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
u @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
Os @ bundle.c5edd476.js:1
t.unstable_runWithPriority @ bundle.c5edd476.js:1
La @ bundle.c5edd476.js:1
Ss @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
M @ bundle.c5edd476.js:1
x.port1.onmessage @ bundle.c5edd476.js:1
Show 39 more frames
bundle.c5edd476.js:1 TypeError: (intermediate value)(intermediate value) is not a function
    at Lc (bundle.c5edd476.js:1)
    at vs (bundle.c5edd476.js:1)
    at hs (bundle.c5edd476.js:1)
    at ms (bundle.c5edd476.js:1)
    at is (bundle.c5edd476.js:1)
    at bundle.c5edd476.js:1
    at t.unstable_runWithPriority (bundle.c5edd476.js:1)
    at La (bundle.c5edd476.js:1)
    at Ua (bundle.c5edd476.js:1)
    at Ba (bundle.c5edd476.js:1)
nc @ bundle.c5edd476.js:1
n.callback @ bundle.c5edd476.js:1
io @ bundle.c5edd476.js:1
lc @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
ws @ bundle.c5edd476.js:1
t.unstable_runWithPriority @ bundle.c5edd476.js:1
La @ bundle.c5edd476.js:1
bs @ bundle.c5edd476.js:1
is @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
t.unstable_runWithPriority @ bundle.c5edd476.js:1
La @ bundle.c5edd476.js:1
Ua @ bundle.c5edd476.js:1
Ba @ bundle.c5edd476.js:1
ts @ bundle.c5edd476.js:1
_i @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
g @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
o @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
u @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
n @ bundle.c5edd476.js:1
c @ bundle.c5edd476.js:1
Promise.then (async)
n @ bundle.c5edd476.js:1
c @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
u @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
e @ bundle.c5edd476.js:1
Os @ bundle.c5edd476.js:1
t.unstable_runWithPriority @ bundle.c5edd476.js:1
La @ bundle.c5edd476.js:1
Ss @ bundle.c5edd476.js:1
(anonymous) @ bundle.c5edd476.js:1
M @ bundle.c5edd476.js:1
x.port1.onmessage @ bundle.c5edd476.js:1
Show 39 more frames
bundle.c5edd476.js:1 TypeError: (intermediate value)(intermediate value) is not a function
    at Lc (bundle.c5edd476.js:1)
    at vs (bundle.c5edd476.js:1)
    at hs (bundle.c5edd476.js:1)
    at ms (bundle.c5edd476.js:1)
    at is (bundle.c5edd476.js:1)
    at bundle.c5edd476.js:1
    at t.unstable_runWithPriority (bundle.c5edd476.js:1)
    at La (bundle.c5edd476.js:1)
    at Ua (bundle.c5edd476.js:1)
    at Ba (bundle.c5edd476.js:1)`

**Comment by DaneEveritt** [comment] 2020-10-13 15:23
Please use a non-production build and provide the errors. This is _completely_ useless for debugging.

Additionally, since your issue stems from custom modifications you have made I am closing this issue unless you can show it is caused by shipped Panel code.

**Closed as completed by DaneEveritt** 2020-10-13 15:23 UTC

**Comment by ShootDot** [comment] 2020-10-13 15:26
How do I use non production build ?
Command please

**Comment by notAreYouScared** [comment] 2020-10-13 23:24
You get this error when you do yarn upgrade and then try and build

**Comment by ShootDot** [comment] 2020-10-14 02:45
Yea I dis that so how do I fix it ?
