### ISSUE TITLE
sftp "The username field is required." even tho username is set.

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3680] opened 2021-10-11 11:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

![Selection_999(3530)](https://user-images.githubusercontent.com/6473565/136786977-6052b1ce-eef0-44d5-a781-a2455013b522.jpg)

### Expected Behavior

no " The username field is required." because username is sent. You can see it in screenshot log.

### Steps to Reproduce

Unfortunately as all issues from me - no way to reproduce. It just happens randomly for me. I have script which checks if ftp works 24/7 and this happens only ocassionally..

### Panel Version

1.6.2

### Wings Version

1.5.0

### Error Logs

```bash
in screenshot
```

**Comment by OpenSource03** [comment] 2021-10-12 13:02
I'm almost sure this is due to improper configuration. Never seen such issue.

**Comment by BenasPaulikas** [comment] 2021-10-20 19:14
@OpenSource03 thank you for your comment. I'm using default settings. This issue happens "ocasionally" not everytime. So it can't be improper configuration.
On top of that I wrote script to check ftp and it works almost everytime except these "ocasionally" and then it auto fixes...

I've checked apache2 logs and it shows that panel is returning 422...

Also checked laravel log and nothing there.

Based on this log how can it be improper configuration?
Error response from Panel: ValidationException: **The username field is required.** (HTTP/422) ip=*hidden*:22970 subsystem=sftp username=**user_140664.a3ee703e**

**Comment by BenasPaulikas** [comment] 2021-10-20 19:19
@OpenSource03 also do you have any specific configuration in mind ? Are you referring to panel or wings configuration ?

**Comment by DaneEveritt** [comment] 2021-10-24 22:07
I can't reproduce this at all, even flooding that endpoint. It really sounds like you have something sitting in front of the panel that is scrubbing the request and dropping or modifying the data in the request. The username displayed in your logs simply means Wings is tracking that specific username for the internal request, not that the Panel actually got that value.

Due the the lack of any actionable reproduction steps and my limited time I'm closing this out. I have no idea what is wrong.

**Closed as completed by DaneEveritt** 2021-10-24 22:07 UTC
