### ISSUE TITLE
User Server Console not live updating

### ISSUE THREAD

**Issue by Maelep** [pterodactyl/panel#3918] opened 2022-01-26 10:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

The user server console doesn't update in live since the last update of the Panel/Wings. I have to refresh the page to update the console.

### Expected Behavior

Live update console.

### Steps to Reproduce

Start a Rust game server, wait for the server started, send `save`: Nothing appear in the console.
CTRTL + R (refresh):
```
save
Invalidate Network Cache took 0.01 seconds
Saved 61,628 ents, cache(0.18), write(0.02), disk(0.03).
Saving complete
```

### Panel Version

1.7.0

### Wings Version

1.5.6

### Error Logs

```bash
Panel: https://bin.ptdl.co/ac5o9/
Wings: https://ptero.co/usupemuzyd
```

**Comment by Jelcoo** [comment] 2022-01-26 11:00
```
ERROR: [Jan 25 23:07:56.682] failed to send event over server websocket connection=d636d04b-b136-402e-9baa-9a26a043fb98 error=write tcp 142.132.158.61:8080->213.189.178.77:58503: use of closed network connection event=stats server=72b07591-8044-4418-bf7a-0ff61ab9981d subsystem=websocket

Stacktrace:
write tcp 142.132.158.61:8080->213.189.178.77:58503: use of closed network connection
github.com/pterodactyl/wings/router/websocket.(*Handler).listenForServerEvents.func1
	/home/runner/work/wings/wings/router/websocket/listeners.go:99
github.com/pterodactyl/wings/router/websocket.(*Handler).listenForServerEvents
	/home/runner/work/wings/wings/router/websocket/listeners.go:145
github.com/pterodactyl/wings/router/websocket.(*Handler).registerListenerEvents.func1
	/home/runner/work/wings/wings/router/websocket/listeners.go:29
runtime.goexit
	/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581
```

**Comment by Maelep** [comment] 2022-01-26 11:02
Can you help me to resolve this?

**Comment by Talhazzers** [comment] 2022-01-26 11:52
I have the same error happening sometimes in version 1.6.6. Restarting wings fixes the problem but recurs after a while.
When i have this problem cpu, memory graphics and console are not updating.

**Comment by Maelep** [comment] 2022-01-26 12:00
> I have the same error happening sometimes in version 1.6.6. Restarting wings fixes the problem but recurs after a while. When i have this problem cpu, memory graphics and console are not updating.

I confirm, restarting Wings make it works but for only some messages...

**Comment by wyatt-herkamp** [comment] 2022-01-26 15:47
Hey, I would like to say I am also having this issue after updating to 1.7.0. It is also stuck on saying starting.

**Comment by Talhazzers** [comment] 2022-01-26 15:49
> Hey, I would like to say I am also having this issue after updating to 1.7.0. It is also stuck on saying starting.

My problem is when the server is online and it happens sometimes

**Comment by UnitedCraft** [comment] 2022-01-26 18:48
I have the same problem. Only restarting the browser resolves the problem.

**Comment by Prisma501** [comment] 2022-01-27 13:07
Can confirm behaviour on panel 1.7.0 with wings 1.5.6

**Comment by Maelep** [comment] 2022-01-27 17:53
It seems that not all messages aren't affected. Taking example of a Rust server, the console updates for many message but the command `status` and `serverinfo`doesn't update while `save` is live updated. From my observations, it seems to be related to messages coming from a `json` format.

**BEFORE REFRESHING**
<img width="911" alt="image" src="https://user-images.githubusercontent.com/53207714/151415546-9a36dea5-a42b-4299-ade7-8894a9f79cbd.png">

**AFTER REFRESHING**
<img width="911" alt="image" src="https://user-images.githubusercontent.com/53207714/151415648-0f4c8d9c-d0d6-4981-abd8-e5717b95f517.png">

**Comment by Talhazzers** [comment] 2022-01-27 22:29
When I have this problem, the whole console not refreshing, No message incoming. Cpu, ram graphics are not refreshed.

**Comment by Maelep** [comment] 2022-01-28 05:09
> It seems that not all messages aren't affected. Taking example of a Rust server, the console updates for many message but the command `status` and `serverinfo`doesn't update while `save` is live updated. From my observations, it seems to be related to messages coming from a `json` format.

The whole console seems to bug after an amount of time where any message need to be refreshed. Restarting Wings resolves some problems bug multiple lines output are still bugged.

**Comment by GaryCraft** [comment] 2022-01-29 03:36
Can confirm this issue, it happens consistently on Wings V1.5.6
Logs are often incomplete until reload.
The Panel does not update the Status from starting to Running.
Sometimes a server page stops updating (does not live update CPU, RAM, or Console) and only restarting Wings solves this issue.
# Screenshots
## Uncomplete logs
Logs are often incomplete in many situations, including some that log JSON structured things or others that take more than some amount of lines, for example trying to log a node.js thrown error

Before reload

![image](https://user-images.githubusercontent.com/68017132/151646106-2d4d6daf-2b61-41ac-9ec2-39326b3e7d18.png)

![image](https://user-images.githubusercontent.com/68017132/151646658-1ab6d622-811e-4bae-b822-1ee055f60150.png)

After reload

![image](https://user-images.githubusercontent.com/68017132/151646113-9ade9f08-0b45-49cf-ae30-a384d6047d6a.png)

![image](https://user-images.githubusercontent.com/68017132/151646685-5432d2b0-ee67-4229-a5dc-4f4cce0b97e1.png)

## Status not changing
Status does not change from ``Starting`` to ``Running`` even though the logs do send the expected message that indicates the server is fully running (this behavior has only been confirmed when the node was updated to Wings 1.5.6)

Expected behavior 

![image](https://user-images.githubusercontent.com/68017132/151646265-ef42476b-116f-4481-a92a-74a1320a091c.png)

Resulting behavior 

![image](https://user-images.githubusercontent.com/68017132/151646330-609d85ac-712a-4bbb-92f6-6f65a14ed5c5.png)

Server Egg Start Configuration

![image](https://user-images.githubusercontent.com/68017132/151646355-cd9d84a0-482e-4f6f-9543-46049e3a2ef6.png)

**Comment by trenutoo** [comment] 2022-01-30 15:59
This is a duplicate of #3921 that has been resolved on develop

**Comment by DaneEveritt** [comment] 2022-01-30 16:02
Please see [this comment for a beta build](https://github.com/pterodactyl/panel/issues/3921#issuecomment-1025173985) you can try running.

**Closed as completed** 2022-01-30 16:02 UTC

**Comment by IvMisticos** [comment] 2022-01-31 23:39
Suppose this has been merged into 1.6.0. If so, I am still getting this [Websocket does not return any data -> Server console and graphs do not update (live)].
```go
ERROR: [Jan 31 19:43:04.543] failed to send event over server websocket connection=23cad336-5988-4bda-b3aa-b01a6833772e error=write tcp server:8080->browser:63483: write: broken pipe event=stats server=823cd4e1-5eea-414b-95cc-b3c9bba53b3c subsystem=websocket

Stacktrace:
write tcp server:8080->browser:63483: write: broken pipe
github.com/pterodactyl/wings/router/websocket.(*Handler).listenForServerEvents.func1
        /home/runner/work/wings/wings/router/websocket/listeners.go:99
github.com/pterodactyl/wings/router/websocket.(*Handler).listenForServerEvents
        /home/runner/work/wings/wings/router/websocket/listeners.go:145
github.com/pterodactyl/wings/router/websocket.(*Handler).registerListenerEvents.func1
        /home/runner/work/wings/wings/router/websocket/listeners.go:29
runtime.goexit
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581
```

**Comment by DaneEveritt** [comment] 2022-02-01 00:39
I can't fix a bad network unfortunately. I don't know exactly what causes that issue, but it isn't anything from within the application.

**Comment by IvMisticos** [comment] 2022-02-01 09:25
err the error might be unrelated then? but is the only one I see. when it happens it happens for all panel users of the same node, all browsers etc so it is wings, restarting it fixes the issue also.

**Comment by trenutoo** [comment] 2022-02-01 11:00
> err the error might be unrelated then? but is the only one I see. when it happens it happens for all panel users of the same node, all browsers etc so it is wings, restarting it fixes the issue also. 

It wouldn't be related to the scan reader blockage that this issue was about. Your websocket issue most likely is #3528 or #3508 with your web browser console containing errors related to websocket connection close state

**Comment by IvMisticos** [comment] 2022-02-01 14:02
Well, initially this issue was about whatever I was experiencing. But guess further new comments have led it to a different issue lol. but as I've just said the first message is my case - "doesn't update in live" and stuff.
