### ISSUE TITLE
Reorder Servers

### ISSUE THREAD

**Issue by Vidsify** [pterodactyl/panel#3238] opened 2021-03-31 18:15 UTC
Having the ability to order serverd by Node or by Alphabetical order would be greatly beneficial so that the dashboard looks more presentable and easier to navigate.

**Comment by trenutoo** [comment] 2021-03-31 18:16
Duplicate of #1439

**Comment by parkervcp** [comment] 2021-03-31 18:16
duplicate of #498

**Closed as completed by parkervcp** 2021-03-31 18:16 UTC
