### ISSUE TITLE
failing variable in post request

### ISSUE THREAD

**Issue by merlinlcb** [pterodactyl/panel#2720] opened 2020-11-16 17:26 UTC
**Background**
Panel or Daemon: Panel
Version of Panel/Daemon: 1.1.1
Server's OS: Ubuntu 20.04 LTS
Your Computer's OS & Browser: tested via postman and through curl request

**Describe the bug**
the start_on_completion variable when creating a server via POST request no longer works after migrating to 1.1.1 from .7
Please provide additional information too, depending on what you have issues with:
Postman: 

**example post request body from postman sent to endpoint /api/application/servers**
`{
  "name": "test",
  "user": 9,
  "nest": 5,
  "egg": 25,
  "docker_image": "quay.io/parkervcp/pterodactyl-images:debian_openjdk-8-jre",
  "startup": "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar server.jar",
  "environment": {
    "SERVER_JARFILE": "server.jar",
    "BUILD_NUMBER": "latest",
    "DL_VERSION": "latest"
  },
  "limits": {
  "memory": 2048,
    "swap": -1,
    "disk": 500,
    "io": 500,
    "cpu": 100
  },
  "feature_limits": {
    "databases": 1,
    "allocations": 1,
    "backups": 0
  },
  "allocation": {
    "default": 285,
    "additional": []
  },
  "start_on_completion": true
}`

**To Reproduce**
Send any create server post request with the variable start_on_completion: true

**Expected behavior**
server should automatically start when installation completes

**Comment by notAreYouScared** [comment] 2020-11-16 18:51
Duplicate of #2384

**Closed as completed** 2020-11-16 19:22 UTC
