### ISSUE TITLE
Switch Daemon easily

### ISSUE THREAD

**Issue by CorruptedUbuntu** [pterodactyl/panel#1800] opened 2019-12-28 19:15 UTC
**Is your feature request related to a problem? Please describe.**
The request is not related to a problem but would be cool to have. This is something that I believe the panel is missing.

**Describe the solution you'd like**
Have a button from the admin side of the panel for all servers in the "Manage" section which you can select another Node/Daemon to switch too.

**Describe alternatives you've considered**
Being able to switch, the system will automatically try to assign the same port which was used for the old daemon and assign it but with the IP from the new node of course.
And if the port is available, it would just choose a random one available,
and if no ports are available it should send an error message like "There is no ports available on the target node." and if the target node does not have enough system resources to be able to move the server it should say "The node does not have enough system resources left in order to move this server.".

**Additional context**
Nope, hope you accept this feature! I think a lot of Minecraft servers, hosts and people would like this feature.

**Comment by DaneEveritt** [comment] 2019-12-28 19:18
Duplicate of #18

**Closed by DaneEveritt** 2019-12-28 19:18 UTC
