### ISSUE TITLE
Feature Request: Creating groups based on subuser permissions

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#310] opened 2017-02-18 01:07 UTC
Low priority feature request:

It would be cool to allow users to create groups based on permissions that they select for their subusers. For example, they could create an "Administrators" group and select all permissions, and then assign their subuser to that particular group. Then they could create a "File Editor" group and then give a few file editing permissions to that group, and then assign a couple of users to that group that they want to be able to edit certain files.

**Comment by DaneEveritt** [comment] 2017-02-18 01:08
duplicate of #101

**Closed by DaneEveritt** 2017-02-18 01:08 UTC
