### ISSUE TITLE
Disk space not shown after deleting files. until server start.

### ISSUE THREAD

**Issue by AreYouRlyScared** [pterodactyl/panel#2414] opened 2020-09-25 06:17 UTC
> **I know... that's a horrid title.** 

**Background (please complete the following information):**
* Panel or Daemon: Both?
* Version of Panel/Daemon: Panel: RC6, Wings: Up to commit https://github.com/pterodactyl/wings/commit/7646c27c5a8106bbe0c93e0ce15d447f7942b660

**Describe the bug**
When a user if over the disk limit, the usage is shown, when a user deletes the file, the disk limit is set back to 0 until the server starts again to get a new size.... but it never starts and never shows the new size.... making the user have to "guess" how much they're over.

Sorry for the 35-second gif but it gets the point across. 
![2020-09-25_02-15-17](https://user-images.githubusercontent.com/1757840/94232955-16aac180-fed5-11ea-9896-b53a49dd49f6.gif)

**To Reproduce**
1. Put server over the disk space limit 
2. Try to start the server
3. Delete a file that wouldn't drop the server below the limit ( So it's still over limit ) 
4. Try to start the server. 

**Expected behavior**
When a user deletes a file/files the size of the deleted files should be removed from the cached disk space and updated in the panel to reflect the changes.

**Comment by DaneEveritt** [comment] 2020-09-25 17:27
![wot-n-tarnation](https://user-images.githubusercontent.com/418376/94297629-ab371300-ff19-11ea-89bd-38bab6e7a3a0.jpg)

**Comment by DaneEveritt** [comment] 2020-09-26 03:13
I uh, can't reproduce this? I also can't make an archive and throw the server over the limit anymore since I fixed that issue as well. Mine just continues to show the expected disk usage. Did this perhaps get fixed by some other random thing?

**Comment by AreYouRlyScared** [comment] 2020-09-26 23:00
Still reproducible on latest commit from last night.

**Comment by DaneEveritt** [comment] 2020-09-26 23:12
I still cannot reproduce this issue.

**Comment by DaneEveritt** [comment] 2020-09-27 00:37
Update:

1. Has to be done in a single tab switching between views, don't have one tab with the console and one with the file manager.
2. Maybe only with folders? (didn't actually check this)
3. Fixed by refreshing the page.

**Closed** 2020-09-27 16:45 UTC

**Comment by zKoz210** [comment] 2020-09-28 09:25
![image](https://user-images.githubusercontent.com/28255085/94414661-43850000-0185-11eb-83c8-7d69e5873a13.png)
![image](https://user-images.githubusercontent.com/28255085/94414987-a5456a00-0185-11eb-875e-d5aad270e2c9.png)


Panel don't display the amount of disk space used at all

**Comment by DaneEveritt** [comment] 2020-09-28 15:13
That is expected if you're running the latest code in develop, seeing as I changed a bunch of FS stuff and didn't finish implementing some stuff.
