### ISSUE TITLE
Categorized/Optimized Server View

### ISSUE THREAD

**Issue by SelynCatto** [pterodactyl/panel#3349] opened 2021-05-12 07:19 UTC
**Is your feature request related to a problem? Please describe.**
If you're an admin of a pterodactyl panel with a lot of servers, or you just have a lot of servers dedicated to a lot of different projects, it will get pretty cluttery when you view others servers as admin, or view your own servers when you have a lot, I think this can be optimized and or categorized.

**Describe the solution you'd like**
Well, it would be nice to have a solution in which the panel allows users to create categories, to which they can perhaps drag and drop servers into, allowing them to properly organize servers and have a better experience using the pterodactyl panel.

**Describe alternatives you've considered**
If the solution described above is not an option, it might be worth a try to add sorting options, like sorting the servers highest to lowest resources assigned, alphabetical order, and based on which node they are located on.

**Comment by trenutoo** [comment] 2021-05-12 07:20
Duplicate of #1439

**Closed as completed** 2021-05-12 07:20 UTC
