### ISSUE TITLE
Voiceserver is missing in customer view

### ISSUE THREAD

**Issue by DatMayo** [pterodactyl/panel#2360] opened 2020-09-18 04:54 UTC
**Background (please complete the following information):**
* Panel or Daemon: Pannel
* Version of Panel/Daemon: 1.0.0-rc.6 (issue started on 1.0.0-rc.3)
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 - Firefox & Chrome

**Describe the bug**
I installed a mumble server for myself. I created a customer (non admin) account for that. ~1 week ago I can't see the server when I login as a customer (but I can access console, filemanager, ... when I paste the management url (https://pannel.xyz/server/abcdef))

Please provide additional information too, depending on what you have issues with:
Panel: 
```
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
```
Daemon:
```
Linux srv1 5.4.41-1-pve #1 SMP PVE 5.4.41-1 (Fri, 15 May 2020 15:06:08 +0200) x86_64 GNU/Linux
```
```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.41-1-pve
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 4GiB
 Name: srv1
 ID: AGJ3:GBGX:5HIK:YB2C:GA7G:GPVL:3VPH:XF4O:SQ3R:25TM:7TUT:H3YN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**To Reproduce**
Unfortunately, I can't tell. Because at some point the server was hidden

**Expected behavior**
The server should be shown again on the customers serverlist.

If there are any infos you need, I'd happy to provide it

**Comment by Sir3lit** [comment] 2020-09-18 05:13
![image](https://user-images.githubusercontent.com/1757840/93558767-2dd53680-f94c-11ea-9ce0-f555c04defd9.png)
 Did you click this button... to be able to view the servers not assigned to you?

**Comment by DatMayo** [comment] 2020-09-18 15:48
I think you got me wrong. I can see the server as admin, but not as user (where the server is asigned to)
![admin](https://user-images.githubusercontent.com/1522607/93618055-168f5b00-f9d7-11ea-978b-ab21fcce9714.png)
![customer](https://user-images.githubusercontent.com/1522607/93618057-1727f180-f9d7-11ea-87fc-1b8c98ddfbec.png)

**Comment by DatMayo** [comment] 2020-09-18 15:51
I added a 2nd server (TS) for testing, this server doesn't show up too

**Comment by DatMayo** [comment] 2020-09-23 09:25
@DaneEveritt @AreYouRlyScared do you need more Infos to identify this issue?

**Comment by DaneEveritt** [comment] 2020-09-23 15:17
Well, until someone else is able to reproduce this there isn't much I can do here seeing as I've been running for months now and I've never seen this happen, and the information given is just "let it sit for a few days" so... :/

**Comment by DatMayo** [comment] 2020-09-23 17:37
No problem. I created a new vustomer account, which has the same issue. Looks like some server files are corrupted. Is there a way i can validate all files if they are at its current revision?

**Comment by DatMayo** [comment] 2020-09-25 18:05
@DaneEveritt After I searched the name of the server, it showed up in my customer list. Even when I add a new server everything is fine now... its so weired. I'm closing this issue (but you can reopen if you want to)

**Comment by DatMayo** [comment] 2020-09-25 18:09
Nevermind, issue still exists :/

**Comment by DaneEveritt** [comment] 2020-09-26 23:13
I still cannot reproduce this issue. I am closing this until a more reproducible example can be found, or someone else is able to chime in and provide more context.

Sorry.

**Closed by DaneEveritt** 2020-09-26 23:13 UTC
Labels: 1.0 🦈, bug 🐛
