### ISSUE TITLE
Backups are not deleted after deleting the server in the panel

### ISSUE THREAD

**Issue by b-kneisel** [pterodactyl/panel#3587] opened 2021-08-29 20:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

If a server has backups and it is deleted, backups are not removed with it and garbage the system.

### Expected Behavior

After deleting a server, the backups should be removed either directly or after a month to prevent garbage on the system. This could also be let the panel admin decide through a configuration.

### Steps to Reproduce

1. Create a Server
2. Create a Backup
3. Go to /var/lib/pterodactyl and execute "`ls -ls | grep 'Aug Day`'" Should output the following: `63704 -rw------- 1 root root   65229859 Aug 29 22:15 9231a18f-458d-446c-ac31e-17d704d59b76.tar.gz`
4. Delete the Server and repeat "`ls -ls | grep 'Aug Day`'" Should output the following: `63704 -rw------- 1 root root   65229859 Aug 29 22:15 9231a18f-458d-446c-ac31e-17d704d59b76.tar.gz`
5. So it can be concluded that backups are not removed after deleting the server. Even after a month, they are still present.

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
No errors.
```

**Comment by DaneEveritt** [comment] 2021-08-29 20:34
[Please use the search function before opening issues](https://github.com/pterodactyl/panel/issues?q=is%3Aissue+is%3Aopen+backups+not+deleted).

duplicate #2564

**Comment by matthewpi** [comment] 2021-08-29 20:34
Duplicate of https://github.com/pterodactyl/panel/issues/2564

**Closed as completed by DaneEveritt** 2021-08-29 20:34 UTC
