### ISSUE TITLE
Steam GSLT for Souce based games (csgo) doesnt save after changing them.

### ISSUE THREAD

**Issue by xSL0W** [pterodactyl/panel#2269] opened 2020-08-26 06:52 UTC
* Panel or Daemon: Panel & Daemon
* Version of Panel/Daemon: 1.0.0-rc.2 
* Server's OS: debian10
* Your Computer's OS & Browser: windows 10 & chrome

**Describe the bug**

Panel: `php -v` (the php version in use).

PHP 7.4.9 (cli) (built: Aug  7 2020 14:55:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

Linux debian-4gb-nbg1-1 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

root@debian-4gb-nbg1-1:/var/www/pterodactyl# docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-10-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 3.76GiB
 Name: debian-4gb-nbg1-1
 ID: CP37:W2OB:UOGY:GIXM:PIP6:UHFO:HFJ6:5LP4:3XXB:FID2:F3W6:3QO6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**To Reproduce**
1. Create a server from admin panel. Source Engine -> CSGO
2. Paste a GSLT TOKEN before creating the server
3. After the server is installed and you want to change the token it will only change visually, like in this photo: 
![image](https://user-images.githubusercontent.com/44480431/91270651-a566da00-e781-11ea-9fc6-083b964a3b17.png)

4. If you start the server, the setting will not apply and will use the old GSLT token.
![image](https://user-images.githubusercontent.com/44480431/91270596-8ec08300-e781-11ea-8002-b9047b869583.png)
 
5. Tried changing token from both admin panel and user panel, none of them worked.

6: PS: It only worked after restarting wings.

**Comment by fabm3n** [comment] 2020-08-26 07:01
Dupe of #2255

**Closed** 2020-08-27 15:38 UTC
