### ISSUE TITLE
Backups silently fail if any file is modified while the backup is going on

### ISSUE THREAD

**Issue by ayypril** [pterodactyl/panel#2068] opened 2020-05-26 18:08 UTC
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v1.0.0 Beta Release 5
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10/Chrome

**Describe the bug**
Backups will silently fail if any file is modified during the backup process, leaving only the following in the wings log:
```
error        router/router_server_backup.go:40        failed to generate backup for server        {"error": "archive/tar: write too long", "errorVerbose": "archive/tar: write too long\ngithub.com/pterodactyl/wings/server.(*Server).Backup\n\tserver/backup.go:94\ngithub.com/pterodactyl/wings/router.postServerBackup.func1\n\trouter/router_server_backup.go:39\nruntime.goexit\n\t/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_amd64.s:1373"}
```
In the panel this shows a backup with a spinning icon forever. Refreshing the page makes this backup disappear, and it never appears in the database.

**To Reproduce**
1. Run a server that writes any sort of temporarily file to disk (ie, minecraft)
2. Start a backup and wait for a file change (in my case, a 77 KB dynmap "pending render" file changed slightly)
3. Wait for it to attempt to complete
4. See error in logs

**Expected behavior**
I'd expect either a better message that an error occurred such as a popup saying "Backup failed. This could be a result of a file that was modified during the backup, please shut off your server and try again", and/or a different way to handle backups that would take a snapshot or copy it to a temporary location and not be affected by files changing during the process.

**Comment by matthewpi** [comment] 2020-05-26 18:38
Think I found the problem, if a file is modified while it is being written to the archive and the size of it exceeds what it was before (the file gets bigger while it's about to be added to the archive) the `Write()` function will throw that error because the header says it should be smaller.
https://pkg.go.dev/archive/tar?tab=doc#Writer.Write
https://github.com/pterodactyl/wings/blob/v1.0.0-beta.5/server/backup/archiver.go#L106
(`io#Copy` takes a writer and a reader which calls the `Write()` function on the tar, https://pkg.go.dev/io?tab=doc#Copy)

After researching this there are only three potential solutions I see that would be implemented
1. Open the file with exclusive access (this would prevent it from being written while it's being archived but may not work if something is actively writing it, then we could always skip this file), this is a decent solution but would probably break a lot of shit with servers needing access to files while a backup is running

2. Read the file into memory before setting the size. (this would destroy the RAM of a machine with the amount of space needed for large files, not to mention having the GC clean up that much memory)

3. Limit the amount of data written to the archive by the Size in the header for a file (basically if the file grows while it is being written, only write the original amount of bits and ignore the rest), probably the best solution as it would cause the least amount of problems and people should understand that live backups may not restore everything and might contain corrupted files.

**Comment by DaneEveritt** [comment] 2020-05-26 20:23
We could do both 1 & 3 by making it togglable, e.g. "Perform hot backup" which would do #3, and if they chose to not do that, it will get locks on the files or skip any it cannot lock?

**Comment by matthewpi** [comment] 2020-05-26 20:28
It might be best to automatically change the backup method based off of the server's state, if it's running then it should do **#​3**, but if it is offline it should probably do **#​1** and block the server from booting until it finishes or fails.  That way when someone sets up a schedule it wouldn't create any problems or confusion as if the schedule stops the server it would do a cold backup while if it doesn't it would do a hot backup.  Same thing if a manual backup is triggered, offline = cold backup, online/starting = hot backup.

**Comment by cfi2017** [comment] 2020-05-29 14:58
There are a couple things you could do to help mitigate this:
- This particular issue was caused by a dynmap cache file that was changing size a lot. You already have an ignore file, perhaps maintaining a list of common cache files to ignore would be a good idea.
- You could – in the case of a live backup – check the file size of the file you're backing up. If it's smaller than a certain threshold, load it into memory, then save it. If it's between that first threshold and a second, larger threshold, copy it to a temporary location on disk before saving it (that way you can ensure that the copy of the file did not change size), delete the copy afterwards. This would still require you to find a solution for files larger than the second threshold, but it would be fairly stable for everything below it. 

I don't think 3 is a particularly good option, because if the file contains any form of end tag or structured data the entire file will be corrupt. 

It might be a better idea to ignore files beyond the second threshold completely (not back them up) in the case of a live backup, and perhaps display a warning and a list to the user containing the files that weren't archived. 

For example:
Threshold 1: 100MB
Threshold 2: 1GB

Dynmap cache file: 1KB
Minecraft Region files: ~10-40MB
Fully explored minecraft region files: ~50MB
CoreProtect database: 40GB

For the files above, the dynmap cache file and smaller minecraft region files would be read into memory (unless it's ignored) and then saved. As it's small, this does not have a high memory overhead and is very fast.

Larger minecraft region files beyond the second threshold would be copied to a temporary directory, consumed by the archiver, and then deleted. This does require some amount of disk space (up to the second threshold per file), but requires hardly any memory (which is good since the files are larger) and the copy means the original file can be edited again without too many issues.

If the file is edited as it's being copied, there might still be issues with corruption, but (and this also goes for the memory variant) without a lock, there's very little to be done about that. 

Finally, the coreprotect database will simply not be backed up (it's SQL, the user will want a better strategy for that anyways) and displayed to the user so they know to handle it.

**Comment by parkervcp** [comment] 2020-05-29 16:29
If they have a 40GB sql file in their MC server folder they are doing something wrong... I also suspect it wouldn't actually be here and would not actually be counted against their files so it's irrelevant.

**Comment by Games4k** [comment] 2020-05-31 19:04
It is also worth mentioning that when the backup failed for me, I ended up in a similar situation as #2049

**Comment by cfi2017** [comment] 2020-06-03 07:26
> If they have a 40GB sql file in their MC server folder they are doing something wrong... I also suspect it wouldn't actually be here and would not actually be counted against their files so it's irrelevant.

The default CoreProtect database can easily outgrow that within days on an active survival server and is simply dumped into their `plugins/CoreProtect` directory. I'm not saying it's proper practice, since in CoreProtects case they also provide configuration options for a proper database, but that is only if people actually take the time to set up a database and configure the plugin properly. 

In any case, even if they are doing something wrong, pterodactyl should - in my opinion - protect the panel administrator in this case by handling even oversized files in an explicit manner, because the panel administrator and the person configuring the plugin don't necessarily need to be the same.

**Comment by parkervcp** [comment] 2020-06-03 19:28
I am saying that the sql would be in a database and not in their server folder. Unless it is using sqlite.

**Comment by DaneEveritt** [comment] 2020-06-04 15:35
I agree with @cfi2017 here. Even if it is weird/technically incorrect, we should be handling it as best we can.

**Comment by matthewpi** [comment] 2020-12-31 17:20
This should've been fixed with some previous changes and make very unlikely to happen after I have reworked the archiver due to it previously opening files and queuing them to be added to the archive instead of opening the file when it is ready to be added.

**Closed by matthewpi** 2020-12-31 17:20 UTC
Labels: bug
