### ISSUE TITLE
You do not have permission to access the socket for this server.

### ISSUE THREAD

**Issue by Dann0010** [pterodactyl/panel#1156] opened 2018-05-16 09:14 UTC
* Panel or Daemon: 0.5.4
* Version of Panel/Daemon: 0.7.4.1
* Server's OS: Centos 7
* Your Computer's OS & Browser: Windows 10 & Opera

------------------------

Users are getting the error
```
There was an error attempting to establish a WebSocket connection to the Daemon. This panel will not work as expected.

You do not have permission to access the socket for this server.
````

When attempting to view their servers console, Its their own server and the Browser console is empty. 

A log from docker if this is any use;
```
fd37d14693a75e1521e8c7/shim.sock" debug=false module="containerd/tasks" pid=10667
May 16 05:07:19 na26 dockerd[1987]: time="2018-05-16T05:07:19-04:00" level=info msg="shim reaped" id=3ac25e164d9862248b3a40bf08d2562a23c0677774fd37d14693a75e1521e8c7 module="containerd/tasks"
May 16 05:07:19 na26 dockerd[1987]: time="2018-05-16T05:07:19.098988646-04:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
```

**Comment by DaneEveritt** [comment] 2018-05-16 16:02
This wouldn't be caused by docker, more likely a failing request to the panel to validate permissions, or they're somehow using an invalid authentication token. I've seen it happen before, but never for someone who should legitimately have permission to access the socket.

Was this server ever suspended by chance? Does this error end up self resolving? What actions are you taking once it appears to resolve it or does it never resolve?

**Comment by diamondburned** [comment] 2018-05-21 06:20
Also happens to me. `logs/wings.log`:

    06:11:41.547Z  WARN wings: Container was not found. Attempting to recreate it. (server=0cb68f74-51e5-44f2-904a-8b8a68e6f38d)
    06:11:41.551Z  INFO wings: Checking if we need to update image quay.io/pterodactyl/core:source, if so it will happen now.
    06:11:45.135Z  INFO wings: Pulling image quay.io/pterodactyl/core:source ... this could take a few minutes.
    06:11:45.204Z  INFO wings: Completed rebuild process for server container. (server=0cb68f74-51e5-44f2-904a-8b8a68e6f38d)
    06:11:45.208Z  WARN wings: Server booting is now BLOCKED. (server=0cb68f74-51e5-44f2-904a-8b8a68e6f38d)
    06:11:45.209Z  INFO wings: Blocking server boot until option installation process is completed. (server=0cb68f74-51e5-44f2-904a-8b8a68e6f38d)
    06:11:45.706Z  INFO wings: Writing output of installation process to file. { file: '/srv/daemon/config/servers/0cb68f74-51e5-44f2-904a-8b8a68e6f38d/install.log' } (server=0cb68f74-51e5-44f2-904a-8b8a68e6f38d)
    06:11:48.450Z  INFO wings: Pulling image ubuntu:16.04 ... this could take a few minutes.
    06:11:49.511Z  INFO wings: Temporarily suspending server to avoid mishaps... (server=0cb68f74-51e5-44f2-904a-8b8a68e6f38d)
    06:11:49.516Z  WARN wings: Server has been suspended. (server=0cb68f74-51e5-44f2-904a-8b8a68e6f38d)

**Comment by DaneEveritt** [comment] 2018-05-21 15:50
Yeah if the server is suspended it will show up, don't see anything unusual in those logs for the time.

**Comment by Bl4ckSpr4y** [comment] 2018-05-21 20:53
This happened for me when the panel thought the server wasn't suspended, and the daemon thought it was suspended. Changing suspended from 1 to 0 in the server config in the daemon fixes it.

**Comment by DaneEveritt** [comment] 2018-09-03 21:36
Haven't seen many reports of this issue, and the few I've seen have been because they suspended the server or corrupted their data by touching things they shouldn't have. Closing this issue since its basically non-reproduciable under normal circumstances.

**Closed by DaneEveritt** 2018-09-03 21:36 UTC
Labels: Bug

**Comment by ZaxLofful** [comment] 2020-07-26 02:09
My servers have never been suspended (unless they do it on their own) and this happens to me. Including logging in and out of the console.

I haven't messed with anything "under the hood" either.
