### ISSUE TITLE
Add Server Folders for Improved Organization

### ISSUE THREAD

**Issue by VinceSMC** [pterodactyl/panel#5257] opened 2024-12-13 08:59 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to see a feature that allows users to create folders within the Pterodactyl panel to organize servers. This feature would enable users to categorize servers into specific groups (e.g., testing, development, production, or building etc). Each folder could act as a container for servers, making it easier to navigate and manage a large number of servers.

This feature would improve usability for users managing numerous servers by providing a structured and cleaner layout.

### Describe the solution you'd like.

The solution could involve a folder creation and management system directly in the Pterodactyl panel. Users could:

1. Create, rename, or delete folders.
2. Enable users to assign servers to specific folders.
3. Open the folders to access the servers.

The folders would be purely organizational and not affect the underlying server structure or operations.

**Comment by rowansc1** [comment] 2024-12-13 14:53
Duplicate of #1439

**Closed as completed by rowansc1** 2024-12-13 14:53 UTC
