### ISSUE TITLE
🚀Server Template🚀

### ISSUE THREAD

**Issue by snaildos** [pterodactyl/panel#3370] opened 2021-05-20 02:14 UTC
**Is your feature request related to a problem? Please describe.**
Nope, It be amazing to have below.

**Describe the solution you'd like**
It would be AMAZING to have a template feature! Here is a example, you create a server, press 'template' (admin only) and you can set a server limit, system specs, etc. Then copy the link, you can then share the link with others and they can login with their account, and press "Create Server", then the server will be created with set specs, with the same environment.

**Describe alternatives you've considered**
Docker Image each template

**Additional context**
No, that's all :)

**Comment by matthewpi** [comment] 2021-05-20 02:35
Duplicate of https://github.com/pterodactyl/panel/issues/2059

**Closed as completed by matthewpi** 2021-05-20 02:35 UTC
