### ISSUE TITLE
Add support for more notification methods like push bullet/discord etc for crash reports and servers errors ect 

### ISSUE THREAD

**Issue by Smartjer123** [pterodactyl/panel#1642] opened 2019-07-17 00:46 UTC
**Is your feature request related to a problem? Please describe.**
This is a feature and is not related to a problem

**Describe the solution you'd like**
Maybe add a place for users and admins to put a push bullet api token or any other notification service like discord(web hook) that they like. That will notify them in the event of a game server crash or a server error like a node going down.

**Describe alternatives you've considered**
Or you could add this as like a module/ addon to the panel that is optional and would allow you to put it like an email address for a user/admin. It would be nice if you could also make it be able to do the things that where talked about in #89 

**Additional context**
LGSM has a feature like this where it can notify you on push pullet. If you add this thank you and I think other people will probably think that this would be cool especially people that don't have an email server like me and self hoster's!

**Comment by DaneEveritt** [comment] 2019-07-26 14:53
Duplicate of #89

**Closed by DaneEveritt** 2019-07-26 14:53 UTC
