### ISSUE TITLE
checkbox to delete files before reinstalation

### ISSUE THREAD

**Issue by ok236449** [pterodactyl/panel#3674] opened 2021-10-09 17:28 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When confirming the server reinstall, there should be a checkbox to delete files before the reinstalation starts. This way you wouldn´t have to do it manually (when reinstalling certain servers with the files left, it doesn´t work - lets say you had minecraft 1.17 installed, you reinstalled to minecraft 1.12.2, but it doesn´t work with the original world files from the newer version - users keep asking about this error)

### Describe the solution you'd like.

The same as is when restoring from a backup

**Comment by trenutoo** [comment] 2021-10-10 05:36
Duplicate of #2422

**Closed as completed** 2021-10-10 05:36 UTC
