### ISSUE TITLE
Manage user permissions

### ISSUE THREAD

**Issue by Mist3rWILD** [pterodactyl/panel#4346] opened 2022-08-31 18:16 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A function that allows an admin not to give permissions to all and sundry. For example: Supporters should be able to manage servers and do something in case of problems, and not manage the permissions of other users or even other admins.

Define user permissions. Create other server permissions/groups.

### Describe the solution you'd like.

I do not have a real solution for this function. But maybe someone from the community or someone from the admin team does.

### Additional context to this request.

You can only get the admin permissions, but with them the user can manage everything and he should not. And giving everyone access permissions for all servers every time is tedious.

**Comment by parkervcp** [comment] 2022-08-31 18:18
Duplicate of #279

**Closed as completed by parkervcp** 2022-08-31 18:18 UTC
