### ISSUE TITLE
Segmentation fault on aarch64 using arm64 wings binary

### ISSUE THREAD

**Issue by leon0399** [pterodactyl/panel#3591] opened 2021-08-31 21:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Executing `arm64` wings binary on `aarch64` fails to 'Segmentation fault`

I am using Oracle's "Free Tier" servers with `Ampere A1 Compute`:

* `uname -a`: `Linux <redacted> 5.4.17-2102.201.3.el7uek.aarch64 #2 SMP Fri Apr 23 09:31:49 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux`
* `cat /etc/oracle-release`: `Oracle Linux Server release 7.9`

### Expected Behavior

Not to fail 🤷 

### Steps to Reproduce

1. Create Ampere A1 instance in Oracle Cloud
2. Download `arm64` wings binary
3. Execute it

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```
[user@server ~]$ wings
Segmentation fault
```

**Comment by DaneEveritt** [comment] 2021-08-31 21:22
closing, no error logs provided

**Closed as completed by DaneEveritt** 2021-08-31 21:22 UTC

**Comment by leon0399** [comment] 2021-09-01 00:01
> closing, no error logs provided

I *could not* provide logs, since it *does not even start*

**Comment by parkervcp** [comment] 2021-09-01 02:56
> > closing, no error logs provided
> 
> I *could not* provide logs, since it *does not even start*
> 

You can always copy and paste the console output.

**Comment by leon0399** [comment] 2021-09-01 10:21
> > > closing, no error logs provided
> > 
> > 
> > I _could not_ provide logs, since it _does not even start_
> 
> You can always copy and paste the console output.

updated

**Comment by leon0399** [comment] 2021-09-02 08:52
@DaneEveritt reopen, please

**Comment by trenutoo** [comment] 2021-09-22 17:41
@leon0399  #3638 - Caused by Oracle Linux. Use a different distro to fix your problem.
