### ISSUE TITLE
Delete server backup when a server is deleted

### ISSUE THREAD

**Issue by evanonym0us** [pterodactyl/panel#3756] opened 2021-11-18 13:04 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Server backups should be deleted when a server is deleted.

### Describe the solution you'd like.

Add a feature that deletes server backups when a server is deleted. Maybe also add an option to purge already existing backup files from deleted servers.

**Comment by Boy132** [comment] 2021-11-18 13:05
Duplicate of #2564

**Closed as completed** 2021-11-18 13:54 UTC
