### ISSUE TITLE
Add your own subdomains to a server

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3647] opened 2021-09-25 18:50 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Like https://www.mc-market.org/resources/17640/

### Describe the solution you'd like.

Like https://www.mc-market.org/resources/17640/

**Comment by trenutoo** [comment] 2021-09-25 19:45
Duplicate of #1550 - however, who knows if Dane/Matthew has changed their opinion. I doubt it. You can use the addon you are linking, which I assume utilizes Cloudflare API.

**Comment by matthewpi** [comment] 2021-09-25 19:49
I see no reason why this should be implemented officially.  It's a niche feature only used by hosts that provides little benefit to most users.  Even ignoring that, there is not a standard way to create DNS records, so our implementation would most likely only work with `x` DNS provider and people would just keep requesting different providers.

**Closed as completed by matthewpi** 2021-09-25 19:49 UTC
