### ISSUE TITLE
Reorganize servers

### ISSUE THREAD

**Issue by mallusrgreatv2** [pterodactyl/panel#4974] opened 2024-01-11 15:56 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be helpful if you could, for example, set servers above others, or below others

### Describe the solution you'd like.

![image](https://github.com/pterodactyl/panel/assets/69511006/9a87c79d-80f9-4f6f-ba4f-52bae41f04b9)
This button is usable for this, I want it made so that you can drag this button around.

**Comment by QuintenQVD0** [comment] 2024-01-11 15:57
Has been request multiple times, and you clearly did not check the open request for it.
IF you want it rn there is a paid (non offical) add-on for it.

**Comment by parkervcp** [comment] 2024-01-11 16:25
Duplicate of #498

**Closed as completed by parkervcp** 2024-01-11 16:25 UTC
