### ISSUE TITLE
Docker's network host mode on a single server instance

### ISSUE THREAD

**Issue by NicoloLazzaroni** [pterodactyl/panel#3467] opened 2021-07-14 20:13 UTC
Dear Pterodactyl community,

My suggestion is to add a feature that makes it possible to only apply Docker's Network "host" mode to a single server instance.
https://pterodactyl.io/wings/1.0/configuration.html#custom-network-interfaces

I am not sure it would be possible, but surely would be very helpful.

Best Regards

**Comment by trenutoo** [comment] 2021-07-14 20:14
Duplicate of #1418

**Closed as completed** 2021-07-14 20:15 UTC
