### ISSUE TITLE
Daemon: docker, mount /etc/localtime

### ISSUE THREAD

**Issue by kefirawp** [pterodactyl/panel#2185] opened 2020-07-22 09:45 UTC
My time zone in the file /etc/timezone is "Europe/Moscow", but the time is displayed incorrectly.
Is it possible to mount the /etc/localtime file?

**Comment by SkippTekk** [comment] 2020-07-22 09:53
If you want the server to be a certain time for Minecraft. Use

-Duser.timezone="LOCATION"

**Comment by kefirawp** [comment] 2020-07-22 10:03
I have CSGO server

**Comment by fabm3n** [comment] 2020-07-22 10:05
Please use the Discord for Support. https://pterodactyl.io/discord
If this is a bug or feature request use the issue template.

**Comment by fabm3n** [comment] 2020-07-22 10:08
Also i think it's a dupe of #2073

**Closed** 2020-07-22 10:47 UTC

**Comment by andris155** [comment] 2020-09-17 20:53
@SkippTekk big thanks for solution.
