### ISSUE TITLE
In console can't copy using ctrl+c

### ISSUE THREAD

**Issue by Creveoolus** [pterodactyl/panel#3997] opened 2022-03-11 15:18 UTC
### Current Behavior

When selecting something in console and pressing Ctrl+C it doesen't copy.

### Expected Behavior

Selected text should be copied.

### Steps to Reproduce

- Select something in console
- Press Ctrl+C (Use cyrillic layout)

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

Minecraft

### Docker Image

17

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by gOOvER** [comment] 2022-03-11 15:20
can't confirm; i can  copy all from console with ctrl+c

**Comment by trenutoo** [comment] 2022-03-11 15:27
Are you sure that your Panel is on 1.7.0? Pretty sure this was an issue with earlier versions.

I can't reproduce this on 1.7.0 using Chrome or FF.

**Comment by Creveoolus** [comment] 2022-03-11 15:31
Made few changes. You should use cyrillic layout to reproduce.

**Comment by gOOvER** [comment] 2022-03-11 15:47
> Made few changes. You should use cyrillic layout to reproduce.

should be the same as EU or US  or  sth else Layout. The command is the same. And i cant test it with cyrillic, becasue i cant read it xD

**Comment by Creveoolus** [comment] 2022-03-11 16:21
> > Made few changes. You should use cyrillic layout to reproduce.
> 
> should be the same as EU or US or sth else Layout. The command is the same. And i cant test it with cyrillic, becasue i cant read it xD

You should be able to read it, its just a keyboard layout. The fact is, it doesn't work with cyrillic keyboard layout.

**Comment by schrej** [comment] 2022-03-11 16:33
What's the exact layout you're talking about? Most cyrillic layouts seem to be `JCUKEN`, and that has the C on the same position as QWERTY, so it should work fine.

**Comment by VibeGAMESNL** [comment] 2022-03-19 10:56
Works fine for me.

**Comment by Creveoolus** [comment] 2022-03-24 11:55
> What's the exact layout you're talking about? Most cyrillic layouts seem to be `JCUKEN`, and that has the C on the same position as QWERTY, so it should work fine.

Russian > German

**Comment by schrej** [comment] 2022-03-24 13:11
@Creveoolus if you can't contribute anything to the issue you've created yourself, shut up. Also, this is no place for politics, or whatever that was supposed to mean.

**Comment by DaneEveritt** [comment] 2022-03-28 17:48
I don't know, I'm closing this out since it seems like something I wouldn't be able to figure out very easily, and I'm not very interested in trying to debug with a switched keyboard layout.

https://github.com/pterodactyl/panel/blob/develop/resources/scripts/components/server/Console.tsx#L150-L152

**Closed as completed by DaneEveritt** 2022-03-28 17:48 UTC

**Comment by Creveoolus** [comment] 2022-03-29 11:59
> @Creveoolus if you can't contribute anything to the issue you've created yourself, shut up. Also, this is no place for politics, or whatever that was supposed to mean.

It wasn't politics, bruh. I have Russian keyboard in german layout 
![image](https://user-images.githubusercontent.com/48063151/160606414-a3f8b89c-f112-46d2-8413-1479eb238802.png)


And please don't get angry at no point :P
