### ISSUE TITLE
Separate local backups in folders by server akin to remote backups

### ISSUE THREAD

**Issue by Sabinno** [pterodactyl/panel#3529] opened 2021-08-07 00:35 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I'd like to see backups separated by folders named after each server GUID, just like remote backups are. Primarily so I can track down backups much more easily for troubleshooting and debugging purposes. Frankly, it's just less ugly as well, which is never a bad thing.

### Describe the solution you'd like.

Ideally, the same logic for organizing backups that currently applies to remote backups would also apply for local backups.

### Additional context to this request.

It seems like a strange oversight that this has not been implemented only for local backups. I see zero downsides to this, only benefits for organization, troubleshooting, and debugging purposes.

**Comment by trenutoo** [comment] 2021-08-07 07:31
duplicate of #2594

**Closed as completed** 2021-08-07 14:56 UTC
