### ISSUE TITLE
Node cpu usage 7x cores!

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3899] opened 2022-01-21 00:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

I had simmilar issues before but I think after recent wings updates they are narrowed only to one YAY!

Ill try to provide as much info as possible anomalies in graphs:

![image](https://user-images.githubusercontent.com/6473565/150442805-dec91e52-ee55-4d7e-826f-f66a44e64348.png)
At this point you might think this is decompress but it's not. They use less cpu than 7x cores

![image](https://user-images.githubusercontent.com/6473565/150442996-b5388435-0d55-4810-90a6-4fa8e7ad7fb4.png)

![image](https://user-images.githubusercontent.com/6473565/150443028-2213066f-34ef-4b1f-ad15-73f20d6a20b1.png)
This one is interesting.

![image](https://user-images.githubusercontent.com/6473565/150443163-eda18f84-6aa1-47b7-a49a-ab44693d5f43.png)

Disk usage,Disk read/write, threads all same

### Expected Behavior

No crazy CPU increase.

### Steps to Reproduce

Unfortunately I don't have much. I've checked all logs syslog, pterodactyl logs and I cant find what causes this. Could you recommend any tools I could use to debug running application ?

I'm ready to do anything to solve this issue. It's good that it's only this one issue is left.

P.S. This happened on two separate linux servers. 

### Panel Version

1.7.0

### Wings Version

1.5.5

**Comment by iamkubi** [comment] 2022-01-21 00:38
You said you checked the logs, but can you include them?  The wings logs covering a period while Wings is using 700% CPU should say *something*.

**Comment by BenasPaulikas** [comment] 2022-01-21 00:49
Yeah I hoped so...
P.S. This is log from second occurence(little different times than in graph)

```
 INFO: [Jan 21 01:01:21.016] syncing server configuration with panel server=28f0c0b5-34ed-456a-a0e4-4a003cb086a1
 INFO: [Jan 21 01:01:21.080] performing server limit modification on-the-fly server=28f0c0b5-34ed-456a-a0e4-4a003cb086a1
 INFO: [Jan 21 01:01:21.087] performing server limit modification on-the-fly server=28f0c0b5-34ed-456a-a0e4-4a003cb086a1
 WARN: [Jan 21 01:21:08.263] failed to send event to websocket: close already sent event= server=5d3b96e9-f01d-4178-b5a4-70579ebcbb55 subsystem=websocket
 INFO: [Jan 21 01:21:09.286] syncing server configuration with panel server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:09.398] performing server limit modification on-the-fly server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:09.408] performing server limit modification on-the-fly server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:11.959] syncing server state with remote source before executing installation process server=880d1d16-1ee9-4f7a-863e-e03b22bb8391
 INFO: [Jan 21 01:21:12.016] performing server limit modification on-the-fly server=880d1d16-1ee9-4f7a-863e-e03b22bb8391
 INFO: [Jan 21 01:21:12.074] beginning installation process for server server=880d1d16-1ee9-4f7a-863e-e03b22bb8391
 INFO: [Jan 21 01:21:12.172] starting resource polling for container container_id=a381ad24-aea9-4770-8b38-9139fe962346 environment=docker
 INFO: [Jan 21 01:21:13.288] creating install container for server process install_script=/tmp/pterodactyl/880d1d16-1ee9-4f7a-863e-e03b22bb8391/install.sh server=880d1d16-1ee9-4f7a-863e-e03b22bb8391
 INFO: [Jan 21 01:21:13.412] running installation script for server in container container_id=c5b8af02e0efb45db567f09326a64b84c09cda3c2e8a07586a6474b7e1567a32 server=880d1d16-1ee9-4f7a-863e-e03b22bb8391
 INFO: [Jan 21 01:21:15.274] detected server as entering a crashed state; running crash handler server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:15.804] syncing server configuration with panel server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:15.856] performing server limit modification on-the-fly server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:15.864] performing server limit modification on-the-fly server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:18.654] starting resource polling for container container_id=a381ad24-aea9-4770-8b38-9139fe962346 environment=docker
 INFO: [Jan 21 01:21:21.769] detected server as entering a crashed state; running crash handler server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:22.337] did not restart server after crash; occurred too soon after the last server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:24.929] completed installation process for server server=880d1d16-1ee9-4f7a-863e-e03b22bb8391
 INFO: [Jan 21 01:21:25.317] syncing server configuration with panel server=880d1d16-1ee9-4f7a-863e-e03b22bb8391
 INFO: [Jan 21 01:21:25.366] performing server limit modification on-the-fly server=880d1d16-1ee9-4f7a-863e-e03b22bb8391
 INFO: [Jan 21 01:21:25.374] performing server limit modification on-the-fly server=880d1d16-1ee9-4f7a-863e-e03b22bb8391
 INFO: [Jan 21 01:21:26.568] syncing server configuration with panel server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:26.629] performing server limit modification on-the-fly server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:26.642] performing server limit modification on-the-fly server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:28.216] starting resource polling for container container_id=880d1d16-1ee9-4f7a-863e-e03b22bb8391 environment=docker
 INFO: [Jan 21 01:21:29.488] starting resource polling for container container_id=a381ad24-aea9-4770-8b38-9139fe962346 environment=docker
ERROR: [Jan 21 01:21:29.649] error processing websocket event "set state" error=server is running error_identifier=695abfb7-5b9b-45e6-bf09-d79e30e67e2c event=set state server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:32.588] detected server as entering a crashed state; running crash handler server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:33.152] did not restart server after crash; occurred too soon after the last server=a381ad24-aea9-4770-8b38-9139fe962346
 INFO: [Jan 21 01:21:38.010] starting file decompression file=GAMEMODE BRASIL HISTORY CITY DESBUGADA O BUG DO DANO E OUTROS BUGS RESOLVIDOS POR GABRIEL LIMA DO BLCV.zip request_id=11a242df-a7a3-4d2e-bce2-b7796b70ac5a root_path=/ server_id=a381ad24-aea9-4770-8b38-9139fe962346
**
Right here cpu increases
I've checked unarchive took no more than 1 s
**
 INFO: [Jan 21 01:21:47.809] detected server as entering a crashed state; running crash handler server=ab47c2d0-08ea-49b2-b46b-6d8d66d86eb8
 INFO: [Jan 21 01:21:48.307] syncing server configuration with panel server=ab47c2d0-08ea-49b2-b46b-6d8d66d86eb8
 INFO: [Jan 21 01:21:48.436] performing server limit modification on-the-fly server=ab47c2d0-08ea-49b2-b46b-6d8d66d86eb8
 INFO: [Jan 21 01:21:48.444] performing server limit modification on-the-fly server=ab47c2d0-08ea-49b2-b46b-6d8d66d86eb8
 INFO: [Jan 21 01:21:51.214] starting resource polling for container container_id=ab47c2d0-08ea-49b2-b46b-6d8d66d86eb8 environment=docker
 INFO: [Jan 21 01:21:58.151] starting file decompression file=n3xt_fabricararmas.zip request_id=89157f6b-3d9e-469a-aad1-e56923f0b5b8 root_path=/mods/deathmatch/resources server_id=f561edf7-80e3-44b4-89a8-2af05970d722
```

**Comment by BenasPaulikas** [comment] 2022-01-21 00:52
I've noticed I'm running without --debug. Please hold on one hour ill be back with more info soon.

**Comment by notAreYouScared** [comment] 2022-01-21 04:59
> I've noticed I'm running without --debug. Please hold on one hour ill be back with more info soon.

Wings will use a lot of CPU for several tasks, some are listed below

compressing or uncompressing large files
File downloads and uploads ( due to the use of sftp, every package is encrypted and then decrypted at the other end ) 
Backup created ( due to the compression of files ) 

Other than those... nothing should really be eating that much CPU. I'd be very interested in those logs with debug mode enabled, as it would show what API calls are being made during those times.

**Comment by BenasPaulikas** [comment] 2022-01-21 07:14
@iamkubi @AreYouRlyScared 

Fair point about compressing, file downloads, backups. However it's not that. My graphs are not picking up abnormal disk activity. I've also tried to do all these actions and its still all good(it's okay for wings to use some cpu) But when it's using 8x cores it's just getting worse and worse.

Okay as You can see its not spending any CPU in kernel mode(happened during this occurence only)

![image](https://user-images.githubusercontent.com/6473565/150479425-ad9e27c9-9d72-4673-9be9-efed235b46a6.png)

==== Logs ====
(Notice it's -1 hour from graphs. so)
06:32:25 - all good
06:32:30 - wings using 8x cores
~https://pastebin.com/1cJbvnD9~
https://pastebin.com/raw/nQkB9jaU

**Comment by iamkubi** [comment] 2022-01-21 07:21
What does top look like?

**Comment by BenasPaulikas** [comment] 2022-01-21 07:26
I didn't had `top` during that time. Ands wings are restarted already. However I have all other data saved in netdata (no other anomalies there) no crazy open files or files write/read.

**Comment by BenasPaulikas** [comment] 2022-01-21 07:27
Sorry pastebin doesn't have all data. Attaching new one

**Comment by BenasPaulikas** [comment] 2022-01-21 07:28
https://pastebin.com/raw/nQkB9jaU

**Comment by BenasPaulikas** [comment] 2022-01-21 07:30
I could also use this https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/go_expvar#using-netdata-go_expvar-module 
to further investigate this case

However I think it would need one package install into wings.

**Comment by BenasPaulikas** [comment] 2022-01-21 07:38
I'm also attaching strace summary(it's happening again at this moment)

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 71.82  100.316130         363    275820     26411 futex
 17.79   24.852253          27    888766       103 epoll_pwait
  6.07    8.477878         208     40682      1147 nanosleep
  1.13    1.581581          35     43993           getpid
  0.83    1.164901          26     43991           tgkill
  0.70    0.983980           8    110378        16 write
  0.58    0.807830          18     43988      1829 rt_sigreturn
  0.48    0.675682          25     26796     10146 read
  0.14    0.196098           8     21849           sched_yield
  0.10    0.133983          75      1781           close
  0.08    0.116339          67      1732         2 openat
  0.07    0.091329          27      3290           madvise
  0.07    0.091008          49      1834      1730 epoll_ctl
  0.05    0.075921          22      3446           getrandom
  0.03    0.041773          47       888           pwrite64
  0.03    0.038184          13      2762        33 newfstatat
  0.01    0.014239          16       858           fchownat
  0.00    0.004232         176        24         3 unlinkat
  0.00    0.002295          13       168           getdents64
  0.00    0.001896           9       204           setsockopt
  0.00    0.001610          29        54           getsockname
  0.00    0.001301          13       100        50 accept4
  0.00    0.000025          25         1           fchmodat
  0.00    0.000019           4         4           socket
  0.00    0.000014           3         4         1 connect
  0.00    0.000004           4         1           truncate
  0.00    0.000001           0         4           getpeername
  0.00    0.000000           0         1           fstat
  0.00    0.000000           0         1           getsockopt
  0.00    0.000000           0         3           restart_syscall
  0.00    0.000000           0         2           mkdirat
------ ----------- ----------- --------- --------- ----------------
100.00  139.670506               1513425     41471 total


real    0m18.224s
user    0m0.849s
sys     0m9.590s
```

**Comment by BenasPaulikas** [comment] 2022-01-21 07:40
![image](https://user-images.githubusercontent.com/6473565/150486220-e328a17a-f815-40ac-b6ef-8e227e39a021.png)

**Comment by BenasPaulikas** [comment] 2022-01-21 07:40
![image](https://user-images.githubusercontent.com/6473565/150486267-2b866f91-7dc6-4485-8521-c6a695e70843.png)

**Comment by iamkubi** [comment] 2022-01-21 10:57
Well I've got no real idea there.  The top output rules out an issue with the graphs, and nothing in the strace output looks (to me) like it should cause heavy CPU usage.  I suspect you'll probably want to enable the CPU profiler by running `wings --profiler cpu`.  That should provide a better idea of what's consuming the CPU.

**Comment by DaneEveritt** [comment] 2022-01-21 13:26
Also please stop posting individual pictures as replies back to back. I appreciate that you're trying to provide as much context as possible, but random screenshots are not particularly helpful, and it causes a _ton_ of notifications when you keep responding one image at a time.

As @iamkubi mentioned, about the only thing that will be useful here is an actual profile of the running application, given that you cannot provide reproduction steps, and pictures of your one machine going off the rails is hardly indicative of an actual issue in Wings. I believe the CPU usage, but pictures of it isn't going to do anything to help me reproduce or narrow down the offending code. 👍🏼

**Comment by BenasPaulikas** [comment] 2022-01-22 00:02
@iamkubi @DaneEveritt ty for tip about! 

```
wings --profiler cpu
```
Honestly I think it's first time I'm hearing about this :) I'm attaching .pprof file I hope that will help understanding this issue :)

Once wings cpu rose from 30%-50%(of one core) to 600% I kept it spinning for 10 minutes. Hopefully thats enough to see that in .pprof

https://drive.google.com/file/d/1GbH3lUS8VMkT6zlyL5u7_ZZQZuEy3qGF/view?usp=sharing

P.S. If anything else is needed let me know. I'm flexible. I can reproduce this issue several times per day

**Comment by DaneEveritt** [comment] 2022-01-23 14:15
Try running with this build: https://github.com/pterodactyl/wings/suites/5027724859/artifacts/148198270

It fixes some GC issues in the server output handlers.

**Comment by BenasPaulikas** [comment] 2022-01-23 19:23
@DaneEveritt Thank you for build on the Sunday evening :) Really appreciated!

I've ran it and maybe it improved because cpu is not reaching 7x cores immediately. It's reaching lower cpu and slower. Attaching image and cpu profile. Maybe you fixed one bug but there's another issue.
![image](https://user-images.githubusercontent.com/6473565/150694480-3020c426-bd79-416b-8b99-5b8f1e605b34.png)

https://drive.google.com/file/d/1SLm-axg-IZnn36VgYVxdZ_QPelRZb98b/view?usp=sharing

**Comment by DaneEveritt** [comment] 2022-01-23 23:39
Based on @matthewpi and I's analysis, we don't believe there is much else we can do to improve that result. I made some additional changes and they're being released in 1.5.6 right now, but I don't think we're going to sink much more time into addressing that usage. It seems highly likely that you're overloading your instance, or have servers spamming console output at a rate that is near impossible for Wings to adequately handle.

Closed in:
https://github.com/pterodactyl/wings/commit/b5536dfc7767dc47c9d4bd699404301cf8afaf77
https://github.com/pterodactyl/wings/commit/de04e73e820061b17da26e309629198191099552

**Closed as completed by DaneEveritt** 2022-01-23 23:39 UTC

**Comment by BenasPaulikas** [comment] 2022-01-23 23:59
@DaneEveritt ty for taking time to reply :+1: Can't wait to try 1.5.6 :)

Do I understand correctly that based on my .pprof issue was wings receiving too much console output. 
Does that mean that turning off all servers should lower cpu usage immediately ?

**Comment by DaneEveritt** [comment] 2022-01-24 00:15
It appears there is at least one server flooding console output.

**Comment by BenasPaulikas** [comment] 2022-01-24 03:44
@DaneEveritt So far no high cpu usage. I'm quite confident this fixed my issues. Also wings look more optimized now :+1:

**Comment by BenasPaulikas** [comment] 2022-01-24 11:32
@DaneEveritt After running for more time I can confirm it's much better.
After cpu reaches > 120% of one core I'm auto restarting wings after some time(cpu doesn't get lower once it increases sharply)

![image](https://user-images.githubusercontent.com/6473565/150774517-d302f571-c037-4b07-a242-91ae94ad9cff.png)

however I still think there is issue:
* After wings restart CPU hovers at about 30% of one core(for about few hours)
* Then suddenly it rises to 100% of one core
* Then in some time rises again to 180% of one core
* If it would be console spam issue after wings restart it would still use a lot of cpu? But it isn't.

I'm attaching .pprof after wings cpu rose 2x times to almost 200% core speed.
https://drive.google.com/file/d/1n7jEkuQrTBlf0Yh8qxrra41iIl61CgQ-/view?usp=sharing

Also I'm attaching .pprof which is fine(wings have been running for quite sime time and cpu usage is normal ~ 30% of the core)
I'm attaching this one so you would have .pprof to compare(when it's normal)
https://drive.google.com/file/d/1DDyY_9Z9I_bK0SeA0BwL6Bnqia_gd-m8/view?usp=sharing

I really appreciate your help. With recent changes it's much much better. And I think latest .pprof could help solve this cpu leak issue. Thank you in advance.

**Comment by DaneEveritt** [comment] 2022-01-24 13:51
Can you please open a new issue with that information and those profiles, and just reference this one in it?

**Comment by BenasPaulikas** [comment] 2022-01-24 14:20
@DaneEveritt done https://github.com/pterodactyl/panel/issues/3911
