### ISSUE TITLE
Cannot logout most likely due to redis

### ISSUE THREAD

**Issue by JanDevDE** [Pterodactyl/Panel#954] opened 2018-02-18 16:09 UTC
* Panel 0.7.0
* Ubuntu 16.04

## Details:

So, I ran the "php artisan p:environment:setup" command in the upgrading process and as redis is the new recommended driver for everything, I switched to it. However, after finishing the upgrade to 0.7.0 and doing some stuff in the panel, I tried to log out and just got a "Whoops, looks like something went wrong." error.

After that I ran the "php artisan pterodactyl:env" command. I switched the session driver and the queue driver back to databse and everything worked fine again.

So I think it's a bug. (Hopefully not my fault.)

Log:

https://hastebin.com/anuwawowuy.tex

**Comment by schrej** [comment] 2018-02-18 16:27
duplicate of #950

**Closed** 2018-02-18 16:27 UTC
