### ISSUE TITLE
Reinstalling server throws unexpected "(" in operand

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2212] opened 2020-08-03 21:01 UTC
**Background (please complete the following information):**
* Panel or Daemon: Wings 
* Version of Panel/Daemon:  Beta 9
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win10 / Chrome

**Describe the bug**
End user triggered a reinstall from the front end. Wings claimed the install failed.

```
 INFO: [Jul 30 19:45:23.390] beginning installation process for server server=1ed7f804-0b60-42cf-97f6-482350c05792
DEBUG: [Jul 30 19:45:23.390] acquiring installation process lock server=1ed7f804-0b60-42cf-97f6-482350c05792
DEBUG: [Jul 30 19:45:24.842] {"status":"Pulling from frolvlad/alpine-glibc","id":"latest"}
DEBUG: [Jul 30 19:45:24.843] {"status":"Digest: sha256:d2c43001078bbb004fc901d247a3c51b58c58f8f7782f08e8306d680930d8eb0"}
DEBUG: [Jul 30 19:45:24.843] {"status":"Status: Image is up to date for frolvlad/alpine-glibc:latest"}
 INFO: [Jul 30 19:45:24.844] creating install container for server process install_script=/tmp/pterodactyl/500840337/install.sh server=1ed7f804-0b60-42cf-97f6-482350c05792
 INFO: [Jul 30 19:45:25.832] running installation script for server in container container_id=5a6d30ae28be81ee3f2c9812b067f9901e1fb67dba9129aa099359af83be4782 server=1ed7f804-0b60-42cf-97f6-482350c05792
DEBUG: [Jul 30 19:45:36.596] pulling installation logs for server container_id=5a6d30ae28be81ee3f2c9812b067f9901e1fb67dba9129aa099359af83be4782 server=1ed7f804-0b60-42cf-97f6-482350c05792
DEBUG: [Jul 30 19:45:36.597] writing most recent installation logs to disk path=/var/log/pterodactyl/install/1ed7f804-0b60-42cf-97f6-482350c05792.log server=1ed7f804-0b60-42cf-97f6-482350c05792
 WARN: [Jul 30 19:45:36.665] failed to complete after-execute step of installation process error=template: header:6: unexpected "(" in operand server=1ed7f804-0b60-42cf-97f6-482350c05792

Stacktrace:
github.com/pterodactyl/wings/server.(*InstallationProcess).Run
        /home/runner/work/wings/wings/server/install.go:218
github.com/pterodactyl/wings/server.(*Server).internalInstall
        /home/runner/work/wings/wings/server/install.go:88
github.com/pterodactyl/wings/server.(*Server).Install
        /home/runner/work/wings/wings/server/install.go:39
github.com/pterodactyl/wings/server.(*Server).Reinstall
        /home/runner/work/wings/wings/server/install.go:68
github.com/pterodactyl/wings/router.postServerReinstall.func1
        /home/runner/work/wings/wings/router/router_server.go:151
```

**To Reproduce**
1. Reinstall server? 

Didn't get the steps exactly taken to result in this error from the user. I Will update once the info is obtained. 

**Expected behavior**
Reinstall to not fail

**Comment by Sir3lit** [comment] 2020-08-03 21:04
This also leaves the server in a "stopping" state and refuses to accept any other power actions. All power actions return an "another power action is currently being processed for this server, please try again later" error thrown in the console ... Might be related to #1994 ?

**Comment by DaneEveritt** [comment] 2020-08-03 21:44
The stopping issue is probably because it sets stopping and then the error is encountered. It should probably remove that state if an error is hit so it can be stopped again.

**Comment by DaneEveritt** [comment] 2020-08-04 03:57
Quite certain this isn't `beta.9` since it is fixed in https://github.com/pterodactyl/wings/commit/db0dc179375cf6594b001445b37b16c793982ea3 (and I can't reproduce).

**Closed by DaneEveritt** 2020-08-04 03:57 UTC
Labels: beta 🦈, bug 🐛
