### ISSUE TITLE
Feature Request: Choose how a port is allocated.

### ISSUE THREAD

**Issue by alixplayz** [pterodactyl/panel#3874] opened 2022-01-11 12:23 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It'd be really nice to choose whether a port should be allocated to a server using the -p option within docker, or with the --expose option. Instead of always using both (which is the case now when you allocate a port to a server), as they are quite different.

EDIT: Would also be nice to able to choose these two separately https://i.imgur.com/XUrjg38.png

### Describe the solution you'd like.

https://i.imgur.com/l8VcfbQ.png
Right here you could add a little dropdown that gives you the option to:
1. Bind port to the ip (-p)
2. Expose port (--expose)
3. Auto/both - which could be as it is now (using both the -p and --expose option)

Ofc there should be a disclaimer that it's for just advanced users, or whatever.

**Comment by parkervcp** [comment] 2022-01-11 12:34
The panel was built for hosting external facing servers that need a port assigned to them. The ability to use it to host bots and things is just due to how flexible it is.

Expose allows ports on the internal network which is what you get when you allocate a port with 127.0.0.1/172.18.0.1/"custom network" in the panel.

In my eyes this is already done.

**Comment by alixplayz** [comment] 2022-01-11 12:49
What about this then:
"EDIT: Would also be nice to able to choose these two separately https://i.imgur.com/XUrjg38.png"

I want to be able to forward a port from the container to a different port on the host. Is that possible through pterodactyl?

**Comment by DaneEveritt** [comment] 2022-01-11 13:04
No, as @parkervcp mentioned Pterodactyl was designed around some fairly broad use-cases for hosting games, not managing arbitrary Docker setups. Unfortunately these highly specific requests start to bring the Panel more into the realm of generalized-container-hosting management, rather than games specifically.

I think it would be reasonable to support exposing & binding allocations as separate options, but I don't want to build in support for what you've identified in your image. The goal here is to accomplish what 90% of people need out of the software by default. Venturing into these highly specific networking setups is getting well out of that realm, and introducing a lot of cognitive complexity for end-users, and maintenance overhead for the few of us working on the project.

Unfortunately given everything else going on right now, I don't see this ending up as a high priority, but I'll leave it open since I like the idea of coming up with a way to split bind/expose.

**Comment by alixplayz** [comment] 2022-01-11 13:37
Thanks for the detailed response. I do understand that 100% yeah. The fact that it's built for game servers. However, many games such as Minecraft (in my case) are so highly customizable in there plugin/mod coding that this is getting less and less "highly specific".

To explain my case more. I want a Minecraft Bungeecord server to be able to communicate with a Minecraft Hub server. There are 2 ways I've found doing this.

First way is for them to communicate on a specific port. However, you can't bind (-p option in docker) the same port to two containers in docker. What you can do however is expose the port on two containers (which should be all that's required in this case).

Second way is to make a HTTP request (in my case to localhost). Which I haven't found is possible, as you cant allocate port 80 to a server with pterodactyl. https://i.imgur.com/FyrIePk.png (would be really nice if there was a way to bypass this)

**Comment by trenutoo** [comment] 2022-01-11 13:42
For Minecraft proxies you do what Parker mentioned above. There's also a guide for it at https://pterodactyl.io/community/games/minecraft.html

**Comment by DaneEveritt** [comment] 2022-01-11 14:46
I don't follow why you would be binding the same port to two containers? If you want them to communicate with each-other, but only have one publicly accessible, just bind one to a public interface, and the other to a local interface, `127.0.0.1`.

**Comment by DaneEveritt** [comment] 2022-02-19 15:22
Looking at this again, I see what you're going for, but my solution above would accomplish the same goal without having to build out even more logic into the Panel and Wings instances to do this.

For right now I'm going to close this out because I don't foresee myself ever getting around to building such a thing.

**Closed as completed by DaneEveritt** 2022-02-19 15:22 UTC
