### ISSUE TITLE
Panel not responding/console commands/websocket unresponsive.

### ISSUE THREAD

**Issue by crispyaus** [pterodactyl/panel#3573] opened 2021-08-24 10:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Console will populate with some content, then become unresponsive after a few seconds. No new content will be sent to console, and nothing is sent from client to server. 
![aYshdvvQ4y](https://user-images.githubusercontent.com/34707863/130604928-a28b7bb6-a2a9-48ba-b570-8dec98833be5.gif)

### Expected Behavior

-

### Steps to Reproduce

Not clear what are the steps here to reproduce, to note that it does not happen in any other servers on the panel that I have tried, just this one.

### Panel Version

1.5.1

### Wings Version

1.4.7

**Comment by parkervcp** [comment] 2021-08-24 11:29
A few questions.

Do you have the server console open in more than one place?
Did you restart wings and see if the issue goes away?
If you have https: Have you recently rotated a certificate and not restarted wings yet?

**Comment by crispyaus** [comment] 2021-08-24 11:44
Hi,
Do you have the server console open in more than one place? **No**
Did you restart wings and see if the issue goes away? **Have restarted wings, rebooted the dedi**
If you have https: Have you recently rotated a certificate and not restarted wings yet? **No**

I have now deleted that server, created a fresh one with paper 1.17, it seems and i have encountered issues using 1.16.5 in the past. So it could possibly be that? Since the other servers and this new server using 1.17 is working fine.

**Comment by nikrozman21** [comment] 2021-08-24 11:48
I can confirm this same issue happens to me too. I'm on the exact same versions as OP, haven't rotated the certificate, and don't have the console open in multiple places. Restarting wings usually fixes the problem. Running wings with --debug also doesn't show anything out of the ordinary, neither do Docker logs.

**Comment by trenutoo** [comment] 2021-08-24 13:22
Duplicate of #3528

**Closed as completed by trenutoo** 2021-08-24 13:22 UTC
