### ISSUE TITLE
Attribute for nodes to show resource usage

### ISSUE THREAD

**Issue by williamd5** [pterodactyl/panel#2144] opened 2020-07-02 23:19 UTC
**Describe the solution you'd like**
An object called "usage" could be added to a node's properties. This object could include the sum of the maximum RAM, CPU, Disk, etc. that all servers on this node have.

**Describe alternatives you've considered**
Currently, this is only possible (actually impossible because of a bug, reported in issue #2143) to be achieved by looping all nodes, then all servers, checking on which node the server is and incrementing the usage attributes for the nodes.

**Additional**
The alternative solution requires a lot of physical server resources, especially if there are a lot of servers created. This attribute can be useful to set up node management scripts that automatically find the most optimal node to create a server with n RAM, CPU, Disk, etc. on.

**Comment by DaneEveritt** [comment] 2020-07-03 03:02
For now, just call the node listing endpoint with `?include=servers` and you can do all of the math with a single request rather than a ton.

**Comment by DaneEveritt** [comment] 2020-07-03 04:19
Duplicate of https://github.com/pterodactyl/panel/issues/1518

**Closed by DaneEveritt** 2020-07-03 04:19 UTC
