### ISSUE TITLE
Node uuid ist empty - 1.0 beta

### ISSUE THREAD

**Issue by vanlueckn** [pterodactyl/panel#1932] opened 2020-04-16 17:14 UTC
The database fielt "uuid" ist entry when creating a new node. If i try to create a second node, i get a error 500 with the following content:

`production.ERROR: QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'nodes_uuid_unique' (SQL: insert into `nodes` (`public`, `behind_proxy`, `memory_overallocate`, `disk_overallocate`, `daemonBase`, `daemonSFTP`, `daemonListen`, `maintenance_mode`, `name`, `description`, `location_id`, `fqdn`, `scheme`, `memory`, `disk`, `daemon_token`, `daemon_token_id`, `updated_at`, `created_at`) values (1, 0, 20, 10, /srv/daemon-data, 2022, 8080, 0, opusgaming Host 02, Host 02, 2, host02.opusgaming.de, https, 128621, 875000, eyJpdiI6Ill2MFpQMVZJa0dVYVlndWI5RzV4MHc9PSIsInZhbHVlIjoiODRNcHVNNWk2eWtNXC9TR3QrOEl1Y0lZWGdIRmkyb01kUXFOR1gxWjQ5RG1za1JyQXREV0QzTjZNOHZBdmdBVXdrQzNvV2VtUDRsTXAzRUFJUmtXTlhLS2ZVc05qQnM1TFI1NkFNalZRdWY4PSIsIm1hYyI6IjcxNGFhZGVkYmJiNmU4ZTYwNTgzMDk1OWQ5NDVlNDU4OGI5OTE0NmQ4YmEyZmYzM2NiYzU2NTg1ZmFlYThlN2UifQ==, oSPWMb7FfME87yNc, 2020-04-16 19:08:51, 2020-04-16 19:08:51)) in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
Stack trace:`

When i manually set a value for uuid, i can create a new node. The uuid field keeps empty every time i try to create a new node.

**Comment by parkervcp** [comment] 2020-04-16 17:15
duplicate of #1930

**Closed by parkervcp** 2020-04-16 17:15 UTC
