### ISSUE TITLE
Latest update causes infinite loading and 500 error

### ISSUE THREAD

**Issue by james090500** [pterodactyl/panel#3224] opened 2021-03-26 18:16 UTC
**Background (please complete the following information):**
* Panel or Daemon: 1.3.2
* Version of Panel/Daemon: 1.3.2
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10/Chrome

**Describe the bug**
Php 8.0.3. This commit here adding tagging: c7375f0
https://github.com/pterodactyl/panel/blob/9b46d59045956378b3aeb275bb87c1933e0b3e6c/app/Http/Controllers/Api/Client/Servers/ResourceUtilizationController.php#L46

However, people who have `cache_driver` set with `file` or `database` will experience 500 errors as it doesn't support tagging. 

**To Reproduce**
1. Install Pterodactyl, have `cache_driver` as `file` in .env

**Expected behavior**
Not to error

**Comment by TASelwyn** [comment] 2021-03-26 18:18
Mhm.
Can confirm this occur is existing.
However, I am using redis & the php7.4.16

**Comment by james090500** [comment] 2021-03-26 18:19
> Mhm.
> Can confirm this occur is existing.
> However, I am using redis & the php7.4.16

Is your cache driver definitely set as "redis".

**Comment by TASelwyn** [comment] 2021-03-26 18:20
> > Mhm.
> > Can confirm this occur is existing.
> > However, I am using redis & the php7.4.16
> 
> Is your cache driver definitely set as "redis".
https://i.devil.wtf/2021/HauY4OqizpiV5QeW

I think so :)

**Comment by james090500** [comment] 2021-03-26 18:21
> > > Mhm.
> > > Can confirm this occur is existing.
> > > However, I am using redis & the php7.4.16
> > 
> > 
> > Is your cache driver definitely set as "redis".
> > https://i.devil.wtf/2021/HauY4OqizpiV5QeW
> 
> I think so :)

![image](https://user-images.githubusercontent.com/20372645/112676178-0661a800-8e60-11eb-8640-5925765920a5.png)

**Comment by TASelwyn** [comment] 2021-03-26 18:22
> > > > Mhm.
> > > > Can confirm this occur is existing.
> > > > However, I am using redis & the php7.4.16
> > > 
> > > 
> > > Is your cache driver definitely set as "redis".
> > > https://i.devil.wtf/2021/HauY4OqizpiV5QeW
> > 
> > 
> > I think so :)
> 
> ![image](https://user-images.githubusercontent.com/20372645/112676178-0661a800-8e60-11eb-8640-5925765920a5.png)

haha, my bad.
You are right, its' def set to file


Update: Setting CACHE_DRIVER to redis fixed it :)

**Comment by bentalexanderhaase** [comment] 2021-03-26 18:51
Same issue here. The cache driver has been `redis` for literally years. Interestingly it changed after the update.

**Comment by TASelwyn** [comment] 2021-03-26 18:52
> Same issue here. The cache driver has been `redis` for literally years. Interestingly it changed after the update.

Mhm, I thought mine was redis too. But it apparantly wasn't.

**Comment by edbrk** [comment] 2021-03-30 14:47
I havn't seen this issue on php 8.

**Comment by DaneEveritt** [comment] 2021-04-03 17:47
Closing this without fixing. We specifically don't support the file based cache driver and get people to install redis for things so that this can be avoided normally.

**Comment by DaneEveritt** [comment] 2021-04-03 17:52
Turns out I fucked up ages ago and accidentally allowed people to pick `file` as the driver, which is tragic.

**Closed as completed** 2021-04-03 17:53 UTC

**Comment by Beaast-exe** [comment] 2021-04-18 09:32
I had this problem until today.
Changing the CACHE_DRIVER on .env to "redis" fixed it.
NOTE: It was a fresh install of pterodactyl (Well, not so fresh, like 2 weeks, but you got it)

**Comment by TASelwyn** [comment] 2021-04-18 21:51
> I had this problem until today.
> Changing the CACHE_DRIVER on .env to "redis" fixed it.
> NOTE: It was a fresh install of pterodactyl (Well, not so fresh, like 2 weeks, but you got it)

Well, that is the suggested fix here. :)

**Comment by Patrity** [comment] 2021-04-23 14:18
Reopening to expand on this issue.
I encountered this same bug when upgrading. I found this issue and took the same steps which led to the following error output which points to a missing app key in the .env
https://bin.ptdl.co/vdvtl/

After quite some time of trying different things, thinking I malformed my .env file, I finally restarted my `redis-server` service (ubuntu 20.04) and things began acting normally again.

From this, I think we can learn that we need better error handling for when the redis service is not available.

**Comment by DaneEveritt** [comment] 2021-04-24 16:57
Your issue has nothing to do with this one and is not a bug.

**Comment by Patrity** [comment] 2021-04-24 17:01
> Your issue has nothing to do with this one and is not a bug.

Reporting a malformed app key when really a failed redis connection has occured is not a bug, huh? Interesting.

**Comment by DaneEveritt** [comment] 2021-04-24 17:14
I know how this software works, it doesn't report a malformed key because redis isn't running. If you believe otherwise you're welcome to open an issue at https://github.com/laravel/framework and have them look into it.

Either way, it has absolutely nothing to do with this specific issue.

**Comment by Patrity** [comment] 2021-04-24 17:19
I posted it here because it did in fact stem from this issue. I had to take additional steps that I outlined above in order to remedy this silly issue. I posted it here in case others ran into the same issue and it turns out someone else did in the discord. You can know the software from top to bottom all you'd like, but your pissing contest here is pointless when I only reported it here to aid others.
