### ISSUE TITLE
MariaDB query syntax outdated

### ISSUE THREAD

**Issue by SpirTBBX** [pterodactyl/panel#2949] opened 2021-01-01 12:40 UTC
* Panel or Daemon: 1.1.3
* Version of Panel/Daemon: 1.1.3
* Server's OS: Debian 9
* Your Computer's OS & Browser: Windows 10, Latest version of Microsoft Edge & Google Chrome

Issue:
I was trying to update my panel and wings from 1.1.3 to 1.2.0. I've followed the docs at Upgrading the panel and when I ran the force database seed, I got this error "SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs (SQL: alter table `eggs` add `docker_images` json null after `docker_image`, add `update_url` text null after `docker_images`)"

I reported my Issue at Pterodactyl's discord and the bot replied saying that my MariaDB or Mysql was outdated.
Running the command mysql -V got my mysql and mariadb version. Both of them newer than what bot said I needed to have.
mysql  Ver 15.1 Distrib 10.5.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Also I went to phpmyadmin to get maybe more info about my mysql server and got the same information.
At discord they said that there wasn't any "error" with my setup for this issue and they said to open a github bug report issue here.

I'd expect for the panel to work once I never had this issue. When I first tried to install 1.0 when upgrading from 0.7, It said that it was outdated and fixed it upgrading my MariaDB server. I added the repository of mariadb stable and running apt update says that all packages are up to date.

**Comment by DaneEveritt** [comment] 2021-01-04 00:14
I cannot help you at all with the information provided. Please include the full error including what specific migration is failing.

**Comment by SpirTBBX** [comment] 2021-01-08 23:12
The only "logs" I can provide are the errors that my MySQL server is complaining about, once it is the only issue I'm getting atm.

Here is the output of all panel upgrade commands:

... I have downloaded the panel and extracted all the files...

root@debian:/var/www/pterodactyl# chmod -R 755 storage/* bootstrap/cache
root@debian:/var/www/pterodactyl# composer install --no-dev --optimize-autoloader
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: appstract/laravel-blade-directives
Discovered Package: fideloper/proxy
Discovered Package: laracasts/utilities
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Discovered Package: prologue/alerts
Discovered Package: spatie/laravel-fractal
Discovered Package: spatie/laravel-query-builder
Package manifest generated successfully.
45 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
root@debian:/var/www/pterodactyl# php artisan view:clear
Compiled views cleared!
root@debian:/var/www/pterodactyl# php artisan config:clear
Configuration cache cleared!
root@debian:/var/www/pterodactyl# php artisan migrate --seed --force
Migrating: 2020_12_12_102435_support_multiple_docker_images_and_updates

In Connection.php line 671:

  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You h
  ave to change some columns to TEXT or BLOBs (SQL: alter table `eggs` add `docker_images` json null after `docker_image`, add `update_url` text null after `docker_images`)


In PDOStatement.php line 129:

  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You h
  ave to change some columns to TEXT or BLOBs


In PDOStatement.php line 127:

  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You h
  ave to change some columns to TEXT or BLOBs

**Comment by DaneEveritt** [comment] 2021-01-10 20:39
Sounds like you have a custom egg with an insane amount of data in it. Since no one else is reporting this issue and I cannot reproduce it I am closing this issue.

**Closed as completed by DaneEveritt** 2021-01-10 20:39 UTC
