### ISSUE TITLE
All players connected get the IP 172.18.0.1

### ISSUE THREAD

**Issue by KewaiiGamer** [pterodactyl/panel#1039] opened 2018-03-08 16:03 UTC
* Daemon: 
* Version of Daemon: 0.5.4
* Server's OS: Ubuntu 14.04
* Your Computer's OS & Browser: Windows 10 but is not dependent of that

Pretty much with this new version of the Daemon all of the players that connect to the Game Server are using the same IP 172.18.0.1. 
Only tested in CS:GO.
The server is binded to 0.0.0.0

**Comment by KewaiiGamer** [comment] 2018-03-08 16:14
Players also seem to be getting banned by rcon attempts and people that get IP-banned will make all others players get banned too. So it's a major issuse

**Comment by ki2007** [comment] 2018-03-08 18:40
That's most probably caused by the userland-proxy. So a docker thing and not really something the panel or the daemon does.

Only using hairpin-nat over docker-proxy would change that. 
Apparently there are some problems though on specific hardware configurations.

Using iptables should also give better performance, but I think thats more in the 10^-100 area.

**Comment by DaneEveritt** [comment] 2018-03-09 02:14
That doesn't really sound like a software issue since we have tons of other hosts and users running without issues. Its most likely a weird configuration or network setup, but I can't really help since I don't have many details.

I'd suggest hopping on Discord and asking around on there. I'm closing this issue unless other people can also relate to this and provide enough information showing that it is indeed an issue with this software.

**Closed by DaneEveritt** 2018-03-09 02:14 UTC

**Comment by KewaiiGamer** [comment] 2018-03-09 06:11
I fixed it by replacing ufw by iptables. Thanks for your suggestion @ki2007 !

**Comment by mclucario** [comment] 2019-08-30 23:00
For Fedora / RHEL / CentOS (aka firewalld users) you can remove the masuqerade from the zone that contains docker0/pterodactyl0.

Example:
Get your active zones:
`sudo firewall-cmd --get-active-zones`

Output Example:
![grafik](https://user-images.githubusercontent.com/10533763/64055038-614ef280-cb8a-11e9-9df9-cb157db2933e.png)

Remove masquerading from the zone that contains your docker0/pterodactyl0 interface
`sudo sudo firewall-cmd --zone=FedoraServer --remove-masquerade`

If that worked and nothing broke, then repeat your command and append `--permanent` to save your changes.

**Comment by parkervcp** [comment] 2019-08-31 00:18
The `FedoraServer` isn't a default and that is mostly useless to everyone but you. I have several fedora servers and none have that.

**Comment by parkervcp** [comment] 2019-08-31 00:21
and I get that you are trying to point out that it's the "docker0" in that but I don't generally see this kind of issue on centos.

**Comment by mclucario** [comment] 2019-08-31 19:58
> 
> 
> The `FedoraServer` isn't a default and that is mostly useless to everyone but you. I have several fedora servers and none have that.

The FedoraServer zone is an example. I never said its a default neither did I say its gartantueed fix. ;)

> 
> 
> and I get that you are trying to point out that it's the "docker0" in that but I don't generally see this kind of issue on centos.

Thats good for you.

**Comment by parkervcp** [comment] 2019-08-31 21:04
Also your comment is not helpful as this affected ubuntu not centos.

**Comment by mclucario** [comment] 2019-08-31 21:14
> 
> 
> Also your comment is not helpful as this affected ubuntu not centos.

Its literally the first thing you find when you look for the issue on Google. This might not apply to Ubuntu but it would have helped me if someone else noted it on here beforehand and since that wasn't the case so I did that. This is not really worth discussing either.

**Comment by GiovaniFerraroTrivelli** [comment] 2020-11-24 03:57
I am having a similar issue, using updated Panel and Wings (1.1.1). Running HLDS and CS: GO servers.

Immediately after starting a server, some players (if they connect faster) receive the IP 172.18.0.1.

![unknown](https://user-images.githubusercontent.com/27016185/100046631-53206e00-2def-11eb-8a73-feb2ce8ddd64.png)

Host is running Ubuntu 16.04.6 LTS.
