### ISSUE TITLE
Node Maintenance Bug

### ISSUE THREAD

**Issue by alexgn100** [pterodactyl/panel#3168] opened 2021-03-09 16:55 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel and Daemon
* Version of Panel/Daemon: 1.3.1 / 1.3.1
* Server's OS: Debian 10.8
* Your Computer's OS & Browser: Windows 10

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: PHP 8.0.3
Daemon: Linux games-03 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
Docker: `Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 33
  Running: 15
  Paused: 0
  Stopped: 18
 Images: 49
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-14-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 31.42GiB
 Name: games-03
 ID: G2V7:44DL:YIUK:CNEV:JYXG:AZER:JNCY:RURN:2HPT:4ZKD:SA6B:SGGH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`

**To Reproduce**
1. Go to the Admin Panel
2. Click on Nodes
3. Select one Node
4. Go to Settings
5. Activate  Maintenance Mode
6. Go to the User Site
7. Click on a Server this on the Node
8. User still can manage the Server

**Expected behavior**
When i enable the  Maintenance Mode on a Node the User can stil manage their Server. In an older version, when maintenance mode was enabled, I could no longer manage a server on it.

**Comment by trenutoo** [comment] 2021-03-09 16:55
Duplicate of #2705

**Closed as completed** 2021-03-09 17:00 UTC
