### ISSUE TITLE
1.0.0 Beta - Locations don't work

### ISSUE THREAD

**Issue by AToska21** [pterodactyl/panel#2053] opened 2020-05-20 19:22 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0 Beta
* Server's OS: Linux Debian 10
* Your Computer's OS & Browser: Windows 10 1908 (or something like that), Google Chrome 81.0.4044.138 (Official Build) (64-bit) (cohort: Stable)

**Describe the bug**
When I try to create a location It just reloads itself and does nothing.
Panel: PHP 7.3.14-1~deb10u1 (cli) (built: Feb 16 2020 15:07:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

**To Reproduce**
1. Go to Admin configuration
2. Click on Locations
3. Create a new one
4. Nothing happens.

**Expected behavior**
The location was supposed to be created.

**Comment by parkervcp** [comment] 2020-05-20 20:57
This is working for me. Do you have any logs to back up this not working?

You do need a short code and a description to create a location.

**Comment by Sir3lit** [comment] 2020-05-21 00:43
That short code should've been made optional.....

**Comment by parkervcp** [comment] 2020-05-21 12:06
Oh it's still needed.

**Comment by Sir3lit** [comment] 2020-05-22 03:43
Sorry.... Correction the shortcode is required, as that's its name. The Description was made optional. I'm not able to reproduce this??

Without logs or anything to go off id call for this to be closed.

**Comment by DaneEveritt** [comment] 2020-05-22 15:15
@AToska21 please respond to this issue with logs from the panel, otherwise I am closing this for now since it cannot be reproduced.

**Closed by DaneEveritt** 2020-05-22 15:15 UTC
