### ISSUE TITLE
Cant change password of an acc

### ISSUE THREAD

**Issue by Yomanz** [Pterodactyl/Panel#952] opened 2018-02-18 15:57 UTC
* Panel
* Version of Panel/Daemon: 0.7
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Ubuntu 16.04 Firefox

## Add Details Below:

I made the account via CLI but when trying to change the password via admin panel I get:
`strpos() expects parameter 1 to be string, object given`

**Comment by Yomanz** [comment] 2018-02-18 16:02
https://you-are.verygay.today/q7ei8.png also when trying to login!

**Comment by Yomanz** [comment] 2018-02-18 16:03
https://cdn.discordapp.com/attachments/374638621988225025/414814208857997314/unknown.png
Also when logging in,

**Comment by schrej** [comment] 2018-02-18 16:27
duplicate of #950

**Closed by schrej** 2018-02-18 16:27 UTC
Labels: Bug, P: High
