### ISSUE TITLE
Time in Daemon isn't correct

### ISSUE THREAD

**Issue by DJKenzoDE** [pterodactyl/panel#2239] opened 2020-08-15 17:06 UTC
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: Wings 1.0.0 Beta 9
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 + Chrome Latest Version

**Describe the bug**
The Time in the Deamon its not correct. I have it installed on Ubuntu 20.04 
In the logs from Minecraft and the Console are 2 Hours behind.
Here ScreenShot from the System and the Time with 3 commands [hwclock, date, timedatectl]
https://prnt.sc/u04qjz

**To Reproduce**
Setting up the Server [apt-get update, apt-get upgrade]
Show its nano, screen and htop installed, when not i installed it
Installed the Panel first with mysql-db
Installed the Daemon

**Comment by fabm3n** [comment] 2020-08-15 17:08
Dupe of #2073 we just should reopen that

**Comment by parkervcp** [comment] 2020-08-15 17:12
This is also a duplicate of #2195 Which also calls out this sort of issue.

**Comment by fabm3n** [comment] 2020-08-15 17:14
Nope #2195 is about the extremly wrong formatted time of backups in the panel.
This is about wrong timezones inside of the docker container.

**Comment by parkervcp** [comment] 2020-08-15 17:18
I am going to go with a "people will still complain about the time because it's not in their timezone" argument as well.
If you have a user outside the server timezone the time and date will still be wrong to that user.

Honestly the "server time is in UTC" complaint is tedious to me. Imaging having servers around the globe and if they were all set in their respective time zones trying to parse any kind of logging would be stupid to make sure they were all correct.

**Comment by DaneEveritt** [comment] 2020-08-18 02:31
I'm getting pretty tired of these issues cropping up constantly. No matter what crazy complicated shit I end up coming up with there is  _always_ some process or system that struggles to fetch a time correctly.

Passing through the `TZ=` flag is a very standardized way of handling timezones. I'd much rather just continue doing that rather than relying on these timezone mounts which are flaky at best and every OS seems to handle differently. At this point I think it makes more sense for the images running the games to be handling any timezone related issues, be that reading the `TZ` variable and executing commands to set the time correctly in the container, or passing that flag along to the game in some game-specific manner.

**Closed by DaneEveritt** 2020-08-18 02:31 UTC
