### ISSUE TITLE
Server search doesn't work in admin

### ISSUE THREAD

**Issue by stijnb1234** [pterodactyl/panel#2317] opened 2020-09-06 14:12 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-rc.3
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 with Brave (Chromium based)

**Describe the bug**
The search button on the server list on the admin side doesn't work.

![image](https://user-images.githubusercontent.com/27051051/92327661-89094e00-f05b-11ea-9300-6c37d0cce20e.png)
It will change the url to ?query=...., but the results in the table won't change.

**To Reproduce**
1. Go to admin panel
2. Go to server list (/admin/servers)
3. Typ in search words, and click on enter
4. Nothing changes, it only reloads the page

**Expected behavior**
The table changes based on the entered keywords.

**Comment by Sir3lit** [comment] 2020-09-06 19:22
Duplicate of #2100

**Comment by schrej** [comment] 2020-09-06 19:42
No, not a duplicate.

**Comment by DaneEveritt** [comment] 2020-09-07 20:22
Closing it as a duplicate of #2100 and I'll update that one to reflect all search, since they all use the same logic, which is what is broken.

**Closed** 2020-09-07 20:22 UTC
Labels: 1.0 🦈, bug 🐛
