### ISSUE TITLE
Translation system

### ISSUE THREAD

**Issue by MrKubuS** [pterodactyl/panel#4276] opened 2022-07-23 06:52 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Translation system

### Describe the solution you'd like.

Translation system

**Comment by 0x7d8** [comment] 2022-07-23 07:12
I dont think you did search for feature requests for this

**Comment by Jelcoo** [comment] 2022-07-23 08:15
There is an open pr for this,  #2888

**Comment by trenutoo** [comment] 2022-07-23 10:00
Duplicate of #2518

**Closed as completed by trenutoo** 2022-07-23 10:00 UTC
