### ISSUE TITLE
Can't allocate more memory to node

### ISSUE THREAD

**Issue by Keystirras** [Pterodactyl/Panel#914] opened 2018-02-04 16:36 UTC
Linux ns518452 4.9.58-xxxx-std-ipv6-64 #1 SMP Mon Oct 23 11:35:59 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.2.2-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  1 2018 16:01:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.58-xxxx-std-ipv6-64
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.43GiB
Name: ns518452
ID: JN7C:67ZI:6DCB:BIKA:RLGV:O3HT:LMM7:LL4D:PUZ4:2P2N:E44M:SR2L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

* Panel or Daemon: Panel
* Version of Panel/Daemon: Beta 7.something
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Win 10 + Google Chrome

When i try editing the memory space allowed in the panel for a node it just re-directs me to a "Whoops, looks like something went wrong." page. 
Here's the logs for the panel: 409747274605002752

**Comment by lancepioch** [comment] 2018-02-04 17:05
We need the panel logs.

**Comment by DaneEveritt** [comment] 2018-02-04 18:56
Duplicate of #915

**Closed by DaneEveritt** 2018-02-04 18:56 UTC
Labels: Beta/RC Build, Bug
