### ISSUE TITLE
email/username search in the search bar

### ISSUE THREAD

**Issue by JakeySuccessor** [pterodactyl/panel#2740] opened 2020-11-24 21:28 UTC
**Is your feature request related to a problem? Please describe.**
 I would like to request an addition to search usernames/email in the search bar like we previously could in 0.7.19

**Describe the solution you'd like**
Previously to find a user server list you would search for their email/email but now you can not search for it so you would have to manually check each server user to see if it is. 

**Describe alternatives you've considered**
A method to look at a specific users server-id / package viewer on the clients

**Additional context**
Not really

**Comment by DaneEveritt** [comment] 2020-11-29 19:02
Duplicate of https://github.com/pterodactyl/panel/issues/2366

**Closed as completed by DaneEveritt** 2020-11-29 19:02 UTC
