### ISSUE TITLE
Node having problems with connecting to the database, when panel connects fine.

### ISSUE THREAD

**Issue by splyfof** [pterodactyl/panel#4070] opened 2022-05-08 17:39 UTC
### Current Behavior

when trying to view a servers settings (or really do anything in the panel.splyfof.com/servers/f82e21fc section, panel.splyfof.com is also just loading forever) im getting a error code 500 which looks to be a database issue.
![image](https://user-images.githubusercontent.com/83120236/167308401-1b72aaf9-4843-4027-a29a-fe56a6cd4dc3.png)
![image](https://user-images.githubusercontent.com/83120236/167308421-edc08536-575a-41f0-bc3d-5c0f0b8c894e.png)
i have tried to change the db password in the file /var/www/pterodactyl/.env to something incorrect, which results in a 500 error everywhere in the panel, so the db password is not the problem.
i have granted the pterodactyl database user all the perms it needed according to the docs.
![image](https://user-images.githubusercontent.com/83120236/167308121-76608e40-6d77-4c8f-867a-577b8e51c229.png)
so the problem looks to be that the node has problems with connecting to the database when the panel can connect fine.
i have talked to some people in the discord but no-one could see the problem so thats why im thinking it might be a bug

### Expected Behavior

i would expect it show me the servers and settings of each server normally

### Steps to Reproduce

start the vps
check wings, nginx and mysql are up and running
go to panel.splyfof.com (or your domain address) and see that its just loading forever

### Panel Version

1.7.0

### Wings Version

1.6.1

### Error Logs

```bash
https://ptero.co/icibyzygum
http://bin.ptdl.co/twbt0
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment] 2022-05-08 17:50
>   go to panel.splyfof.com (or your domain address) and see that its just loading forever

Works fine for me. It would be a network issue between the web server and you.

> SQLSTATE[HY000] [1045] Access denied for user 'pterodactyl'@'localhost' (using password: YES)

This is from the Panel <> database connection and  appears to be an old error

>  Type of Pterodactyl\Transformers\Api\Client\ServerTransformer::$availableIncludes must be array (as in class League\Fractal\TransformerAbstract)

You've updated composer packages and broke the panel. Support for new PHP 8.1 dependencies exists in future Panel 1.8 release. 


Our support bot on Discord is configured to reply to all of your issues above if you post individual errors. Also, this is a duplicate of #4027 and #4028

**Closed as completed** 2022-05-08 18:03 UTC
