### ISSUE TITLE
SSH Terminal for the Minecraft Server

### ISSUE THREAD

**Issue by WOLFI3654** [pterodactyl/panel#2324] opened 2020-09-10 17:15 UTC
**Is your feature request related to a problem? Please describe.**
We all know how it feels to upload plugins with a web manager to the server. SFTP came to rescue there.
But I think the same way we are using SFTP now for uploading files could also be applied to the terminal. 

**Describe the solution you'd like**
Since the FTP Server is already routed through SSH (SFTP), the minecraft console could be routed through SSH aswell in the form of a simple terminal.(instead of your traditional bash shell on your remote server you just get the minecraft console) This way you could manage your minecraft server with your favourite SSH client which supports both FTP and Terminal connections. This would give the minecraft server a much more traditional server feel and it would make actually monitoring the console much more easier since most IDEs support SSH terminals + FTP aswell (at least with add-ons). This would help to integrate the minecraft server into your dev-envoirement so greatly.
Furthermore, people who actually manage the vServer/root Server(or even minecraft server administrators) where the panel instance is hosted can just create a new connection profile in their SSH client pointing directly to the minecraft server instance.
I think one of the reason people decide to put a mc-server panel on their machiene is to make a server setup and management much easier. I quite well remember the days of manually copying jar files, templates and screen -x ing into the server session and just a centralized and integrated way to manage both console and files would just be marvelous. 

**Describe alternatives you've considered**
Definetly just using the webbrowser. But that feels a bit boring (like uploading the plugins with a simple file manager).
And it slows down your workflow quite a bit if you have to switch through all your windows.

**Comment by Sir3lit** [comment] 2020-09-10 17:18
I'd consider this related to https://github.com/pterodactyl/panel/issues/2297 as they have the same end result of wanting an SSH console for the servers.

**Comment by DaneEveritt** [comment] 2020-09-10 19:42
Yes, this is a duplicate of that.

**Closed by DaneEveritt** 2020-09-10 19:42 UTC
