### ISSUE TITLE
Add ability to set node temporarly offline

### ISSUE THREAD

**Issue by ET-Bent** [Pterodactyl/Panel#423] opened 2017-05-03 06:45 UTC
Looking forward to server migrations between nodes it would be beneficial to add the ability to mark nodes as temporarily disabled in the panel.

So instead of showing servers on these nodes as "error", they could be marked as "maintenance" or similar.

**Comment by DaneEveritt** [comment] 2017-05-03 15:57
duplicate of #142

**Closed by DaneEveritt** 2017-05-03 15:57 UTC
