### ISSUE TITLE
Error 500 (RequestException.php:113) thrown when attempting to use files tab & start server

### ISSUE THREAD

**Issue by Supermarcel10** [pterodactyl/panel#5159] opened 2024-07-12 21:09 UTC
### Current Behavior

Server console works and allows pressing the `start` button. Pressing the `start` button throws an error:
```
Error Event [0c06876e-300d-4ba9-857a-861f35cc1f42]: failed to chown root server directory during pre-boot process: server/filesystem: chown: failed to chown during walk function: no such file or directory
```

Moving over to the files tab, an error is displayed:
```
Something went wrong

There was an error while communicating with the machine running this server. This error has been logged, please try again. (code: 500) (request_id: add4ce35-4e9b-4536-ab66-5740acc8c03e)
```
![image](https://github.com/user-attachments/assets/a8d744ec-6811-43af-90f4-9e9693b2ca69)

All other tabs work and display as normal.

### Expected Behavior

Server works as normal and displays the files in the directory.

### Why is this important?

This can be used as a form of reloading a manual backup that was made before.

### Reproducing

> [!CAUTION]
> Running these actions may inadvertedly delete/destroy your server without any confirmation.

> [!NOTE]
> Replace each `SERVER_UUID` with an actual server UUID instance.
> For example `d49f11d4-7249-4c87-bf6a-4965512274c7`

1) Escalate to root.
2) Run `cd /var/lib/pterodactyl/volumes/`.
3) Run `tar -czvf backup.tar.gz SERVER_UUID`.
4) Run `rm -rd SERVER_UUID`.
5) Run `mkdir backup`
6) Run `tar -xvzf backup.tar.gz -C backup/`.
7) Run `cp -rd backup/* SERVER_UUID`. 
6) Run `chown -R pterodactyl SERVER_UUID`.
7) Run `chmod -R 755 SERVER_UUID`.

### Testing

When you test now, the server should have the issue described in "Current Behaviour".

### Workaroud

1) Create a new server instance.
2) Let it build.
3) Run the following to copy over all of the files from the old server instance:
```
cd ../NEW_SERVER_UUID
rm server.properties
cp -rd OLD_SERVER_UUID/* NEW_SERVER_UUID/*
```
4) Change any configurations on the panel such as startup commands.
5) Run server (successfully runs and no longer produces error). View the files by clicking on the files tab, and no 500 error is produced - thus proving the problem is solved.

### Panel Version

1.11.7

### Wings Version

1.11.3

### Error Logs

```bash
https://pastebin.com/dVfnGuzL
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment] 2024-08-07 02:15
I believe I know the root cause of this.
Can you confirm if restarting wings causes the errors to go away?

**Comment by Supermarcel10** [comment] 2024-08-07 07:06
I have the old instance still there, so I gave that a try.

Original state as described. After restarting wings, the "Files" tab no longer throws a 500 and the server can be started without any issues.

**Comment by danny6167** [comment] 2024-08-29 03:02
Thank you for confirming that.

This will be resolved in the next release of wings.
Ref: https://github.com/pterodactyl/wings/commit/8744e64f1d888921b6f7cac1ebacc31d86e48cd4

**Closed as completed by danny6167** 2024-08-29 03:02 UTC
