### ISSUE TITLE
Backup unpacking all files in main directory without folders

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3306] opened 2021-04-28 00:52 UTC
* Version of Panel: 1.4.0 
* Version of Wings: 1.4.0
* System Information: Linux pterodactyl 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
* Server's OS: Debian 10
* PHP Version: PHP 7.4.16 (cli) (built: Mar  5 2021 08:36:10) ( NTS ) Zend Engine v3.4.0,

* Your Computer's OS & Browser: Win10 & Firefox

**Describe the bug**
After unpacking the backup, all files are displayed in the main directory. No folders are created. 

**To Reproduce**
Steps to reproduce this behavior:

1. Create an Backup
2. Resore an Backup

**Expected behavior**
Evidence video: https://www.youtube.com/watch?v=mq_dat6MxUU

**Comment by trenutoo** [comment] 2021-04-28 00:53
Duplicate of #3296 and already fixed, you need to wait for a new release

**Closed as completed** 2021-04-28 02:09 UTC
