### ISSUE TITLE
Transfer issues Invalid parameter number at PDOStatement.php:67

### ISSUE THREAD

**Issue by Pho3niX90** [pterodactyl/panel#3169] opened 2021-03-09 18:36 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.1
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 / Chrome

**More information:**
Panel is located on its own server. 

**Describe the bug**
The transfer never happens, and stays in the transfer state. 

Panel: PHP 8.0.3 (cli) (built: Mar  5 2021 07:54:13) ( NTS )
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

**Node1:**
Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Node2:**
Linux 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
1. Initiated a transfer of a server from node1, to node2
2. Error log at the bottom.

**Expected behavior**
The transfer needs to happen, or indicate an error, and revert changes done.

wings statuses from nodes
![image](https://user-images.githubusercontent.com/7858187/110520436-20d51b00-8117-11eb-90ff-d960befad5bd.png)

```
[previous exception] [object] (PDOException(code: HY093): SQLSTATE[HY093]: Invalid parameter number at /var/www/pterodactyl/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:67)
[stacktrace]
#0 /var/www/pterodactyl/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(67): PDOStatement->bindValue()
#1 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(589): Doctrine\\DBAL\\Driver\\PDOStatement->bindValue()
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(494): Illuminate\\Database\\Connection->bindValues()
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(671): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(638): Illuminate\\Database\\Connection->runQueryCallback()
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(503): Illuminate\\Database\\Connection->run()
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(436): Illuminate\\Database\\Connection->affectingStatement()
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2913): Illuminate\\Database\\Connection->update()
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(824): Illuminate\\Database\\Query\\Builder->update()
#9 /var/www/pterodactyl/app/Http/Controllers/Api/Remote/Servers/ServerTransferController.php(207): Illuminate\\Database\\Eloquent\\Builder->update()
#10 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): Pterodactyl\\Http\\Controllers\\Api\\Remote\\Servers\\ServerTransferController->Pterodactyl\\Http\\Controllers\\Api\\Remote\\Servers\\{closure}()
#11 /var/www/pterodactyl/app/Http/Controllers/Api/Remote/Servers/ServerTransferController.php(208): Illuminate\\Database\\Connection->transaction()
#12 /var/www/pterodactyl/app/Http/Controllers/Api/Remote/Servers/ServerTransferController.php(139): Pterodactyl\\Http\\Controllers\\Api\\Remote\\Servers\\ServerTransferController->processFailedTransfer()
#13 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Pterodactyl\\Http\\Controllers\\Api\\Remote\\Servers\\ServerTransferController->failure()
#14 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#15 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#17 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->run()
#18 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#19 /var/www/pterodactyl/app/Http/Middleware/Api/Daemon/DaemonAuthenticate.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\Daemon\\DaemonAuthenticate->handle()
#21 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#23 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then()
#25 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack()
#26 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute()
#27 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute()
#28 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#29 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#30 /var/www/pterodactyl/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#32 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#34 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#38 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#40 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#42 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#44 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#45 /var/www/pterodactyl/public/index.php(68): Illuminate\\Foundation\\Http\\Kernel->handle()
#46 {main}
"}
```

**Comment by Software-Noob** [comment] 2021-03-09 18:40
The transfer method has changed to the backup driver, which should resolve these issues. It hasn't been released yet but is currently available on the Wings develop branch

**Comment by DaneEveritt** [comment] 2021-03-09 18:44
This has nothing to do with the driver @Software-Noob. Also even if it did the new driver was in 1.3.1.

**Comment by Pho3niX90** [comment] 2021-03-09 18:51
Please let me know if you need more information of anything.

**Comment by Pho3niX90** [comment] 2021-03-09 18:56
Just to add more reference to the first part of the screenshot:
The first TLS error is from the other node. 
The other errors are from an unknown IP (5.188.210.227)

**Comment by Telesphoreo** [comment] 2021-03-09 20:02
Make sure you have all of the extensions for PHP 8.0 installed that the panel requires

**Comment by Pho3niX90** [comment] 2021-03-09 20:50
@Telesphoreo 

![image](https://user-images.githubusercontent.com/7858187/110536150-cf825700-8129-11eb-827d-be8b7cc622e1.png)

**Comment by Pho3niX90** [comment] 2021-03-10 10:14
As a test, I downgraded to php7.4.

It still fails, however doesn't stay in the transfer state and updates the database correctly. 

Process:
transfer from node1 to node2.

I have attached a screenshot of the schedules table:
![image](https://user-images.githubusercontent.com/7858187/110612919-53275c80-8199-11eb-8ff3-4fc9313ca264.png)

Interestingly enough, not all the allocations are then returned to the pool on failure
![image](https://user-images.githubusercontent.com/7858187/110613108-8964dc00-8199-11eb-9625-a2c13c6a3e2e.png)

More error screenshots from wings
![image](https://user-images.githubusercontent.com/7858187/110613385-e06ab100-8199-11eb-94e3-ad9a07819da9.png)

The "PositiveSSL Certificate" was purchased from Sectigo

**Comment by Pho3niX90** [comment] 2021-03-10 10:38
Another update

Running wings with `--ignore-certificate-errors` made the transfer report successful. However, now this is seen:
![image](https://user-images.githubusercontent.com/7858187/110615913-9c2ce000-819c-11eb-8078-1f861621e110.png)

only console not working from all panels from this server, filemanager etc is working fine 

Console error:
![image](https://user-images.githubusercontent.com/7858187/110616570-59b7d300-819d-11eb-8c41-da89cb169001.png)

Wings:
https://ptero.co/ivequfabuz
useful from line 181

I also noticed that it didn't remove 2 allocations it had prior to the transfer to the old server
![image](https://user-images.githubusercontent.com/7858187/110617435-612bac00-819e-11eb-8e76-d7c886806629.png)

**Comment by DaneEveritt** [comment] 2021-03-21 17:30
Honestly, just going to close this because I've not heard of other people having _this many_ different issues with transfers. It honestly sounds like something got messed up in your upgrade and just compounded down the line to multiple different issues.

**Comment by Lochnair** [comment] 2021-08-06 23:25
Ran into what I believe is the same issue when transferring servers to a new node:

```
[2021-08-07 00:44:24] production.ERROR: SQLSTATE[HY093]: Invalid parameter number (SQL: update `allocations` set `server_id` = ?, `allocations`.`updated_at` = 2021-08-07 00:44:24 where `id` in (2036, 2037)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY093): SQLSTATE[HY093]: Invalid parameter number (SQL: update `allocations` set `server_id` = ?, `allocations`.`updated_at` = 2021-08-07 00:44:24 where `id` in (2036, 2037)) at /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php:692)
```
Relevant part of the code:

https://github.com/pterodactyl/panel/blob/10b357b71e747f72e1474959c70efa04866d8a47/app/Http/Controllers/Api/Remote/Servers/ServerTransferController.php#L156-L163

Added a some extra logging to see if I could catch what was going wrong, seems the allocations array ends up nested somehow:
```
[2021-08-07 00:44:24] production.DEBUG: Remove old allocations:  [2036,[2037,2038,2039,2040]]
```

Replaced the code to make the allocations array with this:
```
$allocations = array_merge([$transfer->old_allocation], $transfer->old_additional_allocations);
```

Running a transfer again after doing that works fine for me, and the allocations array is now not nested. I don't know if the array behavior I'm seeing is caused by PHP 8 or not, but I did see some mentions of that being the reason on a Reddit thread with a Laravel user seeing a similar problem.

Either way I believe there _is_ an issue here that needs to be fixed. I'd appreciate input from someone that knows the codebase better if my quick fix will work properly in all cases, so we can get a fix submitted for inclusion.

**Comment by DaneEveritt** [comment] 2021-08-07 15:41
Yeah looks like it is merging an array of items `$transfer->old_additional_allocations` into A, rather than the items within that array into A.

**Comment by Valiantiam** [comment] 2021-08-12 02:17
Just chiming in to say I'm having these exact issues as stated above, and implementing the fix from @Lochnair did not fix the issue in my case.

I also have PHP8

**Comment by Valiantiam** [comment] 2021-08-12 02:58
> Ran into what I believe is the same issue when transferring servers to a new node:
> 
> ```
> [2021-08-07 00:44:24] production.ERROR: SQLSTATE[HY093]: Invalid parameter number (SQL: update `allocations` set `server_id` = ?, `allocations`.`updated_at` = 2021-08-07 00:44:24 where `id` in (2036, 2037)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY093): SQLSTATE[HY093]: Invalid parameter number (SQL: update `allocations` set `server_id` = ?, `allocations`.`updated_at` = 2021-08-07 00:44:24 where `id` in (2036, 2037)) at /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php:692)
> ```
> 
> Relevant part of the code:
> 
> https://github.com/pterodactyl/panel/blob/10b357b71e747f72e1474959c70efa04866d8a47/app/Http/Controllers/Api/Remote/Servers/ServerTransferController.php#L156-L163
> 
> Added a some extra logging to see if I could catch what was going wrong, seems the allocations array ends up nested somehow:
> 
> ```
> [2021-08-07 00:44:24] production.DEBUG: Remove old allocations:  [2036,[2037,2038,2039,2040]]
> ```
> 
> Replaced the code to make the allocations array with this:
> 
> ```
> $allocations = array_merge([$transfer->old_allocation], $transfer->old_additional_allocations);
> ```
> 
> Running a transfer again after doing that works fine for me, and the allocations array is now not nested. I don't know if the array behavior I'm seeing is caused by PHP 8 or not, but I did see some mentions of that being the reason on a Reddit thread with a Laravel user seeing a similar problem.
> 
> Either way I believe there _is_ an issue here that needs to be fixed. I'd appreciate input from someone that knows the codebase better if my quick fix will work properly in all cases, so we can get a fix submitted for inclusion.

Did you replace that entire section with your new code. or just line 156? I ask because my attempt to resolve didn't work, and I wanted to make sure I was following your _workaround_ for it.

**Comment by Lochnair** [comment] 2021-08-14 19:58
@Valiantiam I replaced 
https://github.com/pterodactyl/panel/blob/10b357b71e747f72e1474959c70efa04866d8a47/app/Http/Controllers/Api/Remote/Servers/ServerTransferController.php#L156-L159

With:
```php
$allocations = array_merge([$transfer->old_allocation], $transfer->old_additional_allocations);

```

Later I also found I had to replace the equivalent code for failed transfers:
https://github.com/pterodactyl/panel/blob/10b357b71e747f72e1474959c70efa04866d8a47/app/Http/Controllers/Api/Remote/Servers/ServerTransferController.php#L202-L205

Like so:

```php
$allocations = array_merge([$transfer->new_allocation], $transfer->new_additional_allocations);

```

**Comment by Valiantiam** [comment] 2021-08-16 21:56
Happy to report those exact changes worked like a charm. Thank you so much. This is going to make a week of migrations I have to do, SO much easier. THANK YOU.

Hopefully this is as simple of a fix as the devs need for an official patch.

thank you again.

**Closed as completed** 2021-08-18 18:58 UTC
