### ISSUE TITLE
Unable to select file in file manager when there is file operation overlay over the file

### ISSUE THREAD

**Issue by itsmemac** [pterodactyl/panel#4768] opened 2023-04-27 15:50 UTC
### Current Behavior

Unable to select the last file in the file manager when there is file operation overlay (Move, Archieve & Delete button overlay)

You are only able to select it by unselecting all the files and selecting the last file first so its doesn't get overlayed

<a href="https://imgur.com/Cn1EnHR" target="_blank" rel="nofollow">Video link</a>

### Expected Behavior

Should be able to select item even when there is overlay

### Steps to Reproduce

- Select files in File Manager
- Scroll to the last file
- Try selecting the last file

### Panel Version

1.11.3

### Wings Version

1.11.5

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment] 2023-04-27 16:06
Duplicate of #4553.

**Closed as not planned** 2023-05-13 05:27 UTC
