### ISSUE TITLE
Wings console and graphics that no longer refresh (on 2 panel) 

### ISSUE THREAD

**Issue by bagou4502** [pterodactyl/panel#3528] opened 2021-08-06 21:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

On several panel some servers bug and no longer refresh the console and graphics
I have this problem on several panels and therefore several different wings.
I can fix this by restarting the wings.

### Expected Behavior

You can see this videofor explain the problem
[https://youtu.be/5iGzVIGrMWI?t=56](url)

In this video I do anything to show the problem
And at a time the panel no longer refreshes the console automatically and no longer displays the graphics of the server

I think its a wings problem because i got that in my wings logs

```
ERROR: [Aug  6 17:30:36.315] error during environment resource polling container_id=4df5a01a-490a-412a-809b-bce56d487fcb environment=docker error=cannot enable resource polling on a stopped server

Stacktrace:
cannot enable resource polling on a stopped server
github.com/pterodactyl/wings/environment/docker.(*Environment).pollResources
        /home/runner/work/wings/wings/environment/docker/stats.go:19
github.com/pterodactyl/wings/environment/docker.(*Environment).Attach.func1.2
        /home/runner/work/wings/wings/environment/docker/container.go:81
runtime.goexit
        /opt/hostedtoolcache/go/1.16.6/x64/src/runtime/asm_amd64.s:1371
```

### Steps to Reproduce

I think you need to start / stop / kill the server very quickly for the problem to occur

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
Wings : https://ptero.co/yuqigawahe.cs
Panel : https://ptero.co/uwuhapigiv.sql
```

**Comment by parkervcp** [comment] 2021-08-06 21:46
If you look carefully at the "bright red lines" they tell you another power action is already being processed.

**Comment by bagou4502** [comment] 2021-08-06 21:51
Yes but why after that i need to restart wings ???? 
My problem is not that. my problem is an auto refresh problem.
at 1:19 of the video you can see i need to refresh manualy for refresh the console and the graphs
if i have many "bright red lines" its because i want to remake this bug but with a normal utilisations i have same problem

**Comment by bagou4502** [comment] 2021-08-06 21:56
https://imgur.com/53d2e6f7-1631-4cf9-a871-6ce88d08638d
Here its on an custom panel but you get that on all panel

**Comment by bagou4502** [comment] 2021-08-08 10:23
i think you need to add a command / button to reload the server (As if wings were starting and loading the server)

**Comment by BasToTheMax** [comment] 2021-09-27 09:52
Sometimes I have the same issue

**Comment by skw359** [comment] 2021-10-07 01:44
I was able to find a (what I think is a reliable) method to reproduce the issue. Basically, make console output data extremely raidly (more than it can keep up in web browser) and then after some brief period of time, it freezes, effectively forcing you to restart wings
(This is probably dumb, but it was the only way I could find reproducing the error consistently than anything else)
~Hopefully that gives some insight, was able to reproduce like 3 times

Feel free to ask about the rapid console output, if it's not specific enough lol

**Comment by JacobHowell** [comment] 2021-10-13 16:25
I am experiencing the same issue with Panel V1.6.2 and Wings V1.5.1. The information graphics like memory, CPU, server status colors, and the console freeze. I did recently have multiple windows of the panel open, so it may be related to that. As @bagou4502 said, restarting Wings seems to fix it.

**Comment by Jckf** [comment] 2021-11-25 14:00
We're experiencing this as well, with Pterodactyl v1.6.6 and Wings v1.3.1. The node is running only 2 other servers, and none of them are outputting anything to the console at a high rate. The issue can affect one or more servers, not necessarily _all_ servers on the same node.

EDIT: It appears to be sporadic. Reloading the panel doesn't fix it, but it starts responding again after a while - without having to restart anything.

EDIT 2: Still happens after upgrading to Wings v1.5.3.

**Comment by angwdev** [comment] 2022-03-11 04:21
I'm having the same issue since updating to docker 20.10.13 but restarting wings doesn't work.

**Comment by angwdev** [comment] 2022-03-11 12:55
System reboot, problem persist.
journalctl -u docker.service:
`level=error msg="collecting stats for (container ID): proto: wrong wireType = 0 for field Hugetlb"`

**Comment by DaneEveritt** [comment] 2022-03-28 18:46
Closing, too difficult to reproduce and I don't have time to spend looking into it deeply.

**Closed as completed by DaneEveritt** 2022-03-28 18:46 UTC
