### ISSUE TITLE
Fresh Ubuntu 22.04 install & pterodactyl install MySQL Issues

### ISSUE THREAD

**Issue by Hellmanx** [pterodactyl/panel#5044] opened 2024-03-25 23:42 UTC
### Current Behavior

I am trying to connect artisan to the MySQL database and keep getting:

` [ERROR] Unable to connect to the MySQL server using the provided credentials. The error returned was "SQLSTATE[HY000]
         [2054] Server sent charset (0) unknown to the client. Please, report to the developers".

 [ERROR] Your connection credentials have NOT been saved. You will need to provide valid connection information before
         proceeding.
`

### Expected Behavior

I expect it to sign into mysql database name, username, password, port, and host name are correct.

### Steps to Reproduce

Follow the "Getting Started" page: https://pterodactyl.io/panel/1.0/getting_started.html#dependencies

### Panel Version

1.11

### Wings Version

1.11

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment] 2024-03-26 00:29
This is not a bug with Pterodactyl. 
Please use the discord for support.

**Comment by Boy132** [comment] 2024-03-26 07:32
Duplicate of #5010
(and yes, you should use the [Discord](https://discord.gg/pterodactyl))

**Closed as completed** 2024-03-26 17:31 UTC
