### ISSUE TITLE
Backups not working

### ISSUE THREAD

**Issue by JanDevDE** [pterodactyl/panel#2296] opened 2020-08-31 17:07 UTC
**Background (please complete the following information):**
* Panel or Daemon: rc2 both
* Version of Panel/Daemon: Daemon
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Chrome

**Describe the bug**
Backups are not working for me.

```
Error: `DEBUG: [Aug 31 17:05:45.391] POST /api/servers/44d877cf-26a3-41e0-b3ca-8121281ba3a5/backup client_ip=192.168.208.1 latency=96.811µs status=202
DEBUG: [Aug 31 17:05:45.393] making request to external HTTP endpoint endpoint=https://panel.jandev.de/api/remote/backups/534df176-b708-4d9d-a793-6d695e4c5635 headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[Bearer bAl2Cwf2(redacted)] Content-Type:[application/json]] method=POST
 
WARN: [Aug 31 17:05:45.598] string: The checksum type must be a string. (HTTP/) backup=534df176-b708-4d9d-a793-6d695e4c5635 server=44d877cf-26a3-41e0-b3ca-8121281ba3a5
 
WARN: [Aug 31 17:05:45.598] failed to notify panel of failed backup state backup=534df176-b708-4d9d-a793-6d695e4c5635 error=read /var/lib/pterodactyl/volumes/44d877cf-26a3-41e0-b3ca-8121281ba3a5: is a directory server=44d877cf-26a3-41e0-b3ca-8121281ba3a5
        /go/wings/server/backup.go:94
        /go/wings/router/router_server_backup.go:41

ERROR: [Aug 31 17:05:45.598] failed to generate backup for server error=read /var/lib/pterodactyl/volumes/44d877cf-26a3-41e0-b3ca-8121281ba3a5: is a directory server=44d877cf-26a3-41e0-b3ca-8121281ba3a5
        /go/wings/server/backup.go:105
        /go/wings/router/router_server_backup.go:41
`
```

**To Reproduce**
1. Go to the panel
2. Create a backup
3. The backup will silently fail and because of the issue mentioned in https://github.com/pterodactyl/panel/issues/2280#issuecomment-683907440 also not be deletable.

**Expected behavior**
Backup should work.

**Comment by matthewpi** [comment] 2020-08-31 17:11
Duplicate of #2271

**Closed by matthewpi** 2020-08-31 17:11 UTC

**Comment by JanDevDE** [comment] 2020-08-31 17:13
ah, didn't search for closed issues @matthewpi ^^
