### ISSUE TITLE
Backups Do Not Delete After Termination

### ISSUE THREAD

**Issue by Bradler26** [pterodactyl/panel#2744] opened 2020-11-25 08:47 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.1.1 
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win 10, Chrome

**Describe the bug**
Not too sure if this is the intended design or a bug but when a server is terminated all the actual server files get removed like they should but it seems the zipped backup files remain in the backup folder. This would result in a server's backup space getting filled up pretty quickly if it keeps everyone's indefinitely even if they no longer use your service.

**To Reproduce**
1. Create a server
2. Take a backup of the server
3. Terminate the server
4. cd to backup folder and check if the backup is still there.

**Expected behavior**
Possibly a delay time that can be set? Maybe after 7 days of not having a server, the files are deleted or the files just get instantly deleted anyway as it's not like the user can access them through the panel.

Sorry if this isn't a bug, I tried asking on the discord but didn't get much of a response so I just assumed it was a bug. Hopefully, I don't waste time.

**Comment by parkervcp** [comment] 2020-11-25 12:41
Duplicate of #2564 
Closing out as this was already reported.

**Closed as completed by parkervcp** 2020-11-25 12:41 UTC
