### ISSUE TITLE
More API options and permissions.

### ISSUE THREAD

**Issue by Zekhap** [pterodactyl/panel#4930] opened 2023-11-25 14:32 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I propose the addition of enhanced access control features within the server panel's API, specifically the ability to customize permissions for API keys. Currently, using a client key limits access to only the servers accessible to the client, which is beneficial. However, I would like to extend this functionality to application keys as well, allowing them to retrieve the same information as client keys. Additionally, I suggest the inclusion of a feature that enables the administrator to selectively grant permissions to each API key, ensuring more granular control over data access. This would enhance security and tailor the API key's capabilities to specific needs.

### Describe the solution you'd like.

I envision a solution where both client keys and application keys can be configured to access servers based on the client's permissions. If a client key is used, the API should return information only for the servers accessible to that client. However, for application keys, I propose extending this capability to mimic the access level of a client key, ensuring consistency in the data retrieved. Furthermore, I would like the ability to fine-tune permissions for each API key, allowing administrators to specify the exact operations and data sets accessible to each key. This could be implemented through a user-friendly interface in the server panel, simplifying the process of configuring API key permissions.

### Additional context to this request.

I used ChatGPT to write this. Since im not that good to formulate sentences.

**Comment by Boy132** [comment] 2023-11-25 14:59
> However, I would like to extend this functionality to application keys as well, allowing them to retrieve the same information as client keys.

You can use the client api key of an admin for both the application and the client api. Also application api keys will be removed somewhere in the future.

> I suggest the inclusion of a feature that enables the administrator to selectively grant permissions to each API key

Duplicate of #4091

**Comment by Zekhap** [comment] 2023-11-25 16:42
Oh i didn't see that duplicate, i searched for api but didn't find anything similar.
Yes i could do that but, what if i don't want the key to be able to delete servers?
Also just wanted a single api key instead of using client key and api key just to get info about the servers.

**Comment by Boy132** [comment] 2023-11-25 16:48
> Yes i could do that but, what if i don't want the key to be able to delete servers?

That's what #4091 is about.

> Also just wanted a single api key instead of using client key and api key just to get info about the servers.

Yeah, that would be the case with the client api key of an admin user.

**Closed as completed** 2023-11-25 17:02 UTC

**Comment by Zekhap** [comment] 2023-11-25 18:48
Actually i still need to use the application key cause i can't list servers that i don't own.
Im admin also.

**Comment by Boy132** [comment] 2023-11-25 19:21
> Actually i still need to use the application key cause i can't list servers that i don't own. Im admin also.

You can, set the `type` parameter to `admin-all`:
![image](https://github.com/pterodactyl/panel/assets/8203120/09be6fb0-c3fd-471d-800f-652b46b33088)

**Comment by Zekhap** [comment] 2023-11-25 19:55
Wait how?
im using the "/api/client/" and i get only two servers that i own, and the rest 15 servers i don't get in my list.
But i can do "/api/client/servers/IDHERE" and get the info about the servers i don't own.
