### ISSUE TITLE
Suggestion: Server Category

### ISSUE THREAD

**Issue by Askarionn** [pterodactyl/panel#3614] opened 2021-09-13 06:13 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Adding categories for server.
Example:
I own a minecraft server, and in Minecraft we have different type of games.
We have a lot of servers in pterodactyl, and it will be usefull if we can create categories.
For example: in my case, i can create a category for lobby servers, a category for Bungeecord servers, etc

### Describe the solution you'd like.

Not sure how to explain. It can be same like a normal server in pterodactyl, but when i click on the category it will show you the servers from that category and you can hide/show the servers from that specific category.

**Comment by matthewpi** [comment] 2021-09-13 06:14
Duplicate of https://github.com/pterodactyl/panel/issues/1439

**Closed as completed by matthewpi** 2021-09-13 06:14 UTC
