### ISSUE TITLE
Schedules - Last Run: Never

### ISSUE THREAD

**Issue by EshanMistry73** [pterodactyl/panel#2609] opened 2020-10-26 12:00 UTC
**Background (please complete the following information):**
* Version of Panel/Daemon: 1.0.1 Daemon , 1.0.3 Panel
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10, Google Chrome

**Describe the bug**
Was talking to the Discord support group, and seems quiet a few of us were having the same issue - so we was told to make a bug report for it!

For background, the panel and daemon is latest of writing this report, and everything works fluid minus the schedules. You can create/edit/delete them fine, however, they never run - despite what timings you put into this. Was told to restart pteroq.service, which worked fine on the panel server, however still no luck sadly! Mail etc is also being sent fine, and ill include some screenshots below if they are of any use! Any help is appreciated 👍 

![image](https://user-images.githubusercontent.com/14224587/97169909-c5674980-1782-11eb-86fc-8d88c653a18c.png)

![image](https://user-images.githubusercontent.com/14224587/97169972-db750a00-1782-11eb-8221-5593cc23e308.png)

**Comment by MasterLuke117** [comment] 2020-10-26 12:25
I'm having the same issue, no schedules are running for me,

1.0.1 Daemon , 1.0.3 Panel
ubuntu 20.04

cron and pteroq.service are running just fine,  the panel logs shows this error every minute: https://bin.ptdl.co/uxu12/

```[2020-10-24 06:34:01] production.ERROR: Pterodactyl\Exceptions\Model\DataValidationException: Data integrity exception encountered while performing database write operation. {"name":["The name field is required."]} in /var/www/pterodactyl/app/Models/Model.php:60```

**Comment by MasterLuke117** [comment] 2020-10-26 12:31
@EshanMistry73 
please go to your panel server and run: 
```tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99```

post the error log link here.

perhaps you are getting the same error i am.

**Comment by EshanMistry73** [comment] 2020-10-26 12:36
> @EshanMistry73
> please go to your panel server and run:
> `tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99`
> 
> post the error log link here.
> 
> perhaps you are getting the same error i am.

Hey, i have been getting the same error since the upgrade although i mentioned it in the Discord and it seemed fine/wasn't affecting anything so didn't really bother with it, but you may be right in the sense maybe it is related - https://bin.ptdl.co/wqj49/

**Comment by DaneEveritt** [comment] 2020-10-26 13:56
Have you guys restarted pteroq since upgrading?

**Comment by EshanMistry73** [comment] 2020-10-26 13:59
> Have you guys restarted pteroq since upgrading?

Yes Sir! `systemctl restart pteroq`

**Comment by Sikatsu** [comment] 2020-10-26 14:15
Seems related to #2601

**Comment by DaneEveritt** [comment] 2020-10-26 15:20
I need logs (with timestamps that line up with what you're seeing) from the Panel, including the stack traces. Please do not manually truncate the logs, and please avoid excessive redaction in them, it makes it incredibly difficult to debug because things often get redacted that are a.) not sensitive info and b.) important to understanding the context of the issue.

There are _many_ different things that can lead to schedules not processing, so I'll need to see log output from `pteroq` showing that the task is being "run", a picture of your specific task not running, and logs from the Panel if any errors end up reported. Please also include any records from the `failed_jobs` table if you have any job failure output in the pteroq output.

Please also check that the server the task should execute on is running, and that wings is not reporting any errors. You can also check to see if wings even gets an API call to perform whatever action against that server.

**Comment by EshanMistry73** [comment] 2020-10-26 15:56
> I need logs (with timestamps that line up with what you're seeing) from the Panel, including the stack traces. Please do not manually truncate the logs, and please avoid excessive redaction in them, it makes it incredibly difficult to debug because things often get redacted that are a.) not sensitive info and b.) important to understanding the context of the issue.
> 
> There are _many_ different things that can lead to schedules not processing, so I'll need to see log output from `pteroq` showing that the task is being "run", a picture of your specific task not running, and logs from the Panel if any errors end up reported. Please also include any records from the `failed_jobs` table if you have any job failure output in the pteroq output.
> 
> Please also check that the server the task should execute on is running, and that wings is not reporting any errors. You can also check to see if wings even gets an API call to perform whatever action against that server.

Hey sorry, minus that one log from earlier, what other logs do you require, or if you have a list of cmds to check i can report back!

**Comment by Artuto** [comment] 2020-10-26 16:22
Having this issue as well. We have schedules that run every day at 00:00 (to restart servers and make backups), and schedules only seem to run on servers that are on Node 1 but not on Node 2

Panel logs: http://bin.ptdl.co/drbh7
Pteroq logs:

```
Oct 25 20:19:32 localhost systemd[1]: Started Pterodactyl Queue Worker.
Oct 25 23:50:05 libertyland-1 php[859]: [2020-10-25 23:50:05][cy8goKdCz8PygZOxUnpG0voqtr6zCRr6] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 25 23:50:05 libertyland-1 php[859]: [2020-10-25 23:50:05][cy8goKdCz8PygZOxUnpG0voqtr6zCRr6] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 25 23:55:05 libertyland-1 php[859]: [2020-10-25 23:55:05][CFvtR8RovTj7uVBnjmq1Qy1R2EmstugD] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 25 23:55:05 libertyland-1 php[859]: [2020-10-25 23:55:05][CFvtR8RovTj7uVBnjmq1Qy1R2EmstugD] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 25 23:55:05 libertyland-1 php[859]: [2020-10-25 23:55:05][E5KhDxBdwMvZpJNTrqe8Vte4nKvv4rKD] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 25 23:55:05 libertyland-1 php[859]: [2020-10-25 23:55:05][E5KhDxBdwMvZpJNTrqe8Vte4nKvv4rKD] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 25 23:59:02 libertyland-1 php[859]: [2020-10-25 23:59:02][2k0q2SXw0dH6dXdjcpuF0MEj6m8fATSS] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 25 23:59:02 libertyland-1 php[859]: [2020-10-25 23:59:02][2k0q2SXw0dH6dXdjcpuF0MEj6m8fATSS] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 26 00:00:02 libertyland-1 php[859]: [2020-10-26 00:00:02][WyDSwzq4ZsPj4Q9fdW7J8W2kSgsw76fZ] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 26 00:00:02 libertyland-1 php[859]: [2020-10-26 00:00:02][WyDSwzq4ZsPj4Q9fdW7J8W2kSgsw76fZ] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 26 00:00:05 libertyland-1 php[859]: [2020-10-26 00:00:05][CMMJfzXCDL5JOHPwsenVzIM6W0Dwfl2c] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 26 00:00:05 libertyland-1 php[859]: [2020-10-26 00:00:05][CMMJfzXCDL5JOHPwsenVzIM6W0Dwfl2c] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 26 00:00:05 libertyland-1 php[859]: [2020-10-26 00:00:05][dMpiY2gbk0elC5j6Aq0STOJm4wG9otFb] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Oct 26 00:00:05 libertyland-1 php[859]: [2020-10-26 00:00:05][dMpiY2gbk0elC5j6Aq0STOJm4wG9otFb] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
```

Here's a task that is stuck. Last run should be today (Oct 26th) but it is yesterday (we forced it to run):
![image](https://user-images.githubusercontent.com/9273973/97198076-086df080-1774-11eb-8cd4-a70d02dc34d2.png)

And this is a task on a server on Node 1 that ran perfectly:
![image](https://user-images.githubusercontent.com/9273973/97198258-39e6bc00-1774-11eb-90d2-a3f1add6d951.png)

The `failed_jobs` table is empty
```
MariaDB [panel]> SELECT * FROM failed_jobs;
Empty set (0.000 sec)
```

The servers on Node 2 are indeed running when the schedule is supposed to run. There are no errors in Node 2 logs.

**Comment by DaneEveritt** [comment] 2020-10-26 16:57
@Artuto do you have any Panel logs from `2020-10-25 23:50:05` to `2020-10-26 00:00:05`

**Comment by Artuto** [comment] 2020-10-26 17:14
Panel logs starting of 2020-10-25 and 2020-10-26 are full of errors like the following:

`[2020-10-25 23:50:02] production.ERROR: Pterodactyl\Exceptions\Model\DataValidationException: Data integrity exception encountered while performing database write operation. {"name":["The name field is required."]} in /var/www/pterodactyl/app/Models/Model.php:60`

I can upload the full logs but they are the same over and over and over (at least from what I can see).

**Comment by DaneEveritt** [comment] 2020-10-26 18:00
Okay, just pasting one from the logs here for my own ease of following along, this helps a bunch, thanks:

```
[2020-10-26 09:45:02] production.ERROR: Pterodactyl\Exceptions\Model\DataValidationException: Data integrity exception encountered while performing database write operation. {"name":["The name field is required."]} in /var/www/pterodactyl/app/Models/Model.php:60
Stack trace:
#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(381): Pterodactyl\Models\Model::Pterodactyl\Models\{closure}(Object(Pterodactyl\Models\Schedule))
#1 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(226): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('eloquent.saving...', Array)
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(199): Illuminate\Events\Dispatcher->dispatch('eloquent.saving...', Array, true)
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(189): Illuminate\Events\Dispatcher->until('eloquent.saving...', Object(Pterodactyl\Models\Schedule))
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(712): Illuminate\Database\Eloquent\Model->fireModelEvent('saving')
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(757): Illuminate\Database\Eloquent\Model->save(Array)
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(28): Illuminate\Database\Eloquent\Model->Illuminate\Database\Eloquent\{closure}(Object(Illuminate\Database\MySqlConnection))
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(758): Illuminate\Database\Connection->transaction(Object(Closure))
#8 /var/www/pterodactyl/app/Services/Schedules/ProcessScheduleService.php(58): Illuminate\Database\Eloquent\Model->saveOrFail()
#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(28): Pterodactyl\Services\Schedules\ProcessScheduleService->Pterodactyl\Services\Schedules\{closure}(Object(Illuminate\Database\MySqlConnection))
#10 /var/www/pterodactyl/app/Services/Schedules/ProcessScheduleService.php(61): Illuminate\Database\Connection->transaction(Object(Closure))
#11 /var/www/pterodactyl/app/Console/Commands/Schedule/ProcessRunnableCommand.php(45): Pterodactyl\Services\Schedules\ProcessScheduleService->handle(Object(Pterodactyl\Models\Schedule))
#12 [internal function]: Pterodactyl\Console\Commands\Schedule\ProcessRunnableCommand->handle(Object(Pterodactyl\Services\Schedules\ProcessScheduleService))
#13 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#14 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#17 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#18 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#19 /var/www/pterodactyl/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#20 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#21 /var/www/pterodactyl/vendor/symfony/console/Application.php(911): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/pterodactyl/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Pterodactyl\Console\Commands\Schedule\ProcessRunnableCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/pterodactyl/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/pterodactyl/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 {main}  
```

**Comment by DaneEveritt** [comment] 2020-10-27 02:45
It looks like we allow schedules without a name in the Panel, which is a weird thing that I don't really remember doing, but here we are. Certainly explains the validation issues.

**Comment by DaneEveritt** [comment] 2020-10-27 03:00
Just realized what is happening here. Based on the screenshots from Discord, you have that one invalid schedule with a null name which is fixed in the commit above. However, that null name was causing the entire `ProcessRunnableCommand` to be aborted because of the exception, so any schedules after that invalid one were ignored.

**Closed as completed** 2020-10-27 03:16 UTC

**Comment by GiovaniFerraroTrivelli** [comment] 2020-11-13 06:14
Sorry for reopening but I am having the same issue.

Panel is running version 1.1.1. All nodes are running version 1.1.1 too. failed_jobs table and laravel logs are empty.

The problem is exactly as @EshanMistry73 posted.

**Comment by DrDirtyDevil** [comment] 2021-11-17 12:12
i have the same issue as described above, what do I have to do effectively to fix the null name thing ? 

I have 2 servers with a backup task running every 6 hours but it doesn't do anything 
![Schermafbeelding 2021-11-17 om 13 12 11 PM](https://user-images.githubusercontent.com/60276285/142198397-431c610d-5d5f-4156-be2c-fe2b8a0faaea.png)

the run from 1:05 pm I did manually

**Comment by PilaScat** [comment] 2023-12-30 15:46
![image](https://github.com/pterodactyl/panel/assets/12989749/7f4199f9-59f9-4c86-b4cf-4d688e92f38e)
same problem, always had this problem, no schedule ever worked
latest ptero panel and node, running in docker on unraid

**Comment by PilaScat** [comment] 2023-12-31 12:25
![image](https://github.com/pterodactyl/panel/assets/12989749/fce3c57d-872d-4dd9-891d-15a156ba6c50)
same

**Comment by PilaScat** [comment] 2024-11-05 23:11
I still have the same problem, any fixes?

**Comment by Rangerr97** [comment] 2025-08-15 18:46
I seem to having this issue now myself, is there a fix for it yet?
My schedules are stuck processing and never work, and the only thing I've found to stop that is to delete the schedule.
I can hit Run Now and that will work, but the auto run only gets stuck.
