### ISSUE TITLE
Admin Area Overall Statistics

### ISSUE THREAD

**Issue by metallicgloss** [pterodactyl/panel#700] opened 2017-10-20 21:28 UTC
_This feature requested was originally suggested on Discord, and upvoted by multiple people including myself. The original idea was suggested by HexDev#5923_

**The feature request**
Create a more detailed admin dashboard with overall node and server information showing CPU, RAM, storage and connectivity statistics - allowing for easy viewing of info to help with node and server management. Currently, storage and memory statistics can be viewed for each node and CPU and memory details are available for each individual server - but an overall information page for resources across all nodes would be beneficial.

A possible addition to this feature would be able to view the in-use statistics in addition to the assigned resources which are currently available for each node. If this is not a possibility just an overview would help massively.

![284b242c5](https://user-images.githubusercontent.com/11693849/31842435-0530942e-b5e6-11e7-8916-5b2f9dccf526.png)

**Comment by DaneEveritt** [comment] 2018-03-10 20:07
Duplicate of #156

**Closed by DaneEveritt** 2018-03-10 20:07 UTC
Labels: Feature Request, P: Low
