### ISSUE TITLE
Changing port allocation doesn't actually change it

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#470] opened 2017-06-03 15:49 UTC
Changing a port allocation for a server does not actually change the port that the server is listening on.

For example, it WILL change the exposed port in Docker, but it will not change the port in which the server listens on. I recently spun up a vanilla Minecraft server using port 25577. I then changed the allocation by removing 25577 and adding 25580. After restarting the server and running a `docker ps`, this is what I see:

`23.111.140.210:25580->25580/tcp, 23.111.140.210:25580->25580/udp `

That appears to be correct. However, after starting the server, here is the port that the server is trying to utilize:

`[15:48:01] [Query Listener #1/INFO]: Query running on 0.0.0.0:25577`

**Comment by schrej** [comment] 2017-06-04 08:45
Closing as it seems like it was intended to close with that commit but somehow didn't

**Closed by schrej** 2017-06-04 08:45 UTC

**Comment by DaneEveritt** [comment] 2017-06-04 14:22
It didn't close because that commit is in a different unmerged branch

**Comment by schrej** [comment] 2017-06-04 15:57
Ah all right, didn't know GitHub takes that into account.

**Comment by DaneEveritt** [comment] 2017-06-19 01:49
Somehow both of those commits are actually ment to reference a different issue, #467.
