### ISSUE TITLE
Current Node Usage

### ISSUE THREAD

**Issue by DrLudicrous** [pterodactyl/panel#3840] opened 2022-01-02 16:44 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Be able to monitor current resource usage of a specific node via panel as an administrator. 

This allowing you to diagnose resource problems and just to see. For example; if you see the CPU usage is maxed when it shouldn't be you can see why servers on that node are lagging.

It would also be good to see if the storage is reaching its actual limit and not just allocated limit. 

I am sure there are other reasons as to why we would want this. I personally would like it to see what the capability of a server in regards to its CPU and RAM

Just because we all like to see a graph of current usage

### Describe the solution you'd like.

Having both "At A Glance" section and having a "Current Resource Usage" section or its own tab

**Comment by trenutoo** [comment] 2022-01-03 02:15
Duplicate of #3708

**Closed as completed** 2022-01-03 02:19 UTC
