### ISSUE TITLE
Quick Eggs switcher for users

### ISSUE THREAD

**Issue by warstrolo** [pterodactyl/panel#3775] opened 2021-11-30 10:18 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Basicly to describe the feature, that i think would be really cool to add
Atm : Users that want to change the minecraft server type (vanilla, forge etc  ...) must ask an admin to change the version
What would be nice : A way for users to change the server type (eggs) without have to ask admin.

### Describe the solution you'd like.

 The admin configure "pack" so that users that have for exemple forge, can actually change the server type to vanilla or paper, cause it's in the same pack

**Comment by Boy132** [comment] 2021-11-30 10:21
Duplicate of #1257

**Comment by Software-Noob** [comment] 2021-11-30 10:23
Duplicate of #1257

**Comment by warstrolo** [comment] 2021-11-30 10:46
Yup but with more explication and feature explanation

**Comment by DaneEveritt** [comment] 2021-11-30 17:39
You can just add your additional details to that one. :)

**Closed as completed by DaneEveritt** 2021-11-30 17:39 UTC
