### ISSUE TITLE
DNS resolution failure in Docker container

### ISSUE THREAD

**Issue by DBLouis** [pterodactyl/panel#2632] opened 2020-10-31 19:12 UTC
**Background:**
* Panel or Daemon: Both
* Version of Panel/Daemon: 1.0.3/1.0.1
* Server's OS: Debian 10
* Your Computer's OS & Browser: Linux/Firefox

**Describe the bug**
Installation of Minecraft server always fails because of DNS issue in Docker container.

```
container@pterodactyl~ Server marked as offline...
container@pterodactyl~ Starting installation process, this could take a few minutes...
Err:1 http://deb.debian.org/debian buster InRelease                  
  Temporary failure resolving 'deb.debian.org'
Err:2 http://security.debian.org/debian-security buster/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:3 http://deb.debian.org/debian buster-updates InRelease          
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done    
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package curl
E: Unable to locate package jq
/mnt/install/install.sh: line 12: curl: command not found
/mnt/install/install.sh: line 12: jq: command not found
/mnt/install/install.sh: line 13: curl: command not found
/mnt/install/install.sh: line 13: jq: command not found
/mnt/install/install.sh: line 13: jq: command not found
Using the latest paper version
/mnt/install/install.sh: line 22: curl: command not found
/mnt/install/install.sh: line 22: jq: command not found
/mnt/install/install.sh: line 23: curl: command not found
/mnt/install/install.sh: line 23: jq: command not found
Build is valid. Using version latest
Version being downloaded
MC Version: 
Build: latest
running curl -o server.jar https://papermc.io/api/v1/paper//latest/download
/mnt/install/install.sh: line 46: curl: command not found
container@pterodactyl~ Installation process completed.
```

Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
PHP 7.3.19-1~deb10u1

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-12-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.35GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by DaneEveritt** [comment] 2020-10-31 19:13
This is not a bug with Pterodactyl: `Temporary failure resolving 'deb.debian.org'`

We cannot control these types of issues.

**Closed as completed by DaneEveritt** 2020-10-31 19:13 UTC

**Comment by siliconninja** [comment] 2020-12-25 16:52
I had the same problem, but this solution depends on if your network blocks external DNS servers like `1.1.1.1` that Pterodactyl ships with by default.

Normal docker containers worked for me because they used the system's DNS servers. (I tested with `curl -X GET google.com` inside the container and `curl -X GET 1.1.1.1` to see that DNS resolution failed.) It turns out that the problem is that my network blocked the default DNS servers Pterodactyl uses to override the Docker containers with. I had to instead use the ones that were detected by the system.

This would not be the best solution if the DNS IP addresses change (say, the network uses DHCP to get the DNS IPs), but nonetheless it does work. (Maybe no DNS server addresses in the config means that it'll pull from default DNS servers in the system by not overriding the containers' DNS settings, since Docker does this by default? I'd need to look into the code to find what it does in that case.)

This works on my Ubuntu 20.04 LTS server running five Paper Minecraft (1.16.3) Docker containers and 1 Bungeecord Docker container.

To do this:
1. Stop all containers within Pterodactyl or through the Docker CLI
2. Run `systemctl stop wings` (as root/sudo)
3. Copy 2 detected IP addresses from `/etc/resolv.conf` (exact location of `resolv.conf` depends on distro)
4. Paste them in `/etc/pterodactyl/config.yml` under the `dns` section:
````yaml
docker:
  network:
    interface: 172.18.0.1
    dns:
    - <detected_ip_1>
    - <detected_ip_2>
````
5. Run `systemctl start wings` (as root/sudo)
6. Test with `curl -X GET google.com` inside a Docker container. It should look something like:
````html
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
````

**Comment by Doncellup** [comment] 2022-06-15 16:45
> I had the same problem, but this solution depends on if your network blocks external DNS servers like `1.1.1.1` that Pterodactyl ships with by default.
> 
> Normal docker containers worked for me because they used the system's DNS servers. (I tested with `curl -X GET google.com` inside the container and `curl -X GET 1.1.1.1` to see that DNS resolution failed.) It turns out that the problem is that my network blocked the default DNS servers Pterodactyl uses to override the Docker containers with. I had to instead use the ones that were detected by the system.
> 
> This would not be the best solution if the DNS IP addresses change (say, the network uses DHCP to get the DNS IPs), but nonetheless it does work. (Maybe no DNS server addresses in the config means that it'll pull from default DNS servers in the system by not overriding the containers' DNS settings, since Docker does this by default? I'd need to look into the code to find what it does in that case.)
> 
> This works on my Ubuntu 20.04 LTS server running five Paper Minecraft (1.16.3) Docker containers and 1 Bungeecord Docker container.
> 
> To do this:
> 
> 1. Stop all containers within Pterodactyl or through the Docker CLI
> 2. Run `systemctl stop wings` (as root/sudo)
> 3. Copy 2 detected IP addresses from `/etc/resolv.conf` (exact location of `resolv.conf` depends on distro)
> 4. Paste them in `/etc/pterodactyl/config.yml` under the `dns` section:
> 
> ```yaml
> docker:
>   network:
>     interface: 172.18.0.1
>     dns:
>     - <detected_ip_1>
>     - <detected_ip_2>
> ```
> 
> 5. Run `systemctl start wings` (as root/sudo)
> 6. Test with `curl -X GET google.com` inside a Docker container. It should look something like:
> 
> ```
> <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
> <TITLE>301 Moved</TITLE></HEAD><BODY>
> <H1>301 Moved</H1>
> The document has moved
> <A HREF="http://www.google.com/">here</A>.
> </BODY></HTML>
> ```

Thanks a lot !
