### ISSUE TITLE
Allow us to sort servers

### ISSUE THREAD

**Issue by JoelDeadMach** [pterodactyl/panel#1697] opened 2019-09-08 13:14 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my servers arent sorted, it just makes it unclear.

**Describe the solution you'd like**
It would be nice if you can move servers up or down, so you can sort the servers. Example All hubs on the top, and all others below. since i have like 5 hubs running, etc.

**Comment by parkervcp** [comment] 2019-09-08 13:22
Duplicate of #1439

**Closed by parkervcp** 2019-09-08 13:22 UTC
