### ISSUE TITLE
Functionality on Reinstall Server

### ISSUE THREAD

**Issue by hardixnph** [pterodactyl/panel#3325] opened 2021-05-04 08:26 UTC
**Is your feature request related to a problem? Please describe.**
I don't want to manually remove files from serverfiles.

**Describe the solution you'd like**
If you can add a thing on the **Reinstall Server** function to automatically removes all files from serverfiles.

**Describe alternatives you've considered**
Add functionality to remove all files from serverfiles when **Reinstall Server** is pressed.

**Additional context**
Thank you and sorry for bad explications.

**Comment by LogischJo** [comment] 2021-05-04 08:47
The reinstall button rerun the server install script. Maybe a window for choosing the deletion of the files aswell but to be honest I guess that you can delete all your files in the file manager aswell very fast..

**Comment by hardixnph** [comment] 2021-05-04 09:26
I want to avoid deleting files manually...

**Comment by LogischJo** [comment] 2021-05-04 09:28
Well, the question is why… It’s very fast in the file manager aswell so this feature is useless in my opinion.

**Comment by playaz44** [comment] 2021-05-04 15:30
I would be in favour of adding the option to select the option to delete all files from the server when reinstalling.

**Comment by Kaesewuerfel** [comment] 2021-05-04 19:47
sooooo useless

**Comment by trenutoo** [comment] 2021-05-05 11:16
Duplicate of #2422

**Closed as completed** 2021-05-05 12:18 UTC
