### ISSUE TITLE
Button to download backups to the server

### ISSUE THREAD

**Issue by DrewSin-4** [pterodactyl/panel#2631] opened 2020-10-31 17:54 UTC
**Is your feature request related to a problem? Please describe.**

It’d be nicer to have a button in the backups section of the panel to download the backup to the server rather than having to download it to your PC. It’d be handy for those that may not have high download speeds.

**Describe the solution you'd like**
I pretty much described it above. But the button could be “Upload to Server” or similar.  

**Describe alternatives you've considered**
A script which hooks into the backup system (we use AWS S3) to download it to the server.

**Comment by DaneEveritt** [comment] 2020-10-31 18:19
Dupe of #2016 & #2196

**Closed as completed by DaneEveritt** 2020-10-31 18:19 UTC
