### ISSUE TITLE
Server Container Detaching and Failing to Stop

### ISSUE THREAD

**Issue by AutoJukebox** [Pterodactyl/Panel#956] opened 2018-02-18 17:11 UTC
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.4.6
* Server's OS: CentOS 7
* Your Computer's OS & Browser: Windows 10 & Chrome

Hello, After upgrading to 0.4.6 I have noticed that several servers seem to be detaching and are not able to be started or stopped without killing it via docker. 

It happens on all of my nodes running 0.4.6 and seems to only happen to select few servers.

Related Content from Wings.log:

https://hastebin.com/vifajezona.json

https://hastebin.com/owosopokow.json

Docker Info: https://hastebin.com/iqewufagip.go

uname -a output: ` uname -a
Linux redacted 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by vipesz** [comment] 2018-02-18 17:46
this issue can be resolved by stopping all of the containers and rebooting the servers

this has to do with centos and docker, not necessarily pterodactyl

**Comment by metallicgloss** [comment] 2018-02-18 20:40
I have had the same issue occur to 2 servers, whereby they still run but are detached from the panel that shows it in an off state. The only way to be able to start the server again is to manually kill the container.

I'm running Ubuntu 16.04, rather than CentOS. Would that command solve the problem on Ubuntu?

**Comment by DaneEveritt** [comment] 2018-02-18 21:49
Unless this can be reproduced on 0.5.0 I'm going to close this since 0.4.6, while supported, is not receiving updates and this issue is very hard to track down as is.

**Closed by DaneEveritt** 2018-02-18 21:49 UTC
