### ISSUE TITLE
Multiple selection with tickbox at the bottom of the page is impossible

### ISSUE THREAD

**Issue by Rushaway** [pterodactyl/panel#4883] opened 2023-10-03 10:26 UTC
### Current Behavior

If you select multiples files and try select the file with tickbox at the bottom of the page, you can't.

### Expected Behavior

Be allow to select a file correctly without having to switch page zoom.

### Steps to Reproduce

- Having more than 50 files on the page.
- Select on from the top or anywhere (not the last files at the bottom)
- Then try to select the last one with the tickbox.

![image](https://github.com/pterodactyl/panel/assets/11679883/94641365-139e-4805-886f-a0fd37f81b42)

### Panel Version

1.11.3

### Wings Version

latest

### Games and/or Eggs Affected

all

### Error Logs

```bash
N/A
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment] 2023-10-03 10:38
Duplicate of #4883

**Comment by Boy132** [comment] 2023-10-03 12:49
Duplicate of #4553
(will be fixed in the next release)

**Closed as completed** 2023-10-03 13:22 UTC
