### ISSUE TITLE
Install Server fails

### ISSUE THREAD

**Issue by fabm3n** [pterodactyl/panel#2241] opened 2020-08-15 17:44 UTC
**Background (please complete the following information):**
* Panel or Daemon: daemon
* Version of Panel/Daemon: latest dev build
* Server's OS: ubuntu 20.04

**Describe the bug**
When I try to install a Server it fails and the following stacktrace appears in the wings log:
Aug 15 19:41:04  wings[20020]: ERROR: [Aug 15 19:41:04.934] failed to run install process for server error=pattern contains path separator server=15b53568-cca8-4ad3-a04b-5198cba8c889
Aug 15 19:41:04  wings[20020]: Stacktrace:
Aug 15 19:41:04  wings[20020]: github.com/pterodactyl/wings/server.(*InstallationProcess).BeforeExecute
Aug 15 19:41:04  wings[20020]:         server/install.go:342
Aug 15 19:41:04  wings[20020]: github.com/pterodactyl/wings/server.(*InstallationProcess).Run
Aug 15 19:41:04  wings[20020]:         server/install.go:217
Aug 15 19:41:04  wings[20020]: github.com/pterodactyl/wings/server.(*Server).internalInstall
Aug 15 19:41:04  wings[20020]:         server/install.go:102
Aug 15 19:41:04  wings[20020]: github.com/pterodactyl/wings/server.(*Server).Install
Aug 15 19:41:04  wings[20020]:         server/install.go:43
Aug 15 19:41:04  wings[20020]: github.com/pterodactyl/wings/router.postCreateServer.func1
Aug 15 19:41:04  wings[20020]:         router/router_system.go:62

**To Reproduce**
1. Install a Server (Tried Minecraft, TS3 and ARK)
2. Check wings log

**Expected behavior**
Server installs without errors

**Comment by DaneEveritt** [comment] 2020-08-20 02:22
Cannot reproduce, please try again on the latest releases and see what happens. Also, when running dev builds please also include the specific git hash you're building off, it helps a lot.

**Comment by fabm3n** [comment] 2020-08-20 04:48
It was version a24a5466e551a5ac25c61fe46cfe312d6a8653c2
I will try it again later with the latest version.

**Comment by fabm3n** [comment] 2020-08-20 07:18
Issue still exists on wings 43d8bd6 and panel f144ba8

updated wings error:
`Aug 20 09:11:56  wings[29576]: ERROR: [Aug 20 09:11:56.640] failed to run install process for server error=pattern contains path separator server=82f63e15-ad8a-4b43-a8>
Aug 20 09:11:56  wings[29576]: Stacktrace:
Aug 20 09:11:56  wings[29576]: github.com/pterodactyl/wings/server.(*InstallationProcess).BeforeExecute
Aug 20 09:11:56  wings[29576]:         server/install.go:341
Aug 20 09:11:56  wings[29576]: github.com/pterodactyl/wings/server.(*InstallationProcess).Run
Aug 20 09:11:56  wings[29576]:         server/install.go:216
Aug 20 09:11:56  wings[29576]: github.com/pterodactyl/wings/server.(*Server).internalInstall
Aug 20 09:11:56  wings[29576]:         server/install.go:101
Aug 20 09:11:56  wings[29576]: github.com/pterodactyl/wings/server.(*Server).Install
Aug 20 09:11:56  wings[29576]:         server/install.go:44
Aug 20 09:11:56  wings[29576]: github.com/pterodactyl/wings/router.postCreateServer.func1
Aug 20 09:11:56  wings[29576]:         router/router_system.go:62
`

Tested on Minecraft Vanilla, Minecraft Paper, Garrys Mod

**Comment by DaneEveritt** [comment] 2020-08-20 15:15
Is your panel not updated or something? I was completely unable to reproduce with any of the Minecraft eggs.

**Comment by DaneEveritt** [comment] 2020-08-23 21:30
closed by https://github.com/pterodactyl/wings/commit/37fbae0fcde322a8f1937a9a5adb49d373925d3f

**Closed by DaneEveritt** 2020-08-23 21:30 UTC
