### ISSUE TITLE
PHP 8.1 causing a lot of problems.

### ISSUE THREAD

**Issue by JustKilian** [pterodactyl/panel#3923] opened 2022-01-28 23:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

I have automatic updates. Then suddenly i couldnt access the servers inside the wings anymore. I thought updating wings and the panel might work. But first i couldnt even update the Panel cause he wouldnt use php 8.1 so i told him to use php8.0. Worked. Then after updating Wings. The wings do not connect to the Panel anymore. Error 521 i think.

### Expected Behavior

Panel can acces wings servers and reverse. 

### Steps to Reproduce

Update to the newest panel and wings. Update Ubuntu to the newest updates. Including PHP8.1

### Panel Version

1.7.0

### Wings Version

1.5.6

### Error Logs

```bash
https://pteropaste.com/81pzr2 Panel
https://ptero.co/apyfogysah Wing 1
https://ptero.co/yqaxaxobet Wing 2
```

**Comment by trenutoo** [comment] 2022-01-28 23:58
PHP 8.1 would only cause artisan/queue worker not to function properly and can be fixed with composer update for the dependencies.

It has no effect on your connection between panel and wings. Your wings are not running or reachable, since Cloudflare is returning 521 timeout error. Based on your Wings logs, you did not whitelist your Wings on Cloudflare. 

Please use the Discord server for configuration issues, as this is not a bug in the software.

**Closed as completed** 2022-01-29 00:17 UTC
