### ISSUE TITLE
Storage limit for backups

### ISSUE THREAD

**Issue by arthurbarret0** [pterodactyl/panel#5007] opened 2024-02-12 21:37 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Possibility to set a storage limit specifically for backups, meaning there is an overall storage limit, and within that, there would be a dedicated limit for backup storage.

### Describe the solution you'd like.

By setting a storage limit for backups, let's say I set it to 50GB for backup storage:

1. **Server A:** Utilizing 10GB of storage, it can store 5 backups (towards the total of 50GB for backup storage).

2. **Server B:** Utilizing 40GB of storage, it can store only 1 backup. Attempting to manually create a new backup will result in an error. If the attempt is made through a scheduled task, it will delete the existing backup and create a new one.

This limitation facilitates easier management of backup storage on remote servers and predictability of costs.

**Comment by Boy132** [comment] 2024-02-12 21:44
Duplicate of #3996

**Closed as completed** 2024-02-12 21:45 UTC
