### ISSUE TITLE
Add Options for Standard Users/Admins

### ISSUE THREAD

**Issue by Exonical** [Pterodactyl/Panel#871] opened 2018-01-13 19:00 UTC
Possibility of having the Panel owner set admins permission to modify servers on selected nodes. Ability to toggle on and off global permissions of users to allow them to rebuild/reinstall servers that they own with a possibility of a limit per day/hour etc. in-case it's abused by a standard user

**Comment by DaneEveritt** [comment] 2018-01-13 19:02
duplicate of #279

**Closed by DaneEveritt** 2018-01-13 19:02 UTC
