### ISSUE TITLE
Servers failing to reinstall after a failed first install

### ISSUE THREAD

**Issue by Dann0010** [pterodactyl/panel#1154] opened 2018-05-16 08:29 UTC
* Panel or Daemon: 07.4.1
* Version of Panel/Daemon: 0.5.3
* Server's OS: Centos 7
* Your Computer's OS & Browser: Windows 10 & Opera

------------------------

Docker version: 18.02.0-ce

After a failed first install, When attempting to toggle the install (It has been pending for over a week) and reinstall the server brings this error up;

May 16 04:15:03 na23 node[12891]:
```
{  
   "name":"wings",
   "hostname":"na23",
   "pid":12891,
   "level":60,
   "path":"/v1/server/reinstall",
   "method":"POST",
   "msg":"TypeError: Cannot read property 'reinstall' of undefined\n    at Auth.allowed (/srv/dc/controllers/routes.js:266:26)\n    at AuthorizationMiddleware.allowed (/srv/daemon/src/middleware/authorizable.js:60:24)\n    at RouteController.reinstallServer (/srv/daemon/src/controllers/routes.js:263:14)\n    at Server.Restost (/srv/daemon/src/http/routes.js:143:12)\n    at next (/srv/daemon/node_modules/restify/lib/server.js:912:30)\n    at f (/srv/daemon/node_modules/once/once.js:25:25)\n    at Auth.init (/srv/daemon/src/http/routes.js:56:16)\n  horizationMiddleware.init (/srv/daemon/src/middleware/authorizable.js:44:16)\n    at Server.RestServer.use (/srv/daemon/src/http/routes.js:54:10)\n    at next (/srv/daemon/node_modules/restify/lib/server.js:912:30)",
   "time":"   2018-
```
The server then continues to error whilst showing as installed.

**Comment by DaneEveritt** [comment] 2018-05-16 16:00
That is intended behavior, but probably poorly shown in the UI. An installation failure cannot be fixed with a reinstall. I'll leave this issue here but it'll be focused on either improving the UI in those instances or making reinstall fire off a "delete the broken one and try this again from the top" type of request.

**Comment by DaneEveritt** [comment] 2018-05-24 05:05
Not really sure how you even made that happen.

![](https://dha4w82d62smt.cloudfront.net/items/302V3V2v2S2B3C2I3k41/Image%202018-05-23%20at%2022.04.50.png?X-CloudApp-Visitor-Id=96ca79f4c38114a1183dea2252e1ec4f&v=2a912343)

**Closed** 2018-07-01 21:37 UTC
Labels: Feature, P: Medium
