### ISSUE TITLE
The server owner field only accept email in create server.

### ISSUE THREAD

**Issue by Doc94** [pterodactyl/panel#2654] opened 2020-11-03 14:48 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.3
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: W10, Opera GX

**Describe the bug**
Previous to 1.0 when create a server you can use the username in the field of "Server Owner", now this not work, only work with email.

**To Reproduce**
1. Go to 'Admin Panel' -> 'Servers' -> 'Create New'
2. Click on 'Server Owner' in Owner Details
3. Try to put the username of any user

**Expected behavior**
The field "Server Owner" when create server in admin panel can accept more search terms like: name, username or email.

![2020-11-03_11-46-36](https://user-images.githubusercontent.com/3602279/97999661-5d3fe580-1dca-11eb-8e90-787a82e99457.gif)

**Comment by fabm3n** [comment] 2020-11-03 14:49
Dupe of #2366

**Closed as completed** 2020-11-03 15:11 UTC
