### ISSUE TITLE
☀★Backup ways (Feature Request / Suggestion) ★☀

### ISSUE THREAD

**Issue by SquishyBread** [Pterodactyl/Panel#529] opened 2017-07-01 09:44 UTC
Hey there!

I think there should be a place where you could back up files to another data holding server or Dropbox or Google Drive or Box whatever storage and a choice to do it daily weekly or monthly or manually.
For the data server one I guess it could upload it to another server via one of these options:
☀ FTP
☀ FTPS
☀ NFS/CIFS

Hope you take this suggestion into consideration!
★ SquishyBread

**Comment by schrej** [comment] 2017-07-01 09:49
duplicate of #114

**Closed** 2017-07-01 09:49 UTC

**Comment by SquishyBread** [comment] 2017-07-01 09:55
Actually it isn't and I just got to know this community -_-

**Comment by schrej** [comment] 2017-07-01 10:01
It is a duplicate (you are requesting mostly the same features as the ones in the other issue).
Also while duplicates are annoying we won't be mad at you, just try finding existing issues and maybe comment on them before creating new ones ;)

**Comment by DaneEveritt** [comment] 2017-07-01 17:00
Like @schrej said, this is effectively a duplicate of #114, and even if its not the exact same the core principles are the same. Its easiest for us if you just add your suggestions to the existing issue, we try to keep our issue list slim, as 50 issues is a lot for our small team to manage as it is.
