### ISSUE TITLE
API credentials UI bug

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2547] opened 2020-10-17 22:34 UTC
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/c370e08f651a33085fef29bf001b149c4bb913b0 & https://github.com/pterodactyl/wings/commit/3cd17a28565ca55176dc072edfaddb62a3dbb07d
* Version of Panel/Daemon: 1.0.1
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/28255085/96354680-08218580-10e2-11eb-90ca-067a39e6c31d.gif)

**Comment by DaneEveritt** [comment] 2020-10-18 02:45
Again, please use words to describe the bug. I have literally no idea what's happening here.

**Comment by DarthShmev** [comment] 2020-10-19 13:21
Seems to me as a long description for the api key is breaking the design. A possible fix would be to hide the overflow?

**Comment by DarthShmev** [comment] 2020-10-19 13:44
Looks like the `break-words` utility is being used for the key description which seems to causes the apparent UI issue. Perhaps truncate the overflowing text with an ellipsis?

**Comment by DaneEveritt** [comment] 2020-10-19 17:57
Until a worded description is provided to reproduce this I am closing the issue.

**Comment by DarthShmev** [comment] 2020-10-19 18:14
While hovering over the api key, the row shrinks in size. When moving the mouse elsewhere, the row size reverts to accommodate the length of the description.

Mouse not hovering of api key row:
![image](https://user-images.githubusercontent.com/34663790/96494919-086e6d80-1215-11eb-84e8-b6f07bb80630.png)

Mouse hovering over api key row:
![image](https://user-images.githubusercontent.com/34663790/96495011-3358c180-1215-11eb-9d24-d8ca6626c7b3.png)

Hopefully this clarify things, though @zKoz210 should definitely clarify his intentions of this issue.

**Comment by notAreYouScared** [comment] 2020-10-19 18:15
I'm not able to re produce this....

**Comment by DaneEveritt** [comment] 2020-10-19 18:16
Guessing there is a missing border on the unhovered version so hovering adds a 1px border thus...

**Comment by DarthShmev** [comment] 2020-10-19 18:19
I'll take a look.

**Comment by DarthShmev** [comment] 2020-10-19 18:25
> I'm not able to re produce this....

I am able to re produce this and I am currently running the develop branch. What about you?

**Comment by DarthShmev** [comment] 2020-10-19 18:31
Is the intended behaviour to show the whole description like so?
![image](https://user-images.githubusercontent.com/34663790/96496497-52585300-1217-11eb-85a3-6afcf0b95e92.png)

Or would truncation be fine?
![image](https://user-images.githubusercontent.com/34663790/96496706-93506780-1217-11eb-8a52-b8f29feac246.png)

I'm not sure if this would be the ideal solution because the description should be readable. Lmk

**Comment by DarthShmev** [comment] 2020-10-19 18:48
Changing `<p css={tw`text-sm **break-words**`}>{key.description}</p>` to `<p css={tw`text-sm **break-all**`}>{key.description}</p>` fixes the issue for me.

The final result is:
![image](https://user-images.githubusercontent.com/34663790/96498436-0b1f9180-121a-11eb-9163-189da82ec7bf.png)

**Comment by DaneEveritt** [comment] 2020-10-19 22:38
@DarthShmev does that break normal words weirdly though? I don't use it specifically because it doesn't wrap words as expected, and just breaks them in the middle making it very hard to read.

**Comment by notAreYouScared** [comment] 2020-11-02 05:53
I'm still not able to reproduce this...

**Comment by DaneEveritt** [comment] 2020-11-11 04:56
Closing this due to lack of responses or clear steps to reproduce.

**Closed as completed by DaneEveritt** 2020-11-11 04:56 UTC

**Comment by zKoz210** [comment] 2020-11-29 22:07
1) Create several with a long description 
2) Try to move the mouse over the description 
3) You will get the fact that the text is constantly jumping, then the description becomes longer, then shorter (Safari)
