### ISSUE TITLE
Schedule running every minute

### ISSUE THREAD

**Issue by xiaous** [pterodactyl/panel#2139] opened 2020-06-29 15:52 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.17
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 / Chrome

**Describe the bug**
Schedules running every minute. There's nothing in logs and pteroq service is reporting no failures. 

**To Reproduce**
1. Create schedule with expression * * 0,2,4,6,8,10,12,14,16,18,20,22 0 

**Expected behavior**
Schedule will run at xx:00.

**Observed behavior**
Schedule runs every minute.

![schedule](https://user-images.githubusercontent.com/9314129/86027626-f1560680-b9fe-11ea-8db5-e7ebbafc5f4c.PNG)
![execution](https://user-images.githubusercontent.com/9314129/86027629-f1ee9d00-b9fe-11ea-84b0-2d454da3311a.PNG)

**Comment by DaneEveritt** [comment] 2020-06-29 16:25
Sorry, I guess I wasn't fast enough deleting my comment, this can actually remain part of that other issue.

Duplicate of https://github.com/pterodactyl/panel/issues/2139

**Closed by DaneEveritt** 2020-06-29 16:25 UTC
