### ISSUE TITLE
HTML Files drops unexpected error.

### ISSUE THREAD

**Issue by sebastnalmiron** [pterodactyl/panel#2603] opened 2020-10-26 00:37 UTC
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel - 1.0.2 // Wings - 1.0.1 
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 - Brave Browser

This bug basically happens when opening an .html file at the File Manager of the panel. Nothing to explain more. In my case I was trying to open this specifically: https://pastebin.com/kfQfH4sy , dropping the followin error: https://prnt.sc/v6pq3c

Panel log error: https://bin.ptdl.co/4gxth/

**To Reproduce**
1. Go to 'File Manager'
2. Upload a HTML file
4. Open it
5. Unexpected error

**Comment by notAreYouScared** [comment] 2020-10-26 07:22
I'm not able to reproduce this...
![2020-10-26_03-22-00](https://user-images.githubusercontent.com/1757840/97144244-7d243900-173a-11eb-8d93-a5ca09c1afed.gif)

**Comment by sebastnalmiron** [comment] 2020-10-26 14:11
Really strange sincerely. I updated to the latest version of the panel (1.0.3) and occurs the same, I don't have any trouble by opening other files (config.yml, messages, data.json or other files). Just happening with this.

Video (Opening other files works): https://youtu.be/Jo5T_2XGiFA

**Comment by sebastnalmiron** [comment] 2020-10-26 14:16
I did a little test. The problem is not coming when creating an empty HTML file. It is happening with the file I want to upload. Here it goes: https://pastebin.com/1tZ1s6RP (Here's the Github repository in case you want to check https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/assets/plan/web/login.html)

**Comment by DaneEveritt** [comment] 2020-10-26 15:24
Have you confirmed this against Chrome/Firefox/Edge?

**Comment by sebastnalmiron** [comment] 2020-10-26 20:34
![Screenshot_2](https://user-images.githubusercontent.com/34576139/97225450-6a991680-17b1-11eb-89b0-31ef39fe106d.png)
Happens the same at Microsoft Edge

**Comment by sn8to** [comment] 2021-01-07 03:12
Our panel is also experiencing this issue. We've been unable to find any solid reproduction steps or anybody else who had this same issue, but here we are. When we upgraded to version 1.2.0 it finally started to load html files fine for about 2 minutes, then it broke again after and hasn't worked since.

**Comment by DaneEveritt** [comment] 2021-01-07 03:42
Without logs or the ability to reproduce this I cannot fix this, so I'm closing it. Sorry. Feel free to comment when there is something a bit more solid to work with if you find anything though and we can re-open.

**Closed as completed by DaneEveritt** 2021-01-07 03:42 UTC
