### ISSUE TITLE
Popup Console

### ISSUE THREAD

**Issue by Lorenzo0111** [pterodactyl/panel#3322] opened 2021-05-03 15:48 UTC
**Is your feature request related to a problem? Please describe.**
It is inconvenient to have to open the entire console page every time I want to see the logs in real time.

**Describe the solution you'd like**
Can you re-add the old popup console?

**Comment by trenutoo** [comment] 2021-05-03 15:48
Duplicate of #2584

**Closed as completed** 2021-05-03 15:49 UTC
