### ISSUE TITLE
1.0.0 RC3 console sorting wrongly

### ISSUE THREAD

**Issue by TheNickSkater** [pterodactyl/panel#2303] opened 2020-09-01 11:32 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-RC3
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10, Google Chrome

**Describe the bug**
If in console a text is written that is multiple lines (and it is written at once) it will fail to sort itself correctly.
Example: https://prnt.sc/u9k3gq This should be sorted correctly, but it's not. Only if I refresh the console page, it correct again.

**To Reproduce**
1. Go to console
2. Execute something that writes multiple lines of text at once into console
3. See it not sorting correctly

**Expected behavior**
Well, it should sort correctly and not mix up lines.

**Comment by Sir3lit** [comment] 2020-09-01 17:58
I feel the docker output log should be posted as well. Because if docker posted it in that order. There is nothing we can do to fix it.

**Comment by TheNickSkater** [comment] 2020-09-01 20:58
> I feel the docker output log should be posted as well. Because if docker posted it in that order. There is nothing we can do to fix it.

But its displayed correctly after a page refresh, so that cant be the issue.

**Comment by DaneEveritt** [comment] 2020-09-10 03:33
Haven't been able to reproduce, and haven't seen anyone else reporting this issue. We can re-open this if it crops back up.

**Comment by danny6167** [comment] 2020-09-10 03:36
I experienced the same issue. Ill see if I can reproduce it on the current develop branch when I get home tonight.

**Comment by DaneEveritt** [comment] 2020-09-10 03:57
Can you please tell me what egg and such is needed for this? I don't even know what game that is in the screenshot above.

**Comment by Sir3lit** [comment] 2020-09-10 04:13
Thats a source game

**Comment by danny6167** [comment] 2020-09-10 04:16
Don't know what the OP is using. I believe I noticed it on Minecraft but was able to reproduce with just a bash script with a bunch of echo statements after each other.

**Comment by TheNickSkater** [comment] 2020-09-10 06:17
I had Team Fortress 2 as the EGG. I had sourcemod installed and used "sm plugins list" to list all plugins. Glad I'm not the only one.

**Comment by danny6167** [comment] 2020-09-10 08:46
Reproduced on the current develop branch, running in docker using the supplied docker-compose files.
Panel: d86d0fedb4a4df3f14fc4e98583164ecf4408c1a
Daemon: a31e805c5a23214729f4cf3a2f15f905df32d291
The egg used was minecraft, edited to run the bash script below as a startup command (./test.sh)

![image](https://user-images.githubusercontent.com/388231/92703391-b8ce9380-f384-11ea-8437-27043ad80dd6.png)

test.sh
```
#!/bin/bash
echo 1
echo 2
echo 3
echo 4
echo 5
echo 6
echo 7
echo 8
echo 9
echo 10
echo 11
```

**Comment by JanDevDE** [comment] 2020-09-12 13:40
Can confirm this for minecraft too. (Made a plugin with sysouts and they're unordered.)

Problem persists across latest release versions.

**Comment by DaneEveritt** [comment] 2020-09-13 03:26
Closed in https://github.com/pterodactyl/wings/commit/d02e37620d70c2689a354f858a35a02d2a160aca

**Closed by DaneEveritt** 2020-09-13 03:26 UTC
Labels: 1.0 🦈, bug 🐛
