### ISSUE TITLE
Category system for servers

### ISSUE THREAD

**Issue by JoelDeadMach** [pterodactyl/panel#1851] opened 2020-03-15 13:51 UTC
**Is your feature request related to a problem? Please describe.**
My current problem is that i have a lot of servers running at a panel using multiple dedicated servers, it really looks a messy bcs i have like 10 lobby servers and like 3 proxies running etc.

**Describe the solution you'd like**
I would like to have a categorize system to put your servers in a category example category Lobbies and there you can put all your servers.

**Comment by TrixterTheTux** [comment] 2020-03-15 13:54
Duplicate of #1439

**Closed by TrixterTheTux** 2020-03-15 13:54 UTC
