### ISSUE TITLE
Device Checkpoint page requires reload to show up

### ISSUE THREAD

**Issue by dkay0670** [pterodactyl/panel#2166] opened 2020-07-11 20:35 UTC
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon:  `1.0.0-beta.5`
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: macOS 10.15 Firefox (also occurs in Safari)

**Describe the bug**
Device Checkpoint page requires a reload to show.
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` `php7.4.7`

**To Reproduce**
1. Enable Two-Factor Authentication
2. Sign out
3. See the error
4. Reload, and see it appear

**Expected behavior**
The Device Checkpoint page comes up without a reload.

**Comment by DarthShmev** [comment] 2020-07-12 05:32
I can reproduce this issue on the `develop` branch as well. A blank white page is shown until you reload.

**Comment by DaneEveritt** [comment] 2020-07-12 17:46
Duplicate of https://github.com/pterodactyl/panel/issues/2011

**Closed by DaneEveritt** 2020-07-12 17:46 UTC
