### ISSUE TITLE
Crash Logs Saving

### ISSUE THREAD

**Issue by mallusrgreatv2** [pterodactyl/panel#4879] opened 2023-10-01 04:13 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Instead of removing all the logs from last instances (when the user stops a running server) when the user leaves and comes back, if the stopping was due to a crash, it should preserve the logs. Normally I would be sleeping and when I come back, my bot would be crashed with only the context - "Server marked as offline...". Then I'd have to log on to my vps and then check the docker logs of that server's container, which would break the point of the panel (I think).

### Describe the solution you'd like.

Preservation of logs from when it crashed. It could be removed once the user sees it though.

**Comment by Boy132** [comment] 2023-10-01 12:11
Duplicate of #4306 and #4550

**Closed as not planned** 2023-10-02 23:41 UTC
