### ISSUE TITLE
Panel is flashing on installing new servers

### ISSUE THREAD

**Issue by 123hotdog1100** [pterodactyl/panel#2202] opened 2020-08-01 18:16 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0 Beta
* Server's OS: Ubuntu 20.00
* Your Computer's OS & Browser:Windows 10 Pro, mozilla firefox 

**Describe the bug**
The panel display keeps flashing when the server is installing and you're on the console tab for the server that is installing
Video showing issue https://youtu.be/pTPV-ANNliI
Panel: `php -v` (the php version in use). PHP 7.4.8
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
Kernal Linux Server-01 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x8_64 x86_64 x86_64 GNU/Linux
Docker info https://pastebin.com/7FNATzXu

**To Reproduce**
1.Start installing server
2.Go to the server control panel (https://somedomain.com/server/SERVER_ID
3.Be on the console tab and it will start flashing

**Expected behavior**
Expected to not flash and be a stable image

**Comment by parkervcp** [comment] 2020-08-01 18:17
Dupe of #2190

**Closed by parkervcp** 2020-08-01 18:17 UTC
