### ISSUE TITLE
Context deadline except

### ISSUE THREAD

**Issue by Corenb** [pterodactyl/panel#2141] opened 2020-07-01 17:24 UTC
**Background:**
* Panel or Daemon:  Daemon
* Version of Panel/Daemon:  1.0.0-beta.6
* Server's OS: Debian 9
* Your Computer's OS & Browser: Win 10 + Mozilla Firefox

**To Reproduce**
Try to start a server with a personnal script as startup line.

**Expected behavior**
Console panel error:
`container@pterodactyl~ Server marked as starting...
container@pterodactyl~ Server marked as offline...
container@pterodactyl~ Server marked as stopping...
container@pterodactyl~ Error Event [814793bb-c701-431a-bda5-d04fafab742e]: context deadline exceeded`

Daemon error :
`
DEBUG: [Jul  1 19:16:39.901] saw server status change event server=4cfdb27f-b684-42d0-859e-b330c3c350d3 status=starting
 INFO: [Jul  1 19:16:39.901] syncing server configuration with panel server=4cfdb27f-b684-42d0-859e-b330c3c350d3
DEBUG: [Jul  1 19:16:39.901] making request to external HTTP endpoint endpoint=https://panel.breakerland.fr/api/remote/servers/4cfdb27f-b684-42d0-859e-b330c3c350d3 headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[Bearer rpzDA3W9(redacted)] Content-Type:[application/json]] method=GET
DEBUG: [Jul  1 19:16:50.210] saw server status change event server=4cfdb27f-b684-42d0-859e-b330c3c350d3 status=stopping
DEBUG: [Jul  1 19:16:50.210] saw server status change event server=4cfdb27f-b684-42d0-859e-b330c3c350d3 status=offline
ERROR: [Jul  1 19:16:50.210] failed to handle websocket process; an error was encountered processing an event error=context deadline exceeded error_identifier=814793bb-c701-431a-bda5-d04fafab742e event=set state server=4cfdb27f-b684-42d0-859e-b330c3c350d3

INVALID TRACER
`

**Comment by fabm3n** [comment] 2020-07-01 17:25
Update to beta 7 of wings.

**Comment by parkervcp** [comment] 2020-07-01 17:26
Please be sure to update your daemon to beta 7 first.

**Comment by parkervcp** [comment] 2020-07-01 17:29
closing as dupe of #2130

**Closed by parkervcp** 2020-07-01 17:29 UTC
