### ISSUE TITLE
clients cant upload/edit from SFTP

### ISSUE THREAD

**Issue by fabri2000779** [pterodactyl/panel#1462] opened 2019-02-02 00:40 UTC
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 7.11 - 6.9
* Server's OS: Ubuntu 16.04 LTD
* Your Computer's OS & Browser: Windows 10 Pro

**Describe the bug**
This started happening with daemon 6.9, after the update we got reports of clients that cant upload files or edit them via SFTP
Daemon log: https://gist.github.com/fabri2000779/504983a4dde650f23a835b902a6696fc

**Comment by Sir3lit** [comment] 2019-02-02 00:53
The editing i can't reproduce, but i can reproduce attempting to upload files. That in face does fail

```
00:51:13.012Z  WARN wings: An error occurred while attempting to perform an OPEN operation in the SFTP server. (server=ebeb8c0b-                                                                                                             83e8-4498-a610-9e2e9ab47df9, path=/Logs/IntelRST_MSI.log)
    exception: {
      "errno": -21,
      "code": "EISDIR",
      "syscall": "open",
      "path": "/srv/daemon-data/ebeb8c0b-83e8-4498-a610-9e2e9ab47df9"
    }
    --
    identifier: XtDCTa8Ew9lTiru7q1sbKq6HD3Esxl7U6EaGS5rg3lQrZRL48F4dsPEn9aV3e6Bi
00:51:14.156Z  WARN wings: An error occurred while attempting to perform an OPEN operation in the SFTP server. (server=ebeb8c0b-                                                                                                             83e8-4498-a610-9e2e9ab47df9, path=/Logs/IntelME.log)
    exception: {
      "errno": -21,
      "code": "EISDIR",
      "syscall": "open",
      "path": "/srv/daemon-data/ebeb8c0b-83e8-4498-a610-9e2e9ab47df9"
    }
    --
    identifier: YoaH7FmpSKN0Kmy9yxSkdHK3w8IIETDKKq0fJlSvPViTwPj0gjqveO0ve0gJZH2u
```

**Comment by DaneEveritt** [comment] 2019-02-02 04:32
resolved in https://github.com/pterodactyl/daemon/commit/d13e44a657b7f0cbc32f36f6659c879a9ecdf3a4

**Closed by DaneEveritt** 2019-02-02 04:32 UTC
