### ISSUE TITLE
Owner permissions

### ISSUE THREAD

**Issue by ririko5834** [pterodactyl/panel#3237] opened 2021-03-31 06:26 UTC
Can you please add that user (who was created first) will get owner permissions? Only this user should be able to grant admin perms to other users, and other users with admin perms should not be able to delete owner user.

**Comment by danny6167** [comment] 2021-03-31 06:32
Duplicate of https://github.com/pterodactyl/panel/issues/279

**Comment by matthewpi** [comment] 2021-03-31 16:11
This is not something that will be implemented due to there being a better option outlined in #279.

**Closed as completed by matthewpi** 2021-03-31 16:11 UTC
