### ISSUE TITLE
Entering escape character in command input seems to break it

### ISSUE THREAD

**Issue by AngryCarrot789** [pterodactyl/panel#3819] opened 2021-12-17 09:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

If you input the character '' (unicode value of U+001b) and press enter, it won't say a command has been executed. If you then try to execute another command, it just tries to execute an empty command

![image](https://user-images.githubusercontent.com/32274404/146523244-fadec5d3-60df-4f08-934d-dec5745bc59c.png)

### Expected Behavior

It should just process that escape character, maybe

### Steps to Reproduce

Input the character '' (unicode value of U+001b) and press enter

### Panel Version

1.6.6

### Wings Version

1.5.3

**Comment by Jelcoo** [comment] 2021-12-17 11:09
Are you sure this isn't a problem with minecraft itself?

**Comment by AngryCarrot789** [comment] 2021-12-17 11:44
oh it might be...

**Comment by trenutoo** [comment] 2021-12-17 12:11
I can't replicate this on Forge or Vanilla Minecraft, the default eggs shipped with the panel. This would also be a duplicate of #3258

**Closed as completed** 2021-12-19 17:55 UTC
