### ISSUE TITLE
API Node Key

### ISSUE THREAD

**Issue by DAThosting** [pterodactyl/panel#1774] opened 2019-12-11 10:34 UTC
I'm working with your API to create nodes automatically.

Now it would be awesome, if it's possible to get the Node Key from the given configuration for core.json.
If I could get this, then a complete automation to add nodes and linking them with the panel is possible.

**Comment by TrixterTheTux** [comment] 2019-12-11 10:40
Duplicate of https://github.com/pterodactyl/panel/issues/1632

**Closed by TrixterTheTux** 2019-12-11 10:40 UTC

**Comment by ZeProf2Code** [comment] 2019-12-11 12:55
@DAThosting Fixed in #1775

**Comment by MajorCoreUA** [comment] 2019-12-20 13:14
> @DAThosting Fixed in #1775

I'v got an 403 error:
{
    "errors": [
        {
            "code": "AccessDeniedHttpException",
            "status": "403",
            "detail": "An error was encountered while processing this request."
        }
    ]
}
I sent post request to https://domain/api/application/nodes/6/token (where 6 is node id), but i got this error. API key is absolutely correct because other standard request had finish success. Can you help me please? Maybe i did something wrong?

**Comment by ZeProf2Code** [comment] 2019-12-20 15:53
@MajorCoreUA You need to have a application key who have the permission to read & write the nodes

**Comment by MajorCoreUA** [comment] 2019-12-20 15:59
> @MajorCoreUA You need to have a application key who have the permission to read & write the nodes

Okay, it works. But how i can get a new token? This action just update token and i had answer like this: 
{
"errors":[
{
"code":"ConfigurationNotPersistedException",
"status":"400",
"detail":"The daemon configuration <strong>has been updated<\/strong>, however there was an error encountered while attempting to automatically update the configuration file on the Daemon. You will need to manually update the configuration file (core.json) for the daemon to apply these changes."
}
]
}

**Comment by MajorCoreUA** [comment] 2019-12-20 20:32
> @MajorCoreUA You need to have a application key who have the permission to read & write the nodes

Your method really doesn't allow get node token via API, it's just create new token and offer us to update core.json manually. Can you fix it please?(

**Comment by MajorCoreUA** [comment] 2019-12-20 20:33
@ZeProf2Code  

Your method really doesn't allow get node token via API, it's just create new token and offer us to update core.json manually. Can you fix it please?(

**Comment by ZeProf2Code** [comment] 2020-02-14 23:49
@MajorCoreUA It was intended look at the name of my PR.
