### ISSUE TITLE
panel client freezes if someone else has the panel open in another tab (but hasn't looked at it in a while)

### ISSUE THREAD

**Issue by AngryCarrot789** [pterodactyl/panel#3508] opened 2021-07-31 18:49 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.

### Current Behavior

All of the data (console, graps, cpu, etc) stops updating and only updates if you refresh the page, but its still frozen; refreshing just briefly updates the data

### Expected Behavior

it should continue updating like normal

### Steps to Reproduce

- have the panel site open on your end
- have someone else open the panel on their end, but they keep it opened in another tab (so they aren't looking at the site, its just in another tab. they could be watching youtube or something) 
- after an unknown amount of time (10 minutes, an hour, im not exactly sure), the site for me should just simply stop updating at some point

### Panel Version

1.4.0

### Wings Version

1.4.2

### Error Logs

```bash
i dont have access to the "back end", and ive tried to contact my friend who manages it but he hasn't responded yet
```

**Comment by AngryCarrot789** [comment] 2021-07-31 18:53
i forgot to mention, but if the other person then goes back to that tab, it starts responding again (for me and everyone else), and to the person who had the idle tab, all of the data just starts speeding in (graphs update really fast for a few seconds (or longer, depending on how long they left the tab idle))

which makes me think it might have something to do with the data somehow getting buffered in wings maybe, and if too much data is buffered it stops sending it to everyone (im not exactly sure how wings works though)

**Comment by creeperQ7** [comment] 2021-08-02 09:41
I have the exact same issue.

**Comment by tinyoverflow** [comment] 2021-08-26 13:29
While I can confirm that this issue exists, I cannot confirm why exactly this happens. This also happened to me while nobody else could possibly access the panel, because I had the only account.

**Comment by trenutoo** [comment] 2021-08-26 14:20
#3528 is a duplicate with some-what more information.

**Comment by luizsusin** [comment] 2021-08-29 20:15
I can also confirm that this issue happens, but not sure about the reason as well. Sometimes, if the output of the console is too long, it can also freeze. I'm not sure if this is related. Restarting wings fixes the issue for some time.

**Comment by OneHitX** [comment] 2021-09-18 22:15
I confirm the problem exists.

Too large a log on the console, or repeatedly pressing the start, stop, and kill buttons on the console causes this issue.

The problem doesn't happen when the node has few servers <10.

**Comment by luizsusin** [comment] 2021-09-19 10:48
> I confirm the problem exists.
> 
> Too large a log on the console, or repeatedly pressing the start, stop, and kill buttons on the console causes this issue.
> 
> The problem doesn't happen when the node has few servers <10.

My node has just one server and it has been happening for as long as I can remember.
Not looking at the tab for a while really caused the problem most of the times I've had it.

**Comment by DaneEveritt** [comment] 2022-02-19 15:33
I've never reproduced this and there are no clear steps, so I'm closing this.

I understand that might be frustrating, but please understand I truly can't do anything about it if I can't ever reproduce the issue.

**Closed as completed by DaneEveritt** 2022-02-19 15:33 UTC
