### ISSUE TITLE
Fetch Node Resource Usage From API

### ISSUE THREAD

**Issue by Craftzman7** [pterodactyl/panel#3875] opened 2022-01-12 01:21 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add a field to the `/api/application/nodes` endpoint to fetch the amount of disk space and memory allocated to the node.

### Describe the solution you'd like.

Just add a field to the node attributes object

**Comment by trenutoo** [comment] 2022-01-12 08:18
The allocated_resources are already returned in the API request.

`GET https://pterodactyl.panel.test/api/application/nodes/1`

`allocated_resources: { memory: 4000, disk: 0 }`

**Comment by Craftzman7** [comment] 2022-01-12 21:06
I should have been more clear in what I wanted. I was thinking of the amount of allocated resources that are being used. Not the total amount that's allocated.

**Comment by yesBad** [comment] 2022-01-12 21:13
I would never see this happening, as I believe the one asking for these stats in panel was closed.
As all stats are provided by docker or whatever.

**Comment by trenutoo** [comment] 2022-01-12 21:23
> I should have been more clear in what I wanted. I was thinking of the amount of allocated resources that are being used. Not the total amount that's allocated.

Will not happen. Duplicate of #3708

**Closed as completed by trenutoo** 2022-01-12 21:23 UTC
