### ISSUE TITLE
Panel resizes constantly when chrome download bar is open

### ISSUE THREAD

**Issue by GabrielSerealia** [pterodactyl/panel#1629] opened 2019-07-08 16:12 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.14
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chrome

**Describe the bug**
When the download panel is open the page rescales constantly causing a violent vibration effect.
https://i.serealia.ca/files/OJGLkaH_2019-07-08_12-08-33.webm

**To Reproduce**
1. Be on the statistics page
2. Have download bar open

**Expected behavior**
Page scales to new dimensions

**Comment by DaneEveritt** [comment] 2019-07-08 18:54
Duplicate of #1442

**Closed by DaneEveritt** 2019-07-08 18:54 UTC
