### ISSUE TITLE
[Feature Req] Server State Notifications

### ISSUE THREAD

**Issue by ryantechdev** [pterodactyl/panel#2847] opened 2020-12-09 17:24 UTC
This is completely a "almost nobody needs this but it might be nice to have for some people" feature request.

**Is your feature request related to a problem? Please describe.**
I host some unstable servers (due to lack of work from the game's team) and I'd like to receive notifications when a server crashes, with Discord webhooks (or IFTTT, something like that)

**Describe the solution you'd like**
I'd like the option to receive updates when my server(s) turn on, off, start, stop, crash, etc.

**Describe alternatives you've considered**
Minecraft has a plugin called DiscordSRV which notifies you when your server goes online or offline, but that only works for Spigot/Paper servers, not every server I host.

**Additional context**
(concepts)

![image](https://user-images.githubusercontent.com/66895770/101664235-972f8780-3a19-11eb-82c2-b39ab514bca2.png)
![image](https://user-images.githubusercontent.com/66895770/101664126-79622280-3a19-11eb-85d5-ddc7df64d0d1.png)

**Comment by schrej** [comment] 2020-12-09 18:06
duplicate of #89

**Closed as completed by schrej** 2020-12-09 18:06 UTC
