### ISSUE TITLE
Scheduler bug 

### ISSUE THREAD

**Issue by SanjaySRocks** [pterodactyl/panel#3282] opened 2021-04-20 17:01 UTC
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**

* Panel or Wings: Panel
* Version of Panel/Wings: 1.3.2 (latest)
* Panel Logs: http://bin.ptdl.co/h9mdh
* Wings Logs: https://ptero.co/hewifoziru
* Server's OS: Debian 10
* Your Computer's OS & Browser: Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Wings: `uname -a` and `docker info` (your kernel version and information regarding docker)

**To Reproduce**
Steps to reproduce this behavior:

1. Install Any game server you like in my case i used custom egg from parker github hlds
2. After installing game go to schedules and create a schedule & task to restart server in send power action command
3. Server restarts after adding cron instantly and also run on set time , idk why its kinda weird
4. however when i try this with shutdown command it doesnt run instantly but on schedule time.

**Expected behavior**
I expected to work schedule cronjob only to set time not instantly after adding cron. 

My timezone was Asia/Kolkata both in panel and vps time I am confirmed

**Comment by nathanctech** [comment] 2021-04-20 18:35
I repeated your steps and did not encounter your issue. What settings did you set up with the cron schedule, and what did it say for its next run time? Does it actually record itself as having run once?

**Comment by SanjaySRocks** [comment] 2021-04-20 18:48
It's run perfectly on given task time but when I set power action to
restart server or server custom command it run instant ly after adding task

**Comment by SanjaySRocks** [comment] 2021-04-21 06:06
hi if you're on discord add me SanjayS#5187 so I can show you.

**Comment by trenutoo** [comment] 2021-04-21 17:05
Show the schedule that you are trying to use and having issues with, most likely it's not a bug and rather invalid cron time

**Comment by SanjaySRocks** [comment] 2021-04-21 17:11
I am sure I did the correct cron task if u can share discord id I can show
u live

**Comment by trenutoo** [comment] 2021-04-21 17:17
Post your schedule in this bug report as you opened one

**Comment by FoksVHox** [comment] 2021-04-21 20:43
I'm unable to reproduce this. I think it's something on your end as pointed before. Make sure that the queue worker is running.

**Comment by DaneEveritt** [comment] 2021-04-22 15:24
Either provide screenshots showing your schedule setup here so that others can try to match it, or I'm closing this issue based on the number of people who cannot reproduce your issue.

**Comment by SanjaySRocks** [comment] 2021-04-22 15:44
I will attach screenshot wait

**Comment by SanjaySRocks** [comment] 2021-04-23 06:40
![image](https://user-images.githubusercontent.com/30376256/115829323-7dbd3400-a42c-11eb-8211-92fa14fef08c.png)

![image](https://user-images.githubusercontent.com/30376256/115829375-8ca3e680-a42c-11eb-9d2f-b1785085ed26.png)

**Comment by trenutoo** [comment] 2021-04-23 08:21
I  personally can't replicate your issue. I tried different actions and times, including the one in your screenshot. The only way for me to trigger a schedule prematurely was to run it manually

**Comment by DaneEveritt** [comment] 2021-04-24 21:44
Can't reproduce, and many other people cannot so I'm closing this out. Sorry.

**Closed as completed by DaneEveritt** 2021-04-24 21:44 UTC
