### ISSUE TITLE
Changing an egg does not work

### ISSUE THREAD

**Issue by jbdevic** [pterodactyl/panel#3924] opened 2022-01-29 20:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Hello,

We are looking to modify the egg manually on a server (running and whose installation has worked well).
For example, we pass a minecraft server on an Arma 3 server but nothing happens

### Expected Behavior

The server should reinstall with the new egg and change the startup line

### Steps to Reproduce

1. Go to the settings of a server 
2. Change the egg of the server
3. See that nothing happens

### Panel Version

1.7.0

### Wings Version

1.5.6

### Error Logs

```bash
https://ptero.co/xobimazahi

https://bin.ptdl.co/eiz0h/
```

**Comment by redthirten** [comment] 2022-01-31 01:46
This is a grey area in expected behavior because switching eggs for a server does not erase/reset the volume, and some could consider this a good thing or a bad thing. Bad in your case if you want to re-tool the server instead of just replacing it, but also bad for someone who may want to switch to a similar egg or a different version of an egg, but keep the server's data (like saves, etc). Same goes for updating the startup variable for the server (though this I hear is being fixed in the next major release): Some people would want it to update, and others will want their custom startup command for that *one* server to remain (for whatever reason).

I think the switch egg feature is mainly for trying out a different version egg of the same service; not to re-tool the server. Egg install scripts differ from app to app, so the Minecraft install script doesn't know how to delete the existing Arma 3 files (short of nuking the whole volume, which would be bad for an existing Minecraft server that needs a simple reinstall).

**Comment by jbdevic** [comment] 2022-01-31 10:32
Thanks for your clarification, it's true that I myself had a hard time understanding the expected functioning of the system

It is not very clear because on the page of the server, it is specified that it would be reinstalled 
![2022-01-31_11-30-48](https://user-images.githubusercontent.com/20879586/151777950-a5261805-756a-4d70-8d0f-b038c5df2780.png)

In my case, unless I am mistaken, even if I change egg, the server does not shut down and the installation process does not take place

**Comment by redthirten** [comment] 2022-01-31 18:17
> It is not very clear because on the page of the server, it is specified that it would be reinstalled

This I definitely agree with... I think it's something they have in the pipeline, but some of the verbiage in the panel is either vague or inaccurate.

**Closed as not planned** 2024-05-04 22:38 UTC
