### ISSUE TITLE
Feature Request: Update Script

### ISSUE THREAD

**Issue by BassManMike73** [Pterodactyl/Panel#527] opened 2017-06-30 16:59 UTC
In addition to install script an update script for server software updates would be very helpful.

For example, Feed the Beast modpacks are often updated and a simple script could be written to backup important world and data files, remove old server files and replace them with the current version.

**Comment by DaneEveritt** [comment] 2017-09-30 18:00
duplicate of #240

**Closed by DaneEveritt** 2017-09-30 18:00 UTC
