### ISSUE TITLE
Panel: On install status "2" (failed) specific tabs are not shown.

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#794] opened 2017-12-04 15:35 UTC
* Version of Panel:  285485d7
* Server's OS: Ubuntu 16.04 
* Your Computer's OS & Browser: Firefox Developer Edition 

In the Administrator Server List if i open a server that has the install status "2"
the given site will not show all tabs like here:
![](https://image.prntscr.com/image/EU0fyJBlQWiBZoN0rDst_w.png)

Instead it will hide some configuration sites what does not make any sense.
![](https://image.prntscr.com/image/TZDqf4hLRXeYgmFYsUtJXQ.png)

i want to reach the configuration of the server independently of what state the server is in.

because of the following error that is still occuring: https://github.com/Pterodactyl/Panel/issues/788
i have to create a clone but thats not quite easy if i dont have the settings written down or if i dont change the install status manually to "1"
(screenshot of the install entry in the database)
![](https://image.prntscr.com/image/s6ntFEBYSuCBjaeYGeSFQw.png)

**Comment by DaneEveritt** [comment] 2017-12-04 15:50
This is not a bug and is completely intentional. If a server gets marked as status 2 it is because the Daemon does not have any of the server files or data in a state that it can work with.

Your "bug" here is simply because another bug is causing issues.

**Closed by DaneEveritt** 2017-12-04 15:50 UTC

**Comment by ProJaCore** [comment] 2017-12-04 15:53
I did manually changed the install status via mysql and started the server. 
why does it still fail to reinstall?

**Comment by DaneEveritt** [comment] 2017-12-04 15:54
That has nothing to do with this issue, please keep conversations on the relevant issues.

**Comment by ProJaCore** [comment] 2017-12-04 16:00
oh okay i didnt notice the reply on the other recent thread. i did git pull the panel instead of the daemon.
