### ISSUE TITLE
More than 5 seconds load time of any page

### ISSUE THREAD

**Issue by BirkhoffLee** [pterodactyl/panel#1760] opened 2019-12-05 10:16 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.15
* Server's OS: Ubuntu 18.04, panel's running in a debian stretch container
* Your Computer's OS & Browser: macOS, FireFox latest

**Describe the bug**
Any single page takes at least 5 seconds to load, even accessing `/` on localhost using curl. I installed `jkocik/laravel-profiler` to try figure out what's taking up so much time and this is all I got here:

<img width="1310" alt="CleanShot 2019-12-05 at 18 00 19@2x" src="https://user-images.githubusercontent.com/8148095/70226059-1d701880-178b-11ea-9790-eb3f7891c9bc.png">

I have no prior experience of Laravel, and would appreciate if you know what's going on here since there's 0 log indicating any clue of the issue. Thanks a lot.

Panel: 7.2.24 fpm

**Comment by mattmalec** [comment] 2019-12-05 12:18
Does it run pretty slow for you the first time, gets fast for the next couple requests, then slow again?

**Comment by BirkhoffLee** [comment] 2019-12-05 12:31
It’s always same slow, I’m afraid.

**Comment by parkervcp** [comment] 2019-12-05 13:47
I have several different panels in containers. It sounds like an issue on your end.

**Comment by BirkhoffLee** [comment] 2019-12-05 13:48
@parkervcp Yes I guess so - how do I find out the culprit though?

**Comment by parkervcp** [comment] 2019-12-05 13:49
Have you tried running it outside your container?

**Comment by mattmalec** [comment] 2019-12-05 17:18
> It’s always same slow, I’m afraid.
> […](#)
I get something similar running a standard installation.

**Comment by DaneEveritt** [comment] 2019-12-05 17:21
What are the specs on the machine you're running. This looks similar to profiles I would see in a local environment where the files were served over NFS mounts (or just on abysmal disks).

**Comment by mattmalec** [comment] 2019-12-05 17:24
I see it running slow on my EC2 instance and an OVH dedicated server (tested on both hard drives & SSDs)

**Comment by BirkhoffLee** [comment] 2019-12-05 23:27
@DaneEveritt I’m also running it on a dedicated server

**Comment by parkervcp** [comment] 2019-12-06 00:03
Are you both running it in a docker container? This has no been clarified.

**Comment by mattmalec** [comment] 2019-12-06 00:36
No, I’m running a standard installation.

**Comment by DaneEveritt** [comment] 2019-12-06 00:47
Those routes you're looking at in the screenshot hit an external API endpoint in a blocking manner, are you accounting for that?

**Comment by mattmalec** [comment] 2019-12-06 01:06
For me, my daemon & panel are on separate EC2 instances. Is it usually that delayed?

**Comment by BirkhoffLee** [comment] 2019-12-06 10:41
I'm running daemon and panel both in containers, on a same machine.

**Comment by BirkhoffLee** [comment] 2019-12-06 10:42
Is it possible that database causes the delay? I have no evidence, just a wild guess.

**Comment by DaneEveritt** [comment] 2019-12-06 17:15
Well there is just not enough information here to make any solid guesses about the issue, but the endpoints you have in the picture are just the API status calls, so unless you can show a callgraph of a different page I'm not sure how much more help I can offer.

If other pages are also slow, you can try using https://blackfire.io to profile them which will provide a much more useful tree showing where the issue lies.

**Comment by BirkhoffLee** [comment] 2019-12-06 17:17
Any page is slow, including `/` which is `/auth/login`

**Comment by lancepioch** [comment] 2019-12-06 21:19
@BirkhoffLee Are the results the same if you try another decent sized PHP app? My estimated guess is that it has to do with either your disk speed and/or your container/vm/storage.

**Comment by schrej** [comment] 2019-12-07 12:26
Do you have caching enabled and use something that is in-memory, e.g. Redis or Memcached?

**Comment by mattmalec** [comment] 2019-12-07 17:55
I know the panel uses Redis for something when I was configuring it.

**Comment by parkervcp** [comment] 2019-12-07 18:43
One thing to note is that the demon panel and node are on the lowest power VPS' I could find and they don't have any issues. Both the daemon and panel are in docker containers as well.

**Comment by DaneEveritt** [comment] 2019-12-07 18:45
I'm going to close this until enough information can be provided to definitively point to an issue in the codebase. Unfortunately based off what I've seen from this, and my own expierences running this and other PHP software, it appears to be an issue with your machine or environment configuration, and not this software.

**Closed by DaneEveritt** 2019-12-07 18:45 UTC

**Comment by LaserKaspar** [comment] 2026-01-05 02:05
The cause of slow page loading for me was that the CPU was kind of overloaded. I inspected the cause and found out, that fpm hits the CPU very hard on each page load.

I could resolve this issue by enabling opcache in fpm, I forgot to enable mine so it needed to compile php on each requests (even if the same endpoints are hit) which obviously is very slow.
