### ISSUE TITLE
Request: Radio button to "hide variables" if no input is given

### ISSUE THREAD

**Issue by xyeLz** [pterodactyl/panel#1295] opened 2018-08-21 15:17 UTC
I create quite a few eggs and when I do, I add a bunch of variables and then include those in the startup parameters for the user so they are referenced somewhere.

However, all too often this sometimes can result in a startup string with a whole bunch of empty parameters. For example, in Call of Duty, you might have an optional variable called "map". If the user doesn't input a map, it defaults to mp_carentan. However, in the startup, it still shows up looking like this: server_map "".

What I'm proposing is some sort of option or radio button that removes the variable from the startup parameters if no input is selected. Thus, if the owner decides not to input "mp_carentan", it will remove the variable from the startup parameters. Obviously this will require that the variable knows the preliminary action. Ie: the startup parameter looks like: server_map {{MAP}}. The panel only knows what {{MAP}} is, so we will need a way to associate server_map with that particular variable.

Not an urgent request, but would really go a long way in cleaning up the startup parameters for almost ALL of my eggs.

**Comment by parkervcp** [comment] 2018-08-21 15:40
This is a duplicate of #1258

**Closed by parkervcp** 2018-08-21 15:40 UTC
