### ISSUE TITLE
Transfer Failed Code 500

### ISSUE THREAD

**Issue by coco0325** [pterodactyl/panel#4696] opened 2023-02-15 07:30 UTC
### Current Behavior

I tried several times transferring the same server, and it always failed when uploading progress arrived at 2.9 GiB / 23.6 GiB.

Error: 
failed to push archive to target error=unexpected status code from destination: 500

Wed, 15 Feb 2023 14:36:18 CST [Transfer System] [Source Node]: Uploading [                         ] 171.6 MiB / 23.6 GiB
Wed, 15 Feb 2023 14:36:23 CST [Transfer System] [Source Node]: Uploading [                         ] 473.0 MiB / 23.6 GiB
Wed, 15 Feb 2023 14:36:28 CST [Transfer System] [Source Node]: Uploading [                         ] 782.4 MiB / 23.6 GiB
Wed, 15 Feb 2023 14:36:33 CST [Transfer System] [Source Node]: Uploading [=                        ] 1.1 GiB / 23.6 GiB
Wed, 15 Feb 2023 14:36:38 CST [Transfer System] [Source Node]: Uploading [=                        ] 1.4 GiB / 23.6 GiB
Wed, 15 Feb 2023 14:36:43 CST [Transfer System] [Source Node]: Uploading [=                        ] 1.8 GiB / 23.6 GiB
Wed, 15 Feb 2023 14:36:48 CST [Transfer System] [Source Node]: Uploading [==                       ] 2.1 GiB / 23.6 GiB
Wed, 15 Feb 2023 14:36:53 CST [Transfer System] [Source Node]: Uploading [==                       ] 2.4 GiB / 23.6 GiB
Wed, 15 Feb 2023 14:36:58 CST [Transfer System] [Source Node]: Uploading [==                       ] 2.7 GiB / 23.6 GiB
Wed, 15 Feb 2023 14:37:03 CST [Transfer System] [Source Node]: Uploading [===                      ] 2.9 GiB / 23.6 GiB
container@pterodactyl~ Transfer has failed.

### Expected Behavior

Transfer the server data correctly.

### Steps to Reproduce

Transfer a server.

### Panel Version

1.11.3

### Wings Version

1.11.4

### Error Logs

```bash
https://ptero.co/kecewuzoqa
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by jughead0800** [comment] 2023-02-22 15:02
I have exactly the same issue
 ```
ERROR: [Feb 22 02:25:24.126] failed to push archive to target error=unexpected status code from destination: 502 server=5eacb4e6-7ceb-4178-81d0-4aa523307eed subsystem=transfer
ERROR: [Feb 22 02:39:44.032] failed to push archive to target error=unexpected status code from destination: 500 server=5eacb4e6-7ceb-4178-81d0-4aa523307eed subsystem=transfer
```

it seems to time out at about 2 mins for me  i suspect its a config setting in whatever webserver/proxy wings uses to send the files. there was some mention of it, and how to adjust the time to longer, but i have been looking for hours and i cant find the link... 

after a several, it also caps at just under 1GiB of transfer, which is about what i can push in that time. It is 100% repeatable, across several nodes

**Comment by gilvex** [comment] 2023-06-18 19:10
Bump. Same issue

**Comment by SuperKali** [comment] 2023-10-13 07:57
i confirm i have the same problem

ERROR: [Oct 13 09:52:58.701] failed to push archive to target error=unexpected status code from destination: 500 server=6cbace3f-e372-4186-9a51-50fcf07fbbff subsystem=transfer

**Comment by SuperKali** [comment] 2023-10-13 09:09
Apparently the problem is if we use Cloudflare as proxy

**Comment by theFra985** [comment] 2023-11-05 00:07
It can also happen when using an nginx reverse proxy without a high enough `client_max_body_size`.
The server archive gets POSTed to the target daemon via the configured HTTP port so if any of the reverse proxies in front of it filters out the request based on body size the transfer will fail.

**Comment by GameServersHub** [comment] 2023-11-12 05:12
Has anyone located a fix for using cloudflare and resolving this error?

**Comment by xal3xhx** [comment] 2023-11-13 16:54
Confirmed also having the same issue, it seams like some kind of timeout is happening ive tried changing may settings in nginx and cloudflare with no luck yet

**Comment by Boy132** [comment] 2023-11-14 08:17
For everyone with the same problem: please provide wings logs (`sudo wings diagnostics`) of _both nodes_. (source and destination, right after the failed transfer)
Ideally on the [Discord](https://discord.gg/pterodactyl).

Also, make sure that the wings version on both nodes matches and that your wings (and panel) is up-to-date in general.

**Comment by xal3xhx** [comment] 2023-11-14 15:48
here is the logs and info for the failed transfer
server 
name: Alex's GMod - Jazz
UUID: 46c425a0-b56d-4966-87cc-93432917777e

source node
name: Alexs_Localnode2 
UUID: 53d03cd8-6482-4bb6-8fe5-b98c1ba77297

dest node
name: praxis server
UUID: d9389e54-20fc-4c46-b3ca-08a9f63ddcd5

Both nodes are behind a cloudflare Zero Trust access tunnel with agents running on both sites
the setting are the same for both host names
HTTP Host Header: Null
Disable Chunked Encoding: True
Connect Timeout: 60
No Happy  Eyeballs: False
Proxy Type: None
Idle Connection Expiration Time: 190
Keep Alive Connections: 100
TCP Keep Alive Interval: 30
Protect with Access: False

console output during transfer:
`container@pterodactyl~ Server marked as offline...
Tue, 14 Nov 2023 15:24:30 UTC [Transfer System] [Source Node]: Uploading [                         ] 24.0 MiB / 18.2 GiB
Tue, 14 Nov 2023 15:24:35 UTC [Transfer System] [Source Node]: Uploading [                         ] 53.0 MiB / 18.2 GiB
<truncated>
Tue, 14 Nov 2023 15:27:55 UTC [Transfer System] [Source Node]: Uploading [==                       ] 1.5 GiB / 18.2 GiB
Tue, 14 Nov 2023 15:28:00 UTC [Transfer System] [Source Node]: Uploading [==                       ] 1.5 GiB / 18.2 GiB
container@pterodactyl~ Transfer has failed.
container@pterodactyl~ Server marked as offline...`

each time i have done a transfer no matter the server it always seams to fail around 1.6GB

Logs from source wings: https://ptero.co/eputoqezuk
i think The sftp errors can be ignored (i am unsure what is causing them at the moment)

Logs from dest wings: https://ptero.co/mydotoheqi

this was coss-posted in discord as requested: https://discord.com/channels/122900397965705216/1174012892325089321

**Closed as completed** 2024-05-04 22:42 UTC

**Comment by S0ly** [comment] 2025-10-18 18:51
same issue

**Comment by GenOpenDiesel** [comment] 2025-10-18 19:10
Upgrade wings and panel to new version

**Comment by S0ly** [comment] 2025-10-18 19:12
I'm already on latest versions : 
**Wings 1.11.13 - Transfer Bug Report**

**Issue:** Server transfers failing with HTTP 500 on destination node

**Root Cause:** Wings crashes with nil pointer dereference when receiving transfer archive
```
runtime error: invalid memory address or nil pointer dereference
github.com/pterodactyl/wings/router/router_transfer.go:70
```

**Affected Versions:** Wings 1.11.13

**Symptoms:**
- Source node shows: `failed to push archive to target error=unexpected status code from destination: 500`
- Destination Wings crashes during incoming transfer POST request
- Transfer fails partway through upload
