### ISSUE TITLE
Re-organisation of servers in the panel.

### ISSUE THREAD

**Issue by 1ogiq** [pterodactyl/panel#4732] opened 2023-03-23 18:25 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I'd like to see a QoL change, which allows for the re-organisation of servers in the panel. 

Right now, our panel is cluttered and messy and the only way to fix it at this point in time looks to be to delete and recreate them in the order we'd like it to be in.

Thanks!

### Describe the solution you'd like.

Just an option to drag a server around the panel to place it somewhere it is more easily accessible or in a more organised order.

**Comment by TrixterTheTux** [comment] 2023-03-23 19:11
Duplicate of #1439

**Closed as completed by TrixterTheTux** 2023-03-23 19:11 UTC
