### ISSUE TITLE
Console formatting / reload bug.

### ISSUE THREAD

**Issue by Zendrex** [Pterodactyl/Panel#330] opened 2017-03-04 00:15 UTC
Panel and daemon version: canary

Found a couple issues on the latest dev branch for the panel.

1. Any user viewing the console page for a server will get a forced refresh of the console if anyone from anywhere else viewing the console decides to refresh/load the page.

2. On page refresh, the formatting of the console is killed and shows the formatting code in the console instead of colors.

ex: https://gyazo.com/c783071fcfce650750cdb79436d4ccd3

@schrej has a test account to my panel if needed for testing, ask him for the info

**Comment by Zendrex** [comment] 2017-03-04 00:17
I'm coming to the conclusion that this is NOT a cloudflare issue but something regarding the panel.

**Comment by DaneEveritt** [comment] 2017-03-04 02:56
Issue 2 isn't really anything I can control since we are reading from the log at that point, only way around would be tracking console output into memory which isn't ideal, but might be possible.

The first issue... thats interesting, no idea why that would even happen but I'll take a peak.

**Comment by DaneEveritt** [comment] 2017-03-04 04:21
Confirmed bug caused by [this code](https://github.com/Pterodactyl/Panel/blob/develop/public/themes/pterodactyl/js/frontend/console.js#L166) which is causing the new log to be pushed to all users connected to the socket, rather than the user who requested it. This did not occur in previous versions as the call was previously an AJAX request.

Should be an easy fix, but won't happen until admin re-theme is done since it'll take some daemon modification as well.

**Comment by DaneEveritt** [comment] 2017-04-01 01:49
This was fixed in https://github.com/Pterodactyl/Panel/commit/0c6e6f39feff1748efb928ffb380177b78df66d4

**Closed by DaneEveritt** 2017-04-01 01:49 UTC
Labels: + daemon, bug, pre-release
