### ISSUE TITLE
Player Counter

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3650] opened 2021-09-25 19:03 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Show a Player Counter under the Start / Stop buttons.
Like: https://www.mc-market.org/resources/18699/

### Describe the solution you'd like.

Reprogram this software

**Comment by trenutoo** [comment] 2021-09-25 19:14
Duplicate of #1218

**Closed as completed by trenutoo** 2021-09-25 19:14 UTC
