### ISSUE TITLE
Automatically delete oldest backup

### ISSUE THREAD

**Issue by DrakMC** [pterodactyl/panel#2578] opened 2020-10-23 09:18 UTC
**Describe the solution you'd like**
I would like the feature to automatically delete the oldest backup of the server. This would be good, as the oldest backup in the schedules would be deleted every day and then the server would be backed up. This would free up disk space as well as the backup limit that is set for the server.

**Comment by parkervcp** [comment] 2020-10-23 10:50
Dupe of #2536

**Closed as completed** 2020-10-23 10:50 UTC
