### ISSUE TITLE
Limit download/upload

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#4743] opened 2023-04-03 14:11 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Option to limit container download/upload

### Describe the solution you'd like.

Option to limit the download/upload of the container Where it will be possible to control it in "Build Configuration", to prevent malicious users from exhausting your network

### Additional context to this request.

to prevent malicious users from exhausting your network

**Comment by Boy132** [comment] 2023-04-05 09:14
Duplicate of #3352 (see https://github.com/pterodactyl/panel/issues/3352#issuecomment-840237399)

**Closed as not planned** 2023-05-13 05:31 UTC
