### ISSUE TITLE
Backup schedule task requires payload? must have a string to create task

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2126] opened 2020-06-17 07:40 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Beta 5

**Describe the bug**
when creating a backup task, the payload is required for some reason? in this case, the payload is ignored files. so you have to have an ignored file in order to create it. 

**To Reproduce**
1. Create a backup task

I did try to add `.nullable()` / `.nullable(true)` to the othewise statement but that didn't seen to do anything.
https://github.com/pterodactyl/panel/blob/develop/resources/scripts/components/server/schedules/TaskDetailsModal.tsx#L138

**Comment by DaneEveritt** [comment] 2020-06-17 15:06
Duplicate of #2067

**Closed by DaneEveritt** 2020-06-17 15:06 UTC
