### ISSUE TITLE
Allow Backup tasks in Schedules to be blocking

### ISSUE THREAD

**Issue by zediious** [pterodactyl/panel#4796] opened 2023-06-01 18:42 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like for Schedules to pause their execution/be blocked when they reach a Backup task, until the backup task has been completed. Often, I need to run commands before and after the backup has completed. Since the scheduler immediately goes to the next task (after whatever time offset you set), I cannot accurately predict when the backup will complete and run commands at the right time.

### Describe the solution you'd like.

This could be a default functionality, or something that can be enabled per backup task. Essentially, a checkmark within the Backup task labelled "Make task blocking" or something along those lines would be perfect in my mind.

The solution I'm employing now is simply setting a large offset after the backup. It's possible that the backup could exceed this time though, and that leaves me uneasy.

### Additional context to this request.

I tested this by running the following schedule;
![Screenshot_1742](https://github.com/pterodactyl/panel/assets/12464778/6454226c-1bcc-4c59-a469-31bee29835ce)

The `save-on` command is run exactly 7 seconds after `say [AUTO-BACKUP] Server backup is beginning now. World saving will be off until completion.` is run, so it seems that the backup task is immediately moved on from, even though it's still running.

**Comment by Boy132** [comment] 2023-06-01 19:29
Duplicate of #2872

**Comment by zediious** [comment] 2023-06-01 20:10
> Duplicate of #2872

Whoops! Was not thorough enough in my search evidently.

**Closed as completed** 2023-06-02 17:28 UTC
