### ISSUE TITLE
Add a server migration feature

### ISSUE THREAD

**Issue by galaxy119** [pterodactyl/panel#2256] opened 2020-08-24 10:12 UTC
**Is your feature request related to a problem? Please describe.**
I run a network of Dedis for hosting game servers. Sometimes, people want to change the location of their server. IE: Move their service from US-West to US-East, or even to EU, etc. Currently, to do so, if I wish to preserve the server's files, I need to create a new server on the panel for the new destination node, tarball their current server's files, send them to the dedi for the new destination node, and then replace the default server install files for the new panel server with the ones from the old one, and then I can delete the old server on the panel.

**Describe the solution you'd like**
I would like to be able to migrate servers between nodes via the panel, where it handles all of the tedious things, such as sending the server files, and assigning the server on the new destination to the user etc.

**Describe alternatives you've considered**
The only alternative I've really considered is forcing users who migrate nodes to deal with manually copying config/etc. files over, or, my current solution, bash scripts to help automate the process as much as I can.

**Comment by schrej** [comment] 2020-08-24 10:15
duplicate of #18

**Closed by schrej** 2020-08-24 10:15 UTC
