### ISSUE TITLE
Add module system to panel

### ISSUE THREAD

**Issue by WeeskyBDW** [pterodactyl/panel#2437] opened 2020-10-01 06:03 UTC
**Is your feature request related to a problem? Please describe.**
Actually, they are no reel way to modify the panel  without modify directly the code. It can be a problem for upgrading it. Also, it's not particulary easy to add/modify/delete things easly and safely.

**Describe the solution you'd like**
I suggest a module system like popular CMS (also know has plugin or addon, depends of CMS)

We can imagine a folder with all modules. Every module have a json file with name, description, autor, version and Main controller like this:

```
{
    "name": "My first module",
    "description": "My awesome first module",
    "author": "WeeskyBDW",
    "version": 0.1
    "mainController": "myFirstModuleController.php"
}
```

In main controller, we can use pterodactyl methods to add users buttons, add admins buttons etc..

Thx to read this issue and gl to dev team

**Comment by schrej** [comment] 2020-10-01 08:09
duplicate of #2234

**Closed by schrej** 2020-10-01 08:09 UTC
