### ISSUE TITLE
It is recommended to add a registered user module

### ISSUE THREAD

**Issue by aopkcn** [pterodactyl/panel#4298] opened 2022-08-03 06:58 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Initially installed on the server, using the web registration method to register as an administrator account for the first time, instead of holding a free open source project for secondary development and selling

### Describe the solution you'd like.

A development theme actually sells for £15

### Additional context to this request.

。。。

**Comment by Boy132** [comment] 2022-08-03 07:37
Duplicate of #3408, #3102

**Closed as not planned** 2022-08-03 08:28 UTC
