### ISSUE TITLE
Password Resets / Welcome Email password setting, fails due to 400 Bad Request response

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2064] opened 2020-05-24 05:38 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Beta 4
* Server's OS: Ubuntu 18.04

**Describe the bug**
When a user attempts to request a password reset email they're replied with 
`An error was encountered while processing this request.`
Nothing is logged in the larval logs, upon further investigation when it attempts to process the action it's getting a  `400 Bad Response` reply. Same for requesting a password reset email.

**To Reproduce**
1. Create a new user and attempt to use the "set password" link in the email
OR
1. Try to reset your password.

**Expected behavior**
It to work.

**Comment by Sir3lit** [comment] 2020-05-24 05:38
Might be related to #2060 ??

**Comment by DaneEveritt** [comment] 2020-05-25 22:34
I am unable to reproduce this using the steps provided. I was able to reset my password on multiple accounts, as well as on newly created accounts both using the email sent and the password reset flow.

**Comment by Sir3lit** [comment] 2020-05-25 23:13
Upon enabling debug mode and getting the full stack. 

```
{
    "errors": [
        {
            "code": "HttpException",
            "status": "400",
            "detail": "Failed to validate reCAPTCHA data.",
            "source": {
                "line": 76,
                "file": "/app/Http/Middleware/VerifyReCaptcha.php"
            },
            "meta": {
                "trace": [
                    "#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Pterodactyl\\Http\\Middleware\\VerifyReCaptcha->handle()",
                    "#1 /var/www/pterodactyl/app/Http/Middleware/RedirectIfAuthenticated.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Pterodactyl\\Http\\Middleware\\RedirectIfAuthenticated->handle()",
                    "#3 /var/www/pterodactyl/app/Http/Middleware/RequireTwoFactorAuthentication.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Pterodactyl\\Http\\Middleware\\RequireTwoFactorAuthentication->handle()",
                    "#5 /var/www/pterodactyl/app/Http/Middleware/LanguageMiddleware.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Pterodactyl\\Http\\Middleware\\LanguageMiddleware->handle()",
                    "#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()",
                    "#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#10 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()",
                    "#11 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#12 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()",
                    "#13 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#14 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()",
                    "#15 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()",
                    "#17 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#18 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()",
                    "#19 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#20 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()",
                    "#21 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()",
                    "#22 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()",
                    "#23 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()",
                    "#24 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()",
                    "#25 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()",
                    "#26 /var/www/pterodactyl/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#27 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()",
                    "#28 /var/www/pterodactyl/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#29 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()",
                    "#30 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#31 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
                    "#32 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#33 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
                    "#34 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#35 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()",
                    "#36 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#37 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()",
                    "#38 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#39 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()",
                    "#40 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
                    "#41 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()",
                    "#42 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()",
                    "#43 /var/www/pterodactyl/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()",
                    "#44 {main}"
                ]
            }
        }
    ]
}
```

Currently using the default ReCaptcha shipped with the panel. 

![image](https://user-images.githubusercontent.com/1757840/82847330-87a48300-9ebb-11ea-9ffd-32f3ac2c27f3.png)

**Comment by Games4k** [comment] 2020-05-27 00:09
Yeah, I’m having the same problems too. I am completely unable to reset account password or create new accounts through mails. Having the same issue.

**Comment by Sir3lit** [comment] 2020-05-27 03:33
The work around for now is to disable recapcha in the settings

**Comment by Exonical** [comment] 2020-06-27 16:31
Received the same issue with password reset/welcome email. Using my own generated reCAPTCHA keys. Fixed by disabling reCAPTCHA. Running latest Beta 5.

**Closed** 2020-08-02 04:08 UTC
Labels: beta 🦈, bug 🐛
