### ISSUE TITLE
Ctrl+C/CMD+C to copy from console broken on v1.3.1 

### ISSUE THREAD

**Issue by WaffleThief123** [pterodactyl/panel#3203] opened 2021-03-20 14:07 UTC
**Background (please complete the following information):**
* Panel  
* Version : 1.3.1 
* Server's OS: Debian 10, Ubu18.04m Ubu20.04
* Your Computer's OS & Browser: Brave, Chrome, Safari

**Describe the bug**
Copying using keyboard hotkeys is currently broken on 1.3.1, tested on prior version 1.2.x and works there.  Possible bug regression?

**To Reproduce**
1. Go to console
2. highlight text
3. CTRL/CMD + C
4. fail

**Expected behavior**
Failing to copy occurs.

**Comment by NickEvansDev** [comment] 2021-03-20 14:09
I'm unable to reproduce the issue, cmd+c is working fine (v1.3.1, macos 11.1 with chrome)

**Comment by ssh-sysadmin** [comment] 2021-03-20 14:28
I can reproduce the issue on Brave, Windows 10, panel v1.3.1

**Comment by FoksVHox** [comment] 2021-03-20 14:30
Dupe of #3158

**Closed as completed** 2021-03-20 16:36 UTC
