### ISSUE TITLE
Console randomy failing to load

### ISSUE THREAD

**Issue by cybooo** [pterodactyl/panel#3533] opened 2021-08-09 13:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Console randomly fails to load up and shows an "An error was encountered by the application while rendering this view. Try refreshing the page" error. 

### Expected Behavior

Console loads properly.

### Steps to Reproduce

Click on any server, and this may happen randomly.

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
https://ptero.co/uwojigabog
https://bin.ptdl.co/l11ti/

https://imgur.com/a/RvlORrN (Panel with console view)
```

**Comment by notAreYouScared** [comment] 2021-08-09 15:38
I've ran into this issue a few times randomly on previous versions. Not sure what causes it a refresh fixes it.

**Comment by DaneEveritt** [comment] 2021-08-09 16:29
Same, until we track down a specific error or steps to reproduce though I'm just going to close this out since it is a trivial work-around, albeit annoying issue.

**Closed as completed by DaneEveritt** 2021-08-09 16:29 UTC
