### ISSUE TITLE
Invalid memory address

### ISSUE THREAD

**Issue by Corenb** [pterodactyl/panel#2004] opened 2020-05-08 09:11 UTC
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0 beta release 3
* Server's OS: Debian 9
* Your Computer's OS & Browser: Win 10 + Mozilla Firefox

**Describe the bug**
When update the panel and daemon from 1.0 beta release 1 to release 3, I can't start anymore servers from the panel.
Please provide additional information too, depending on what you have issues with:
Panel: PHP 7.4.5
Kernel info: Linux ns3018348 4.19-ovh-xxxx-std-ipv6-64
Docker info:
```
Client:
 Debug Mode: false

Server:
 Containers: 29
  Running: 3
  Paused: 0
  Stopped: 26
 Images: 11
 Server Version: 19.03.8
 Storage Driver: devicemapper
  Pool Name: docker-8:2-7472688-pool
  Pool Blocksize: 65.54kB
  Base Device Size: 10.74GB
  Backing Filesystem: xfs
  Udev Sync Supported: true
  Data file: /dev/loop0
  Metadata file: /dev/loop1
  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
  Data Space Used: 3.822GB
  Data Space Total: 107.4GB
  Data Space Available: 71.45GB
  Metadata Space Used: 21.29MB
  Metadata Space Total: 2.147GB
  Metadata Space Available: 2.126GB
  Thin Pool Minimum Free Space: 10.74GB
  Deferred Removal Enabled: true
  Deferred Deletion Enabled: true
  Deferred Deleted Device Count: 0
  Library Version: 1.02.137 (2016-11-30)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk s                                                                                                                                                             yslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.0-ovh-xxxx-std-ipv6-64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.34GiB
 Name: ns3018348
 ID: LCWP:2IBP:NBXS:AFFJ:QLZU:ADYY:NCB5:6RGL:73IH:5QG4:MPHC:YDCE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: the devicemapper storage-driver is deprecated, and will be removed in a                                                                                                                                                              future release.
WARNING: devicemapper: usage of loopback devices is strongly discouraged for pro                                                                                                                                                             duction use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage de                                                                                                                                                             vice.
```

**To Reproduce**
1. Just try to start a server after updating

**Expected behavior**
Nothing in the console.
Just this error in the wings console :
```
2020/05/07 22:48:35 [Recovery] 2020/05/07 - 22:48:35 panic recovered:
GET /api/servers/941c2414-93cd-40ae-9a3b-aa81ec2ee9cd/ws HTTP/1.1
Host: panel.breakerland.fr:8080
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Cache-Control: no-cache
Connection: keep-alive, Upgrade
Cookie: XSRF-TOKEN=eyJpdiI6Ijlyc0sycjBvWE9vdEt4NDRXUGlRa2c9PSIsInZhbHVlIjoiOUk1dVRSSjRjcjd5RnR0M1Z5UkhzTEZHd2FBSkl3Y3diT01RNnkyc3BjTTRcLzE1YjQ4Rmt1aFRtb0hJT0NIeisiLCJtYWMiOiI5Y2MzYmZkNDI0MGYwMGJiYzljNTMzNjY3MjZmNThmNDhlN2Q2MTdmOGY4MzgyNWE2MWQxZDlhZTc0MmY1OWRmIn0%3D; pterodactyl_session=eyJpdiI6ImN6dmY0XC8zVjBjdGU3NkQzVlZWNGR3PT0iLCJ2YWx1ZSI6IlM3b3UrTmZiZ1JnaXd2aFRXT0t2VVZRa2QxbGZxaWFjVDNhMm94TVBJVmcwaFJIU0JHMmdLV2RBTGc0KzkrOUEiLCJtYWMiOiJmMTU0ZTc2NWEwMDZkMmJiZmNhMmQ0NmNmYmE4ZTZiMTZmN2VjZDYzMmI2MzJiZGI5YjI3NTdiYzJkNWY0MTg4In0%3D; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IkRJa25zYlNrQTY0YlM3TWNhVVh6MkE9PSIsInZhbHVlIjoiXC92UDMzUVV5MkJpXC9hUlVtXC94TGVBaFBZSXo1a0loRDBqS0dkVWNLY0VOVmRXYkZpam44MTByRm0wVE9TdlU4XC95dlZaQ2kwODN4aGJKVUROYUZ3dlhGdmtmY3pUMlhteGtPZ3czTjlnczdpT0tnSnRHc1hrS1VRRzBuTFBDcHpwTFZ3Sk9jQnE4RklvRjZubWplMzNBbG00dmZCa2c0TjU2RTJNQktrdFdBMD0iLCJtYWMiOiJjMGQ3ZTBkMGJmNDk5M2RlMDMwNzEyOGIyY2Q5MTcwZDNjZTczODdmMGRkMmEwY2M3MjQxMzc5MGVlMzQ4YTljIn0%3D
Origin: https://panel.breakerland.fr
Pragma: no-cache
Sec-Websocket-Extensions: permessage-deflate
Sec-Websocket-Key: Y2zcCVJqLD+oYusEyR7C1g==
Sec-Websocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0


runtime error: invalid memory address or nil pointer dereference
/usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:82 (0x443050)
/usr/local/Cellar/go/1.12.1/libexec/src/runtime/signal_unix.go:390 (0x442e7f)
/Users/dane/Sites/development/code/wings/server/environment_docker.go:206 (0xc864a8)
/Users/dane/Sites/development/code/wings/router/websocket/websocket.go:242 (0xcb46b7)
/Users/dane/Sites/development/code/wings/router/router_server_ws.go:55 (0xcc6b06)
/Users/dane/go/pkg/mod/github.com/gin-gonic/gin@v1.6.2/context.go:156 (0xa5ed59)
/Users/dane/Sites/development/code/wings/router/middleware.go:66 (0xcc173f)
/Users/dane/go/pkg/mod/github.com/gin-gonic/gin@v1.6.2/context.go:156 (0xa5ed59)
/Users/dane/Sites/development/code/wings/router/middleware.go:16 (0xcc11ba)
/Users/dane/go/pkg/mod/github.com/gin-gonic/gin@v1.6.2/context.go:156 (0xa5ed59)
/Users/dane/go/pkg/mod/github.com/gin-gonic/gin@v1.6.2/recovery.go:83 (0xa72d29)
/Users/dane/go/pkg/mod/github.com/gin-gonic/gin@v1.6.2/context.go:156 (0xa5ed59)
/Users/dane/go/pkg/mod/github.com/gin-gonic/gin@v1.6.2/logger.go:241 (0xa71e50)
/Users/dane/go/pkg/mod/github.com/gin-gonic/gin@v1.6.2/context.go:156 (0xa5ed59)
/Users/dane/go/pkg/mod/github.com/gin-gonic/gin@v1.6.2/gin.go:409 (0xa68fdc)
/Users/dane/go/pkg/mod/github.com/gin-gonic/gin@v1.6.2/gin.go:367 (0xa686ae)
/usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:2774 (0x77fdf7)
/usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1878 (0x77b9e0)
/usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337 (0x45cbf0)

[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 500
[GIN] 2020/05/07 - 22:48:35 | 500 |  6.118660978s |  193.248.44.109 | GET      "/api/servers/941c2414-93cd-40ae-9a3b-aa81ec2ee9cd/ws"
```

**Comment by parkervcp** [comment] 2020-05-08 10:18
Duplicate of #2000

**Closed** 2020-05-08 12:42 UTC
