### ISSUE TITLE
Panel startup doesn't seem to accept quotations

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#721] opened 2017-11-04 22:17 UTC
I'm using my Rust service and when I attempt to set a hostname with spaces, it truncates to only the first word. Therefore, `+server.hostname "My Little Pony"` turns into `+server.hostname "My"`. The same thing happens for `+server.description`. This is a particularly big issue because the default map in Rust is "Procedural Map", but I can't set this via the console because it's also two words, and when this gets truncated, the Rust server won't start because "Procedural" isn't a valid map. Using a config file resolves these issues, but isn't ideal for the users as the variables should also work properly. When looking at the console output of the server, the quotations do display properly, which confuses me since it seems as if it's simply ignoring them for some reason.

I tried escaping these commands using `+server.hostname \"{{SERVER_HOSTNAME}}\"` but this resulted in the same behavior. Also, setting the variable to `My%20Little%20Pony` just resulted in a server with that same exact name.

**Comment by lancepioch** [comment] 2017-11-10 03:59
Hostnames can't have spaces in them.

Sources: [RFC952](https://tools.ietf.org/html/rfc952) and [RFC1123](https://tools.ietf.org/html/rfc1123)

**Comment by xyeLz** [comment] 2017-11-10 15:19
I think you're misunderstanding what I am posting about. I'm not referring to an FQDN hostname. I'm referring to the Rust variable of +server.hostname. This also affects +server.description as well as other variables which are actually important. For example, the +server.map variable is set to `Procedural Map`. Because there's a space, it uses only "Procedural", which doesn't allow the server to start. This should be re-opened please.

**Comment by DaneEveritt** [comment] 2017-11-11 19:41
Found another bug relating to this where variables with quotations in them don't render in the ACP when viewing a server startup page due to the way the JS was setting the value. Not sure if thats specific to 0.7 or not.

**Comment by DaneEveritt** [comment] 2017-11-11 19:57
I tested this with @TrixterTheTux and we aren't seeing this behavior on either version of the Daemon. Try putting quotes around the value of the variable, and not in the startup command and see what happens?

**Comment by xyeLz** [comment] 2017-11-22 22:28
Yeah I have tried that as well. I've pretty much tried everything from the standpoint of putting things around quotes and escaping them, etc. to no avail.

The thing is, I don't think this affects games like CS:GO. However, it does affect my Rust server. Would it be possible to have @tenten8401 test this with his Rust container to see if it might be directly related to my container? I tried downloading his image and creating a server but I'm not sure if I have the right version. There doesn't seem to be any logic built in to even download and install steamcmd so I don't know how Rust would even be installed there. However, if he has a working version, I figured it might be worth a test there...

**Comment by xyeLz** [comment] 2017-11-24 17:09
So I was able to test this a bit more with someone who understands programming more than I. I gave him full access to my Rust container files on GitLab so he went through the files to see if ther was anything wrong.

He did find that there was an area of the file that was missing quotations:

`do
  echo "starting server"
  exec ./RustDedicated $OPTS
  echo "\nRestarting server...\n"
  sleep 10
done`

You’ll see the $OPTS was not enclosed in quotations. After doing this, I was able to see a multiple word hostname in my server. However, and this is the kicker, it only works if I escape the variables. If I remove the escapes, it doesn’t work.

Is there somewhere I can l look next to try and figure this out why it seems to require escaping?

**Comment by DaneEveritt** [comment] 2017-11-24 18:06
It would help to see what the actual output from OPTS is, because we cannot reproduce this at all on the containers we provide.

**Comment by xyeLz** [comment] 2017-11-25 23:39
Here's my startrust.sh file, for reference:

```
#!/bin/sh

# use rusts steamclient.so
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/container/rust/RustDedicated_Data/Plugins/x86_64
cd /home/container/rust

OPTS="$*"
echo "$OPTS"

clear
while :
do
  echo "starting server"
  exec ./RustDedicated $OPTS
  echo "\nRestarting server...\n"
  sleep 10
done
```

And here is the output of $OPTS, as per your request:

`+server.port 28970 +rcon.port 28971 +server.secure 1 +server.maxplayers +rcon.password "rconpassword" +server.password "test" +server.hostname "mike pilau rust" +server.level "Procedural Map" +server.seed "133769" +server.worldsize "3000" +ser
ver.identity "mikey1" +rcon.web 1 +cfg "" +server.description "the best server ever!" +server.url "" +server.headerimage ""`

**Comment by xyeLz** [comment] 2017-11-28 20:10
@DaneEveritt I'm just curious, the fix you had eluded to earlier where quotations aren't rendering in the ACP, was this resolved in the latest version? What was the fix? I'd like to apply this to my existing 0.6.3 environment if possible since it's the live environment that I'm having the issue in and would like to see what's going on.

**Comment by DaneEveritt** [comment] 2017-12-05 00:45
I still have been unable to replicate this on any of our default images, and I don't see anything that would cause the issues you are seeing.

**Comment by xyeLz** [comment] 2017-12-07 15:31
The issue I'm having appears to be related to the files I'm using during the process. Something isn't properly rendering the quotations. It doesn't appear to be daemon related.

As long as quotations are properly displaying within the server console when quotations are specified in the startup arguments, then I have no complaints with this case being closed.

**Comment by tenten8401** [comment] 2017-12-07 15:40
It could be how bash is handling variables, just a thought. No guarantees on that however.

**Comment by DaneEveritt** [comment] 2017-12-15 03:10
I'm closing this until it can be properly replicated by more than one user. If you manage to find anything else please do comment here, but unfortunately it is not something that we can really fix with the information available, and it does seem to be limited to your specific custom services.

**Closed by DaneEveritt** 2017-12-15 03:10 UTC
Labels: Bug, P: High
