### ISSUE TITLE
Add option to reorder servers or order by name rather than ID

### ISSUE THREAD

**Issue by RickyB98** [pterodactyl/panel#3196] opened 2021-03-18 09:03 UTC
**Is your feature request related to a problem? Please describe.**
When the list of servers in your account becomes significantly large, it becomes difficult to find the server you're looking for. The search button is okay but it feels like it isn't as quick as it could be.

**Describe the solution you'd like**
Make the possible to reorder the server list. Perhaps add the possibility to group the servers by owner, node, location, an ad-hoc field, or whatever could be useful, especially for the admin view.

**Describe alternatives you've considered**
Alternatively, show the servers in alphabetical order rather than by creation date (ID). The same goes for all other sections (nodes, locations, etc.).

**Additional context**
N/A

**Comment by trenutoo** [comment] 2021-03-18 09:05
Duplicate of #1439

**Closed as completed** 2021-03-18 09:13 UTC
