### ISSUE TITLE
Migrating servers from node to other

### ISSUE THREAD

**Issue by HLF-Raideer** [Pterodactyl/Panel#411] opened 2017-04-26 08:19 UTC
Before we installed pterodactyl, we have used Multicraft control panel.
.. right now it is more useable than the older, but i have one suggestion to upgrade the panel.

"Migrating servers from one node to an another"
 It is very simple .. in admin panel can be a migrating side and you can choose where want to move the server. The panel copies all files after it suspends the server and notifies the user if the migrating is ready.

..i don't think that there need to write anything more .. this is all what i want :D

**Comment by HLF-Raideer** [comment] 2017-04-26 08:23
It can also be a good idea to clone servers from one node to another..
(After user chossed the node where he want to move the server, appears a drop-down menu, where need to choose the right ip and port on the node where he want to move.)

**Comment by MeltedLux** [comment] 2017-04-26 11:25
Duplicate of https://github.com/Pterodactyl/Panel/issues/18

**Closed** 2017-04-26 11:28 UTC
