### ISSUE TITLE
Pterodactyl 1.0, BungeeCord Bad hostline

### ISSUE THREAD

**Issue by Games4k** [pterodactyl/panel#1992] opened 2020-05-03 14:23 UTC
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: panel 1.0.0, wings 1.0
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: MacOS, Google Chrome

**Describe the bug**
There's an issue when starting bungeecord for the second time. I'm getting the following error:
```
14:10:30 [SEVERE] Exception in thread "main" 
14:10:30 [SEVERE] java.lang.IllegalArgumentException: Bad hostline: 
14:10:30 [SEVERE]     at net.md_5.bungee.Util.getAddr(Util.java:48)
14:10:30 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.getServers(YamlConfig.java:221)
14:10:30 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:106)
14:10:30 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
14:10:30 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
14:10:30 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
14:10:30 [SEVERE] Caused by: java.net.URISyntaxException: Expected authority at index 6: tcp://
14:10:30 [SEVERE]     at java.net.URI$Parser.fail(URI.java:2848)
14:10:30 [SEVERE]     at java.net.URI$Parser.failExpecting(URI.java:2854)
14:10:30 [SEVERE]     at java.net.URI$Parser.parseHierarchical(URI.java:3102)
14:10:30 [SEVERE]     at java.net.URI$Parser.parse(URI.java:3053)
14:10:30 [SEVERE]     at java.net.URI.<init>(URI.java:588)
14:10:30 [SEVERE]     at net.md_5.bungee.Util.getAddr(Util.java:45)
14:10:30 [SEVERE]     ... 5 more
```

It seems like this error is due to improper egg, which adds the following lines to the config:
```
listeners[0]:
  host: 0.0.0.0:30001
  query_enabled: 'true'
  query_port: 30001
```

instead of editing listeners:, it adds listeners[0]: section.

**To Reproduce**
1. Install a BungeeCord server
2. It should boot up normally the first time.
3. Now restart it, and you should see the error message

**Expected behavior**
The expected behavior would be a fully started and running Bungeecord server.

**Comment by Sir3lit** [comment] 2020-05-03 16:35
Not sure if this would be related to Issue #1956

**Comment by DaneEveritt** [comment] 2020-05-04 04:05
It is neither of those issues @Sir3lit, it looks like it is just not handling the array logic correctly there.

**Comment by DaneEveritt** [comment] 2020-05-18 01:23
Theoretically fixed in bd063682dc1427d739017e9caf74e2a15b8da976

**Comment by Games4k** [comment] 2020-05-23 10:40
I don't think so. That was on the latest version:

![Screen Shot 2020-05-23 at 12 33 41 PM](https://user-images.githubusercontent.com/29690431/82728707-8a07b100-9cf2-11ea-826b-e3ffc9c131e0.png)

**Comment by Games4k** [comment] 2020-05-23 10:40
Also, with migrated db & seeds

**Comment by FoksVHox** [comment] 2020-05-23 10:42
@Games4k He said Theoretically, not practical.

**Comment by Games4k** [comment] 2020-05-24 11:36
I know, that's why I wanted to inform him that it's not, just in case he doesn't already know that

**Comment by DaneEveritt** [comment] 2020-05-24 22:40
@Games4k was that configuration file correct before Pterodactyl tried to do things? It won't correct any existing messed up ones, but I also haven't been able to reproduce it doing that to new configuration files.

**Comment by dieterblancke** [comment] 2020-09-03 12:45
How did you solve this? I am having a similar issue after just upgrading my panel.

I'm using the default Pterodactyl BungeeCord Egg and on a fresh bungeecord install it breaks the config as mentioned above.

**Comment by dieterblancke** [comment] 2020-09-04 08:59
Maybe it might be best for me to add some additional information.

This is what happens when I create a new server and start it up for the first time using the default BungeeCord egg (latest bungeecord version):
```yaml
listeners:
  '0':
    host: 0.0.0.0:25600
    query_enabled: true
    query_port: 25600
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  md_5:
  - admin
```

This then gives the following error in the console:
```
8:51:33 [SEVERE] Exception in thread "main" 
08:51:33 [SEVERE] java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.Collection
08:51:33 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig.java:234)
08:51:33 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:85)
08:51:33 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
08:51:33 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
08:51:33 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

It seems to not fully generate the config aswell because of the errors. I might be wrong but it seems like it's changing the config already while BungeeCord is still generating it?

After further testing, I had a BungeeCord instance that was created on the older panel (was still created using NodeJS wings). I changed the host in there and the panel DOES correctly set the host values without breaking the listeners list. It seems to be an issue only when the config is being generated by BungeeCord.

I hope this extra explanation helps.

**Comment by DaneEveritt** [comment] 2020-09-04 15:41
If I had to guess without actually reading my code: it looks like instead of a numeric `0` key being used, a string literal `"0"` is being used, which results in that difference (since the parser would evaluate them the same way I believe, but save differently). That would explain why the one we generate on first boot doesn't work but it works fine if manually corrected.

**Comment by DaneEveritt** [comment] 2020-09-07 20:19
Closed by https://github.com/pterodactyl/wings/pull/56

**Closed** 2020-09-10 03:28 UTC
Labels: 1.0 🦈, bug 🐛
