### ISSUE TITLE
Server stats such as CPU, Memory Usage is not updated

### ISSUE THREAD

**Issue by alvin0319** [pterodactyl/panel#4005] opened 2022-03-16 05:45 UTC
### Current Behavior

![image](https://user-images.githubusercontent.com/32565818/158522676-b18be85f-ce02-4cf1-ba88-0ce38788e559.png)

As you can see in this image, the CPU, Memory Usage is stuck at 0%. Also, the Server uptime is not updated.

When I tried to debug the WebSocket logs, it showed me something weird result.
![image](https://user-images.githubusercontent.com/32565818/158524388-780d9289-c9e2-4462-91b2-accde5ca4e7b.png)
I guess this should be the actual CPU and memory usage.

### Expected Behavior

CPU and Memory Usage, Server uptime should be updated.

### Steps to Reproduce

I have followed the installation step in https://pterodactly.io, nothing to reproduce.

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

Minecraft (PocketMine-MP, WaterdogPE)

### Docker Image

ghcr.io/parkervcp/yolks:debian

### Error Logs

```bash
Wings: https://ptero.co/hujydewulu
Panel: https://bin.ptdl.co/gjf2f/ (I guess this is not the actual problem, it seems I misconfigured SMTP settings)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment] 2022-03-16 05:50
Duplicate of #3999

**Closed as completed by trenutoo** 2022-03-16 05:50 UTC
