### ISSUE TITLE
Panel:On Container Rebuild no indication of processing

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#798] opened 2017-12-05 07:42 UTC
* Panel: latest
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: FFDE

Whenever i update my docker image i use Rebuild Container. 
However if i press the start button in the console of the server it just outputs theese lines which looks like its death:
![](https://image.prntscr.com/image/Y40nNuU4QiOs1VtPIzFLKQ.png)

After some seconds it will then automatically start the server.
# BUT
In this time i am able to press again start where a second rebuild request comes in.
when this happen it will throw me this error:
```

[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Please wait while your server is being rebuilt.
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] An error was encountered while attempting to rebuild this container. Please contact your administrator for assistance. PTDL:ERR_ID:MH7eqNRbihKFrBOsi3n6
```
Wings is confused in this case 
### But its working at the end so its more just a design bug

Here are some logs from wings: https://hastebin.com/qobanelaga.js

Happy wingsmas

**Comment by ProJaCore** [comment] 2017-12-07 12:17
@schrej i am using the latest daemon from the git branch develop

**Comment by schrej** [comment] 2017-12-07 12:59
@ProJaCore Yes, we are working on a new daemon written in golang though, which makes the current one the "old" one ;)

**Comment by DaneEveritt** [comment] 2017-12-08 02:03
I'm not able to reproduce any issues here. The rebuild message is potentially confusing, but the server should boot just fine afterwards.

**Comment by DaneEveritt** [comment] 2017-12-08 02:11
I've gone ahead and added some more output and moved the order of outputs around a bit to hopefully make things clearer.

```
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Your server container needs to be rebuilt. This should only take a few seconds, but could take a few minutes. You do not need to do anything else while this occurs. Your server will automatically continue with startup once this process is completed.
[Pterodactyl Daemon] Rebuilding server container...
[Pterodactyl Daemon] New container built, rotating hamsters...
[Pterodactyl Daemon] Container is being initialized...
[Pterodactyl Daemon] Completed rebuild process for server. Server is now booting.
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 51M / 100M
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server container started. Attaching...
[Pterodactyl Daemon] Attached to server container.
```

**Comment by DaneEveritt** [comment] 2017-12-08 02:15
I see what you were trying to say now. If you press start while it is rebuilding you get that error.

**Comment by DaneEveritt** [comment] 2017-12-08 02:41
```
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Your server container needs to be rebuilt. This should only take a few seconds, but could take a few minutes. You do not need to do anything else while this occurs. Your server will automatically continue with startup once this process is completed.
[Pterodactyl Daemon] Server marked as STOPPING
[Pterodactyl Daemon] Rebuilding server container...
[Pterodactyl Daemon] New container built, rotating hamsters...
[Pterodactyl Daemon] Container is being initialized...
[Pterodactyl Daemon] Completed rebuild process for server. Server is now booting.
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 52M / 100M
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server container started. Attaching...
[Pterodactyl Daemon] Attached to server container.
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
:/home/container$ java -Xms128M -Xmx512M -jar server.jar
```

All fixed now. Good find 👍

**Closed** 2017-12-08 02:43 UTC
Labels: Bug, Old Daemon, P: Low
