### ISSUE TITLE
FTP Accounts for Sub Users

### ISSUE THREAD

**Issue by Whip-Tide** [Pterodactyl/Panel#627] opened 2017-09-15 11:14 UTC
As using this portal for over 3 months now i've notied that Sub Users/Main User use the same SFTP credentials.

You should add so Sub Users have their own SFTP credentials for logging, restrictions etc.

**Comment by parkervcp** [comment] 2017-09-15 11:17
Duplicate of #281 #101 and exact copy of #623. The most recent still open request.

**Closed** 2017-09-15 12:51 UTC
