### ISSUE TITLE
Add server name to console screen for mobile. 

### ISSUE THREAD

**Issue by LilSadPanda** [pterodactyl/panel#4199] opened 2022-06-28 13:01 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

As if 1.9.1 you can not see server name anymore on mobile. 

### Describe the solution you'd like.

A way to display server name on the console page

**Comment by AndyIsHereBoi** [comment] 2022-06-28 15:55
I can confirm this is also happening for me![Screenshot_20220628-105047.jpg](https://user-images.githubusercontent.com/69745145/176225217-5a43e9d6-2e3b-4c0c-9d99-c9c32f326eb2.jpg)
It just doesn't show

**Comment by DaneEveritt** [comment] 2022-06-28 22:20
I plan on completely re-designing the mobile and desktop views to support a sidebar and accordion menu on mobile, so I'm closing this out since there isn't a great way to do this on mobile without taking up even more room on an already snug screen.

For now this is intentional, expect improvements over time. :)

**Closed as completed by DaneEveritt** 2022-06-28 22:20 UTC

**Comment by rollexxmaxx-design** [comment] 2025-12-18 17:11
[../](url)
