### ISSUE TITLE
The archive provided is in a format Wings does not understand

### ISSUE THREAD

**Issue by ExtremTechniker** [pterodactyl/panel#3588] opened 2021-08-30 11:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

In my Minecraft, produces .log.gz file. When decompressing this file via the panel the is an error 

> An error occurred on the remote host: The archive provided is in a format Wings does not understand.. (request id: ca743371-ab94-4d32-bd4a-8f444ab1ee17)

### Expected Behavior

File .log.gz should decompress like normal zip files

### Steps to Reproduce

Use Minecraft .log.gz file, right click, Click unarchive, error is on the top of the page

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
https://ptero.co/xozayemalo

http://bin.ptdl.co/0zb8j
```

**Comment by matthewpi** [comment] 2021-10-06 17:33
This is not a bug as much as it is a feature request.  The `decompress` endpoint is named poorly, even though in the UI is states `Extract`.  It will only work on archives that can optionally be compressed, not just compressed files.

**Comment by danny6167** [comment] 2024-06-14 11:07
Closing as duplicate of (fixed) https://github.com/pterodactyl/panel/issues/5034

**Closed as not planned by danny6167** 2024-06-14 11:07 UTC
