### ISSUE TITLE
Too Many Attempts Error

### ISSUE THREAD

**Issue by YTRemRem** [pterodactyl/panel#2490] opened 2020-10-12 14:06 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v1.0.0
* Server's OS: CentOS8
* Your Computer's OS & Browser: Windows 10 & Google Chrome

**Describe the bug**
When a admin user login to the panel it will shows a error saying Too Many Attempts.
Please provide additional information too, depending on what you have issues with:
https://imgur.com/3rhGoXs
Panel: PHP 7.4.11

**To Reproduce**
Using an admin account to login to the panel

**Expected behavior**
Listed all server list

**Comment by Pemigrade** [comment] 2020-10-12 16:00
I'm getting the same error on v1.0.0. It seems to only occur sometimes, even when using @YTRemRem's included steps to reproduce.

I've found that when it does not occur upon sign-in, you can usually reproduce it by selecting a server, creating a new database, then attempting to delete that database.

A search for "Too Many Attempts" in the Discord reveals that 67% (4/6) of the too many attempts errors occurred in the past 10 days, even though the discord search logs date back to 2017, so I think that the 1.0 panel may cause this issue but cannot be certain.

**Comment by DaneEveritt** [comment] 2020-10-12 16:03
Its just an error caused by hitting the API throttles, it was bound to happen and I'll need to come up with a better throttle or more tunable throttles to avoid it happening. It happens as an admin because you're making far more requests to far more servers than a normal account.

**Comment by DaneEveritt** [comment] 2020-10-13 03:16
This can be configured for now by upping `APP_API_CLIENT_RATELIMIT=240` in the `.env` file to whatever value seems reasonable for number of requests per minute. I updated the default to `720` for now.

**Comment by DaneEveritt** [comment] 2020-10-13 03:16
closed in https://github.com/pterodactyl/panel/commit/ef586bf75276623c07ac7185eb5b9d3152ac7a45

**Closed by DaneEveritt** 2020-10-13 03:16 UTC

**Comment by Hellohi3654** [comment] 2021-11-02 10:02
Hi I've been getting this error lately and I'm now unable to login to my panel

I have increased app_api_client_ratelimit and application ratelimit to 1000000 and it is still doing it
I have also tried just doubling the current values

**Comment by mdxwzl** [comment] 2021-11-27 07:37
> Hi I've been getting this error lately and I'm now unable to login to my panel
> 
> I have increased app_api_client_ratelimit and application ratelimit to 1000000 and it is still doing it I have also tried just doubling the current values

I have the same problem

**Comment by Niktixx** [comment] 2021-12-03 18:01
Same for me...

**Comment by Hellohi3654** [comment] 2021-12-04 13:19
I ended up fixing my issue 
I removed the theme I had installed by restoring a backup I had made
Been working fine since using the default theme

**Comment by Niktixx** [comment] 2021-12-10 06:15
> I ended up fixing my issue 
> I removed the theme I had installed by restoring a backup I had made
> Been working fine since using the default theme

Which Theme have you been using?

**Comment by CeriseRouge0** [comment] 2022-01-17 18:02
Hello,
I have the same problem with the Unix Theme.
It is probably the theme.

This theme is beautiful...
