### ISSUE TITLE
Be able to assign/allocate port 80 to a server in the panel

### ISSUE THREAD

**Issue by alixplayz** [pterodactyl/panel#3873] opened 2022-01-10 22:44 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Currently when trying to allocate port 80 to a server. It says it has to be above port 1024, which is problematic as I need to make a HTTP request on 80 from the server.

### Describe the solution you'd like.

.

**Comment by trenutoo** [comment] 2022-01-10 22:55
Duplicate of #3749

**Closed as completed by trenutoo** 2022-01-10 22:55 UTC
