### ISSUE TITLE
Add API endpoint for transferring servers.

### ISSUE THREAD

**Issue by OddDevelopment** [pterodactyl/panel#4903] opened 2023-10-22 01:27 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A way to use the API to transfer servers.

### Describe the solution you'd like.

Adding an API endpoint so I can transfer servers using the pterodactyl API.

**Comment by devnote-dev** [comment] 2023-10-22 01:32
Potential duplicate of #2148 which is/was (?) being used to track this feature. It's also already been confirmed to come in v2.

**Comment by matthewpi** [comment] 2024-05-04 22:56
This endpoint will come with the overhauled application api in v2.

**Closed as not planned by matthewpi** 2024-05-04 22:56 UTC

**Comment by HerrSammyDE** [comment] 2024-05-04 23:34
> This endpoint will come with the overhauled application api in v2.

When will that be?
