### ISSUE TITLE
Group Servers for better overview

### ISSUE THREAD

**Issue by NickCloudAT** [pterodactyl/panel#2963] opened 2021-01-02 19:17 UTC
**Is your feature request related to a problem? Please describe.**
It's pretty annoying when you have many many Servers and just want some of them to be shown.

**Describe the solution you'd like**
A "grouping" System where you can create groups (e.g. Minecraft) where you can put in Servers and you can then filter by group in the Server overview.

**Describe alternatives you've considered**
I dont really have any as I think a grouping System would be best.

**Additional context**
As said, it's pretty annoying if you have many Servers and for example a Minecraft Bungee Network. The Minecraft Servers may not even be in order in the overview list and it would be easier to sort by "Minecraft Network" (if you'd create a group called like that) to list only all Minecraft Servers you set into that group.

**Comment by matthewpi** [comment] 2021-01-02 19:20
Duplicate of https://github.com/pterodactyl/panel/issues/1439

**Closed as completed by matthewpi** 2021-01-02 19:20 UTC
