### ISSUE TITLE
CPU Limit Not Working

### ISSUE THREAD

**Issue by skw359** [pterodactyl/panel#3620] opened 2021-09-14 02:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Setting the CPU Limits in Pterodactyl's Server Administration page does not update when inputted values. For example - setting it to '0' keeps reverting back to the previous change, it basically does not save. 

### Expected Behavior

For the CPU Limit to be updated 

### Steps to Reproduce

Go to a server in Pterodactyl, enter its respective admin page -> Build Configuration -> try updating the CPU Limit and it'll probably not work (will not update)

### Panel Version

1.6.0

### Wings Version

1.5.0

### Error Logs

```bash
Wings: https://ptero.co/sagobuyexa.cs
Panel: https://bin.ptdl.co/yuksf/
```

**Comment by matthewpi** [comment] 2021-09-14 02:43
Duplicate of https://github.com/pterodactyl/panel/issues/3613

**Closed as completed by matthewpi** 2021-09-14 02:43 UTC
