### ISSUE TITLE
Unable to delete failed backups

### ISSUE THREAD

**Issue by Sibald** [pterodactyl/panel#2921] opened 2020-12-28 01:42 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Newest
* Server's OS: Ubuntu 18.04 LTS
* Your Computer's OS & Browser: Chrome 

Bug:
When a backup is made in the panel for a server and the backup fails to create. When you want to delete the failed backup their is an error displaying on the top of the panel.

I'm unable to delete failed backups on the panel.

**Comment by matthewpi** [comment] 2020-12-29 03:16
Please include more information about the error you see.  Whenever I have failed backups they are able to be deleted without any errors.

**Comment by DaneEveritt** [comment] 2021-01-10 20:38
Closing: lack of information.

**Closed as completed by DaneEveritt** 2021-01-10 20:38 UTC

**Comment by adrijanb** [comment] 2021-03-06 09:48
Hey,

I would like to open this issue again. I can provide you with information

**Comment by adrijanb** [comment] 2021-03-06 09:52
If a backup fails (for example: it could not reach the s3) the panel is saying that the backup is "failed". Due the failed state of the backup , you cannot delete the backup anymore. 


https://streamable.com/t22ntb

**Comment by LaserKaspar** [comment] 2022-05-09 18:55
I am facing the same issue... Did you find a fix?

**Comment by hexandcube** [comment] 2022-09-02 09:29
I'm having the same issue
https://user-images.githubusercontent.com/41151156/188109784-673674af-54f3-4e78-a14d-44c9e4d4d876.mp4

**Comment by hexandcube** [comment] 2022-11-04 11:10
How do I delete a failed s3 backup from the list. Do I really have to reinstall the server? Please reopen the issue.

**Comment by matthewpi** [comment] 2022-11-04 17:40
> How do I delete a failed s3 backup from the list. Do I really have to reinstall the server? Please reopen the issue.

This issue was fixed awhile ago and ever since I've been unable to reproduce it.  Reinstalling the server will do nothing.  To remove a failed backup all you need to do is just click the delete button in the context menu.  If the backup is still "processing" you will need to wait up to 6 hours for it to be marked as failed.  If you get an error while trying to delete a backup, open a new issue about it, but make sure you are running the latest Panel (v1.10.4) and Wings (v1.7.2) before opening an issue.
