### ISSUE TITLE
Cpu usage can be rounded. 

### ISSUE THREAD

**Issue by LilSadPanda** [pterodactyl/panel#4188] opened 2022-06-27 20:12 UTC
### Current Behavior

![Screenshot_20220627_220850](https://user-images.githubusercontent.com/56886085/176026989-3538ff33-8ab9-404f-bc94-cf4b0be8e04c.jpg)

### Expected Behavior

Can be displayed as 0.35% 

### Steps to Reproduce

Currently on mobile but its sometimes visible when refreshing. 

### Panel Version

1.9.0

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment] 2022-06-27 20:32
Duplicate of #4168

**Closed as not planned** 2022-06-27 21:42 UTC
