### ISSUE TITLE
Unresponsive console

### ISSUE THREAD

**Issue by popcorn9499** [pterodactyl/panel#2734] opened 2020-11-24 01:56 UTC
**Background (please complete the following information):**
* Panel or Daemon: It appears on the web panel however it may be something with the daemon (I will explain further
* Version of Panel/Daemon: panel 1.1.1 daemon 1.1.1
* Server's OS: Panel: Ubuntu Server 18.04.5 4.15.0-124 Running apache 2.4.29 Daemon: Arch Linux 5.9.9-arch1-1
* Your Computer's OS & Browser: Windows 10 Google Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: 
```
PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
```
Daemon: 
`Linux file-server-1 5.9.9-arch1-1 #1 SMP PREEMPT Wed, 18 Nov 2020 19:52:04 +0000 x86_64 GNU/Linux`
```
Server:
 Containers: 31
  Running: 11
  Paused: 0
  Stopped: 20
 Images: 174
 Server Version: 19.03.13-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c623d1b36f09f8ef6536a057bd658b3aa8632828.m
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.9.9-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.36GiB
 Name: file-server-1
 ID: (Some ID)
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
**To Reproduce**
1. Go to `Sever Console page` 
2. Either type `list` or some command that should return a value, or wait until a user joins
3. Nothing new appears on console until you refresh the page

The fix to restore intended behavior from my experience of about a day is to restart the server.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
I expect to see the console update when commands r run or even when the server console outputs something. Like so
[link](https://photos.popicraft.net/u/files/19.35.03-23.11.20-K3eCTSi0Bq.mp4)

**Comment by popcorn9499** [comment] 2020-11-25 23:08
needed to make an edit as rereading this I was not clear on my issue. I appologize.


The edit was under reproduce.

Nothing new appears on the console until you refresh the page.

I am hopeful I can get something logged to determine what is going on in this program

**Comment by popcorn9499** [comment] 2020-11-26 01:16
Decided since it occured again. I remembered to take a brief video clip of what is occuring. [link](https://photos.popicraft.net/u/files/19.15.43-25.11.20-ZY97tbsOs7.mp4)

**Comment by popcorn9499** [comment] 2020-11-26 04:08
I saw one thing weird when I put wings into debug mode. I configured this in the config file for wings. anyways 
```
DEBUG: [Nov 25 22:02:42.245] GET /api/servers/ef5917fa-8a84-4234-889f-82741661509d/ws client_ip=192.168.1.1 latency=1h13m14.758864737s status=200
```
The latency being over a hour struck me as odd this just struck me as rather odd and i'm not sure if this is portraying to the issue I am having or not but figured it was worth mentioning

**Comment by matthewpi** [comment] 2020-11-27 00:11
> I saw one thing weird when I put wings into debug mode. I configured this in the config file for wings. anyways
> 
> ```
> DEBUG: [Nov 25 22:02:42.245] GET /api/servers/ef5917fa-8a84-4234-889f-82741661509d/ws client_ip=192.168.1.1 latency=1h13m14.758864737s status=200
> ```
> 
> The latency being over a hour struck me as odd this just struck me as rather odd and i'm not sure if this is portraying to the issue I am having or not but figured it was worth mentioning

The latency on the `/api/servers/{uuid}/ws` route is how long the connection was active for.

**Comment by popcorn9499** [comment] 2020-11-27 01:22
> > I saw one thing weird when I put wings into debug mode. I configured this in the config file for wings. anyways
> > ```
> > DEBUG: [Nov 25 22:02:42.245] GET /api/servers/ef5917fa-8a84-4234-889f-82741661509d/ws client_ip=192.168.1.1 latency=1h13m14.758864737s status=200
> > ```
> > 
> > 
> > The latency being over a hour struck me as odd this just struck me as rather odd and i'm not sure if this is portraying to the issue I am having or not but figured it was worth mentioning
> 
> The latency on the `/api/servers/{uuid}/ws` route is how long the connection was active for.

wouldn't that of been better to call connection time or active time?


however that really then has nothing to do with the issue I guess. however it is still an issue and idk y it occurs so often

**Comment by DaneEveritt** [comment] 2020-11-29 18:46
Please include logs from your browser developer console (network activity and any console messages), the information provided here is not enough to warrant me spending hours and hours trying to reproduce the issue.

While I believe that it happens, it is a fruitless activity for me to devote so much of my limited time to trying to reproduce such an issue right now.

**Comment by popcorn9499** [comment] 2020-11-29 19:00
Alright fair enough. I will send the information requested. When you say "network activity" u just mean the [Export HAR](https://photos.popicraft.net/u/files/12.59.48-29.11.20.png) Option in the developer console? @DaneEveritt

**Comment by DaneEveritt** [comment] 2020-11-29 19:01
No, I just mean confirm there are no failing requests in the Network tab, apologies on the confusion there.

**Comment by popcorn9499** [comment] 2020-11-29 19:04
It is alright just wanted to make sure. When it happens again in the next day or so I will send something your way.

**Comment by popcorn9499** [comment] 2020-11-30 06:23
It did not look like much to me. I didn't see anything that stood out as an error however I honestly don't do much web dev type stuff so I am a little new to poking around the debug tools on web browsers.

However I took screenshots of a quick video of the information I gathered.


[Chrome Network Tab](https://photos.popicraft.net/u/files/23.58.19-29.11.20-8n8AjGTaJX.mp4)
[Chrome Console Tab](https://photos.popicraft.net/u/files/23.58.40-29.11.20.png)
[Chrome Websocket Responses](https://photos.popicraft.net/u/files/00.02.31-30.11.20.png)

[Firefox Network Tab](https://photos.popicraft.net/u/files/00.00.25-30.11.20.png)
[Firefox Console Tab](https://photos.popicraft.net/u/files/00.01.42-30.11.20.png)
Firefox Websocket Responses](https://photos.popicraft.net/u/files/00.02.04-30.11.20.png)

Since in looking at how things seemed to operate it looks like the browser talks directly to wings so I also grabbed the relevant part of the log from wings after trying to run a command in console which should of returned something in the console.

Sorry I hadn't figured out where the wings log was sooner. Anyways this is everything from the log at the moment I connect. I turned on debug mode.
```
DEBUG: [Nov 30 00:15:22.743] GET /api/servers/ef5917fa-8a84-4234-889f-82741661509d/ws client_ip=192.168.1.1 latency=17m19.516180771s status=200
DEBUG: [Nov 30 00:15:23.117] listening for server events over websocket server=ef5917fa-8a84-4234-889f-82741661509d
```


Hopefully some of this helps. It looked like for whatever reason wings isn't sending the console event over the web socket for whatever reason.

**Comment by popcorn9499** [comment] 2020-12-01 01:12
something I hadn't noticed before because I thought it was part of the standard output from the minecraft server process but I don't think it is. It isn't in any of the server log files. so this may be what is going on

[image](https://photos.popicraft.net/u/files/19.03.56-30.11.20.png)

**Comment by DaneEveritt** [comment] 2020-12-01 16:09
Ah yeah, that'll do it. That's an issue with Docker streaming us logs and encountering a bad line (or maybe us truncating the file). I've been meaning to report that to Docker since its impossible to catch since it is just dumped to the stdout and I'd have to parse every line looking for it.

**Comment by DaneEveritt** [comment] 2020-12-01 16:09
Marking this as a duplicate of https://github.com/pterodactyl/panel/issues/1950 which I just re-opened. That would be the most logical (and only) reason I can think of that would be giving you this issue.

**Closed as completed by DaneEveritt** 2020-12-01 16:09 UTC
