### ISSUE TITLE
Minecraft Egg Eula.txt

### ISSUE THREAD

**Issue by linusstretchtips** [pterodactyl/panel#2258] opened 2020-08-24 10:35 UTC
When creating and starting a Minecraft server. Eula usually pops up asking to agree to it. (0.7) and on 1.0 the popup doesn't show

0.7.18 (with a theme)
![image](https://user-images.githubusercontent.com/64327566/91034955-bab2fb80-e5fd-11ea-8941-874945ad68cc.png)

1.0
![image](https://user-images.githubusercontent.com/64327566/91034992-ca324480-e5fd-11ea-88d2-bd1acf2a3790.png)

no popups. It just gives out the Exit code

```
[10:26:22 INFO]: You need to agree to the EULA in order to run the server. Go to eula.txt for more info.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
```

**Comment by fabm3n** [comment] 2020-08-24 10:41
dupe of #1941

**Closed** 2020-08-24 11:39 UTC
