### ISSUE TITLE
Improved backups (Suggestion)

### ISSUE THREAD

**Issue by Rezanans-wow** [pterodactyl/panel#3331] opened 2021-05-06 12:31 UTC
Backups is really cool feature of pterodactyl, but it can be better
My first suggestion add Google Drive backups, but its not super good i thinked so, going to **FTP backups** most popular system

FTP backups, because me have some servers with big storage 
So anyway, be good if backups forked. I think its not bad for panel, new features xD

For me really need limit of backups size, so my suggestion

Add alternative backup storage (S3 i know) like
- **FTP/FTPS** (Many cheap dedicated server, with storage example Hetzner storage box super cheap and good for backups)
And add **limit** to backup size setting

> Spoiler: I understand that this is not a necessity, but let it be as a proposal. As for me, it would be cool

**Comment by trenutoo** [comment] 2021-05-06 13:00
Duplicate of #2177

**Comment by Rezanans-wow** [comment] 2021-05-06 13:05
Ok, but about backup size limit still unique in suggestion

**Comment by DaneEveritt** [comment] 2021-05-06 16:08
I'm not adding support for FTP backups. If you want to do something like that you can mount those drives to your disk and use them as a "local" solution, or add code in Wings to handle it.

Backups are confusing enough as is, I don't want to just go down the path of adding endless provider types.

I also don't see the point of limiting the size of a backup when you can just limit the amount of disk space available to a server and use that in combination with the limit on number of backups to restrict usage at a higher level.

**Closed as completed by DaneEveritt** 2021-05-06 16:08 UTC
