### ISSUE TITLE
Upload progress bar

### ISSUE THREAD

**Issue by EsserGaming** [pterodactyl/panel#3314] opened 2021-05-01 01:29 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Have a popup that shows the progress of the file(s) being uploaded.

**Describe alternatives you've considered**
I haven't thought of any.

**Additional context**
Have a progress bar (preferably with percentage/amount of data transferred) show when you upload file(s).

**Comment by notAreYouScared** [comment] 2021-05-01 01:59
Duplicate of #2302

**Comment by EsserGaming** [comment] 2021-05-01 02:33
I know that, but that hasn't been noticed at all.

**Comment by trenutoo** [comment] 2021-05-01 05:52
Open issue indicates that the feature request has not been denied. It does not mean that it's something that will be put under work right away. There is limited dev time available, and you can also read [Dane's response](https://github.com/pterodactyl/panel/issues/2302#issuecomment-765584326) in the linked issue.

**Comment by delije23** [comment] 2021-05-01 13:52
> **Is your feature request related to a problem? Please describe.**
> No
> 
> **Describe the solution you'd like**
> Have a popup that shows the progress of the file(s) being uploaded.
> 
> **Describe alternatives you've considered**
> I haven't thought of any.
> 
> **Additional context**
> Have a progress bar (preferably with percentage/amount of data transferred) show when you upload file(s).

You're better off paying someone to create it for you, rather than waiting Dane to do jack shit about it. He skinned off so much features just to push out 1.0 asap.

**Comment by EsserGaming** [comment] 2021-05-01 14:19
> 
> 
> Open issue indicates that the feature request has not been denied. It does not mean that it's something that will be put under work right away. There is limited dev time available, and you can also read [Dane's response](https://github.com/pterodactyl/panel/issues/2302#issuecomment-765584326) in the linked issue.

Alright, I stand corrected.

**Closed as completed** 2021-05-01 14:19 UTC

**Comment by notAreYouScared** [comment] 2021-05-01 15:53
> You're better off paying someone to create it for you, rather than waiting Dane to do jack shit about it. He skinned off so much features just to push out 1.0 asap.

What features are missing? Please elaborate as he's added some that were only available via plug-ins. 

Also before you start bashing people that do something in their free time, maybe use some proper English? 

> He skinned off so much features
