### ISSUE TITLE
[Schedule] An error occurs when creating a schedule with a long name

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2405] opened 2020-09-23 15:03 UTC
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/cbedd4539c750fd647ee13dee15c7cb0556029c2 & https://github.com/pterodactyl/wings/commit/f0a4efb242a66c1ec34b1139e8853ab1795cfeea
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
![image](https://user-images.githubusercontent.com/28255085/94030695-ca715b80-fdc6-11ea-85b2-3057b41ed94c.png)

If you look at exception:
![image](https://user-images.githubusercontent.com/28255085/94030792-e37a0c80-fdc6-11ea-9261-09390a261d1c.png)

**To Reproduce**
Create schedule with name greater than 255 characters

**Comment by DaneEveritt** [comment] 2020-09-23 15:11
This has already been fixed by @AreYouRlyScared

**Comment by zKoz210** [comment] 2020-09-23 15:15
@DaneEveritt Where exactly? I use the latest version from github

**Comment by DaneEveritt** [comment] 2020-09-23 15:20
Oh sorry, I skimmed this issue since it was just pictures. In the future please actually describe what the issue is more specifically, since when I'm moving quick to triage issues I don't spend ages comparing the differences between two images. In general, the images are not useful to me for comparing errors, this would have been a lot simpler as just describing how the error message isn't telling you the validation error for long schedule names.

**Closed** 2020-09-25 02:25 UTC
