### ISSUE TITLE
Language translation

### ISSUE THREAD

**Issue by ValentinRgt** [pterodactyl/panel#4495] opened 2022-10-27 16:20 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Currently the panel is completely in English and it is quite difficult to translate it.
You have to go through all the pages in the project in Laravel and if one day you decide to update the panel the work will be lost...

The ideal idea would be to have an i18n system in yml/yaml or json file sorted by country identifier, e.g. en.json, de.json, ru.json, fr.json ...
with all the messages present on the panel in order to allow the community to modify them easily on their server.

### Describe the solution you'd like.

In the Laravel project add a folder called "translations" containing all the translation files.

To facilitate the implementation of this, I suggest you use Crowdin as LuckPerms and let the community participate in the translation of the various

Crowdin Luckperms : https://crowdin.com/project/luckperms

**Comment by TrixterTheTux** [comment] 2022-10-27 16:23
Duplicate of #2518

**Closed as completed by TrixterTheTux** 2022-10-27 16:23 UTC
