### ISSUE TITLE
Creating a service based on a custom image > fails

### ISSUE THREAD

**Issue by Altegras** [Pterodactyl/Panel#565] opened 2017-07-26 12:44 UTC
Considering minor bug in wording https://github.com/Pterodactyl/Panel/issues/553 - I understand that here: http://i.imgur.com/nTvV9co.png the panel is reffering to the image.

Which is available (locally built)
```
# docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
ehlogp/games/dedicated        srcds               b6b8ecec0490        21 minutes ago      505MB
quay.io/pterodactyl/core      glibc               f8ff63ba5cd0        11 days ago         17.3MB
php                           7.1-cli             2dbd5ab1d9f5        12 days ago         370MB
debian                        jessie              62a932a5c143        5 weeks ago         123MB
quay.io/pterodactyl/scrappy   latest              8aaf838dd31b        2 months ago        247MB

```

But it fails to install:
```
Jul 26 15:37:10 Games10-DManager node[13010]: {"name":"wings","hostname":"Games10-DManager","pid":13010,"server":"884b5db7-9b63-4cf3-ab2e-2ac2497e4755","level":40,"msg":"Container was not found. Attempting to recreate it.","time":"2017-07-26T12:37:10.351Z","v":0}
Jul 26 15:37:10 Games10-DManager node[13010]: {"name":"wings","hostname":"Games10-DManager","pid":13010,"level":30,"msg":"Checking if we need to update image ehlogp/games/dedicated:srcds, if so it will happen now.","time":"2017-07-26T12:37:10.352Z","v":0}
Jul 26 15:37:12 Games10-DManager dockerd[32074]: time="2017-07-26T15:37:12.093176659+03:00" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Jul 26 15:37:12 Games10-DManager dockerd[32074]: time="2017-07-26T15:37:12.093248348+03:00" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
Jul 26 15:37:12 Games10-DManager dockerd[32074]: time="2017-07-26T15:37:12.093319628+03:00" level=info msg="Translating \"denied: requested access to the resource is denied\" to \"repository ehlogp/games/dedicated not found: does not exist or no pull access\""
Jul 26 15:37:12 Games10-DManager node[13010]: {"name":"wings","hostname":"Games10-DManager","pid":13010,"level":60,"msg":"A fatal error was encountered while attempting to create a server. { Error: (HTTP code 404) unexpected - {\"message\":\"repository ehlogp/games/dedicated not found: does not exist or no pull access\"}\n \n    at /srv/daemon/node_modules/docker-modem/lib/modem.js:243:17\n    at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:270:9)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9) reason: undefined, statusCode: 404, json: null }","time":"2017-07-26T12:37:12.094Z","v":0}
Jul 26 15:37:12 Games10-DManager node[13010]: {"name":"wings","hostname":"Games10-DManager","pid":13010,"server":"884b5db7-9b63-4cf3-ab2e-2ac2497e4755","level":40,"msg":"No container ID was defined in the server JSON, skipping container deletion step.","time":"2017-07-26T12:37:12.096Z","v":0}
Jul 26 15:37:12 Games10-DManager node[13010]: {"name":"wings","hostname":"Games10-DManager","pid":13010,"level":30,"msg":"Notified remote panel of server install status.","time":"2017-07-26T12:37:12.400Z","v":0}
Jul 26 15:37:12 Games10-DManager node[13010]: {"name":"wings","hostname":"Games10-DManager","pid":13010,"server":"884b5db7-9b63-4cf3-ab2e-2ac2497e4755","level":30,"msg":"Server deleted.","time":"2017-07-26T12:37:12.481Z","v":0}
```

Deamon tries to update the image which doesn't exist in registry and it fails, that shouldn't be a "failure" clause, the deamon should check if the image is available locally before failing the installation in my opinion. At this point ... using a custom image saved locally (on the node) seems impossible.

**Comment by schrej** [comment] 2017-07-26 12:46
duplicate of #431

**Closed by schrej** 2017-07-26 12:46 UTC
