### ISSUE TITLE
PHP Artisan migrate fails upon trying to remove index which does not exist.

### ISSUE THREAD

**Issue by henrikx** [pterodactyl/panel#2618] opened 2020-10-27 13:23 UTC
**Background (please complete the following information):**
* Panel or Daemon: panel
* Version of Panel/Daemon: 1.0.3 / mariadb version 10.3
* Server's OS: debian 10

**Describe the bug**
Upon trying to upgrade from version 0.7.16 I got the following error after running `php artisan migrate --force`
```
Migrating: 2020_10_10_165437_change_unique_database_name_to_account_for_server

In Connection.php line 671:
                                                                                                                                                                          
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP INDEX `databases_database_host_id_database_unique`; check that it exists (SQL: alter table `databas  
  es` drop index `databases_database_host_id_database_unique`)                                                                                                            
```
This happens because the index on that table does not exist. I was not able to ignore the error because `php artisan db:seed --force` output 
```

| @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ |
|                                                                              |
|               Your database has not been properly migrated!                  |
|                                                                              |
| @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ |

You must run the following command to finish migrating your database:

  php artisan migrate --step --force

You will not be able to use Pterodactyl Panel as expected without fixing your
database state by running the command above.

                                                                                                                        
 [ERROR] You must correct the error above before continuing.                                                            
```

I was able to correct the missing index with the following mysql query:
```
CREATE INDEX databases_database_host_id_database_unique ON panel.databases (database_host_id);
```
After that `php artisan migrate --force` worked fine.

**To Reproduce**
1. Use version 0.7.16
2. Follow the [official documentation ](https://pterodactyl.io/panel/1.0/upgrade/0.7_to_1.0.html) for migrating from 0.7 to 1.0 until the database migration step.
3. Run `php artisan migrate --force`

I don't know if this will be reproducible for everyone or whether something was wrong with my setup, but this was the steps I did which produced the error.

**Expected behavior**
PHP artisan should ignore errors in queries when the errors are because the result of which it wants to achieve is already present.

**Comment by DaneEveritt** [comment] 2020-10-31 18:30
I've not seen anyone else reporting this issue so I'm closing this out because I don't really feel like trying to reproduce it, and it is likely just a side-effect of some other messed up/missed migration at some point.

**Closed as completed by DaneEveritt** 2020-10-31 18:30 UTC
