### ISSUE TITLE
arrow-up command repeat for console

### ISSUE THREAD

**Issue by robingroppe** [pterodactyl/panel#2595] opened 2020-10-25 15:24 UTC
**Is your feature request related to a problem? Please describe.**

Noticed another "regression" from the 0.7 series. 
Arrow-UP command repeat not working anymore at the console.

**Describe the solution you'd like**

I would like to have that feature implemented again.

**Comment by schrej** [comment] 2020-10-26 10:23
duplicate of #2491

**Closed as completed by schrej** 2020-10-26 10:23 UTC
