### ISSUE TITLE
Ability to create servers with no assigned ports

### ISSUE THREAD

**Issue by Rajdave69** [pterodactyl/panel#4458] opened 2022-10-21 06:41 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be nice to be able to create a server with a port-less allocation. This can be useful for discord bots on the python or js egg because discord bots communicate with the discord API rather than actually using the assigned port. 

### Describe the solution you'd like.

Ability to create allocations without ports for a node and be able to allow usage of port-less allocations through maybe a egg-config option. Eggs like the Python one can keep port-less allocations enabled and eggs like paper can keep it disabled.

**Comment by trenutoo** [comment] 2022-10-21 07:23
Duplicate of #2754

**Closed as completed** 2022-10-21 07:23 UTC
