### ISSUE TITLE
Traffic not show on panel 1.8.0 and wings 1.6.3

### ISSUE THREAD

**Issue by e-zhuravlev** [pterodactyl/panel#4093] opened 2022-05-30 11:04 UTC
### Current Behavior

I am using HOST network mode.
And after the update, I don’t see the traffic display in the panel, is it possible to fix this?

### Expected Behavior

All work

### Steps to Reproduce

Update to last versions)) today!

### Panel Version

1.8.0

### Wings Version

1.6.3

### Games and/or Eggs Affected

CS:GO

### Docker Image

ghcr.io/pterodactyl/games:source

### Error Logs

```bash
http://bin.ptdl.co/ycw5y
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by playaz44** [comment] 2022-05-30 20:14
Does not work on any of the servers. The same error in the logs, panel shows 0kB/s.

**Comment by DaneEveritt** [comment] 2022-05-30 20:29
Does `docker stats <container id>` show any output for those servers?

**Comment by FoksVHox** [comment] 2022-05-30 21:11
Unable to reproduce with 1.8.1 on a fresh install of Pterodactyl

**Comment by e-zhuravlev** [comment] 2022-05-31 05:14
After updating to 1.8.1, it also does not show.
docker stats <container id> 0B / 0B

**Comment by playaz44** [comment] 2022-05-31 15:41
> Does `docker stats <container id>` show any output for those servers?

![image](https://user-images.githubusercontent.com/9553500/171214177-afcacb17-0a14-49e2-baf5-d33a29ee40d4.png)

**Comment by DaneEveritt** [comment] 2022-05-31 20:56
Won't fix it in that case, seems like for whatever reason Docker isn't tracking network utilization for those servers. I don't know enough off the top of my head to have a solution for you, other than knowing it isn't anything to do with Pterodactyl directly.

**Closed as not planned by DaneEveritt** 2022-05-31 20:56 UTC
