### ISSUE TITLE
Allow creation of sub-admin users

### ISSUE THREAD

**Issue by KewaiiGamer** [pterodactyl/panel#1027] opened 2018-03-07 13:43 UTC
I think this would be a good feature for host hosting companies mainly. Basically it would be possible to give users permissions to specific nodes. For example a user has a dedicated server and wants to add it as a node in the panel without having access to other servers and only theirs.

**Comment by lancepioch** [comment] 2018-03-08 15:40
I think this behavior extends past the standard use cases of the panel and adds unnecessary complexity.

If a hosting company wants behaviour like this, then they can implement it themselves so that it fits their specific needs.

**Comment by DaneEveritt** [comment] 2018-03-08 22:58
This is a duplicate of at least two other issues: #279 and one other one that I cannot for the life of me find. I do not have plans to do user-specific nodes at this time as the permissions handling for that gets very complex and introduces a lot of maintenance load. Not to say it won't happen at some point, but at this time it is not a priority. Admin permissions are on the roadmap, and should be expected in the coming weeks.

**Closed by DaneEveritt** 2018-03-08 22:58 UTC
