### ISSUE TITLE
Database Host - Block Nodes

### ISSUE THREAD

**Issue by NotYusta** [pterodactyl/panel#4493] opened 2022-10-27 09:35 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

- Add node whitelist (Admin) other than just LINKED NODE
![image](https://user-images.githubusercontent.com/53965703/198249321-6b1753c2-2a32-44e6-b01e-6b1621b65c2b.png)

### Describe the solution you'd like.

- Prevent nodes to create databases if the node is not specified in the whitelist (client)

**Comment by trenutoo** [comment] 2022-10-27 15:48
Duplicate of #1980 which has been implemented in V2 and is to be released in the future.

**Closed as completed by trenutoo** 2022-10-27 15:48 UTC
