### ISSUE TITLE
Show Live Playercount

### ISSUE THREAD

**Issue by noomis** [pterodactyl/panel#5067] opened 2024-04-10 15:12 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be great to have an Overview of the count of players who are currently on each Server.

### Describe the solution you'd like.

Something like this would be great:

![image](https://github.com/pterodactyl/panel/assets/67051843/424c96ab-1f4f-4298-9b2d-2de0a1c3cb7e)

**Comment by Boy132** [comment] 2024-04-10 15:15
Duplicate of #1218

**Comment by parkervcp** [comment] 2024-04-10 16:06
As #1218 is still open I will close this as a duplicate.

**Closed as completed by parkervcp** 2024-04-10 16:06 UTC
