### ISSUE TITLE
Upload from URL option

### ISSUE THREAD

**Issue by AoElite** [pterodactyl/panel#1730] opened 2019-10-21 01:41 UTC
**Is your feature request related to a problem? Please describe.**
A way to upload files from links directly to the panel.

**Describe the solution you'd like**
A upload from url/link button.

**Additional context**
Having to download a file and then upload it to the panel is a pain, especially for someone who has slow internet.

**Comment by Sir3lit** [comment] 2020-05-10 21:14
Duplicate of #165 ?

**Comment by DaneEveritt** [comment] 2020-05-10 21:17
Yep

**Closed by DaneEveritt** 2020-05-10 21:17 UTC
Labels: Go Daemon, Type: Feature Request
