### ISSUE TITLE
Support for Game Server Querying

### ISSUE THREAD

**Issue by marshyonline** [pterodactyl/panel#2268] opened 2020-08-26 02:13 UTC
**Is your feature request related to a problem? Please describe.**
The current panel does not provide quick access to Game Server Stats / Querying.

**Describe the solution you'd like**
Integrate something like [gamedig](https://www.npmjs.com/package/gamedig) and show this information in the panel.

**Comment by parkervcp** [comment] 2020-08-26 12:34
I would call this a dupe of #1218 first and you can add gamedig as a potential to add in that thread.

**Closed by parkervcp** 2020-08-26 12:34 UTC
