### ISSUE TITLE
A proper permissions system

### ISSUE THREAD

**Issue by Tydium** [pterodactyl/panel#3329] opened 2021-05-06 02:20 UTC
**Is your feature request related to a problem? Please describe.**
100% I have a dev team on a minecraft server, but I don't want them reading/writing certain files/folders at all. All I want is for them to have very specific permissions to a specific folder.

**Describe the solution you'd like**
I would like the permissions tab to have folder specific permissions. This should go vice versa with the whole server also. Like if I don't want anyone to see the server files at all, but just one folder that should be configurable also.

**Describe alternatives you've considered**
none

**Additional context**
Not at the moment. I may come back to edit this.

**Comment by matthewpi** [comment] 2021-05-06 02:51
Duplicate of https://github.com/pterodactyl/panel/issues/2757

**Closed as completed by matthewpi** 2021-05-06 02:51 UTC

**Comment by Tydiumcraftsucks** [comment] 2021-05-08 12:50
Tydiumcraft
