### ISSUE TITLE
Custom Docker Network - Not assigning the allocated IPs correctly

### ISSUE THREAD

**Issue by Kieranwest** [pterodactyl/panel#3865] opened 2022-01-09 01:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Looking at https://pterodactyl.io/wings/1.0/configuration.html#custom-network-interfaces and cross referencing networks from the 'docker network list' command. I've been trying to get the docker containers on my unRAID server to correctly assign their IP addresses onto my LAN. 

Both Wings and the Panel seem to be communicating fine and creating these containers however upon modifying the config.yml to use the macvlan driver and my br0 network. Servers are being assigned random IP addresses from my Internal subnet instead of the allocated ones in the panel. I can confirm the name, driver and mode are matching with my unRAID settings along with the subnet supplied under the v4 interface settings. 

I noticed there was a flag for is_internal under the network section and setting that to either true or false seems to have no affect. Not sure if what I'm asking for is possible as docker networking can be a little hazy for me. 

### Expected Behavior

Changing docker networking to align with unRAIDS existing docker networks to allow allocated IPs via Pterodactyl to be assigned to the docker container directly. Perhaps using the --ip flag, allowing static addresses to be assigned to containers. 

### Steps to Reproduce

Under config.yml
docker.network.name - br0 (Name of my unRAID docker network)
docker.network.driver - macvlan (Matches unRAID docker network driver)
docker.network.is_internal - neither true or false seemed to have an affect
docker.network.interfaces.v4.subnet - x.x.x.x/y (Aligns with my internal network)
docker.network.interfaces.v4.gateway - x.x.x.x (My networks gateway)

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/exihuvacos
```

**Comment by Kieranwest** [comment] 2022-01-12 20:48
Seems assigning a 2nd IP address to my host interface also doesn't allow the container to bind to it. It still defaults to the first IP address regardless of the allocation in Pterodactyl. Not sure if there's anything we can do about that in regards additional flags during the container creation ?

**Comment by Kieranwest** [comment] 2022-01-20 17:35
Any idea if this is something that could potentially come to Pterodactyl ?

**Comment by trenutoo** [comment] 2022-01-20 18:26
> Seems assigning a 2nd IP address to my host interface also doesn't allow the container to bind to it. It still defaults to the first IP address regardless of the allocation in Pterodactyl. Not sure if there's anything we can do about that in regards additional flags during the container creation ?

This sounds like a duplicate of #3841

**Comment by Kieranwest** [comment] 2022-01-20 18:33
> This sounds like a duplicate of #3841

Kinda of, ish. My issue is that the Docker container doesn't get assigned the allocated IP from the pterodactyl panel. So if I assigned 192.168.1.10:25565 to my Minecraft server the docker container would spin up with a random IP like 192.168.1.3 when I have my docker network configured to the same bridge as my host.  Ideally this could be solved by making use of the --ip flag that docker provides but I know Wings makes use of the API rather than the command line. So I'm not sure if that's possible. 

Alternatively if I set my network mode to host. That's when I get the 2nd IP Issue. It'll start the docker container with the 1st IP assigned to my host interface rather than the second.

**Comment by Kieranwest** [comment] 2022-01-24 18:36
Still no thoughts on this?

**Comment by schrej** [comment] 2022-01-24 18:41
This is a duplicate of #3841.

The `--ip` flag sets the IP of the container, not the IP used for the outbound traffic. That's only possible with the method described in that referenced issue.

**Closed as completed by schrej** 2022-01-24 18:41 UTC

**Comment by Kieranwest** [comment] 2022-01-24 18:44
The --ip flag is exactly what I'm looking for. My issue is with the container IP not being assigned correctly. I'm not worried about the outbound traffic. 

My issue is internal routing where the allocation via the panel is not correctly assigning the IP address to the container itself .

**Comment by schrej** [comment] 2022-01-24 18:46
The panel is not supposed to assign an IP Address to a container. That way each IP could only  be used once, and Pterodactyl is not designed that way.

**Comment by Kieranwest** [comment] 2022-01-24 18:48
I understand at the current time it's not possible. However, using the --ip flag would resolve this issue entirely and provide more flexibility in the networking configuration of docker and Pterodactyl. Could it be potentially marked as a feature request ?

**Comment by schrej** [comment] 2022-01-25 08:42
I don't think that would make sense. It's not as simple as "just using the `--ip` flag". It would require massive changes to Pterodactyls data model for this to be usable as it would be required to only allow using one IP for a single server when this feature is enabled. Unless there is much heavier demand for this feature, it won't get added.

**Comment by djzoneporro** [comment] 2022-04-21 16:47
I have the same problem with a custom bridge but I want to assign static ip's to each docker container and in pterodactyl I can't set --ip. 
Is there a way to assign pterodactyl containers a static ip?

**Comment by madpeteguy** [comment] 2022-07-17 19:47
Hello, this feature with assigning ip address is what I currently need.

To be sure that there is no possibility of ip address assignment for servers I read some code.
I found that containers are created with API `github.com/docker/docker v20.10.14+incompatible`.
Going trough docs i have found that *[func (cli \*Client) ContainerCreate(ctx context.Context, config \*container.Config, ...) (container.ContainerCreateCreatedBody, error)](https://pkg.go.dev/github.com/docker/docker@v20.10.17+incompatible/client#Client.ContainerCreate)* can take network configuration with ip address trough *networkingConfig \*[network](https://pkg.go.dev/github.com/docker/docker@v20.10.17+incompatible/api/types/network).[NetworkingConfig](https://pkg.go.dev/github.com/docker/docker@v20.10.17+incompatible/api/types/network#NetworkingConfig)* parameter.

I'm Java dev and have really no Go experience but it seems very easy to make Default Allocation IP appear as a container IP for `driver: macvlan`.
To be honest it was much easier than configuring wings to work with `macvlan` at all.

I created a PR with an example implementation of the feature https://github.com/pterodactyl/wings/pull/134

**Comment by Kieranwest** [comment] 2022-07-19 10:57
> Hello, this feature with assigning ip address is what I currently need.
> 
> To be sure that there is no possibility of ip address assignment for servers I read some code. I found that containers are created with API `github.com/docker/docker v20.10.14+incompatible`. Going trough docs i have found that _[func (cli *Client) ContainerCreate(ctx context.Context, config *container.Config, ...) (container.ContainerCreateCreatedBody, error)](https://pkg.go.dev/github.com/docker/docker@v20.10.17+incompatible/client#Client.ContainerCreate)_ can take network configuration with ip address trough _networkingConfig *[network](https://pkg.go.dev/github.com/docker/docker@v20.10.17+incompatible/api/types/network).[NetworkingConfig](https://pkg.go.dev/github.com/docker/docker@v20.10.17+incompatible/api/types/network#NetworkingConfig)_ parameter.
> 
> I'm Java dev and have really no Go experience but it seems very easy to make Default Allocation IP appear as a container IP for `driver: macvlan`. To be honest it was much easier than configuring wings to work with `macvlan` at all.
> 
> I created a PR with an example implementation of the feature [pterodactyl/wings#134](https://github.com/pterodactyl/wings/pull/134)

Shoutout to you sir! This is exactly what's stopping me from moving pterodactyl over to docker on my unRAID host. Currently stuck with it on a VM -_-. Appreciate this more than you could imagine!

**Comment by madpeteguy** [comment] 2022-10-09 20:53
> Shoutout to you sir! This is exactly what's stopping me from moving pterodactyl over to docker on my unRAID host. Currently stuck with it on a VM -_-. Appreciate this more than you could imagine!

Hello,

I went back to Pterodactyl and found nothing was done with this issue, what's worse, there was a conflict...
So, I solved conflict, rebased fix to current develop and decided to run some tests.
Unfortunately, the fix proposed earlier did not work.
I dedicated the rest of Sunday to find solution and I have succeed.

You can find instructions how I done it in Pull Request coment:
https://github.com/pterodactyl/wings/pull/134#issuecomment-1272623522
I also left sources and docker image test open for public if anyone wish to try it:
https://github.com/madpeteguy/wings/pkgs/container/wings
And for last, released tag includes commit with changes required to build Wings with Github Actions on own fork:
https://github.com/madpeteguy/wings/commits/v1.7.2_mvl

I hope macvlan support will get into official Pterodactyl Wings one day. 🤞

**Comment by Kieranwest** [comment] 2023-09-08 18:31
@schrej was there any chance of this getting merged? Those 40 extra lines do exactly what I need and would be great to have it in the updated releases!

**Comment by madpeteguy** [comment] 2024-10-11 15:00
Updated fix to most recent wings version v1.11.13: https://github.com/pterodactyl/wings/pull/203
You can find modified wings image here: https://github.com/madpeteguy/wings/pkgs/container/wings
I do updates only if i need them.
If anyone need recent updates, two branches can be found here: https://github.com/madpeteguy/wings/branches/all
One with mvl mod, and another for building image in own project - just check what i changed, set own settings and have you own build.
