### ISSUE TITLE
(Feature Idea) - Custom SFTP credentials for each user

### ISSUE THREAD

**Issue by DiscoverSquishy** [Pterodactyl/Panel#623] opened 2017-09-12 08:21 UTC
I have noticed that all sub-users that have access to a server have the same SFTP setting so lets say you give a user access to SFTP but you input that they dont have the right to delete any file yeah that would work via the browser ftp but when connecting to filezilla its pointless because they can just delete it via FileZilla... I suggest creating a new SFTP credential for every new sub-user that would match the permissions the panel admin has set.

I am running on: Ubuntu 16.04

**Note I am not exactly sure if this issue was already made so don't throw hate I don't have all my life to go through the 76 issues!**

**Comment by schrej** [comment] 2017-09-12 11:16
related to #281 
Regarding your Note: If you don't do it we have to. If we have to do it for every issue that gets opened its a lot more work for a few people than if everyone who opens an issue just has a quick look around. There also is a search field available btw.

**Comment by parkervcp** [comment] 2017-09-12 11:17
With the current sftp setup this is not really possible. With the daemon re-write though I believe it was a long goal. Currently though outta just getting the new daemon to feature parity.

**Comment by DiscoverSquishy** [comment] 2017-09-13 09:35
Nice to hear that this got a medium priority! Admins can be trusted with configuring but lets say server with no backups are in real trouble I can't wait till this is implemented! Thank you developers for making this a future update <3

**Comment by DiscoverSquishy** [comment] 2017-09-16 10:56
This is a crucial request that must happen I know it’s a Blackburn but if it wasn't something to do with security I would have let go!

**Comment by schrej** [comment] 2017-09-16 12:49
The rewrite of the daemon is going rather slow. This feature will not be implemented in the old version but only in the new wings. But before implementing any new, additional features we'll have to get the current one to be usable. Until that is the case this will be a backburner, if you like it or not. You can try to implement it into the old daemon yourself if it's so important to you.

And even though this is related to security, it's still not THAT important. Just don't give subusers sftp permissions if you don't trust them for now. I don't even know whether it'll be possible to have individual sftp permissions per user, we'll have to see.

**Comment by DaneEveritt** [comment] 2017-09-18 03:55
This is actually a duplicate of #281 and something that I am looking forward to. However, as @schrej noted, this requires the daemon rewrite to be finished. Its not off the table, just not at the front of the line so to speak.

**Closed by DaneEveritt** 2017-09-18 03:55 UTC
Labels: + daemon, backburner
