### ISSUE TITLE
Issue with creating a new server on the newest release/hotfix

### ISSUE THREAD

**Issue by m4rkey** [pterodactyl/panel#1015] opened 2018-03-03 20:48 UTC
Panel or Daemon: Panel
Version of Panel/Daemon: 0.7.4.1
Server's OS: Debian 9
Your Computer's OS & Browser:  Windows 10, Firefox

Today, I updated to the newest hotfix for the panel, and I tried to create a server and it redirected me to a  Whoops, something went wrong page. This is quite an issue for me, as I create and distribute servers quite often..

https://bin.ptdl.co/gz5ly/ - here are my logs from the panel and I will list my php version below.

EDIT: This also happens when trying to edit server configurations.

PHP 7.2.2-1+0~20180205160742.18+stretch~1.gbpb78b58 (cli) (built: Feb  5 2018 16:07:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2-1+0~20180205160742.18+stretch~1.gbpb78b58, Copyright (c) 1999-2018, by Zend Technologies

**Comment by DaneEveritt** [comment] 2018-03-03 22:26
I am unable to reproduce this issue.

**Comment by jesgeerts** [comment] 2018-03-03 23:00
I have the same issue..

**Comment by m4rkey** [comment] 2018-03-03 23:27
All of my friends are having this issue as well @DaneEveritt It was right after I upgraded, I cant edit anything on server configuration and cant create servers..

**Comment by DaneEveritt** [comment] 2018-03-03 23:34
I legitimately have no idea why it is failing, because I am having 0 problems creating a server in my dev environment. There will be a release later today to fix some other issues and we can see if it gets fixed by that as well.

**Comment by DaneEveritt** [comment] 2018-03-04 04:23
I have had zero luck reproducing this issue and have had no other reports of this happening on other people's systems. There is no reason those rules should be failing, and at this point I have no idea how to move forward with looking for a fix when I cannot get it to fail anywhere else.

**Comment by jesgeerts** [comment] 2018-03-04 07:55
@m4rkey Did you migrate the database? I had the issue when I didn't migrate the update into my database

**Closed** 2018-03-04 16:36 UTC
