### ISSUE TITLE
Unarchiving Large Files

### ISSUE THREAD

**Issue by DrLudicrous** [pterodactyl/panel#3919] opened 2022-01-26 21:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Hi,

So this particular person uploaded a 15GB Zip file through sftp 

When unarchiving the file it comes up with an error stating a communication issue

I figured it may be the actual zip so i attempted to upload a new zip through sftp again. This issue happened again. 

### Expected Behavior

Expected to unarchive all files into the folder it is in. 

### Steps to Reproduce

Attempt to upload a large zip through sftp and unarchive through panel or SSH

 Once trying to archive it will result in a error 500 in red on the panel

### Panel Version

1.7.0

### Wings Version

1.5.6

### Error Logs

```bash
https://ptero.co/uzerocacuj

https://bin.ptdl.co/f1o1n
```

**Comment by FoksVHox** [comment] 2022-01-26 21:12
Duplicate of #2878

**Comment by DrLudicrous** [comment] 2022-01-26 21:16
Thanks

**Closed as completed** 2022-01-26 21:22 UTC
