### ISSUE TITLE
Server Error 500 when making more then one node.

### ISSUE THREAD

**Issue by Minc3** [pterodactyl/panel#1955] opened 2020-04-20 13:47 UTC
* Panel or Daemon: Panel
* Version of Panel/Daemon: v1.0.0 Beta Release 1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser:  ubuntu20.04/Firefox

When I go to create more then one node in the panel, it server error 500.
I have tried both nginx and apache2. it affects both of them.
Fresh install of Ubuntu 18.04.

**To Reproduce**
1. Go to Nodes tab
2. Click on create new button
3. Enter in all the required information
4. Click on create node.

**Comment by Sir3lit** [comment] 2020-04-20 13:50
This has already been fixed with PR #1934

**Comment by parkervcp** [comment] 2020-04-20 13:50
Duplicate of #1930

**Closed by parkervcp** 2020-04-20 13:50 UTC
