### ISSUE TITLE
Request for Historical Resource Usage Tracking Feature in Pterodactyl Panel

### ISSUE THREAD

**Issue by leadvic** [pterodactyl/panel#4864] opened 2023-09-12 20:59 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The proposed feature involves the creation of a historical resource usage tracking system within the Pterodactyl panel. This system would continuously collect and store data on RAM, CPU, and network usage for each server instance hosted on the platform. The primary goal is to provide users with a comprehensive overview of resource utilization over time, enabling them to make informed decisions regarding server management and optimization.

### Describe the solution you'd like.

The implementation of this feature could be achieved through the following steps:

Data Collection: Create a mechanism that periodically captures and records resource usage metrics (RAM, CPU, and network) for each server instance. This data should be associated with each server's unique identifier.

Storage: Store the collected data in a secure and efficient manner, ensuring that historical records are readily accessible when needed. Consider leveraging a database or dedicated storage solution for this purpose.

User Interface: Integrate the historical resource usage data into the Pterodactyl panel's user interface. This could include the addition of new graphs that display historical usage trends for each server instance.

Customization: Allow users to specify the time frame for which historical data should be displayed. Options could include hourly, daily, weekly, or custom date ranges.

Permissions: Implement role-based permissions to control who can access and view historical resource usage data. This ensures that sensitive information remains secure and accessible only to authorized users.

Export Functionality: Consider adding export options that allow users to download historical data for further analysis or reporting purposes, or getting it connected to the API.

I think this feature might not be interesting for everyone and might be storage consuming so I would let the users choose if they want to enable this feature or not.

### Additional context to this request.

I read an issue last year where it was told that this kind of features are not being added. In case that is the response to this, I'd like to know why, as I'd love to see this feature that I would help if possible in making it happen.

**Comment by Boy132** [comment] 2023-09-12 21:06
Basically duplicate of #3708.

TL;DR: Pterodactyl is a hosting panel, not a monitoring software. These kind of features are outside of the project scope.

**Closed as completed** 2023-09-13 02:32 UTC
