### ISSUE TITLE
Panel does not display resource usage on my servers page.

### ISSUE THREAD

**Issue by IAmLythixIAmDumb** [pterodactyl/panel#2198] opened 2020-07-30 17:16 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0 Beta 6
* Server's OS: Ubuntu 18.04 Bionic
* Your Computer's OS & Browser: Ubuntu 20.04 Focal, Chrome Latest

**Describe the bug**
When having servers running and going to the my servers page, their resource usage is not displayed correctly and just shows as using no resources.
![Screenshot](https://user-images.githubusercontent.com/54075275/88952813-38eadf00-d298-11ea-90b2-1806dbb25799.png)

But when on the servers actual control panel it displays the resource usage correctly.
![Screenshot](https://user-images.githubusercontent.com/54075275/88952972-849d8880-d298-11ea-90c2-37ae82cf9990.png)

**To Reproduce**
1. Create a server,
2. Start the server,
3. View the resource usage on its page,
4. Go to the my servers page and see it display as no resource usage.

**Expected behavior**
The panel displays the resource usage correctly just like it should.
Example:
![Screenshot](https://user-images.githubusercontent.com/54075275/88953349-19a08180-d299-11ea-9e96-27bc87db4fe1.png)

**Comment by camjac251** [comment] 2020-07-30 17:37
You may want to post these screenshots in issue #2183 instead. The two seem very similar.

**Comment by DaneEveritt** [comment] 2020-07-30 18:44
Duplicate of #2183

**Closed** 2020-07-30 18:44 UTC
