### ISSUE TITLE
Disable admin show all server

### ISSUE THREAD

**Issue by FaizHarofi** [pterodactyl/panel#4924] opened 2023-11-17 11:53 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I hope that the admin feature can't see and manage all servers, most of my friends are off using pterodactly because the script they created is an ENC but because it's still being developed, the script is made without an ENC, the admin takes all the files on that person's panel and then sells them to others. Thank You

### Describe the solution you'd like.

admins cannot view or manage consoles on other servers

### Additional context to this request.

except creating an account and creating a server

**Comment by danny6167** [comment] 2023-11-17 11:58
Admin accounts would be pretty useless if they couldn't manage all the servers.
Don't give admin accounts to people you can't trust. It's really as simple as that.

**Comment by shugen002** [comment] 2023-11-17 16:17
maybe we should split managable list and all server list for admin ?

**Comment by danny6167** [comment] 2023-11-17 16:56
Owned servers and other servers are already split for admins

**Comment by Ferks-FK** [comment] 2023-11-17 18:58
I think it's easier for you to find a reliable host than for pterodactyl to change the way admins do things.

**Comment by Boy132** [comment] 2023-11-28 10:27
Duplicate of #279, basically

**Closed as not planned** 2023-11-28 18:50 UTC
