### ISSUE TITLE
Filter server according to input

### ISSUE THREAD

**Issue by Elikill58** [pterodactyl/panel#3947] opened 2022-02-08 11:11 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Filter server by name, node or by usage (CPU/RAM)

### Describe the solution you'd like.

Something like that:

![image](https://user-images.githubusercontent.com/17381066/152975366-19062f64-1bab-493f-8a6a-5b143418fcbf.png)

**Comment by trenutoo** [comment] 2022-02-08 11:59
There's already a search on the top of the panel. It doesn't filter search by usage though, sounds weird.

**Comment by Elikill58** [comment] 2022-02-08 12:08
Oh yes, sorry I didn't see it.
Also, for the filter per usage, I understand it can be weird, but it can be to see if a server take too many usage what it should be, and see possible issue

**Comment by trenutoo** [comment] 2022-02-08 12:11
Search is for a string/text. What you are asking for is sorting the servers, which would be duplicate of #498

**Closed as completed** 2022-02-08 12:13 UTC
