### ISSUE TITLE
API egg support

### ISSUE THREAD

**Issue by Danieljunek17** [pterodactyl/panel#3517] opened 2021-08-03 18:32 UTC
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to see a way to fetch eggs more easly from a server right now it is very hard to see which egg a certain server has

### Describe the solution you'd like.

Basicly add to the `Server` object a Integer eggID in:

https://github.com/pterodactyl/panel/blob/develop/resources/scripts/api/server/getServer.ts

**Comment by FoksVHox** [comment] 2021-08-04 21:18
Isn't this a duplicate of  #2864, or am I missing something?

**Comment by Danieljunek17** [comment] 2021-08-04 21:21
> Isn't this a duplicate of #2864, or am I missing something?

I don't think so it will probaly statisfy my problem if they fix it but they ask to post the eggId which can be done directly through the database skipping my method of fetching it

**Comment by trenutoo** [comment] 2021-08-05 10:10
> Isn't this a duplicate of #2864, or am I missing something?

#2864 is requesting completely new endpoints for importing eggs using the API. 

@Danieljunek17 You can accomplish this already with `?include=egg` unless I misunderstood your request.

`https://pterodactyl.file.properties/api/client/servers/e903fae4?include=egg`

```
            "egg": {
                "object": "egg",
                "attributes": {
                    "uuid": "e903fae4-6b67-4fe1-a0c6-a7973ca9830d",
                    "name": "Paper"
                }
            }
```            
![image](https://user-images.githubusercontent.com/10975908/128333024-21b443da-f49f-499d-aae2-d250ce15bd8a.png)

**Comment by Danieljunek17** [comment] 2021-08-05 10:26
yh that is maybe possible but not when using it in the internal file structure from pterodactyl

and further more I wanted the egg ID not the egg in itself

**Comment by DaneEveritt** [comment] 2021-08-05 22:31
You won't get the egg ID from the client ID. It is purposefully not exposed, you can edit the internal structure to include the egg if you need it, only the details necessary for the front-end to function as currently exists are included.

**Closed as completed by DaneEveritt** 2021-08-05 22:31 UTC
