### ISSUE TITLE
Copy Server from Node 1 to Node X

### ISSUE THREAD

**Issue by ScriptVortexDE** [pterodactyl/panel#4908] opened 2023-10-29 20:20 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hello, It would be cool if there is a way to copy a server that you have created 1 to 1.

In other words I have on node 1 a server with 
200%, 2GB RAM, 20GB Space, 1 IP, 2 Ports

And then I can copy it to Node 2, and then a popup comes up where I have to select the IPs and the ports.

### Describe the solution you'd like.

it would be easier for hosting, so that if a customer has problems, you can simply copy them for testing to find the error without disabling the customer's server.

**Comment by matthewpi** [comment] 2023-10-29 20:26
Duplicate of https://github.com/pterodactyl/panel/issues/2148

**Closed as not planned by matthewpi** 2023-10-29 20:26 UTC
