### ISSUE TITLE
IPv6 Support or seperate controller / Panel proxy

### ISSUE THREAD

**Issue by PaulaBras** [pterodactyl/panel#2229] opened 2020-08-07 22:13 UTC
Hello everybody.
I am forced to use IPV6. My servers are in a local network and can transmit to the outside world separately. However, due to the current possibilities, these are not possible to run the panel on a domain that can then reach the daemon in the internal network. If the panel is online (with SSL) then so must the daemon. I think it's a shame. Would it be possible to carry out this communication internally? Communication should then be proxied by the panel.

In the current setup I can only use the panel in local mode and that doesn't make sense for me anymore.

**Comment by DaneEveritt** [comment] 2020-08-18 02:37
Duplicate of https://github.com/pterodactyl/panel/issues/1778

**Closed by DaneEveritt** 2020-08-18 02:37 UTC
