### ISSUE TITLE
Suggestion - Allow a choice to sort servers alpha-numerically

### ISSUE THREAD

**Issue by Ma8ician** [pterodactyl/panel#3147] opened 2021-03-06 21:55 UTC
Hi there we manage 30 + MC servers on 6 Nodes on one panel, plus we have a second network where we host multiple networks.  A fervent prayer would be to allow the display sort order of the servers to be user selected. eg Alpha-numerically by name. by date created. etc.

Another awesome add to the server information would be to add a field to server information for classification of the server - (ties back into the above) we define our servers as production, test, development or Other - if we could sort and or filter by this "subsidiary field" it would make managing our network 10 x easier, with both of those suggestions.

**Comment by TrixterTheTux** [comment] 2021-03-06 21:57
Duplicate of #1439

**Closed as completed by TrixterTheTux** 2021-03-06 21:57 UTC
