### ISSUE TITLE
Wings file editing %## issue, files fail to rename/delete/move

### ISSUE THREAD

**Issue by Jake-Moore** [pterodactyl/panel#2974] opened 2021-01-04 22:53 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel (Wings)
* Version of Panel/Daemon: v1.2.0 Panel
* Server's OS: Ubuntu 18.04 LTS
* Your Computer's OS & Browser: Windows 10 Pro, Chrome

**Describe the bug**
Panel: PHP 7.4.13
Description: When editing a file using the Wings website, file names with " " and others i've found with "(" or ")" cannot be renamed, moved, or deleted
This includes files like "test1 copy.yml" or "test (1).jar"
When the rename menu is opened, those characters are replaced with %## for example: %20 or %28

**To Reproduce**
1. Create a file with any contents with a name containing a space, EX: "test test.yml"
2. Click on '...' and then rename
3. The name prompt should look something like "test%20test.yml"
4. Try to rename it to anything else, even after removing the "%20" and replacing it, it doesn't work

**Expected behavior**
The rename prompt shows %## instead of some characters, even when replaced that file doens't rename. No errors show and those files when deleted, renamed or moved don't change.

**Comment by tinyoverflow** [comment] 2021-01-05 00:09
Commit 3e65a2d05512da7c77c90d9f2768a3538f99f26e and pterodactyl/wings@73f1399e476fc11cf5c8b81ca94c55e7085ea684 changed some things related to encoding. As all of that worked fine in the previous release, it broke in 1.2.0 and I think it is related to these two commits. The rename request itself is sent properly to the panel and the panel also replies with a 204 No Content, implying that the rename was successful, at least from the panels perspective.

I want to append to this, that this also happens if you're trying to replace the encoded values (%##) with its proper values, it still doesn't work. The frontend sends it unencoded to the panel backend, as expected.

**Comment by matthewpi** [comment] 2021-01-05 03:55
I am not able to reproduce this on [feature/react-admin@`ed73f6a`](https://github.com/pterodactyl/panel/tree/ed73f6a020d260334ab277337d55b2599f64f4e0).  This has the latest changes from develop and doesn't have any modifications on the file manager.

I created a file named `test test` using the file manager itself, I then tried to rename the file and it showed `test test` and not `test%20test` like you are saying it would.  I even refreshed the entire page (this forces the refreshing of all files in the file manager) and then opened the rename modal and it still showed `test test` (instead of `test%20test`), I then tried renaming it and it worked properly.

**Comment by AnttiMK** [comment] 2021-01-05 04:37
I'm also able to reproduce with `Panel@1.2.0` and `Wings@1.2.0`. Unable to rename, delete or move files with spaces or parentheses.
![image](https://user-images.githubusercontent.com/13612979/103606781-f3ee6700-4f1f-11eb-9c63-1da543bd6d8a.png)

**Comment by matthewpi** [comment] 2021-01-05 04:49
Ah, this was fixed on `develop` by https://github.com/pterodactyl/panel/pull/2956 and https://github.com/pterodactyl/wings/pull/81

**Closed as completed by matthewpi** 2021-01-05 04:49 UTC
