### ISSUE TITLE
The "Server Owner Search" only searchs by email. No longer includes first or last names.

### ISSUE THREAD

**Issue by credomane** [pterodactyl/panel#2774] opened 2020-12-01 18:03 UTC
**Background (please complete the following information):**
* Panel or Daemon:  Panel
* Version of Panel/Daemon: 1.1.1
* Server's OS: Debian 10.6
* Your Computer's OS & Browser:  Win10/FF83 and Manjaro/FF83

**Describe the bug**
When creating a new server you have to specify a server owner. Before updating to 1.1.1 from 0.7 I could type "anything" into the search field for server owner and get results. Now with 1.1.1 I MUST type something that is in the client's email address. The clientfirst name and last name fields are no longer appear to be used in the search.

**To Reproduce**
1. Start making a new server in the panel.
2. Click in the "Server Owner" search field.
3. Type a client's first name
4. get "no results" for the expect client.
5. Type client's last name instead.
6. get "no results" again.
7. Finally try the client's email.
8. get the expected client.

**Expected behavior**
For it to work like it did before in 0.7 if I typed a client's first name or last name I got results.

**Other observations**
This problem also plagues the `/admin/users` page. Trying to search for a user by something other than email yields the same unexpected/incorrect results. Here the search seems to be explicitly apply a filter to only search email address if the URL bar is to be believed.

**Comment by DaneEveritt** [comment] 2020-12-01 18:29
Please double check with the search field before opening issues, duplicate of https://github.com/pterodactyl/panel/issues/2366. :)

**Closed as completed by DaneEveritt** 2020-12-01 18:29 UTC

**Comment by credomane** [comment] 2020-12-01 19:47
> Please double check with the search field before opening issues

I did do that and found a closed ticket. The same closed ticket you linked even. This ticket contains a bugfix in it for this search issue. A ticket made during the 1.0.0 release *candidates* stage and closed during that same stage. Why would I not assume this fix had been included in the code base already since the ticket was closed? When looking at the source for the 1.1.1 branch the fix does appear to be in the code base but the problem still persists or maybe it reappeared after getting fixed? Bugs to love nothing more than to reappear in unexpected ways after all. I didn't have to make a new server during 1.0.x so I dunno if the problem existed in this version or not. I just know it worked in 0.7.x but doesn't in 1.1.1. After looking around for a while I decided it was a new occurrence of a resolved bug/closed ticket.

If the original issue is still a current and active issue why is it closed? It gives people like me that do the leg work to avoid making duplicates the wrong impression that it is a new problem.

**Comment by matthewpi** [comment] 2020-12-01 19:53
> > Please double check with the search field before opening issues
> 
> I did do that and found a closed ticket. The same closed ticket you linked even. This ticket contains a bugfix in it for this search issue. A ticket made during the 1.0.0 release _candidates_ stage and closed during that same stage. Why would I not assume this fix had been included in the code base already since the ticket was closed? When looking at the source for the 1.1.1 branch the fix does appear to be in the code base but the problem still persists or maybe it reappeared after getting fixed? Bugs to love nothing more than to reappear in unexpected ways after all. I didn't have to make a new server during 1.0.x so I dunno if the problem existed in this version or not. I just know it worked in 0.7.x but doesn't in 1.1.1. After looking around for a while I decided it was a new occurrence of a resolved bug/closed ticket.
> 
> If the original issue is still a current and active issue why is it closed? It gives people like me that do the leg work to avoid making duplicates the wrong impression that it is a new problem.

--

> This is intentional for the time being and will be addressed by the admin area re-write
https://github.com/pterodactyl/panel/issues/2366#issuecomment-695846582

**Comment by credomane** [comment] 2020-12-01 19:56
>When looking at the source for the 1.1.1 branch the fix does appear to be in the code base.

**Comment by DaneEveritt** [comment] 2020-12-01 20:59
It is not in the code base, I am unsure what specifically you are looking at, but it still only searches via email.

https://github.com/pterodactyl/panel/blob/develop/public/themes/pterodactyl/js/admin/new-server.js#L168-L173

**Comment by credomane** [comment] 2020-12-01 21:55
The issue you linked to contains a PR with a change to include an expanded filter list. This expanded filter list is now in the code base here:

https://github.com/pterodactyl/panel/blob/2b5d5c9e5553e0bd04c9886f4df9f793d29d7c52/app/Http/Controllers/Admin/UserController.php#L87-L97

As you have linked it seems this fix/change has yet to be done on the frontend side.
