### ISSUE TITLE
Error when migrating setup data into DB

### ISSUE THREAD

**Issue by ziferr** [pterodactyl/panel#5068] opened 2024-04-10 16:20 UTC
### Current Behavior

**Background:**
- Ubuntu 20.04-standard LXC
- Host running PROXMOX
- fresh install

Used the guide on [here](https://pterodactyl.io/panel/1.0/getting_started.html) to setup Pterodactyl. Got to step "Database Setup" where it then spat out that error.

![error_ptero](https://github.com/pterodactyl/panel/assets/83457993/878105ac-2463-4327-9d1b-499121617e63)

### Expected Behavior

Should migrate all the set up config data from the steps before, no?

### Steps to Reproduce

Don't actually know, just followed the guide, used Proxmox CT template

 _ubuntu-20.04-standard_20.04-1_amd64.tar.gz_ 

Is Ubuntu Focal (standard) ...

### Panel Version

1.11

### Wings Version

1.11

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [ ] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by yesBad** [comment] 2024-04-10 16:22
As per Discord;

Change `character-set-collations` in `/etc/mysql/mariadb.conf.d/50-server.cnf` to `utf8mb4=utf8mb4_general_ci`.
Restart MariaDB after changing the config file.

Please don't lie in the checklist next time, this has been posted & fixed many times in here & in Discord.

**Comment by Boy132** [comment] 2024-04-10 16:25
Duplicate of #5010

And yes, please actually check the [Discord](https://discord.gg/pterodactyl) first...

**Closed as completed** 2024-04-10 16:25 UTC
