### ISSUE TITLE
Crash detection disabled (But no config for it)

### ISSUE THREAD

**Issue by IvMisticos** [pterodactyl/panel#3617] opened 2021-09-13 11:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When a server crashes, all panel says is `Aborting automatic restart, crash detection is disabled for this instance.`

### Expected Behavior

Restart the server after a crash just like previous panel and wings versions did.

### Steps to Reproduce

Update wings and panel to latest version.

### Panel Version

1.6.0

### Wings Version

1.5.0

**Comment by IvMisticos** [comment] 2021-09-13 11:50
The issue is that there is no configuration in panel or anything for it, and in the code I do not see any mentions of `crash_detection_enabled` either panel side - only wings. So, how does one fix the issue? The behavior changed after the update without any configuration changes.

**Comment by parkervcp** [comment] 2021-09-13 12:06
https://pterodactyl.io/wings/1.0/configuration.html#other-values

You want to set the value of `detect_clean_exit_as_crash` to `true`

**Comment by trenutoo** [comment] 2021-09-13 12:14
> https://pterodactyl.io/wings/1.0/configuration.html#other-values
> 
> You want to set the value of `detect_clean_exit_as_crash` to `true`

No, that's not the same.  `detect_clean_exit_as_crash` marks the server as crashed if it's stopped without user interaction, e.g., not pressing the stop button. 

This issue is about crash detection not being enabled to automatically restart crashed servers, which was enabled by default in 1.4.7 and was removed in the 1.5.0 `server/update.go` code refactor. I can confirm that this is indeed a valid bug, as the boolean value is not passed from anywhere right now.

**Comment by IvMisticos** [comment] 2021-09-13 12:21
> 
> 
> https://pterodactyl.io/wings/1.0/configuration.html#other-values
> 
> You want to set the value of `detect_clean_exit_as_crash` to `true`

It is set to true and was set before, always worked but after the update it says this now. There is some new per server option wings side but panel never sends it ig.

**Comment by nackerr** [comment] 2021-09-13 14:30
> 
> 
> https://pterodactyl.io/wings/1.0/configuration.html#other-values
> 
> You want to set the value of `detect_clean_exit_as_crash` to `true`

I can also confirm this is not the fix. Having same issues as Misticos.

**Comment by joshcannotcode** [comment] 2021-09-13 14:57
Having the same issue, can hopefully be fixed soon as server /restart command isn't working for clients.

**Comment by quantiom** [comment] 2021-09-13 15:36
I am also having the same issue.

**Comment by Permanently** [comment] 2021-09-13 20:31
Has only started happening since the newest update. Not sure what would've altered the behaviour in the first place.

**Comment by nackerr** [comment] 2021-09-13 20:35
The issue was fixed with SoftwareNoob’s PR. Just needs to be merged in. You can recompile the binary yourself if you need it immediately. I did this and it’s working fine.

**Closed as completed** 2021-09-13 21:04 UTC
