### ISSUE TITLE
The FQDN or IP address provided does not resolve to a valid IP address.

### ISSUE THREAD

**Issue by AokoAsami199** [pterodactyl/panel#4422] opened 2022-10-10 15:27 UTC
### Current Behavior

I'm in the process of setting up the panel and creating node. When I entered the Fully Qualified Domain Name step, I entered the IP as 20.235.95.18 and ticked the Use HTTP Connection box in the Communicate Over SSL section. When I click to confirm node creation, it gives the following error: The FQDN or IP address provided does not resolve to a valid IP address. I need help !!!

### Expected Behavior

I'm in the process of setting up the panel and creating node. When I entered the Fully Qualified Domain Name step, I entered the IP as 20.235.95.18 and ticked the Use HTTP Connection box in the Communicate Over SSL section. When I click to confirm node creation, it gives the following error: The FQDN or IP address provided does not resolve to a valid IP address. I need help !!!

### Steps to Reproduce

I'm in the process of setting up the panel and creating node. When I entered the Fully Qualified Domain Name step, I entered the IP as 20.235.95.18 and ticked the Use HTTP Connection box in the Communicate Over SSL section. When I click to confirm node creation, it gives the following error: The FQDN or IP address provided does not resolve to a valid IP address. I need help !!!

### Panel Version

1.4.0

### Wings Version

1.4.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment] 2022-10-10 15:29
That is a old panel and wings version

**Comment by FoksVHox** [comment] 2022-10-10 15:50
This was fixed in #4409 which has been merged, but not released. It'll be released with the new version, which most likely will be `1.11`

**Comment by trenutoo** [comment] 2022-10-10 16:26
Duplicate of #4405 which is solved in the next release

**Closed as completed** 2022-10-10 16:27 UTC

**Comment by GamenHaaDee** [comment] 2023-12-14 15:22
I have this problem in the newest version.

**Comment by QuintenQVD0** [comment] 2023-12-14 15:30
> I have this problem in the newest version.

Not panel related, and do not comment on old issues, come to the discord for this
