### ISSUE TITLE
Permissions for friends/staff to admin menu / admin privileges 

### ISSUE THREAD

**Issue by JakeySuccessor** [pterodactyl/panel#2743] opened 2020-11-24 22:22 UTC
**Is your feature request related to a problem? Please describe.**
If I would like to give my friend access to be able to make servers but  I don't want him to have access to the node settings, user access, or access to giving admin permission which may cause chaos

**Describe the solution you'd like**
Make a system to give permissions to users like the permissions in sub-users but for the admin menu/permission to modify ex. server ram, CPU, and startup but no access to the node and users sections of the admin panel. 

It can be a system either like the sub-user system in pterodactyl or something similar to WHMCS permissions. Because currently, the admin is a very powerful privilege to provide to certain users.

**Comment by parkervcp** [comment] 2020-11-24 22:23
Duplicate of #279

**Closed as completed by parkervcp** 2020-11-24 22:23 UTC
