### ISSUE TITLE
Changing CPU Limit to 0, results in no change

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2044] opened 2020-05-19 06:24 UTC
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon:  Beta 5
* Server's OS:  Ubuntu 18.04
* Your Computer's OS & Browser: Winblows 10 / Chrome

**Describe the bug**
Changing the CPU limit back to 0 results in it still using the old value

**To Reproduce**
1. Create a server with CPU limit != 0
2. Change limit to 0 for unlimited

**Expected behavior**
It to revert back to 0.

Value IS saved in the database and passed to wings as 0 in the container config.

**Comment by lflare** [comment] 2020-05-19 06:30
Got to add, this is completely bananas behavior, as setting the limit back to `-1` manually via `docker update {container} --cpu-quota -1` works as intended.

**Comment by Sir3lit** [comment] 2020-05-19 06:56
It should be noted, that restarting wings fixes the containers build, and unlimited is used.

**Comment by lflare** [comment] 2020-05-19 07:28
It should also be noted, that is only effective once. Subsequent resetting of quotas require restarting of wings again. Interesting.

**Comment by DaneEveritt** [comment] 2020-05-31 19:20
Yeah, also seeing this broken when updating a server that already has a limit of 0 to now have a limit. Nothing gets changed. 🤔

**Comment by DaneEveritt** [comment] 2020-05-31 19:42
Closed in https://github.com/pterodactyl/wings/commit/0ae286d617896152541dc14311298b4cb323257a

**Closed by DaneEveritt** 2020-05-31 19:42 UTC
Labels: 1.0.0-beta, Type: Bug
