### ISSUE TITLE
memory/cpu graphs stuck at 0

### ISSUE THREAD

**Issue by popcorn9499** [pterodactyl/panel#2756] opened 2020-11-27 00:24 UTC
**Background (please complete the following information):**
* Panel or Daemon: It appears on the web panel however it may be something with the daemon (I will explain further
* Version of Panel/Daemon: panel 1.1.1 daemon 1.1.1
* Server's OS: Panel: Ubuntu Server 18.04.5 4.15.0-124 Running apache 2.4.29 Daemon: Arch Linux 5.9.9-arch1-1
* Your Computer's OS & Browser: Windows 10 Google Chrome

**Describe the bug**
Panel memory/cpu usage graph in the console stuck at 0.

Please provide additional information too, depending on what you have issues with:
Panel: 
```
PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
```
Daemon: 
`Linux file-server-1 5.9.9-arch1-1 #1 SMP PREEMPT Wed, 18 Nov 2020 19:52:04 +0000 x86_64 GNU/Linux`
```
Server:
 Containers: 31
  Running: 11
  Paused: 0
  Stopped: 20
 Images: 174
 Server Version: 19.03.13-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c623d1b36f09f8ef6536a057bd658b3aa8632828.m
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.9.9-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.36GiB
 Name: file-server-1
 ID: (Some ID)
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
**To Reproduce**
1. Go to `Sever Console page` 
2. look at `Memory Usage` or `CPU Usage` 
3. See its stuck at 0%

After about 2 days or less this appears to occur. The solution is to restart wings. I honestly am not sure where the issue exactly lies but it is a little frusterating.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
I Expect the page to look something like [this](https://photos.popicraft.net/u/files/18.23.22-26.11.20.png) with the memory usage and cpu usage showing the process or container usage.

**Comment by GravityCube** [comment] 2020-11-27 23:36
I think this is a duplicate of #2695

**Comment by popcorn9499** [comment] 2020-11-28 04:34
Similar however It does show after a full system reboot. or a game server restart. it just sometimes randomly disappears

**Comment by DaneEveritt** [comment] 2021-01-10 20:41
Closing: lack of information.

**Closed as completed by DaneEveritt** 2021-01-10 20:41 UTC

**Comment by mind-overflow** [comment] 2021-08-13 15:54
@DaneEveritt what kind of information do you need? It would've been much more helpful if you said it instead of closing the issue. It was described as precisely as possible. I am having the same issue, and I have no clue what else I could say about this.

PS: In my case, the issue persists even after a wings restart and a full system reboot.

**Comment by trenutoo** [comment] 2021-08-13 17:38
> @DaneEveritt what kind of information do you need? It would've been much more helpful if you said it instead of closing the issue. It was described as precisely as possible. I am having the same issue, and I have no clue what else I could say about this.
> 
> PS: In my case, the issue persists even after a wings restart and a full system reboot.

Does `docker stats` return any data? The panel relies on Docker to provide the usage statistics. If they are not working for you, then the Docker version that you installed is wrong. This is a common issue with package manager/dockerd versions. 

Use the method provided in Wings install documentation to install the correct version.

**Comment by mind-overflow** [comment] 2021-08-13 21:38
> > @DaneEveritt what kind of information do you need? It would've been much more helpful if you said it instead of closing the issue. It was described as precisely as possible. I am having the same issue, and I have no clue what else I could say about this.
> > PS: In my case, the issue persists even after a wings restart and a full system reboot.
> 
> Does `docker stats` return any data? The panel relies on Docker to provide the usage statistics. If they are not working for you, then the Docker version that you installed is wrong. This is a common issue with package manager/dockerd versions.
> 
> Use the method provided in Wings install documentation to install the correct version.

Thanks, this was actually very helpful!
Yes, if I type `docker stats`, it returns a lot of things.
```
CONTAINER ID   NAME                                    CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
5be0a3a21206   c5035006-9c11-439d-8f49-1ea20e7973cd    0.00%     0B / 0B               0.00%     0B / 0B           0B / 0B           0
eed5e73bf0a7   gitea                                   0.24%     156.3MiB / 7.775GiB   1.96%     107MB / 205MB     189MB / 262kB     19
2c8b7638e4db   gitea_db_1                              0.13%     216.9MiB / 7.775GiB   2.72%     26.5MB / 105MB    29.1MB / 13.3MB   34
65ac5386f8a2   grafana_db_1                            1.01%     204.8MiB / 7.775GiB   2.57%     1.95MB / 13.8MB   46.1MB / 21.1MB   29
```

The list goes on with a bunch of other containers. However, I don't see anything related to pterodactyl indeed. I'll look into the wings documentation, thanks!

**Comment by parkervcp** [comment] 2021-08-13 23:59
Docker is returning 0 on all stats. So this isn't so much a panel bug but a docker bug.

```
5be0a3a21206   c5035006-9c11-439d-8f49-1ea20e7973cd    0.00%     0B / 0B               0.00%     0B / 0B           0B / 0B           0
```

**Comment by mind-overflow** [comment] 2021-08-14 12:32
> Docker is returning 0 on all stats. So this isn't so much a panel bug but a docker bug.
> 
> ```
> 5be0a3a21206   c5035006-9c11-439d-8f49-1ea20e7973cd    0.00%     0B / 0B               0.00%     0B / 0B           0B / 0B           0
> ```

Oh, you're right! I didn't realize container 5be0a3a21206 was actually pterodactyl. Indeed, I have now checked every container for every server, and they all return 0% usage. I'll have to look deeper into it... Also, apparently, upgrading from docker 20.10.2 to 20.10.8 did not fix the issue. Do you have any suggestion?

I really appreciate your help. Thank you!

**Comment by trenutoo** [comment] 2021-08-14 13:07
This is a common issue when you install the wrong docker version using the distro package manager/snap. Reinstall using the method provided in the Wings install documentation

**Comment by mind-overflow** [comment] 2021-08-14 13:14
@Software-Noob I'm sorry if I sound dumb, but I have looked at the Wings [installation docs](https://pterodactyl.io/wings/1.0/installing.html#installing-docker) and it doesn't say much, except for:
  
> ## Installing Docker
> For a quick install of Docker CE, you can execute the command below:
> 
> `curl -sSL https://get.docker.com/ | CHANNEL=stable bash`
>   
> If you would rather do a manual installation, please reference the official Docker documentation for how to install Docker CE on your server. Some quick links are listed below for commonly supported systems.
> 
> - [Ubuntu](https://docs.docker.com/engine/install/ubuntu/)
> - CentOS
> - Debian
  
Which simply installs the latest officially available version. Given that I just upgraded to 20.10.8, and the latest one was 20.10.2 when I installed Pterodactyl, I don't see why it would be an issue.
  
PS: I have installed docker using the official repo (so, not by using this command, but by using the linked guide on that very same page, for [Ubuntu](https://docs.docker.com/engine/install/ubuntu/)), so I'm not using the default distro one.

**Comment by mind-overflow** [comment] 2021-08-14 13:26
Update: apparently, reinstalling the servers (from the web interface) fixed the issue. I really can't understand why, but it works now. Thanks for all the help and support!

**Comment by ShreshthTiwari** [comment] 2022-04-14 10:17
https://github.com/pterodactyl/panel/issues/3999#issuecomment-1065855097
