### ISSUE TITLE
Admins can't add quotations to client server variables but clients can

### ISSUE THREAD

**Issue by Nexxed** [Pterodactyl/Panel#752] opened 2017-11-10 23:48 UTC
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.6.4

The panel allows the clients to add quotations (") to their variables and save them without having them being removed. Meanwhile, administrator attempts to do the same results in them being completely removed. Furthermore, quotations get removed from the startup command which makes it practically impossible to make commands like `+hostname "My hostname"` as it results in `+hostname My hostname` thus setting the hostname to just "My".

**Comment by DaneEveritt** [comment] 2017-11-10 23:51
Duplicate of #721

**Closed by DaneEveritt** 2017-11-10 23:51 UTC
