### ISSUE TITLE
Integration with phpMyAdmin

### ISSUE THREAD

**Issue by hinakumo** [pterodactyl/panel#3109] opened 2021-02-21 11:29 UTC
**Is your feature request related to a problem? Please describe.**
To simplify the management of MySQL databases, you can use phpMyAdmin, but at the moment there is no way in the panel to create a button to go to phpMyAdmin in the client side. I would like to be able to add a "Go to phpMyAdmin" button on the client side that would automatically log in there.

**Describe the solution you'd like**
I would like to be able to bind a link to phpMyAdmin for each MySQL host in the admin panel, like this:
![brave_vCVh0nvUJf](https://user-images.githubusercontent.com/47789168/108623182-a2a62280-744e-11eb-92e5-fe3691f4d442.png)

**Describe alternatives you've considered**
This feature should be optional because not everyone uses phpMyAdmin.

**Additional context**
I don't know English well, so there may be inaccuracies in translation.

**Comment by schrej** [comment] 2021-02-22 11:07
duplicate of #1170

**Closed as completed by schrej** 2021-02-22 11:07 UTC
