### ISSUE TITLE
0.4.0 daemon, unable to create server & starting servers stuck in 'starting'

### ISSUE THREAD

**Issue by digitronics** [Pterodactyl/Panel#435] opened 2017-05-15 07:43 UTC
This is from an upgrade from `0.5` to `0.6`, the panel is working fine. But having issues with the daemon.
I am unable to create servers, daemon wont create the docker containers. With the starting issue, the servers will start up, but will stay in the `starting` phase. The servers boot and you can join them. But the panel/daemon reports them still starting. Only using/tested with vanilla Minecraft servers. 

Daemon logs did pop up an error:
```
TypeError: Cannot read property 'done' of undefined
    at Async.parallel (/srv/daemon/src/services/index.js:177:57)
    at /srv/daemon/node_modules/async/dist/async.js:3830:24
    at eachOfArrayLike (/srv/daemon/node_modules/async/dist/async.js:1003:9)
    at eachOf (/srv/daemon/node_modules/async/dist/async.js:1051:5)
    at _parallel (/srv/daemon/node_modules/async/dist/async.js:3829:5)
    at Object.parallelLimit [as parallel] (/srv/daemon/node_modules/async/dist/async.js:3912:5)
    at Service.onConsole (/srv/daemon/src/services/index.js:147:15)
    at Service.onConsole (/srv/daemon/src/services/minecraft/index.js:34:22)
    at Server.output (/srv/daemon/src/controllers/server.js:347:22)
    at Carrier.carry.data (/srv/daemon/src/controllers/docker.js:225:29)
```

**uname -a:**

```
Linux ns543214.ip-144-217-11.net 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
````

**php -v:**
```
PHP 7.1.5-1+deb.sury.org~xenial+1 (cli) (built: May 11 2017 14:07:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.5-1+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
```

**docker info:**
```
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 6
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 65
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-77-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.07GiB
Name: ns543214.ip-144-217-11.net
ID: 35B2:P2H2:HART:XPGS:VHF3:RVPN:ALKN:ARJH:MBKE:NEOA:GBAK:X4SQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by DaneEveritt** [comment] 2017-05-25 01:50
This appears to be a duplicate of #443, however it can read `startup`, but not the `done` property.

Is this a custom service?

**Closed** 2017-05-25 01:52 UTC
Labels: + daemon, investigating
