### ISSUE TITLE
Suspended servers ram counts to the allocated ram in the node's page

### ISSUE THREAD

**Issue by Kroffie** [pterodactyl/panel#4013] opened 2022-03-19 19:19 UTC
### Current Behavior

Currently if you look into the nodes overview you see the ram allocated with suspended servers added to the total.

### Expected Behavior

The servers ram will not be displayed in the total ram. So you can see how much ram is available for new servers. Because you might only want to use a suspended server to save the files.

### Steps to Reproduce

1. Create a server (specs don't matter).
2. See how much ram is allocated in the node viewer.
3. Suspend the said server.
4. See how much ram is allocated in the node viewer. It should not have changed.

### Panel Version

1.7.0

### Wings Version

1.6.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment] 2022-03-19 19:31
Pretty sure this is intended as suspended servers still exist on the node.  If you provision a new server to the node and later unsuspend the server you may have exceeded the allocation limit on the node.  While this might not be the behaviour you want, it's most likely intended and not a bug.  If you would like this behaviour tweaked you will most likely have to do it yourself as I don't intend on implementing an option to toggle this behaviour.

Going to close this for now, if this behaviour is indeed unexpected then it will be re-opened.

**Closed as completed by matthewpi** 2022-03-19 19:31 UTC

**Comment by Kroffie** [comment] 2022-03-19 19:33
Ah oke, Mabey make two bars then?
