### ISSUE TITLE
Server status request through api call

### ISSUE THREAD

**Issue by JayJay1989** [pterodactyl/panel#1286] opened 2018-08-14 08:53 UTC
**Is your feature request related to a problem? Please describe.**
when a json request is done with any api key to "http://domain.ext/status/identifier", the result is 'Unauthenticated'

**Describe the solution you'd like**
when a request is done with an admin api key, get the results

**Describe alternatives you've considered**
tried with account & application api key

**Additional context**
 `{
    "error": "Unauthenticated."
}`

**Comment by lancepioch** [comment] 2018-08-14 18:57
I've got multiple people that've confirmed that the api keys work on the latest Panel version. Please update your Panel to the latest version and try again. If it still isn't working for you on the latest Panel version, please visit our Discord for free support.

I'm closing the issue because it's a problem with your setup and not the software, thanks again.

**Closed by lancepioch** 2018-08-14 18:57 UTC

**Comment by JayJay1989** [comment] 2018-08-14 18:59
You are running Pterodactyl Panel version 0.7.9. Your panel is up-to-date!
not a panel issue

**Comment by DaneEveritt** [comment] 2018-08-14 22:14
Thats because you're trying to access an endpoint that isn't part of the API. Server status is returned when you request server information already in the API.

**Comment by JayJay1989** [comment] 2018-08-15 18:44
and how do i get it?
the details i get from the api doesnt include online/offline status...

**Comment by DaneEveritt** [comment] 2018-08-15 20:12
Sorry, its a different endpoint. https://github.com/pterodactyl/panel/blob/develop/routes/api-client.php#L25
