### ISSUE TITLE
Unzippping large files results in error but still completes

### ISSUE THREAD

**Issue by bizzlebazzle** [pterodactyl/panel#1207] opened 2018-06-20 16:36 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: latest (Panel 7.7.0 , Daemon 0.5.6
* Server's OS: Ubuntu 16.04.04
* Your Computer's OS & Browser: Win 10, Chrome 

**Describe the bug**
When attempting to unzip a large zip file (in my case a minecraft modpack) the panel will give the error "decompression of the file exited with code 2 signal null" https://i.imgur.com/GoXt6ds.png

Despite this error the zip file will actually be extracted perfectly fine and is usable afterwards, I'm assuming that there must be some sort of a timeout happening in the panel that makes it assume that the extraction has failed?

**To Reproduce**
1. Upload a "large" zip file (200mb+)
2. Right click in file manager and decompress
3. Receive error
4. Wait a little and extraction sucessfully completes anyway

**Expected behavior**
No error message when files are successfully extracted.

**Comment by omisacma** [comment] 2019-04-09 21:13
Same problem

**Comment by Lucavon** [comment] 2019-05-18 14:52
Still facing this issue. I can provide a copy of an archive that causes this error, if necessary.

**Comment by lancepioch** [comment] 2019-05-22 20:39
> Still facing this issue. I can provide a copy of an archive that causes this error, if necessary.

@Lucavon If you could provide a copy of an archive file that consistently causes this issue but at the smallest size possible, that would be much appreciated, thank you!

**Comment by Lucavon** [comment] 2019-05-22 21:03
@lancepioch I just attempted to decompress the same file that caused this issue last time, but this time it didn't happen. It appears like this issue is not consistently reproducible.

If you want to try it anyway, here's the file I used: https://v.lucavon.de/world20180407.tar (125 MB)

**Comment by DaneEveritt** [comment] 2019-05-24 18:22
I'm guessing the network request times out. Don't really feel like addressing in the current iteration of the panel, but will look into it for the new daemon/panel combo.

**Comment by DaneEveritt** [comment] 2020-07-12 17:52
Closing this out as the new version uses completely new code and logic to do all of this. We can create a new issue if it crops up in this version in the future.

**Closed by DaneEveritt** 2020-07-12 17:52 UTC
Labels: bug 🐛

**Comment by lucasryw** [comment] 2020-10-21 14:31
I'm having the exact same issue with v0.7.19

**Comment by DaneEveritt** [comment] 2020-10-21 15:12
Then upgrade to 1.0. 👍

**Comment by lucasryw** [comment] 2020-10-21 16:01
well, I can't because of the host. I didn't know 0.7 was that old, sorry. but I'll have to use that way. will I have problems/issues with the files using the panel that way? thank you.
