### ISSUE TITLE
Major functionality issue in 6.2: Users cannot edit startup variables

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#509] opened 2017-06-22 19:46 UTC
I upgraded from 6.0 to 6.2 yesterday and since that upgrade users are no longer able to access the Startup Configuration page. I can't confirm whether this is widespread or specific to only some environments, though another user also confirmed the same issue when discussed on Discord.

FWIW, modifying startup commands from the admin section works just fine.

**Comment by xyeLz** [comment] 2017-06-22 20:01
Edit: This may be directly related to #505 but I'm not sure what version he's running on.

**Comment by DaneEveritt** [comment] 2017-06-22 22:26
Can you provide any other details? Can't access because of an error, or some other reason? Any logs?

**Comment by xyeLz** [comment] 2017-06-23 00:37
```[2017-06-22 15:48:46] production.ERROR: ErrorException: Trying to get property of non-object in /efs1/var/www/html/pterodactyl/storage/framework/views/d2fb4333ecc215a90ca2ed6bf6b86de52b677cd1.php:42

Next ErrorException: Trying to get property of non-object (View: /efs1/var/www/html/pterodactyl/resources/themes/pterodactyl/server/settings/startup.blade.php) in /efs1/var/www/html/pterodactyl/storage/framework/views/d2fb4333ecc215a90ca2ed6bf6b86de52b677cd1.php:42

```

**Comment by DaneEveritt** [comment] 2017-06-23 03:17
Gotcha, thanks for the info, I will look into it.

**Comment by DaneEveritt** [comment] 2017-06-29 01:17
This is a duplicate of #505, closing and moving discussion to that issue. 👍

**Closed by DaneEveritt** 2017-06-29 01:17 UTC
Labels: bug
