### ISSUE TITLE
Ability to sort container/server orders

### ISSUE THREAD

**Issue by Pendred** [pterodactyl/panel#3966] opened 2022-02-14 12:37 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The ability to set the order that your containers appear on. Right now it's based on when it was made, so if I have 2 containers that are similar, but I make the second one after a bunch of other ones, it appears at the bottom. Would be extremely helpful to be able to change the order they appear in.

### Describe the solution you'd like.

Just being able to drag the container list and order it how you see fit.

**Comment by parkervcp** [comment] 2022-02-14 12:47
Pretty sure this is a duplicate of #498

**Closed as completed** 2022-02-14 13:32 UTC

**Comment by Pendred** [comment] 2022-02-14 15:58
Almost 5 years have passed since it was requested, this is in my opinion such a necessary feature. 

**If anyone reading this has the technical know-how to create it, I would be more than happy to offer payment to create this not only for myself but for everybody. Please add me on Discord gamer#5678 if this is something that interests you.**

**Comment by gmijo47** [comment] 2022-04-23 14:53
Definitely necessary, in case you have over 100 servers some categorization is really necessary, like @Pendred said more than 5 years have passed, and guess what, nothing 😢
