### ISSUE TITLE
(Feature Request) User Service Reinstall (Multiple installation scripts)

### ISSUE THREAD

**Issue by yerktoyn** [Pterodactyl/Panel#626] opened 2017-09-15 07:33 UTC
For example Minecraft has several server cores, Bukkit, Vanilla, Spigot, PaperSpigot and others.
I would very much like that the user could easily select the server core and version necessary for him.

To reinstall, the user navigates to the main page of the server and presses "Reinstall", then selects from the drop-down list the possible options that were added by the panel administrator. After that, all files are deleted and the necessary installation script is launched.

**Comment by yerktoyn** [comment] 2017-09-15 07:47
Very similar to:
https://github.com/Pterodactyl/Panel/issues/597

**Comment by schrej** [comment] 2017-09-15 07:59
rather a duplicate of #597

**Closed by schrej** 2017-09-15 07:59 UTC
