### ISSUE TITLE
Panel Start / Stop buttons won't work when Container could not be created

### ISSUE THREAD

**Issue by fabm3n** [pterodactyl/panel#2066] opened 2020-05-25 13:45 UTC
**Background:**
* Panel or Daemon: Daemon and / or Panel
* Version of Panel/Daemon: Panel beta4, Dameon beta5
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Win 10 Pro 1909 Build 18363.836
* Your Computer's Browser: Google Chrome 81.0.4044.138
* Dameon uname -a: Linux leo 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Daemon docker info: 

> Client:
>  Debug Mode: false
> 
> Server:
>  Containers: 2
>   Running: 0
>   Paused: 0
>   Stopped: 2
>  Images: 12
>  Server Version: 19.03.9
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
>  runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
>  init version: fec3683
>  Security Options:
>   apparmor
>   seccomp
>    Profile: default
>  Kernel Version: 5.4.0-31-generic
>  Operating System: Ubuntu 20.04 LTS
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 2
>  Total Memory: 7.59GiB
>  Name: leo
>  ID: UKQH:AQFM:AKU2:AAF5:QUII:BPPD:REUL:DPSO:CIIM:VR2B:MI5O:XKBY
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
> 
> WARNING: No swap limit support

**Describe the bug**
If a container cannot be created, the Start and Stop buttons in the Panel have no function anymore. No panel logs are created.

From the Wings Log when the Container can't be created caused by iptables:
https://pastebin.com/KyFjysrj

From the Wings Log when the Container can't be created caused by local image:
https://pastebin.com/TXbjTakX
This is the Emyrion Egg from Phenom: https://git.phenomic.net/PHENOM/Pterodactyl-Egg-Empyrion
The Image is buidl locally, but Wings tries to load it from a repository.

**To Reproduce**
I can only reproduce it with the Empyrion Server, because it fails everytime.

1. Start the Server
That's it, now the buttons doesn't work anymore :D

**Expected behavior**
The Panel and Daemon will handle these crashes better, so it's marked as crashed.
Also the Dameon should be able to load local images (but that needs a other issue right?)

**Comment by thermaldrg** [comment] 2020-05-25 14:32
I believe this issue relates to this one: https://github.com/pterodactyl/panel/issues/2049

**Comment by fabm3n** [comment] 2020-05-25 14:39
I'm not sure because Dane wrote something about Websockets, but if i open the same server in another browser, it still doesn't work. Or did he mean the WS between panel and wings?

**Comment by thermaldrg** [comment] 2020-05-25 15:11
> I'm not sure because Dane wrote something about Websockets, but if i open the same server in another browser, it still doesn't work. Or did he mean the WS between panel and wings?

When you view the server on the panel you connect to a wings websocket to get information such as server status, resource usage and console logs, that websocket seems to die when the server has any issues with installing or starting.

**Comment by fabm3n** [comment] 2020-05-26 06:50
Okay, so it sound's like a dupe, i will close and wait until #2049 is closed and check it then again.

**Comment by DaneEveritt** [comment] 2020-05-26 14:58
I'll close out duplicates as I find them, better to have two that we're on the fence about being duplicates than closing one thinking its a dupe and it turns out to not be. :)

**Comment by IAmLythixIAmDumb** [comment] 2020-05-26 15:23
> I'll close out duplicates as I find them, better to have two that we're on the fence about being duplicates than closing one thinking its a dupe and it turns out to not be. :)

Good thinking

**Comment by fabm3n** [comment] 2020-05-27 18:23
Okay 👍

**Comment by DaneEveritt** [comment] 2020-05-31 17:51
I think this was caused by the fix in https://github.com/pterodactyl/wings/commit/82ffb9804d40e16a636ca18cd867d7fae10df436 which was locking up the websocket whenever it would attempt to send an error down the line. Closing this for now, let's re-open it if the new release doesn't fix it.

**Closed by DaneEveritt** 2020-05-31 17:51 UTC
Labels: 1.0.0-beta, Go Daemon, Type: Bug
