### ISSUE TITLE
Servers do not stop after suspending

### ISSUE THREAD

**Issue by ruscalworld** [pterodactyl/panel#3671] opened 2021-10-07 13:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Servers just does not stop when they are suspended via panel

### Expected Behavior

Server stops when it is suspended

### Steps to Reproduce

1. Create a server in panel. I've tested with Paper 1.12.2 server.
2. Start it and wait until it starts completely.
3. Suspend it from "Manage" tab.
4. See that server is not stopped and you still have control on it if you haven't reloaded the page.

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

```bash
https://ptero.co/nifonamafu
https://bin.ptdl.co/omt0l/ (looks like I've tried to do something when wings was not running)
```

**Comment by matthewpi** [comment] 2021-10-07 13:44
Duplicate of #3639

**Closed as completed** 2021-10-07 13:44 UTC
