### ISSUE TITLE
Dropdown Variable Type

### ISSUE THREAD

**Issue by tenten8401** [Pterodactyl/Panel#588] opened 2017-08-15 16:34 UTC
Title says it all basically.
Can we have a dropdown variable type?
Something that could be controlled by a script preferably too, like for example, a script to check the minecraft version updater and be able to select a minecraft version from the dropdown.

**Comment by DaneEveritt** [comment] 2017-08-16 01:11
Do you want more than text fields for environment variables basically?

**Comment by tenten8401** [comment] 2017-08-16 01:27
@DaneEveritt That would be correct.

**Comment by alukar4eg** [comment] 2017-08-16 06:51
@tenten8401 @DaneEveritt 

Like this post )) https://prnt.sc/g2w13o

**Comment by DaneEveritt** [comment] 2017-09-18 03:48
Duplicate of #570

**Closed by DaneEveritt** 2017-09-18 03:48 UTC
Labels: feature, priority: medium
