### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by Nzii3** [pterodactyl/panel#4606] opened 2022-12-11 15:02 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Folders where you can put servers into for organization, or a way to rearrange servers like a list.

### Describe the solution you'd like.

This can be used to find hosting servers faster.

**Comment by TrixterTheTux** [comment] 2022-12-11 15:05
Duplicate of #1439

**Closed as completed by TrixterTheTux** 2022-12-11 15:05 UTC
