### ISSUE TITLE
Importing Schedules

### ISSUE THREAD

**Issue by JoshJames04** [pterodactyl/panel#3103] opened 2021-02-19 15:06 UTC
**Is your feature request related to a problem? Please describe.**
I find creating the same schedule for multiple different servers very annoying and more time consuming than what it needs to be.

**Describe the solution you'd like**
If there was a way to have a "global schedule template" that can be imported in each server that you want to use it on.

**Describe alternatives you've considered**
Perhaps have "global schedules" that apply to all servers instead of having to import them

**Additional context**
An additional section in the node's settings could have settings for creating these global schedules with or without the ability to import them into specific servers. In each server's schedule tab could then be the option to use these global schedules or simply import them.

**Comment by DaneEveritt** [comment] 2021-02-19 16:17
Duplicate of #3010 which is a duplicate of #1346.

**Closed as completed by DaneEveritt** 2021-02-19 16:17 UTC
