### ISSUE TITLE
I would really like to know/have a way to tell which backup was taken by what server/user.

### ISSUE THREAD

**Issue by andy01745** [pterodactyl/panel#5043] opened 2024-03-25 20:49 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would really like to know/have a way to tell which backup was taken by what server/user. As sometimes in the past I have seen Pterodactyl leave old backups with no server there (Wasting space). At the moment there are just UUIDS of the backups with no way to know who is the owner of the backup. 

### Describe the solution you'd like.

I would really like to know/have a way to tell which backup was taken by what server/user.

### Additional context to this request.

All we see atm No way to know where the backup came from or who made it. With out extracting the backups

![image](https://github.com/pterodactyl/panel/assets/84942293/d39879e2-677e-4760-8f7d-140e98271364)

**Comment by matthewpi** [comment] 2024-03-25 20:51
Duplicate of https://github.com/pterodactyl/panel/issues/2594

**Closed as not planned by matthewpi** 2024-03-25 20:51 UTC
