### ISSUE TITLE
infinite loading console

### ISSUE THREAD

**Issue by Oberfail** [pterodactyl/panel#2027] opened 2020-05-13 18:01 UTC
**Background:**
Panel or Daemon: Panel
Version of Panel/Daemon: 1.0.0-beta.3
Server's OS: Ubuntu 20.04 LTS
Your Computer's OS & Browser: Windows 10 LTSC, Firefox 76.0.1 (64-Bit)

**Describe the bug**
Console is loading forever.

**To Reproduce**
1. Go to the Console of any Server
2. Click on 'Settings'
3. Click on 'Launch SFTP'
4. Click on anything in the new window, click on nothing, dosn't matter
5. Click back on 'Console'

**Expected behavior**
Console should load.

**Comment by Sir3lit** [comment] 2020-05-13 18:04
Any logs in the browsers console when you go back to the console page?

**Comment by Oberfail** [comment] 2020-05-13 18:09
None.

**Comment by Corenb** [comment] 2020-05-16 19:04
I already had this error, it seems to appear when we subusers are created on a previous beta and we update it to the latest version (beta 3 or/and 4).
To resolve this issue, I had to reset my subuser (remove the subuser from the server and set new permissions).

**Comment by Oberfail** [comment] 2020-05-16 21:17
No other Users / Subusers besides me, i'm the Administrator. Its a fresh install in an non production enviroment.

F5 "solves" the issue. But doing these steps again will lead to the same result prior.

**Comment by matthewpi** [comment] 2020-07-12 18:36
Cannot reproduce on [latest develop](https://github.com/pterodactyl/panel/commit/cf366be06c38a84b201fba5cffec4de1f7f9e47f).

**Comment by DaneEveritt** [comment] 2020-07-12 19:03
I've not run into this either, and I think we've fixed numerous different issues relating to the socket, so I'm going to close this out until we can verifiably reproduce the issue with logs.

**Closed by DaneEveritt** 2020-07-12 19:03 UTC
Labels: beta 🦈, bug 🐛

**Comment by Oberfail** [comment] 2020-11-18 21:16
Bug is still present on 1.1.1
https://youtu.be/NEYumIecmQg

**Comment by MystifiedSky** [comment] 2021-06-24 00:30
Bug still exists on latest version having the issue myself.

**Comment by Kolterdyx** [comment] 2023-08-02 09:43
Bug still exists on version 1.11.3
