### ISSUE TITLE
Forking and Templating for servers

### ISSUE THREAD

**Issue by ad1tya2** [pterodactyl/panel#3562] opened 2021-08-21 11:48 UTC
### Discussed in https://github.com/pterodactyl/panel/discussions/3561

<div type='discussions-op-text'>

<sup>Originally posted by **ad1tya2** August 21, 2021</sup>
I own a minecraft network and a lot of the times one of the things that Would help me a lot is the ability to use a template to create a server on top of which i will make changes, like github forking and Commits maybe, 
So basically there are base server templates which i can create and work on top of that, i should be able to create templates on top of templates too if needed, and then when i want i can just create an instance using the template and make the necessary changes.
For example if i needed to make a private gamemode then i can just use the template of the public gamemode and make small changes, and **the biggest part that would be useful is that When a template is updated so are all the servers based on that template**

Please take a look at this and let me know if this sounds good and if there is any prospect of this being put into pterodactyl,
Hoping for a positive reply 
:)</div>

**Comment by FoksVHox** [comment] 2021-08-21 16:40
Dupe of #2148

**Closed as completed** 2021-08-21 16:57 UTC
