### ISSUE TITLE
Missing Content-Length

### ISSUE THREAD

**Issue by daniel-skopek** [pterodactyl/panel#5041] opened 2024-03-22 17:02 UTC
### Current Behavior

When saving empty file via file editor, I get this error: `An error occurred on the remote host: Missing Content-Length. (request id: d7402f12-361f-425c-be9f-995b5df9cae1)`

### Expected Behavior

Empty file should be savable

### Steps to Reproduce

1. Open file
2. Remove all text to make empty file
3. Save file
4. You got the error

### Panel Version

1.11.5

### Wings Version

1.11.11

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment] 2024-03-22 17:16
Duplicate of https://github.com/pterodactyl/panel/issues/5038

**Closed as not planned by matthewpi** 2024-03-22 17:16 UTC
