### ISSUE TITLE
Panel file manager returns 403 on everything other than root directory

### ISSUE THREAD

**Issue by Telesphoreo** [pterodactyl/panel#2037] opened 2020-05-17 03:32 UTC
**Background (please complete the following information):**
* Panel or Daemon: Pterodactyl and Wings
* Version of Panel/Daemon: 1.0.0 beta 3 of panel and 1.0 beta 4 of wings
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 7 using Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
`PHP 7.4.6 (cli) (built: May 14 2020 10:03:35) ( NTS )`
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
uname -a: `Linux <redacted> 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
docker info:
```
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 1
  Paused: 0
  Stopped: 10
 Images: 3
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-29-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.59GiB
 Name: <redacted>
 ID: IWRC:2WM2:UEBP:ZS3Y:XUVS:FN5Z:63RZ:2AQT:Y4EE:GLXG:V2LZ:3UMC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**To Reproduce**
This was done using Minecraft (Paper).
When editing with the built in SFTP editor, you get error 403 on everything other than the root directory. I got these errors when moving server files from the old daemon data folder (on the stable pterodactyl) to the new daemon data folder (used for 1.0 beta 3). I thought this could've been an issue with the old servers having old permissions that changed in the beta, so I made a brand new server and let Pterodactyl handle all the permissions. It still returned 403 on a brand new server (this was me just going into the plugins folder, going to bStats and editing the config. Therefore, it's not an issue with server data as on the test server I let it handle everything on its own. I tried chowning it to pterodactyl:pterodactyl and pterodactyl:root (yes i used -R). i tried chmoding 644, 755, and 777, to no avail. Note that when I was moving data from the old daemon data to the new one, I created the new server using Pterodadctyl, and then moved the data using mv. I didn't move the actual server UUID folders themselves from the old panel version to the new one.

**Expected behavior**
The expected behavior is that you should be able to edit any files, whether they are in the root directory or not.

I did get an error in the console
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
bundle.be157ae4.js:1 Error: Request failed with status code 403
    at e.exports (bundle.be157ae4.js:1)
    at e.exports (bundle.be157ae4.js:1)
    at XMLHttpRequest.d.onreadystatechange (bundle.be157ae4.js:1)
(anonymous) @ bundle.be157ae4.js:1
```
I am not aware of any errors reporting on Wings

**Comment by parkervcp** [comment] 2020-05-17 03:34
You don't say what other folders you were trying to access.

**Comment by Telesphoreo** [comment] 2020-05-17 03:41
@parkervcp Anything other than the root directory of the server. I'm able to edit yml files in the root directory such as spigot.yml and paper.yml and server.properties just fine. If you go into any subdirectory, such as plugins, and into a plugin folder (bStats is the only one on a fresh install) and open up the bStats config.yml, you get error 403. It can be any folder, it will return error 403

**Comment by DaneEveritt** [comment] 2020-05-17 03:41
Can you include the specific URL from the network tab that was 403'ing? Seems more like a permissions issue local to the panel and not directly involving the daemon. The daemon process is able to access files regardless, it has root permissions and can access all of the files, most always the issues arise from the permissions being set funny by the daemon and processes not being able to access things.

The 403 isn't from the daemon, that's the panel saying you're not authorized correctly.

**Comment by Telesphoreo** [comment] 2020-05-17 03:43
@DaneEveritt you mean this? https://pterodactyl.telesphoreo.me/api/client/servers/bd9456ed-454b-4bfb-9fff-6e65838d140a/files/contents?file=%2Fplugins%2FbStats%2Fconfig.yml

And yes sorry, this was a bit misleading. SFTP does work. I was able to connect with FileZilla and edit files. It seems to only be with the built in file editor.

**Comment by DaneEveritt** [comment] 2020-05-17 04:11
Have you confirmed this still happens without your custom `.htaccess` rules?

**Comment by Telesphoreo** [comment] 2020-05-17 04:23
Yes, just tested it. Still gives the same error. Only difference is that now it's the generic 403 Forbidden error.

**Comment by parkervcp** [comment] 2020-05-17 14:04
Are you running apache or nginx?

**Comment by Telesphoreo** [comment] 2020-05-17 19:54
Apache 2.4.43

**Comment by Telesphoreo** [comment] 2020-05-19 00:33
So I just updated to the newest betas, and did some further investigation. I'm able to create files in any directory, and I'm able to edit files that I've created inside the file manager. The file has the permissions of 644 and is chowned to pterodactyl:pterodactyl.
For some reason, I'm able to edit files in the "Factions" folder. However, I'm still not able to edit files in any other folder, such as CoreProtect/config.yml. I've checked and the permissions are exactly the same. No clue why this is happening.

**Comment by DaneEveritt** [comment] 2020-06-13 16:32
I have been unable to reproduce this on any systems, and have not seen reports from anyone else encountering this.

Due to the limited resources available to this project, I am closing this issue as I will not be investigating it further. Thank you for taking the time to make the report, feel free to re-open it if you believe you find something specific that we can change to fix it.

**Closed by DaneEveritt** 2020-06-13 16:32 UTC
Labels: 1.0.0-beta, Type: Bug
