### ISSUE TITLE
Wings 1.0: OCI runtime create failed

### ISSUE THREAD

**Issue by marcelgroeneveld** [pterodactyl/panel#1961] opened 2020-04-22 01:16 UTC
**Background (please complete the following information):**
* Panel or Daemon: Wings Daemon
* Version of Panel/Daemon:  V1 Beta release
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win10/Firefox/Chrome
Daemon server:
Uname ```Linux h2838185.stratoserver.net 4.15.0 #1 SMP Mon Mar 16 15:39:59 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux```
Running ontop of a Parallels hypervisor  (virtuozzo container). Running the 0.7.x daemon on this machine worked just fine, just as anything with docker.

**Describe the bug**
I did a fresh install of ubuntu server 18.04, and installed the new wings daemon on it. I installed the panel on another machine. Configuration and installation had no issues, apart from configuration errors i made myself regarding SSL certificates, but i doubt that was related. After creating the config and restarting the daemon, any server, either created with the default or custom eggs, when started enters a crashed state, and always returns the same error:
```
[GIN-debug] Listening and serving HTTPS on 0.0.0.0:8080
1.5875179886343527e+09  info    sftp    sftp-server@v1.1.1/server.go:128        sftp subsystem listening for connections        {"host": "0.0.0.0", "port": 2022}
-- HERE I START A SERVER:
[GIN] 2020/04/22 - 03:13:18 | 200 |      68.869µs |  85.214.xxx.xxx | GET      "/api/servers/b3a3b9a0-79f4-4895-8329-422f44d67935"
1.5875180024263346e+09  info    server/environment_docker.go:144        syncing server configuration with Panel {"server": "b3a3b9a0-79f4-4895-8329-422f44d67935"}
1.5875180048632236e+09  info    server/state.go:115     detected server as entering a potentially crashed state; running handler        {"server": "b3a3b9a0-79f4-4895-8329-422f44d67935"}
1.5875180048654914e+09  info    server/environment_docker.go:144        syncing server configuration with Panel {"server": "b3a3b9a0-79f4-4895-8329-422f44d67935"}
1.587518006747118e+09   info    server/state.go:115     detected server as entering a potentially crashed state; running handler        {"server": "b3a3b9a0-79f4-4895-8329-422f44d67935"}
1.587518006747408e+09   error   server/state.go:122     failed to handle server crash state     {"server": "b3a3b9a0-79f4-4895-8329-422f44d67935", "error": "Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"process_linux.go:415: setting cgroup config for procHooks process caused \\\\\\\"failed to write \\\\\\\\\\\\\\\"1\\\\\\\\\\\\\\\" to \\\\\\\\\\\\\\\"/sys/fs/cgroup/memory/docker/1d2534567cb7b956f66d6e97e0e40369ef8dc67ff796b4c424b2c58ce47e146c/memory.oom_control\\\\\\\\\\\\\\\": write /sys/fs/cgroup/memory/docker/1d2534567cb7b956f66d6e97e0e40369ef8dc67ff796b4c424b2c58ce47e146c/memory.oom_control: permission denied\\\\\\\"\\\"\": unknown", "errorVerbose": "Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"process_linux.go:415: setting cgroup config for procHooks process caused \\\\\\\"failed to write \\\\\\\\\\\\\\\"1\\\\\\\\\\\\\\\" to \\\\\\\\\\\\\\\"/sys/fs/cgroup/memory/docker/1d2534567cb7b956f66d6e97e0e40369ef8dc67ff796b4c424b2c58ce47e146c/memory.oom_control\\\\\\\\\\\\\\\": write /sys/fs/cgroup/memory/docker/1d2534567cb7b956f66d6e97e0e40369ef8dc67ff796b4c424b2c58ce47e146c/memory.oom_control: permission denied\\\\\\\"\\\"\": unknown\ngithub.com/pterodactyl/wings/server.(*DockerEnvironment).Start\n\t/Users/dane/Sites/development/code/wings/server/environment_docker.go:243\ngithub.com/pterodactyl/wings/server.(*Server).handleServerCrash\n\t/Users/dane/Sites/development/code/wings/server/crash.go:74\ngithub.com/pterodactyl/wings/server.(*Server).SetState.func2\n\t/Users/dane/Sites/development/code/wings/server/state.go:118\nruntime.goexit\n\t/usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337"}
github.com/pterodactyl/wings/server.(*Server).SetState.func2
        /Users/dane/Sites/development/code/wings/server/state.go:122
1.587518006748934e+09   info    server/state.go:120     did not restart server after crash; occurred too soon after last        {"server": "b3a3b9a0-79f4-4895-8329-422f44d67935"}

```

**To Reproduce**
1. Install wings 1.0
2. config wings and start it.
3. Create a server, default or custom egg doesn't matter.
4. start this server.
**Expected behavior**
The gameserver to start.

**Comment by parkervcp** [comment] 2020-04-22 01:20
My guess is that while this is a container it's not properly passing through something to support docker.

**Comment by DaneEveritt** [comment] 2020-04-22 16:16
This looks like an issue with the host system not supporting the OOM disabling options, not anything specifically with Pterodactyl.

**Comment by parkervcp** [comment] 2020-04-22 17:05
Yeah running as a container and not a full vm looks like it didn't pass through cgroups.

**Comment by DaneEveritt** [comment] 2020-04-24 03:35
Closing this as not a bug with the software, this is a configuration issue with your setup that isn't making cgroups accessible to docker.

**Closed by DaneEveritt** 2020-04-24 03:35 UTC
