### ISSUE TITLE
[i18n] add more language translations

### ISSUE THREAD

**Issue by SerinaNya** [pterodactyl/panel#2665] opened 2020-11-06 11:23 UTC
There were several translations in `0.0.x` versions. But now there's only `en`. So why not to add other languages? This helps my users understand the panel more conveniently and easily.
What's more, I'm a native `zh_cn` speaker, so I can help you with a part of the (`zh_cn`) translating job.

**Comment by fabm3n** [comment] 2020-11-06 11:44
Dupe of #2518  (which is the replacement of #1106 )

**Comment by SerinaNya** [comment] 2020-11-06 11:48
So you are working on bringing this feature back, right?

**Comment by RihanArfan** [comment] 2020-11-06 11:52
> So you are working on bringing this feature back, right?

Yes

**Comment by SerinaNya** [comment] 2020-11-06 11:53
That's a good news. And how I can take part in translating?

**Comment by fabm3n** [comment] 2020-11-06 11:55
There is currently no way to translate the panel. All files you will found in github are from the old frontend.

**Comment by SerinaNya** [comment] 2020-11-06 11:58
Can I create a new folder `resources/lang/zh_cn/` and translate the text from `resources/lang/en/`, then open a PR? Does it work?

**Comment by fabm3n** [comment] 2020-11-06 12:00
This would not work because the new 1.0 frontend has no i18n implemented. The whole text is hardcoded.

**Comment by SerinaNya** [comment] 2020-11-06 12:03
Got it. If there is some way to translate the panel, I can offer some help. Thank you and all the developers.

**Closed as completed** 2020-11-06 14:48 UTC
