### ISSUE TITLE
Teamspeak3 Egg Error

### ISSUE THREAD

**Issue by Exonical** [pterodactyl/panel#2130] opened 2020-06-21 11:59 UTC
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0.0-beta.6
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 Enterprise & Microsoft Edge v83.0.478.54

**Describe the bug**
Wings Reported Error:
`ERROR: [Jun 21 09:39:09.053] failed to handle websocket process; an error was encountered processing an event error=context deadline exceeded error_identifier=f855e426-a3d5-40f4-83fd-c92e1e5ea66c event=set state server=6a3b106d-ddb0-4a3c-9294-4980d26e849c`
Panel Console Reported Error:
`container@pterodactyl~ Error Event [9381941e-a054-4a48-9ce4-2c3e80fc202d]: context deadline exceeded`
Daemon:  `Kernel Version: 5.7.4-050704-generic`
Docker Info
`Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.7.4-050704-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.35GiB
 Name: wings01
 ID: WRX5:ESUF:GSIS:4THJ:VIRO:3DLK:XWB3:UQ7H:62R5:72WM:ZSJW:ZX7M
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`

**To Reproduce**
1. Install the shipped TeamSpeak 3 Egg
2. Wait for successful install
3. Start the egg
4. See error in Console & Wings

**Expected behavior**
Teamspeak3 server to run

**Comment by fabm3n** [comment] 2020-06-21 17:39
Can you try wings beta5? Looks like a change after that version produces this issue. 

Another user also had this issue but it only occurs in beta 6. After a change to beta 5 this issue was gone.

**Comment by Sir3lit** [comment] 2020-06-22 02:05
I can not reproduce this.

**Comment by Exonical** [comment] 2020-06-22 08:11
Downgrading to Beta 5 fixed the issue.

**Comment by Sir3lit** [comment] 2020-06-22 08:19
I tried on beta 5 and beta 6, wasn't able to reproduce it.

**Comment by Exonical** [comment] 2020-06-22 08:23
I got it to work with Beta 6. Try using a completely fresh install and use Beta 6 of Wings and try it. After that, downgrade to Beta 5 and start the container, it runs. Then upgrading back to Beta 6, the issue is then fixed. May be something Beta 5 does that was changed in Beta 6 when coming from a fresh install.

**Comment by fabm3n** [comment] 2020-06-22 08:26
I also can't reproduce it, but a friend of mine also had this issue on a fresh installation.

**Comment by DaneEveritt** [comment] 2020-06-22 15:12
Was there more context to that error, specifically a stack trace?

**Comment by Oberfail** [comment] 2020-06-23 03:59
I have simmilar issues with 3/3 tested eggs, (2 of the default ones).
My issue with the teamspeak egg just solved itself magically.

Was able to "solve" the issues with deleting the Configuration Files in the eggs that werent working flawless. Some parts of the configuration files were duplicated or pasted all into a single line.

Will create a more detailed bug report when I got the time for it.

**Comment by DaneEveritt** [comment] 2020-06-23 04:10
closed in 073247e4e1e7b10d94c028fa274c4abdf6439d77

**Closed by DaneEveritt** 2020-06-23 04:11 UTC
Labels: beta 🦈, bug 🐛

**Comment by fabm3n** [comment] 2020-06-29 21:04
This issue still exists in the latest wings develop branch. I had this issue with the ark egg from parkes repo. After pulling the image the server is able to start without the context deadline exceeded issue.

**Comment by DaneEveritt** [comment] 2020-06-29 21:31
Please run the daemon in debug mode and provide the logs from that, it should be logging the errors.

**Comment by fabm3n** [comment] 2020-06-30 10:56
With parkers Sinusbot egg: https://pastebin.com/McAQkaEX

Steps to reproduce:
1. Check that the image isn't pulled before (`docker images`)
2. Install the Server
3. Start the Server and get an error

This only happens to me when the image isn't pulled before. If i pull the image manually it takes longer than the 10 seconds.

**Comment by fabm3n** [comment] 2020-06-30 19:07
Can't reproduce it again with beta 7, looks like it's fixed
