### ISSUE TITLE
Data Import 

### ISSUE THREAD

**Issue by mirmen** [pterodactyl/panel#3029] opened 2021-01-24 14:28 UTC
Add the ability to import all data from FTP/SFTP to the panel. The data will be copied to your server and you will non need to do it manually.

**Comment by parkervcp** [comment] 2021-01-24 15:53
I am not even sure what this means.

**Comment by mirmen** [comment] 2021-01-24 15:59
> I am not even sure what this means.

I'm from Russia. Using Google translator. The bottom line: you have 2 servers. 1 already has ready-made files, but 2 no files. Using this function, you can import data from 1 server 2 via SFTP

**Comment by gOOvER** [comment] 2021-01-24 16:30
It's like CLONE a server. But i don't understand, why u need this?

**Comment by parkervcp** [comment] 2021-01-24 16:35
Also a duplicate of #2148

**Closed as completed by parkervcp** 2021-01-24 16:35 UTC
