### ISSUE TITLE
Wrong time zone

### ISSUE THREAD

**Issue by DrakMC** [pterodactyl/panel#2577] opened 2020-10-23 09:11 UTC
**Background (please complete the following information):**
* Version of Panel/Daemon: 1.0.2
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 & Google Chrome

**Describe the bug**
PHP version: 7.3.19-1~deb10u1
Linux hostname 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
Docker Server version: 19.03.13

**To Reproduce**
After updating the daemon and panel to version 1.0.0, I'm having a bad time zone in the console. The time is delayed by 2 hours.

Screenshot of the issue:
![image](https://user-images.githubusercontent.com/40771376/96987554-78396c80-1523-11eb-8376-3e50fc87cfc0.png)

**Comment by parkervcp** [comment] 2020-10-23 10:45
Dupe of #2546

Closing as this should be resolved in 1.0.2

**Closed as completed by parkervcp** 2020-10-23 10:45 UTC
