### ISSUE TITLE
Add support for MongoDB in databases

### ISSUE THREAD

**Issue by WillFP** [pterodactyl/panel#4088] opened 2022-05-26 08:17 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Instead of only having support for creating SQL databases in the pterodactyl panel, it would be nice to additionally have support for NoSQL databases, like MongoDB - since many Minecraft plugins already have MongoDB support, it makes sense to be able to create MongoDB databases in the panel directly instead of having to do it manually via the terminal - it's just a nice QoL improvement.

### Describe the solution you'd like.

When creating a database, instead of directly making an SQL database, prompt the user for the type of database they want - doesn't clutter the UI, and it's simple to understand the options.

**Comment by hwalker928** [comment] 2022-05-26 16:19
#3412

**Comment by matthewpi** [comment] 2022-05-26 16:46
Duplicate of a previous issue.

**Closed as not planned** 2022-05-26 16:46 UTC

**Comment by Apprisco** [comment] 2024-05-24 02:12
Don't call it a friggin duplicate and close it, when the existing issue is closed for dumb issues.
