### ISSUE TITLE
Server administration buttons

### ISSUE THREAD

**Issue by MrTimotys** [pterodactyl/panel#4220] opened 2022-07-01 07:45 UTC
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like the home page where all servers are displayed to have server management buttons (Start, Restart, Stop) on the right side of each server. Or add a tool where we can choose a bulk action for the servers. 

### Describe the solution you'd like.

I said it above.

**Comment by trenutoo** [comment] 2022-07-01 09:19
Duplicate of #278

**Closed as completed by trenutoo** 2022-07-01 09:19 UTC
