### ISSUE TITLE
Using /stop command on minecraft server, the server don't autorestart

### ISSUE THREAD

**Issue by xion87** [pterodactyl/panel#1271] opened 2018-08-07 09:15 UTC
Background (please complete the following information):
Panel or Daemon: Daemon/Panel
Version of Panel/Daemon: 0.6
Server's OS: ubuntu 16
Your Computer's OS & Browser: win10 chrome

Describe the bug
Please provide additional information too, depending on what you have issues with:
Panel: php -v (the php version in use).
Daemon:
Linux ns3402613.ip-51-255-76.eu 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

To Reproduce
On minecraft server if i use /stop command, the server don't autorestart, on panel will stay marked as "online", forcefull me to kill it. This function was working fine on 0.5.x

Running command trow this error on daemon:
I checked the daemon log, there is no errors:
https://gist.github.com/xion87/fc4992733867554b8fd53c8bc84f0f61
and no error on panel log

**Comment by DaneEveritt** [comment] 2018-08-07 16:13
fixed by https://github.com/pterodactyl/daemon/pull/70

**Closed by DaneEveritt** 2018-08-07 16:13 UTC

**Comment by xion87** [comment] 2018-08-08 21:33
Hey @DaneEveritt you solved the bug partially with 0.6.3, the server will not stuck in Online mode, but it stay in offline and need to be started manually

**Comment by DaneEveritt** [comment] 2018-08-09 17:30
This is working as intended. Previously when you used `stop` in-game (and not through the console in Pterodactyl) your server would be marked as crashed, which is incorrect behavior.

Servers will only auto-restart if they terminate with an error code other than `0`.

**Comment by xion87** [comment] 2018-08-09 17:52
but tell me why with 0.5.6 it work perfect, look how this work:
0.5.6: https://gist.github.com/xion87/cf975a48b50d4d5091affb6d16d29b2d
0.6.3: https://gist.github.com/xion87/c023ff94b1c671173e50ac4e4c4d368f
See the difference

**Comment by DaneEveritt** [comment] 2018-08-09 18:18
`"ExitCode":0`

> Servers will only auto-restart if they terminate with an error code other than 0.

**Comment by xion87** [comment] 2018-08-09 20:25
I have to change the shutdown message to 0? i can't edit the plugin, and this change make me to stay to 0.5.9, since it break all bungee gamemode server where it restart

**Comment by parkervcp** [comment] 2018-08-09 22:01
It's not a shutdown message but the exit code. Exit code 0 is all is good application stopped. All other exit codes cause the panel to think it's crashed and restart the server.

**Comment by MrAlecroYT** [comment] 2018-08-10 14:25
The auto autorestart isnt working with the new daemon 0.6.3

**Comment by MrAlecroYT** [comment] 2018-08-10 14:31
> [09:54:48 INFO]: Startup script './start.sh' does not exist! Stopping server. 
It was working with the daemon 0.5.3 and when i upgrade to the new daemon  and dont work the autostart

**Comment by DaneEveritt** [comment] 2018-08-10 16:03
This is not a bug, please stop reporting them as a bug. You **CANNOT** have a plugin stop your server gracefully and expect the _crash detection_ to pick it up and restart the server. Just because it worked this way previously does not mean it was ever intended to work this way.

**Comment by thomasdaley2** [comment] 2018-09-28 23:36
Can I ask.  HOW could the auto restart server be accomplished?  I will be using pterodactyl soon and want to be sure that when CMI closes the server that it will restart itself.

**Comment by parkervcp** [comment] 2018-09-29 03:04
@thomasdaley2 You are looking for https://github.com/pterodactyl/daemon/blob/develop/CHANGELOG.md#v065-elasticized-elanodactylus

It was defaulted to crash detection on proper shutdown again as that is the expected behavior.
