### ISSUE TITLE
[develop/rc.2] Issues with variable validation

### ISSUE THREAD

**Issue by MarkL4YG** [Pterodactyl/Panel#941] opened 2018-02-14 20:15 UTC
* Panel 
* Version of Panel: latest/``develop`` (More specific: e2cdb3b4b139e4ada4eed538449ae01467848804 )
* Server's OS: Ubuntu 16.04.3 LTS
* Your Computer's OS & Browser: Chrome 

## Details:
When editing variables in the startup parameters of an existing server a value does not change when submitted.  
Since we already had the debug mode enabled already from another issue I noticed it is a validation exception which seems to be suppressed.  

## Example input:
Input rules: ``required|string|max:250``
Example input: ``map_for_gmod``

## Suppressed exception
Located in ``PATCH`` request:  
```
The given data was invalid.
/var/www/html/pterodactyl/app/Services/Servers/VariableValidatorService.php#86
```

**Comment by DaneEveritt** [comment] 2018-02-16 03:09
I am unable to reproduce this. Are you able to provide more of the stack trace and a little bit more detail with how to reproduce this?

**Comment by MarkL4YG** [comment] 2018-02-16 09:11
Uhm, yeah sure. I would've included the log but laravel doesn't appear to write this into the log file.  
Also this issue was appearing on all servers of one of our custom eggs but when I changed the filter to ``required|string|alpha_dash`` the value suddenly got accepted by all but a single server.  
That single server now happens to be the one which showed the behavior in the first place.

Here's the egg file just in case: https://gist.github.com/MarkL4YG/0189e4973dce19a8c66c99b328a8a6df

**Comment by DaneEveritt** [comment] 2018-02-17 22:49
After talking with you on Discord I think I'm going to close this for now, and we can see if this issue appears again for others, if so lets open this again.

**Closed by DaneEveritt** 2018-02-17 22:49 UTC
Labels: Beta/RC Build, Bug

**Comment by MarkL4YG** [comment] 2018-02-17 23:45
I will also check if this re-occurrs after the next update/pull.

**Comment by MarkL4YG** [comment] 2018-02-19 08:23
Appears to be resolved. o/
