### ISSUE TITLE
Startup Variables Ignored By Wings

### ISSUE THREAD

**Issue by Zendrex** [pterodactyl/panel#2255] opened 2020-08-24 09:42 UTC
**Background (please complete the following information):**
* Panel or Daemon: Both
* Version of Panel/Daemon: 1.0.0-rc1
* Server's OS:  Ubuntu 18.04
* Your Computer's OS & Browser: Win10/Firefox

**Describe the bug**
It seems that any startup variables changed at server creation OR post-creation are ignored by wings, but are updated to the database. On top of this, the UI does not update the "startup command" string when variables are changed/saved.

Example: https://gyazo.com/f1953f67d0c59608b63f15130a7694ba

**To Reproduce**
1. Create A Server / Select Existing Server
2. Change Startup Command Variables
3. Start/Restart Server
4. See No Changes Executed

**Expected behavior**
Startup variables to take effect. Wings seems to only use the default nest variables.

**Comment by Sir3lit** [comment] 2020-08-24 12:42
Does restarting wings pull new variables?

**Comment by Zendrex** [comment] 2020-08-24 14:18
@Sir3lit I've attempted this before, and did again just now with no avail.

**Comment by Corenb** [comment] 2020-08-24 16:15
It seems all variables aren't parsed (same for installation variables). When I running installation script, default variables are used instead of server variables.

**Comment by DaneEveritt** [comment] 2020-08-24 16:55
It is quite possible I broke this unintentionally when I made changes to startup variable handling. I'm guessing the API is actually sending along incorrect values. You can confirm this by checking the server install logs in `/var/log/pterodactyl` I believe.

**Comment by Sir3lit** [comment] 2020-08-25 00:15
That does seem to be the issue. That it's passing the defaults to the install script.

**Comment by matthewpi** [comment] 2020-08-25 03:48
Duplicate of #2261 (which has been resolved due to a pull request)

**Comment by DaneEveritt** [comment] 2020-08-25 04:21
This isn't a duplicate.

**Comment by Zendrex** [comment] 2020-08-26 05:45
@DaneEveritt
Just tested RC2 for wings, it seems that this issue still persists in some manner. Restarting wings does grab the correct variables, however updating them post-restart still doesn't update wings.

**Comment by Zendrex** [comment] 2020-08-26 06:10
Also have learned that variables are still not updated in the log, however they seem to work within wings.
Example from DayPlayz#1486 - https://discord.mx/?f=9aqpsul9jm.gif (custom egg)
My Example - https://gyazo.com/b902806d6d6ab2891fcd33e3523817f9 (parkervcp discordjs egg)

**Comment by parkervcp** [comment] 2020-08-26 12:36
> Also have learned that variables are still not updated in the log, however they seem to work within wings.
> https://gyazo.com/b902806d6d6ab2891fcd33e3523817f9 (parkervcp discordjs egg)

This is specific to how I am parsing the commands. I'm not going to sped a ton of time working on fixing that wither.

**Closed** 2020-08-28 04:08 UTC
Labels: beta 🦈, bug 🐛
