### ISSUE TITLE
Unable to change the node's FQDN

### ISSUE THREAD

**Issue by haoteng10** [pterodactyl/panel#1931] opened 2020-04-16 02:49 UTC
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v1.0.0 Beta Release 1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 & Chrome

**Describe the bug**
Panel: 7.4.4
Issue: I am not able to change the domain or port of the node in the 'Nodes' page in management. 
Note: I can not remove the node & add the node back again because there is a server associated with it.

**To Reproduce**
~~1. Go to the 'Nodes' page in management
2. Change Fully Qualified Domain Name to an invalid address that will not connect to the daemon
3. Change Daemon Port to an invalid port that will not connect to the daemon
4. Returns error `There was an exception while attempting to communicate with the daemon resulting in a HTTP/401 response code.`
5. Try to update the domain or port back to the correct address or port.
6. Returns error `There was an exception while attempting to communicate with the daemon resulting in a HTTP/401 response code.` (It seems like it changed the value but refreshing the page will disregard the changes)~~

**To Reproduce (updated)**
1. Go to 'Nodes' page in management
2. Change Fully Qualified Domain Name to an address of another application such as a webserver (running on port 8080)
3. Successfully changed the FQDN
4. Try to update the FQDN back to a correct address
5. Returns error `There was an exception while attempting to communicate with the daemon resulting in a HTTP/401 response code.`

**Expected behavior**
When I tried to change the domain back to a correct address, I expect the panel to make the change.

**Comment by parkervcp** [comment] 2020-04-16 03:10
So I am using IP addresses and this may be a domain lookup issue. So edits works with IP addresses. I will test out fqdns tomorrow.

**Comment by Sir3lit** [comment] 2020-04-16 06:16
Seems to correctly change the port for me, and correctly gives the error of `The FQDN or IP address provided does not resolve to a valid IP address.` when an invalid domain is put in
I'm not able to reproduce this exactly. 

However changing it to a valid domain returns a 405/401, and attempting to change it back fails with a 405/401 depending on the domain you put. The only solution is to edit the database table and change it back manually

**Comment by Sir3lit** [comment] 2020-04-21 11:45
It should be noted that the nodes config.yml was updated when changed to a wrong URL, found this out days after when I tried to restart wings and it failed due to it trying to find an SSL cert that didn't exist for the domain I was testing this issue for.

**Comment by DaneEveritt** [comment] 2020-05-08 03:32
I am not able to reproduce this issue using any of the steps provided.

1. Using an invalid FQDN that does not resolve gives me the expected error about it not resolving.
2. Using a valid FQDN and an invalid port works fine, which makes sense since it connects over the old port when updating things for the daemon.
3. Changing that invalid port BACK to a valid port updates the data and gives the expected "can't communicate with daemon" error since, well, it was an invalid port.

**Comment by haoteng10** [comment] 2020-05-09 15:52
I just found the cause of this issue. 

First, I managed to change the panel's node information to **another** FQDN with port 8080 running a **webserver** Then, of course, the panel cannot connect to that. However, somehow it managed to change the configuration. However, I can not change it back to the working FQDN running the daemon. I managed to solve this issue by turning off that port 8080 webservers.

**Comment by LeCodeCo** [comment] 2020-05-09 22:35
> I don't understand why the panel does not let me change the FQDN back to a working daemon when the address resolves to a web server, not a daemon. Furthermore, I **should not** be able to change the node's information to connect to a **webserver**.

Pterodactyl has no idea what can run on the other end if wings isn't running. When you make your first node, wings won't already be online and configured so Pterodactyl can't block that.

**Comment by haoteng10** [comment] 2020-05-09 23:00
> Pterodactyl has no idea what can run on the other end if wings isn't running. When you make your first node, wings won't already be online and configured so Pterodactyl can't block that.

Then, I should be able to change the FQDN back into a working address. However, it is blocking me from doing so by returning this error `There was an exception while attempting to communicate with the daemon resulting in a HTTP/401 response code.`

**Comment by DaneEveritt** [comment] 2020-05-09 23:21
Ah, it is because when you update the node information it connects to whatever the FQDN currently configured on the node is. In your case you changed it to a valid server, so now when it tries to make changes it uses that valid-but-incorrect FQDN as the base, not the one you changed it to.

**Closed** 2020-05-09 23:25 UTC
Labels: 1.0.0-beta, Type: Bug
