### ISSUE TITLE
Allocation is not working properly

### ISSUE THREAD

**Issue by EpixPlays** [pterodactyl/panel#5080] opened 2024-04-27 17:03 UTC
### Current Behavior

I cannot start the server as it fails to assign the requested address. The address is the one for the server that the panels and wings are running on.

### Expected Behavior

Server starts as usual without errors.

### Steps to Reproduce

I have created a server using the allocation for my server with the port 25565. The port is forwarded correctly. I try to run the server and it does not start.

### Panel Version

1.11.5

### Wings Version

1.11.11

### Games and/or Eggs Affected

All eggs

### Docker Image

All

### Error Logs

```bash
https://ptero.co/hesicafene
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment] 2024-04-27 17:06
This is not a bug with the software.
You are attempting to bind to the wrong IP address. Please use the discord for support

**Comment by EpixPlays** [comment] 2024-04-27 17:08
Hey. I cannot use discord at the moment as I am in the process of recovering my account. Could you possibly help me on here? Thanks.

**Comment by Loki-101** [comment] 2024-04-27 17:40
This is the message the support bot in the Discord is programmed to give you for this kind of error:

The IP address you have assigned to your server is not actually available for use on your machine, or something is already running on that port. Use `ss -plnt | grep :<port>` (replacing <port> with your own) to find what processes might be using it.

**If you don't find any service using the port, then refer to the instructions below.**

Execute the command `hostname -I | awk '{print $1}'` and change your Node allocations to use this IP. Yes, it can be your internal/local IP when you're behind NAT. You still have to use it as that is your network interface IP.

If you have added multiple public IPs to your network interface, then you can view all of them using the command `ip a | grep "inet "`

**Closed as completed** 2024-04-30 18:58 UTC
