### ISSUE TITLE
Another power action is being processed: bug in runc causing container lockup

### ISSUE THREAD

**Issue by INfoUpgraders** [pterodactyl/panel#2475] opened 2020-10-10 20:57 UTC
# ⚠️ NEW READERS! PLEASE READ ENTIRE THREAD. ⚠️ 

Most of the context and a good starting point can be found in [these specific comments](https://github.com/pterodactyl/panel/issues/2475#issuecomment-847219758). Please only respond if including more relevant information, or confirmation of bug fixes.

-------

Panel or Daemon: Panel
* Version of Panel/Daemon: ~~v1.0-rc.7~~ Latest version of panel and daemon now
* Server's OS: Ubuntu 18.04 LTS
* Your Computer's OS & Browser: Chrome

`container@pterodactyl~ Error Event [3872f642-7497-4b62-b9c2-5116d28836d3]: another power action is currently being processed for this server, please try again later` 

Over 750+ servers are running on this node consisting of Minecraft and Discord bots

**To Reproduce**
1. Click the start button (might have to do multiple servers at once)

**Expected behavior**
Not expecting for when multiple servers try to start at the same time for it to error out :)

**Comment by matthewpi** [comment] 2020-10-10 21:57
The power action limit is handled on a per-server basis, it's not for all the servers entirely.

**Comment by DaneEveritt** [comment] 2020-10-10 22:02
As @matthewpi said, additionally you can always kill a server if it is for some reason stuck in a power state which will get it back into working order.

**Comment by INfoUpgraders** [comment] 2020-10-10 23:40
Well this only happens when multiple people are trying to do a power action on their server. Killing a server simply results in the same issue, if you'd like, you can add me on Discord @ INfoUpgraders#0001 and we can further the topic and I can show you guys what is happening exactly.

**Comment by DaneEveritt** [comment] 2020-10-10 23:47
You're welcome to use the #1.0-rc-help channel on Discord to discuss this, however with the limited information provided here I'm not sure how we can really debug this any more and I've not heard from anyone else encountering this issue.

**Comment by INfoUpgraders** [comment] 2020-10-11 16:34
![gyazo gif](https://gyazo.com/8ed613e9caefcdfef76ab4779bef4c15)
This is what happens, usually waiting a while and trying again solves the issues. But I feel as this is a bug with multiple people possibly trying to do things at once. If you need anything else, just let me know in the help channel as I posted the same gif there.

**Comment by xion87** [comment] 2020-10-12 17:46
I confirm the issue, same thing happened to me, if i shutdown the server and go back to console and try to turn on i face the same error ^

**Comment by INfoUpgraders** [comment] 2020-10-13 01:06
@xion87 Roughly, how many servers and members do you have on your panel?

**Comment by AaduMaadu** [comment] 2021-02-01 20:48
Same, this bug has made it impossible to start my servers anymore

**Comment by INfoUpgraders** [comment] 2021-02-01 20:49
Yeah, and the devs made it completely intentional.

**Comment by matthewpi** [comment] 2021-02-01 20:56
> Yeah, and the devs made it completely intentional.

This is a feature designed to prevent race conditions and triggering multiple power actions at the same time (whether it is done by multiple users or an individual).  Sadly with the way software works and the complexity of systems like this, it isn't simple to find out if there is actually a problem or if it is behaving as intended.  Also, with the amount of people that actually use Pterodactyl for both hosts and personal use, this only seems to affect a very small part of users, which leads me to believe it isn't a problem.

**Comment by Ash7771430** [comment] 2021-02-02 02:21
this issue seems to be very big and it should be solved as many of server are now unusable because of this bug

**Comment by INfoUpgraders** [comment] 2021-02-02 02:23
It's always been a bug since the very start of v1.0. I'll make sure more people comment on it so it gets noticed by the devs.

**Comment by Kitapi** [comment] 2021-02-02 02:35
I have seen this error before and I have been looking for a fix for it as its pretty annoying to some and you have to keep refreshing to get rid of it

**Comment by EightsCuh** [comment] 2021-02-02 02:35
Yeah, this bug is really pissing me off i hope that we can see a fix for this cause even just killing it sometimes glitches it for me

**Comment by KorbsStudio** [comment] 2021-02-02 02:35
;-;

**Comment by ItsKas** [comment] 2021-02-02 02:36
I agree that this is very annoying. It keeps happening to me and I have to wait up to a minute for it to let me start my server on the panel.

**Comment by ResolvTech** [comment] 2021-02-02 02:37
I have seen this error before and I have been looking for a fix for it as its pretty annoying to some and you have to keep refreshing to get rid of it

**Comment by Ash7771430** [comment] 2021-02-02 02:38
it annoying but the main thing is even if you wait 2 days there will be same error making the server unusable

**Comment by mysticseagull** [comment] 2021-02-02 02:42
I can say it happened to me before, and from some debugging, I think I slightly concluded it's from having too many servers on one machine. On saying that, It was a fairly low server count compared to 0.7x series, but I do agree with you Matthewpi, I'd say it is behaving intentionally with a bug being the handling of x number of requests. I would love to see it fixed nonetheless if possible.

> This is a feature designed to prevent race conditions and triggering multiple power actions at the same time (whether it is done by multiple users or an individual). Sadly with the way software works and the complexity of systems like this, it isn't simple to find out if there is actually a problem or if it is behaving as intended. Also, with the amount of people that actually use Pterodactyl for both hosts and personal use, this only seems to affect a very small part of users, which leads me to believe it isn't a problem.

**Comment by DaneEveritt** [comment] 2021-02-02 03:17
Unless you're going to respond with enough information for us to even begin trying to reproduce, please stop commenting with "this happens to me too." 

It's been four months since this was reported, please include the relevant version information, steps you took that lead to the issue, and what specific eggs your server(s) are running that are encountering this issue. If you cannot or will not provide that, please don't rely to this issue, thanks! 

We have limited time and resources for debugging things as it is, and bug reports like this don't take high priority since the only steps we've been given are to run 750 Minecraft and discord servers and then press a start button. Additionally, thousands of people run this software and I've not heard from others indicating this is an issue for them. I get that it being broken for you can be frustrating, but you're not the only users of this software, and it helps if you look at this issue with a fresh pair of eyes to understand how frustrating your responses are to us without any additional context to them. 👌🏼

**Comment by INfoUpgraders** [comment] 2021-02-02 03:44
Hello Dane, I understand your frustration as I know there are limited developers and contributors to such a large project. I apologize for not providing correct and enough information in my initial thread. 

As per request,

Version Information: All minor versions of 1.x.x panel w/ corresponding wings.

Steps to reproduce:
1. You need 100-999 containers within a single node as well as for them to be started.
2. Attempt a power action on a couple of the containers near the same time

I understand this may not be optimal for a test/dev environment, but this is what it takes to reproduce the "bug".

Eggs that are encountering this issue: Default eggs that come with the panel, as well as custom eggs.

I appreciate your response and hope this is enough information for you, please let me know if you need anymore!

**Comment by DaneEveritt** [comment] 2021-02-02 05:47
@INfoUpgraders I need you to provide the entire output of the `wings diagnostics` command, it has a ton of contextual information that we need in order to even begin trying to debug this. I literally do not have the resources (or time) available to spin up 100+ server instances just to try and hunt down this type of bug.

**Comment by madoda2s** [comment] 2021-05-17 10:36
YEAH this bug is so so so bad anyone can help please? another power action for this server!

**Comment by AssaultLine** [comment] 2021-05-21 17:17
The original poster said that a requirement of hundreds of containers was needed. I have less than 10 and have it happening. I am currently running on Ubuntu 20.04 on the node that is giving me trouble currently and there is only 6 containers installed on it via pterodactyl. 
I am running the newest version of Panel and Wings, and I am only having this issue mainly with a few specific nodes. They all were installed and set up the same though.
You have no clue how much trouble it is trying to get this fixed, I have people constantly contacting me about their server getting stuck in the same cycle and there is nothing I can do to fix it for them other than restart every node on that dedi.

Specs:
Ryzen 9 3900
128GB RAM
2TB NVMe
Only 6 servers currently installed and its getting the bug at random
Newest version of panel and wings like I already mentioned
Let me know what else is needed and I will try to provide.

**Comment by AssaultLine** [comment] 2021-05-21 17:20
Also to add onto that a bit more, I have found that a power action from a customer/user is not even necessary. At times the server was left running overnight and when the person using the server hops on in the morning it will be off, or at least shown as off in the servers dashboard page. Any power action will give the same error with different Error Event code.

container@pterodactyl~ Error Event [e9848364-f97d-4e5c-bd28-1e0da8c6b24c]: another power action is currently being processed for this server, please try again later

**Comment by KoddyDev** [comment] 2021-05-21 17:25
how to solve without restart my docker and my online servers?

**Comment by DaneEveritt** [comment] 2021-05-21 17:49
You just need to restart wings, you don't have to restart docker.

**Comment by AssaultLine** [comment] 2021-05-21 17:55
I'm going to test this again, but the last time I restarted wings while the server was in this state it then disconnected my entire node and I was forced to restart all of docker anyways to get wings connected back.

**Comment by AssaultLine** [comment] 2021-05-21 18:12
Already tested it and its just like I said, if there are any servers that are in this state where the show that error, and I restart wings then that whole node now shows as offline. And the only way to resolve the node not connecting back is to systemctl restart docker. I believe this has something to do with docker and wings not properly communicating the state of the server and then it won't connect back until it detects the server in the proper state that it should of been in. This is all just my opinion, but this has something to do with docker or wings.

Is there some way for me to disable this specific security setting that causes that error to show in the first place? I'm just wondering what happens if whatever is set to trigger that error is all of a sudden disabled.

**Comment by AssaultLine** [comment] 2021-05-21 18:16
Or possibly could you tell me what file it would be in that tells wings what state the server is in? Maybe I am able to manually edit the file to fix it rather than restarting all of docker. 

I just hate when it happens and the only way to resolve is to kill literally every server hosted on that node. Its upsetting other people and I have so few people per node to begin with. All my dedi's are 12 core or less and I only host up to 12 servers on a node.

**Comment by DaneEveritt** [comment] 2021-05-21 18:56
When this happens are you able to run `docker ps -a` on the node? And if so, what happens if you run `docker info <id>` on one of the servers. This is the first time anyone has actually communicated that they have to restart docker to fix things.

This logic is controlled by a little internal code lock, theres no reason I can think of that restarting wings wouldn't correctly clear that lock.

**Comment by AssaultLine** [comment] 2021-05-23 03:04
I am able to run docker ps -a and it shows the containers, I was unable to do anything with the <id> part of docker info though. I don't think that command can be used for a specific container only for the whole server. 

Something I noticed though is it outputs there is 6 containers but in reality there is only 5 servers installed on that server. And its a fresh install also. Once I restarted docker it went from 4 containers running to 5 containers running and 1 stopped. Is there any useful diagnostic info that I can provide you guys to help more?

**Comment by AssaultLine** [comment] 2021-05-23 03:13
I had the same thing happen on another new node that was just installed. I did the command on here and it showed something a bit different. It shows that the server was exited about 5 hours prior and that it had an error 137 (not sure what that error defines)

```
ubuntu@ns3192364:~$ sudo docker ps -a
CONTAINER ID   IMAGE                                               COMMAND                  CREATED        STATUS                     PORTS                                                                                                                                                                                                                                                            NAMES
24940633a79e   quay.io/parkervcp/pterodactyl-images:game_mordhau   "/bin/bash /entrypoi…"   8 hours ago    Exited (137) 5 hours ago           
```

This server was suffering from the same issue as the other one though.

**Comment by INfoUpgraders** [comment] 2021-05-24 01:24
How much ram did that Morhau game server have? That container crashed because it ran out of memory, you also can enable OOM killer in that containers settings

**Comment by AssaultLine** [comment] 2021-05-24 09:24
> How much ram did that Morhau game server have? That container crashed because it ran out of memory, you also can enable OOM killer in that containers settings

It should have enough where its not going to crash from that. I am currently dealing with the whole node not connecting back though after restarting docker to fix a server. This happens a lot now and I have no solid way of fixing it once it gets to this stage. I am checking wings debug and seeing this


https://ptero.co/qoxedakihu

All of the GET errors near the end are the 2 webpages that I have opened trying to get the server dashboard to load and its throwing out those debugs on it.

**Comment by DaneEveritt** [comment] 2021-05-24 17:43
Sorry, can you try `docker inspect <id>` on a container having issues for me?

**Comment by AssaultLine** [comment] 2021-05-24 22:31
I tried this and it wouldn't even output anything from that container, but when I tried it on a container not currently bugged it showed a lot of details and info. Most of the time I can't get docker to do anything regarding the bugged container, I am just forced to restart it to fix the problem.

**Comment by DaneEveritt** [comment] 2021-05-24 23:01
This sounds like it is related to another issue where Docker completely locks up for random containers.

edit: Couldn't find the specific issue from here, but I remember debugging it on a hosts' instance and it was exactly the same issue where random containers would completely lock up.

https://github.com/opencontainers/runc/issues/2530#issuecomment-844561941

cc @matthewpi do you remember anything about this?

**Comment by DaneEveritt** [comment] 2021-05-24 23:08
I should clarify that by re-opening this issue there is no guarantee I can fix anything, it honestly seems like an issue with the dependency being used, and even if I fix _this_ specific issue, it'll just cascade a level and cause issues elsewhere in the code. The underlying issue is that you cannot execute required actions against the containers so nothing is going to work very well.

edit: appears resolved by https://github.com/opencontainers/runc/pull/2871

See if you can update Docker/runc to get the fix and let me know.

**Comment by trenutoo** [comment] 2021-05-24 23:24
I can confirm that 1.0.0-rc92 does not have this issue, nor 1.0.0-rc94. The culprit should be the runrc 93, using which the issue can be replicated (`runc --v` to check the version). I have been running rc92 without any issues.

**Comment by DaneEveritt** [comment] 2021-05-24 23:28
On second thought I'm actually going to close this issue since there isn't anything specifically that we can do about this, but will leave it pinned to help others find it and update as needed. Perhaps something in the docs might be good.

**Closed by DaneEveritt** 2021-05-24 23:28 UTC
Labels: bug, help wanted :wave:, high priority

**Comment by tommasobenatti** [comment] 2022-01-20 10:08
I'm having this issue too

**Comment by ScottyRobinson** [comment] 2022-01-22 20:45
Recently installed Pterodactyl on a fresh machine, migrated a server over from another node and having the same issue.

**Comment by tommasobenatti** [comment] 2022-01-22 20:46
> Recently installed Pterodactyl on a fresh machine, migrated a server over from another node and having the same issue.

`systemctl restart wings`
@ScottyRobinson

**Comment by ScottyRobinson** [comment] 2022-01-22 20:51
> > Recently installed Pterodactyl on a fresh machine, migrated a server over from another node and having the same issue.
> 
> `systemctl restart wings` @ScottyRobinson

I assume this means we're going to have to run this every single time we run a server restart schedule within Pterodactyl? As everytime we do, we're unfortunately getting the same error everybody else does here.

Here is the `runc --v`:
```
runc version 1.0.2
commit: v1.0.2-0-g52b36a2
spec: 1.0.2-dev
go: go1.16.10
libseccomp: 2.5.1
```

**Comment by zigazajc007** [comment] 2022-01-23 19:31
Even if you have one user with one container/service on the Pterodactyl panel it can happen.

**Comment by AssaultLine** [comment] 2022-01-23 20:48
If you are having this issue it was solved by just reverting to a prior version of containerd.io. It is literally an issue with the newer version, but I would of thought this was solved on all newer versions. I'm not sure what version you are on but this solved it for me.

`apt install containerd.io=1.4.3-1`

And then I believe I also had it hold the package so that it did not update further. Since then I have just been installing the newest version after 4 months or so went by I had thought the bug was fixed, but I have not dealt with this issue since last year 5/23/2021.

**Comment by tommasobenatti** [comment] 2022-01-23 20:50
> `apt install containerd.io=1.4.3-1`

E: Version '1.4.3-1' for 'containerd.io' was not found

on debian 11

**Comment by AssaultLine** [comment] 2022-01-23 20:53
I was on Ubuntu 18.04 and 20.04, I'm not sure about Debian what the command would be. Maybe check the version history for containerd.io on debian.

**Comment by DaneEveritt** [comment] 2022-01-24 00:26
I don't believe this is a containerd issue anymore, it seems to be stemming from specific code changes that were made as reverting seems to address it for people.

**Comment by lamakerx** [comment] 2022-01-24 09:08
+

**Comment by jonathanvincent12313** [comment] 2022-01-25 09:34
> I confirm the issue, same thing happened to me, if i shutdown the server and go back to console and try to turn on i face the same error ^

fardshidmanfakubij

**Comment by jonathanvincent12313** [comment] 2022-01-25 09:35
> # ⚠️ NEW READERS! PLEASE READ ENTIRE THREAD. ⚠️
> Most of the context and a good starting point can be found in [these specific comments](https://github.com/pterodactyl/panel/issues/2475#issuecomment-847219758). Please only respond if including more relevant information, or confirmation of bug fixes.
> 
> Panel or Daemon: Panel
> 
> * Version of Panel/Daemon: ~v1.0-rc.7~ Latest version of panel and daemon now
> * Server's OS: Ubuntu 18.04 LTS
> * Your Computer's OS & Browser: Chrome
> 
> `container@pterodactyl~ Error Event [3872f642-7497-4b62-b9c2-5116d28836d3]: another power action is currently being processed for this server, please try again later`
> 
> Over 750+ servers are running on this node consisting of Minecraft and Discord bots
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Click the start button (might have to do multiple servers at once)
> 
> **Expected behavior** Not expecting for when multiple servers try to start at the same time for it to error out :)

**Comment by jonathanvincent12313** [comment] 2022-01-25 09:35
E

**Comment by jonathanvincent12313** [comment] 2022-01-25 09:35
LEAVE NOW OR DIE!!!!!!!!!!!!!!!!!

**Comment by bubobih** [comment] 2022-01-31 10:40
Same problem 

https://i.imgur.com/n3Un4Ts.jpeg
