### ISSUE TITLE
Wrong CPU usage

### ISSUE THREAD

**Issue by Talhazzers** [pterodactyl/panel#2132] opened 2020-06-22 14:25 UTC
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.13 (Latest: 0.6.13)
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: -

**Describe the bug**
If your server using %100 CPU, panel shows %1000 (only in this kernel version, my other nodes shows true)

Daemon: 
```
5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Client:
 Debug Mode: false

Server:
 Containers: 60
  Running: 10
  Paused: 0
  Stopped: 50
 Images: 18
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-37-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 68.7GiB
 Name: **.**.com
 ID: UANU:WU7W:3MDW:7GSE:HQYD:3MGU:ASUN:26MA:WICV:5IGQ:VWZZ:QINF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**To Reproduce**
1. Install server
2. Start server
3. See CPU usage

**Comment by parkervcp** [comment] 2020-06-22 14:26
duplicate of #2095

**Closed by parkervcp** 2020-06-22 14:26 UTC

**Comment by Talhazzers** [comment] 2020-06-22 14:35
How can I temporarily find a solution for this bug?

**Comment by DaneEveritt** [comment] 2020-06-22 15:14
There is not one for the 0.6.x daemon versions, it is only fixed in the beta releases and I have no plans to backport it right now.
