### ISSUE TITLE
Server data blocks layout broken on Safari

### ISSUE THREAD

**Issue by RedEpicness** [pterodactyl/panel#4221] opened 2022-07-01 10:48 UTC
### Current Behavior

When viewing a servers console, the data blocks on the right on the website stretch too far down along with other layout being broken on Safari. The data blocks do not have a fixed height and instead is stretched with the windows resizing.

Safari version: 15.5 (17613.2.7.1.8)
macOS version: 12.4 (21F79)

![Broken Layout](https://user-images.githubusercontent.com/5306404/176879861-9503aedc-9bda-4de9-8b4b-4f5d0aa1250d.png)

### Expected Behavior

Expected behaviour is a normal layout of the data blocks, like in Firefox as attached below. The data block heights do not stretch if the window is made taller.

![Normal layout](https://user-images.githubusercontent.com/5306404/176880104-557eb653-ae8a-4945-bc5e-429d825e2a38.png)

### Steps to Reproduce

Open up any server console view on Safari, layout is broken.

### Panel Version

1.9.1

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment] 2022-07-01 12:40
Duplicate of #4189

**Closed as completed** 2022-07-01 14:54 UTC
