### ISSUE TITLE
Big problem never solved

### ISSUE THREAD

**Issue by samuxita** [pterodactyl/panel#4638] opened 2022-12-24 10:27 UTC
### Current Behavior

When performing a migration, the backup don't get migrated and removed from the old node. Also, when a server get deleted, the backup is still taking up space. The bug was reported 2 years ago and has never been fixed.

### Expected Behavior

Backup migration when requesting a server migration and backup removal from the old node. Removing the backup when the server get deleted.

### Steps to Reproduce

Simply trying to migrate a server

### Panel Version

1.11.2

### Wings Version

1.11.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment] 2022-12-24 14:53
Duplicate of #2623 (see https://github.com/pterodactyl/panel/issues/2623#issuecomment-731856963) and #2564.

**Closed as completed** 2022-12-25 19:43 UTC
