### ISSUE TITLE
Latest Docker Version Doesn't Know Correct Version

### ISSUE THREAD

**Issue by zaxlofful** [pterodactyl/panel#4609] opened 2022-12-12 08:50 UTC
### Current Behavior

When loading the new docker image, it thinks it needs a update.

Your panel is not up-to-date! The latest version is 1.11.1 and you are currently running version v1.11.1. 

### Expected Behavior

Should know that the latest version is already installed.

### Steps to Reproduce

Just use the latest docker image

### Panel Version

1.11.1

### Wings Version

1.11.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment] 2022-12-12 08:51
This will already be fixed in the next version. (https://github.com/pterodactyl/panel/commit/3432cadd4af095a769912aaca5aaab90b4b47146)

**Comment by zaxlofful** [comment] 2022-12-12 09:05
This is not a "canary" problem, that is already fixed....The verison is the same but its not reading as canary its just seeing the "V" before 1.11.1 and its not the same as "1.11.1"

**Comment by zaxlofful** [comment] 2022-12-12 09:10
Either way, thanks!

**Comment by trenutoo** [comment] 2022-12-12 10:41
Duplicate of #4596

**Closed as completed by trenutoo** 2022-12-12 10:41 UTC
