### ISSUE TITLE
CPU/ram stats randomly stop to work

### ISSUE THREAD

**Issue by xion87** [Pterodactyl/Panel#858] opened 2018-01-08 16:59 UTC
Panel or Daemon: Panel
    Version of Panel/Daemon: 0.64
    Server's OS: Ubuntu16.04.2 LTS
    Your Computer's OS & Browser: Windows 10 and Firefox
    Error log: https://hastebin.com/itijizeced.json
## Add Details Below:
I just started to use this awesome panel 2 days ago, i use 1 bungee server + 20 minecraft server.
I noticed the login server yesterday not showing ram and cpu stats/graph/
![immagine](https://user-images.githubusercontent.com/3611852/34681890-88647bbc-f49d-11e7-856a-0d3fc1bbeec6.png)
Today instead i see another server start to have the same "bug"

The only error that i find on daemon is this: https://hastebin.com/itijizeced.json

**Comment by DaneEveritt** [comment] 2018-01-09 01:38
Duplicate of #343

**Closed by DaneEveritt** 2018-01-09 01:38 UTC
