### ISSUE TITLE
Add auto start server on reboot

### ISSUE THREAD

**Issue by Spartan9802** [pterodactyl/panel#1515] opened 2019-03-08 04:19 UTC
**Is your feature request related to a problem? Please describe.**
It is frustrating that the running servers do not automatically restart after a reboot of the machine while leaving the servers stopped in pause

**Describe the solution you'd like**
Let's imagine that I have three servers that on my three servers two are running, my machine restarts it would be nice if the two servers running started by themselves and left the server that was on pause 

**Describe alternatives you've considered**
I use "php artisan p:server:bulk-power start" but it runs all the servers

**Comment by danny6167** [comment] 2019-03-08 04:22
Duplicate of #136

**Closed** 2019-03-08 17:16 UTC
