### ISSUE TITLE
Error response from Panel: ValidationException: The data.0.ip must be a valid IP address. (HTTP/422)

### ISSUE THREAD

**Issue by sollevix67** [pterodactyl/panel#4302] opened 2022-08-05 17:35 UTC
### Current Behavior

When starting wings after the new update, the exception `ValidationException: The data.0.ip must be a valid IP address. (HTTP/422)` occurs. It also happens every minute. But the panel and wings are otherwise working completely fine.

### Expected Behavior

No exception

### Steps to Reproduce

It happend suddenly after I updated the panel from 1.9.2 to 1.10.1 and wings from 1.6.4 to 1.7.0.

### Panel Version

1.10.1

### Wings Version

1.7.0

### Games and/or Eggs Affected

None

### Docker Image

None

### Error Logs

```bash
INFO: [Aug  5 17:33:30.084] writing log files to disk path=/var/log/pterodactyl/wings.log
DEBUG: [Aug  5 17:33:30.085] running in debug mode    
 INFO: [Aug  5 17:33:30.085] loading configuration from file config_file=/etc/pterodactyl/config.yml
 INFO: [Aug  5 17:33:30.085] configured wings with system timezone timezone=Etc/UTC
DEBUG: [Aug  5 17:33:30.086] ensuring root data directory exists path=/var/lib/pterodactyl
DEBUG: [Aug  5 17:33:30.086] ensuring server data directory exists path=/var/lib/pterodactyl/volumes
DEBUG: [Aug  5 17:33:30.086] ensuring archive data directory exists path=/var/lib/pterodactyl/archives
DEBUG: [Aug  5 17:33:30.086] ensuring backup data directory exists path=/var/lib/pterodactyl/backups
 INFO: [Aug  5 17:33:30.087] checking for pterodactyl system user username={997 997}
 INFO: [Aug  5 17:33:30.087] configured system user successfully gid=997 uid=997 username=pterodactyl
 INFO: [Aug  5 17:33:30.088] fetching list of servers from API
DEBUG: [Aug  5 17:33:30.088] making request to external HTTP endpoint endpoint=https://parcero.sollevix.ovh:9443/api/remote/servers?page=0&per_page=50 headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[(redacted)] Content-Type:[application/json] User-Agent:[Pterodactyl Wings/v1.7.0 (id:fVRj0JU0vqOJpuXX)]] method=GET
 INFO: [Aug  5 17:33:30.126] processing servers returned by the API total_configs=3
DEBUG: [Aug  5 17:33:30.127] using 2 workerpools to instantiate server instances
 INFO: [Aug  5 17:33:30.127] creating new server object from API response server=1d5aedb3-cb33-42be-ab89-8eeabc17cf16
DEBUG: [Aug  5 17:33:30.127] registering event listeners: console, state, resources... server=1d5aedb3-cb33-42be-ab89-8eeabc17cf16
 INFO: [Aug  5 17:33:30.127] creating new server object from API response server=4225e151-1a12-416d-a9e6-8b407c0054c8
DEBUG: [Aug  5 17:33:30.127] registering event listeners: console, state, resources... server=4225e151-1a12-416d-a9e6-8b407c0054c8
 INFO: [Aug  5 17:33:30.132] creating new server object from API response server=c32f4853-0b2d-4ca3-aa98-d52bdd566463
DEBUG: [Aug  5 17:33:30.132] registering event listeners: console, state, resources... server=c32f4853-0b2d-4ca3-aa98-d52bdd566463
 INFO: [Aug  5 17:33:30.137] finished processing server configurations duration=10.230599ms
 INFO: [Aug  5 17:33:30.157] finished loading configuration for server server=1d5aedb3-cb33-42be-ab89-8eeabc17cf16
 INFO: [Aug  5 17:33:30.158] finished loading configuration for server server=4225e151-1a12-416d-a9e6-8b407c0054c8
 INFO: [Aug  5 17:33:30.158] finished loading configuration for server server=c32f4853-0b2d-4ca3-aa98-d52bdd566463
 INFO: [Aug  5 17:33:30.159] configuring server environment and restoring to previous state server=4225e151-1a12-416d-a9e6-8b407c0054c8
 INFO: [Aug  5 17:33:30.159] configuring server environment and restoring to previous state server=c32f4853-0b2d-4ca3-aa98-d52bdd566463
 INFO: [Aug  5 17:33:30.159] configuring server environment and restoring to previous state server=1d5aedb3-cb33-42be-ab89-8eeabc17cf16
 INFO: [Aug  5 17:33:30.160] detected server is running, re-attaching to process... server=c32f4853-0b2d-4ca3-aa98-d52bdd566463
 INFO: [Aug  5 17:33:30.160] detected server is running, re-attaching to process... server=1d5aedb3-cb33-42be-ab89-8eeabc17cf16
 INFO: [Aug  5 17:33:30.161] detected server is running, re-attaching to process... server=4225e151-1a12-416d-a9e6-8b407c0054c8
DEBUG: [Aug  5 17:33:30.161] saw server status change event server=c32f4853-0b2d-4ca3-aa98-d52bdd566463 status=running
DEBUG: [Aug  5 17:33:30.163] saw server status change event server=1d5aedb3-cb33-42be-ab89-8eeabc17cf16 status=running
DEBUG: [Aug  5 17:33:30.163] saw server status change event server=4225e151-1a12-416d-a9e6-8b407c0054c8 status=running
DEBUG: [Aug  5 17:33:30.163] re-syncing server configuration for already running server server=1d5aedb3-cb33-42be-ab89-8eeabc17cf16
DEBUG: [Aug  5 17:33:30.163] making request to external HTTP endpoint endpoint=https://parcero.sollevix.ovh:9443/api/remote/servers/1d5aedb3-cb33-42be-ab89-8eeabc17cf16 headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[(redacted)] Content-Type:[application/json] User-Agent:[Pterodactyl Wings/v1.7.0 (id:fVRj0JU0vqOJpuXX)]] method=GET
 INFO: [Aug  5 17:33:30.165] starting resource polling for container container_id=1d5aedb3-cb33-42be-ab89-8eeabc17cf16 environment=docker
DEBUG: [Aug  5 17:33:30.180] syncing server settings with environment server=1d5aedb3-cb33-42be-ab89-8eeabc17cf16
DEBUG: [Aug  5 17:33:30.180] syncing stop configuration with configured docker environment server=1d5aedb3-cb33-42be-ab89-8eeabc17cf16
 INFO: [Aug  5 17:33:30.180] performing server limit modification on-the-fly server=1d5aedb3-cb33-42be-ab89-8eeabc17cf16
DEBUG: [Aug  5 17:33:30.195] re-syncing server configuration for already running server server=4225e151-1a12-416d-a9e6-8b407c0054c8
DEBUG: [Aug  5 17:33:30.195] making request to external HTTP endpoint endpoint=https://parcero.sollevix.ovh:9443/api/remote/servers/4225e151-1a12-416d-a9e6-8b407c0054c8 headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[(redacted)] Content-Type:[application/json] User-Agent:[Pterodactyl Wings/v1.7.0 (id:fVRj0JU0vqOJpuXX)]] method=GET
 INFO: [Aug  5 17:33:30.196] starting resource polling for container container_id=4225e151-1a12-416d-a9e6-8b407c0054c8 environment=docker
DEBUG: [Aug  5 17:33:30.196] re-syncing server configuration for already running server server=c32f4853-0b2d-4ca3-aa98-d52bdd566463
DEBUG: [Aug  5 17:33:30.196] making request to external HTTP endpoint endpoint=https://parcero.sollevix.ovh:9443/api/remote/servers/c32f4853-0b2d-4ca3-aa98-d52bdd566463 headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[(redacted)] Content-Type:[application/json] User-Agent:[Pterodactyl Wings/v1.7.0 (id:fVRj0JU0vqOJpuXX)]] method=GET
 INFO: [Aug  5 17:33:30.196] starting resource polling for container container_id=c32f4853-0b2d-4ca3-aa98-d52bdd566463 environment=docker
DEBUG: [Aug  5 17:33:30.222] syncing server settings with environment server=4225e151-1a12-416d-a9e6-8b407c0054c8
DEBUG: [Aug  5 17:33:30.222] syncing stop configuration with configured docker environment server=4225e151-1a12-416d-a9e6-8b407c0054c8
 INFO: [Aug  5 17:33:30.222] performing server limit modification on-the-fly server=4225e151-1a12-416d-a9e6-8b407c0054c8
DEBUG: [Aug  5 17:33:30.227] syncing server settings with environment server=c32f4853-0b2d-4ca3-aa98-d52bdd566463
DEBUG: [Aug  5 17:33:30.228] syncing stop configuration with configured docker environment server=c32f4853-0b2d-4ca3-aa98-d52bdd566463
 INFO: [Aug  5 17:33:30.228] performing server limit modification on-the-fly server=c32f4853-0b2d-4ca3-aa98-d52bdd566463
 INFO: [Aug  5 17:33:30.253] configuring system crons  interval=1m0s subsystem=cron
 INFO: [Aug  5 17:33:30.254] starting cron processes   subsystem=cron
DEBUG: [Aug  5 17:33:30.254] sending sftp events to Panel cron=sftp subsystem=cron
 INFO: [Aug  5 17:33:30.254] configuring internal webserver host_address=0.0.0.0 host_port=8080 use_auto_tls=false use_ssl=true
DEBUG: [Aug  5 17:33:30.254] sending internal activity events to Panel cron=activity subsystem=cron
 INFO: [Aug  5 17:33:30.254] updating server states on Panel: marking installing/restoring servers as normal
DEBUG: [Aug  5 17:33:30.254] making request to external HTTP endpoint endpoint=https://parcero.sollevix.ovh:9443/api/remote/activity headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[(redacted)] Content-Type:[application/json] User-Agent:[Pterodactyl Wings/v1.7.0 (id:fVRj0JU0vqOJpuXX)]] method=POST
DEBUG: [Aug  5 17:33:30.255] making request to external HTTP endpoint endpoint=https://parcero.sollevix.ovh:9443/api/remote/servers/reset headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[(redacted)] Content-Type:[application/json] User-Agent:[Pterodactyl Wings/v1.7.0 (id:fVRj0JU0vqOJpuXX)]] method=POST
 INFO: [Aug  5 17:33:30.256] sftp server listening for connections listen=0.0.0.0:2022 public_key=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKPraGFqu4HMQcnCY8UAFNpOYz4fbz/Kyufm1dlyvrlp
ERROR: [Aug  5 17:33:30.278] activity process failed to execute cron=activity error=cron: failed to send activity events to Panel: Error response from Panel: ValidationException: The data.0.ip must be a valid IP address. (HTTP/422) subsystem=cron

Stacktrace:
Error response from Panel: ValidationException: The data.0.ip must be a valid IP address. (HTTP/422)
github.com/pterodactyl/wings/remote.(*client).request.func1
	/home/runner/work/wings/wings/remote/http.go:160
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer
	/home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.2/retry.go:55
github.com/cenkalti/backoff/v4.RetryNotify
	/home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.2/retry.go:34
github.com/cenkalti/backoff/v4.Retry
	/home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.2/retry.go:28
github.com/pterodactyl/wings/remote.(*client).request
	/home/runner/work/wings/wings/remote/http.go:135
github.com/pterodactyl/wings/remote.(*client).Post
	/home/runner/work/wings/wings/remote/http.go:95
github.com/pterodactyl/wings/remote.(*client).SendActivityLogs
	/home/runner/work/wings/wings/remote/servers.go:184
github.com/pterodactyl/wings/internal/cron.(*activityCron).Run
	/home/runner/work/wings/wings/internal/cron/activity_cron.go:43
github.com/pterodactyl/wings/internal/cron.Scheduler.func1
	/home/runner/work/wings/wings/internal/cron/cron.go:50
reflect.Value.call
	/opt/hostedtoolcache/go/1.18.4/x64/src/reflect/value.go:556
reflect.Value.Call
	/opt/hostedtoolcache/go/1.18.4/x64/src/reflect/value.go:339
github.com/go-co-op/gocron.callJobFuncWithParams
	/home/runner/go/pkg/mod/github.com/go-co-op/gocron@v1.15.0/gocron.go:106
github.com/go-co-op/gocron.(*executor).start.func1.2
	/home/runner/go/pkg/mod/github.com/go-co-op/gocron@v1.15.0/executor.go:92
github.com/go-co-op/gocron.(*executor).start.func1
	/home/runner/go/pkg/mod/github.com/go-co-op/gocron@v1.15.0/executor.go:99
runtime.goexit
	/opt/hostedtoolcache/go/1.18.4/x64/src/runtime/asm_amd64.s:1571

cron: failed to send activity events to Panel
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment] 2022-08-05 17:37
Duplicate of #4290 (same cause).

**Closed as completed** 2022-08-05 18:32 UTC
