### ISSUE TITLE
[Feature Request] Download and upload schedules

### ISSUE THREAD

**Issue by PanGeo-Code** [pterodactyl/panel#3611] opened 2021-09-12 23:46 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Downloadable and uploadable schedule templates.

This feature would make it much easyer to give all of your servers the same restart schedule or buckup schedule because you can just copy from one server to the other.

### Describe the solution you'd like.

A Download/Upload button for a schedule file of a Transfer button for users to be able to easily move or dupe schedules

**Comment by matthewpi** [comment] 2021-09-12 23:49
Duplicate of https://github.com/pterodactyl/panel/issues/1346

**Closed as completed by matthewpi** 2021-09-12 23:49 UTC
