### ISSUE TITLE
Filezilla bug?

### ISSUE THREAD

**Issue by Julianvb97** [pterodactyl/panel#1133] opened 2018-05-06 09:15 UTC
* Panel or Daemon:  Daemon
* Version of Panel/Daemon:  0.7.6 
* Server's OS:  Ubuntu 16.04 LTS
* Your Computer's OS & Browser:  Windows 10/Firefox

------------------------
I don't know if this problem has been submitted in the past, but when  I use Filezilla as FTP application I see all of the folders double. But when I use WinSCP I don't. Is this a problem with filezilla in particular or?

I just thought reporting this bug, just to help you guys a bit.

**Comment by Bl4ckSpr4y** [comment] 2018-05-06 09:16
Duplicate of #1099

**Comment by Daxorinator** [comment] 2018-05-06 09:17
Closed, as @Bl4ckSpr4y said, dupe of #1099 , use WinSCP or Downgrade FileZilla, please use Discord if you're having issues like this, GitHub is only for issues that can't be fixed in Discord, IE: Something is actually broken,

**Comment by Julianvb97** [comment] 2018-05-06 09:18
Alright, thank you!

**Closed** 2018-05-06 11:02 UTC
